/** Lossless all-original transfer; never select a convenient subset to fit the cap. */
import fs from 'node:fs/promises';
import path from 'node:path';
import {packageEvidence} from '../yard-canonical-acceptance/package-evidence.mjs';
import {LIMITS} from './identity.mjs';
import {verifyRequiredEvidence,readEvidenceJSON} from './required-evidence.mjs';
const root=path.resolve(import.meta.dirname,'../yard-canonical-acceptance'),out=path.join(root,'results');await fs.mkdir(out,{recursive:true});
const read=name=>readEvidenceJSON(out,name);
const stages=Object.fromEntries(['PREFLIGHT','DEPENDENCIES','SOURCE','BUILD','BROWSER','ENCODED'].map(k=>[k,process.env[k+'_OUTCOME']??'unknown'])),browser=await read('browser.json'),encoded=await read('food-encoded-video.json'),foodBuild=await read('food-builds.json');
const completeness=await verifyRequiredEvidence(out,browser);await fs.writeFile(path.join(out,'food-required-evidence.json'),JSON.stringify(completeness,null,2)+'\n');
const f=browser.food,passed=completeness.complete&&Object.values(stages).every(v=>v==='success')&&browser.sections?.hud==='passed'&&browser.sections?.food==='passed'&&Array.isArray(browser.matrix)&&browser.matrix?.length===11&&browser.matrix.every(r=>r.status==='passed')&&browser.errors?.length===0&&f?.nativeStateCaptures?.length===4&&Array.isArray(f?.affectedHud)&&f?.affectedHud?.length===6&&f.affectedHud.every(r=>r.status==='passed')&&f?.transactions?.length===12&&f?.recording?.originalPreserved===true&&f?.recording?.capabilityTransition?.status==='passed'&&f?.recording?.motion?.allObservedBodyAndSolesClear===true&&f?.retainedIntent?.replayEvidence?.httpStatus===400&&f?.retainedIntent?.replayEvidence?.byteIdenticalToOriginal===true&&f?.retainedIntent?.preservedAfterReload===true&&f?.retainedIntent?.preservedAfterFreshSuccess===true&&f?.retainedIntent?.unionBlockedInActualEditor===true&&encoded.passed===true&&foodBuild.builds?.length===2;
const receipt={head:process.env.GITHUB_SHA,stages,requiredEvidence:{complete:completeness.complete,required:completeness.requiredOriginals,verified:completeness.verifiedOriginals,issues:completeness.issues},acceptance:passed?'MECHANICAL_AND_SCOPED_ENCODED_GATES_PASSED_VISUAL_REVIEW_REQUIRED':'FAILED_OR_INCOMPLETE',visualAcceptance:'PENDING_HUMAN_REVIEW_OF_UNALTERED_VIDEO_AND_NATIVE_SCALE_FOOD_CONTACT_AND_HUD',limits:LIMITS,
 fresh:{baselineHud:browser.matrix?.length??0,affectedFoodHud:f?.affectedHud?.length??0,foodStateImages:f?.nativeStateCaptures?.length??0,actualTransactions:f?.transactions?.length??0,stageVisibleFrames:encoded.analyzedFrames??0,dialogOccludedFrames:encoded.dialogOccludedFrames??0,encodedIntervals:encoded.intervals??[],flatFrames:encoded.flatFrames??null},
 excluded:['production deployment or activation','hosted runtime backend or production services','native Blender sources/private work metadata','new saved visitors or full-stay qualification','art acceptance from numbers','physical-device GPU/FPS or trusted Telegram lifecycle claims','all encoded frames pass: startup retained and dialogs explicitly occluded']};
await fs.writeFile(path.join(out,'food-receipt.json'),JSON.stringify(receipt,null,2)+'\n');
const result=await packageEvidence({rawDir:out,workDir:path.join(root,'work'),uploadDir:path.join(import.meta.dirname,'upload'),metadata:{head:process.env.GITHUB_SHA,acceptance:receipt.acceptance}});
if(process.env.GITHUB_STEP_SUMMARY)await fs.appendFile(process.env.GITHUB_STEP_SUMMARY,`Food evidence: ${receipt.acceptance}. Complete unchanged originals within8MiB: ${result.ok}. Human food/contact/HUD review remains required.\n`);if(!passed||!result.ok)process.exitCode=1;
