/** One clean actual interaction recording. No screenshot, image capture or GPU readback in this module or its called helpers. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {expect} from '@playwright/test';
import {OUT,WORK,report,scene,place,placedPanel,captureFailureDiagnostics,refresh,layout,checkLayout} from '../yard-canonical-acceptance/browser-helpers.mjs';
import {canonicalRows} from './fixtures.mjs';
import {openFoodContext,bootFood,foodState,buyFill,caps} from './browser.mjs';
import {DEFAULT_ROI} from '../yard-placement-redraw/encoded-frames.mjs';
import {canonicalFoodNavigationGeometry} from '../../src/games/companion-yard-v2/pip-prototype/canonical-food-scene.mjs';
import {createCanonicalNavigation} from '../../src/games/companion-yard-v2/pip-prototype/dynamic-navigation.mjs';
import {supportedWorldValid} from '../../src/games/companion-yard-v2/pip-prototype/dynamic-prop-planner.mjs';
import geometry from '../../game-logic/yard-v2/canonical-location-geometry.json' with {type:'json'};
import fixture from '../../src/games/companion-yard-v2/pip-prototype/data/fixture.json' with {type:'json'};
export async function recordFood(browser,owner){
 const f=await owner.seed({food:false}),{c,p}=await openFoodContext(browser,f,{recordVideo:{dir:path.join(WORK,'food-video'),size:{width:390,height:844}}}),video=p.video();
 const result=report.food.recording={file:'food-interactions-native.webm',viewport:{width:390,height:844},deviceScaleFactor:2,encodedSize:{width:390,height:844},isMobile:true,hasTouch:true,rawStartupPreserved:true,worldRaster:'garden-reference-grid-v1; renderer pixel ratio1; device DPR2 does not increase model raster resolution',noScreenshotOrReadPixels:true,startedWallMs:Date.now(),checkpoints:[],markerScope:'Armed after food empty and pot80,60 are genuinely ready. Magenta means unobscured stage; cyan under the unchanged native dialog backdrop means dialog-occluded. Startup is retained but not asserted clear.'};
 try{
  const foodRequests=[];p.on('request',r=>{if(r.url().includes('yard-food-source-r2'))foodRequests.push(r.url());});
  await bootFood(p,f);await place(p,80,60);await expect.poll(async()=>canonicalRows(await owner.saved(f)).length).toBe(1);
  await placedPanel(p,0);await p.locator('[data-pip-control="inspect-selected"]').click();
  await expect.poll(async()=>{const s=await scene(p),r=s?.dynamicSample?.world?.root;return s?.interaction?.phase==='approaching'&&r?.y<94&&r.y>88;},{intervals:[20,30,50],timeout:18000}).toBe(true);
  const beforeActivation=await scene(p);assert.equal(foodRequests.length,0);await owner.mode(f,true);await refresh(p);
  await expect.poll(async()=>(await scene(p))?.canonicalFood?.reentryRequired).toBe(true);const held=await scene(p);assert.equal(held.phase,'reentry-required');assert.equal(held.canonicalFood.render.reason,'CANONICAL_FOOD_REENTRY_REQUIRED');assert.equal(held.renderer.canonicalFood.binding?.visible??false,false);assert.equal(foodRequests.length,0);assert.notDeepEqual(held.dynamicSample.world.root,{x:79,y:129.5,z:0});
  await p.waitForTimeout(250);assert.deepEqual((await scene(p)).dynamicSample.world,held.dynamicSample.world,'Activation must keep the actual frozen pose until an explicit decision');
  const reentryHud=[];for(const[width,height]of [[320,568],[390,844],[568,320]]){await p.setViewportSize({width,height});const reenter=p.locator('[data-pip-control="reenter-food"]');await expect(reenter).toBeEnabled();const screen=await layout(p);checkLayout(screen);assert(screen.stage.w>=280&&screen.stage.h>=192);await reenter.click({trial:true});await expect(p.locator('#yardVisitStatus')).toHaveText('Двор изменился');assert.deepEqual((await scene(p)).dynamicSample.world,held.dynamicSample.world);reentryHud.push({width,height,language:'ru',screen,status:'passed'});}await p.setViewportSize({width:390,height:844});await p.locator('[data-pip-control="reenter-food"]').click();
  await foodState(p,'empty');const restarted=await scene(p);assert.equal(restarted.canonicalFood.reentryRequired,false);assert.deepEqual(restarted.dynamicSample.world.root,{x:79,y:129.5,z:0});assert(foodRequests.length>=1);
  result.capabilityTransition={status:'passed',before:beforeActivation.dynamicSample.world.root,held:held.dynamicSample.world.root,heldPhase:held.phase,foodRequestsBeforeExplicitReentry:0,explicitReentry:true,restarted:restarted.dynamicSample.world.root,recordedInRawStartup:true,hud:reentryHud};
  let s=await foodState(p,'empty');const stage=await p.locator('.cy-scene').boundingBox();assert(stage&&DEFAULT_ROI.x>=stage.x&&DEFAULT_ROI.y>=stage.y&&DEFAULT_ROI.x+DEFAULT_ROI.width<=stage.x+stage.width&&DEFAULT_ROI.y+DEFAULT_ROI.height<=stage.y+stage.height);result.stage=stage;result.resources=caps(s);
  result.browserVersion=browser.version();result.backend=await p.locator('.cy-pip-direct-layer canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2');if(!gl)return{classification:'unavailable'};const d=gl.getExtension('WEBGL_debug_renderer_info'),vendor=gl.getParameter(d?d.UNMASKED_VENDOR_WEBGL:gl.VENDOR),renderer=gl.getParameter(d?d.UNMASKED_RENDERER_WEBGL:gl.RENDERER);return{vendor,renderer,classification:/swiftshader|llvmpipe|softpipe|software/i.test(vendor+' '+renderer)?'software-renderer-reported':'backend-not-classified'};});
  await p.evaluate(()=>{const dialog=document.querySelector('.cy-dialog');if(!dialog||dialog.open)throw Error('Arm only with closed native dialog');const marker=document.createElement('div');marker.setAttribute('aria-hidden','true');marker.dataset.qaEncodedReadiness='true';Object.assign(marker.style,{position:'fixed',left:'0',top:'0',width:'16px',height:'16px',zIndex:'2147483647',pointerEvents:'none',contain:'strict'});window.__foodMarkerTransitions=[];const update=()=>{marker.style.background=dialog.open?'rgb(0,255,255)':'rgb(255,0,255)';window.__foodMarkerTransitions.push({wallMs:Date.now(),performanceMs:performance.now(),dialogOpen:dialog.open});};update();new MutationObserver(update).observe(dialog,{attributes:true,attributeFilter:['open']});document.body.append(marker);});
  result.checkpoints.push({label:'empty-with-pot',wallMs:Date.now(),food:s.canonicalFood});await p.waitForTimeout(200);
  for(const id of ['kibble','berry_plate','bonito_bowl']){s=await buyFill(p,f,owner,id);result.checkpoints.push({label:id,wallMs:Date.now(),food:s.canonicalFood});await p.waitForTimeout(200);}
  await placedPanel(p,0);await p.waitForTimeout(200);
  await p.evaluate(()=>{const samples=[];window.__foodMotionSamples=samples;window.__foodMotionSampling=true;const tick=()=>{if(!window.__foodMotionSampling)return;const s=window.__yardPipIntegration?.snapshot()?.scene,w=s?.dynamicSample?.world;if(w&&samples.length<1800)samples.push({wallMs:Date.now(),elapsedMs:s.lastFrame?.elapsedMs,phase:s.interaction?.phase,world:{root:w.root,heading:w.heading,feet:Object.fromEntries(['L','R'].map(k=>[k,{position:w.feet[k].position,heading:w.feet[k].heading,solePolygon:w.feet[k].solePolygon}]))}});requestAnimationFrame(tick);};requestAnimationFrame(tick);});
  await p.locator('[data-pip-control="inspect-selected"]').click();await expect(p.locator('.cy-dialog')).not.toBeVisible();await expect.poll(async()=>{const r=(await scene(p))?.interaction;return r?.stageCount===1&&r?.selectedAnchor==='leaf-5'&&r?.planLayoutKey?.includes('pip-garden:food:bowl-1');}).toBe(true);
  result.routeStart=(await scene(p)).interaction;result.routeLandmarks={approachDurationMs:15420,curveJoin:{atMs:9702.671,root:{x:96,y:80}},finalLineJoin:{atMs:12157.392,root:{x:94.28606834,y:67.40245577}},normalSupportedSettleStartsMs:14795};result.routeVisualReview='Review uninterrupted forward travel and foot/body steering through the two quintic segments and final line. One approach stage and clearance checks alone do not establish natural motion.';await expect.poll(async()=>(await scene(p))?.interaction?.phase,{timeout:30000}).toBe('settled');
  const samples=await p.evaluate(()=>{window.__foodMotionSampling=false;return window.__foodMotionSamples;});assert(samples.length>=10&&samples.length<1800,'Finite observed route samples required');
  const rows=canonicalRows(await owner.saved(f)),nav=createCanonicalNavigation({geometry:canonicalFoodNavigationGeometry(geometry,{reserved:true}),rows,actor:fixture.actor});for(const sample of samples)assert(supportedWorldValid(sample.world,fixture.actor,nav),'Observed body or sole intersects the reserved food/prop geometry');
  s=await scene(p);assert.equal(s.interaction.savedVisitor,false);assert.equal(s.savedVisitor,false);caps(s);result.routeEnd=s.interaction;result.motion={observedSamples:samples.length,allObservedBodyAndSolesClear:true,qualification:'Finite native RAF observations, complemented by exhaustive source route sampling; not an all-video-frame collision claim.'};
  await fs.writeFile(path.join(OUT,'food-observed-motion.json'),JSON.stringify(samples)+'\n');await p.waitForTimeout(250);result.markerTransitions=await p.evaluate(()=>window.__foodMarkerTransitions);assert.deepEqual(result.markerTransitions.map(r=>r.dialogOpen),[false,true,false,true,false,true,false,true,false]);
  const saved=await owner.saved(f);assert.equal(saved.yard.currencies.treats,160);assert.equal(saved.yard.currencies.shinyTreats,0);assert.equal(saved.yard.bowls.length,1);assert.deepEqual(saved._yardV2.runtime.visits,{});result.status='FUNCTIONAL_PASSED_ENCODED_GATE_PENDING';
 }catch(error){result.status='FAILED_OR_INCOMPLETE';await captureFailureDiagnostics(p,'food-recording-failure');throw error;}
 finally{try{await c.close();}finally{try{await fs.copyFile(await video.path(),path.join(OUT,result.file));result.originalPreserved=true;result.closedWallMs=Date.now();}catch(error){result.originalPreserved=false;throw error;}}}
}
