const ROOT = '/games/settlement/';
const preferWebp = true;

export function asset(file) {
  return ROOT + file;
}

export function sprite(fileBase) {
  return asset(preferWebp ? `${fileBase}.webp` : `${fileBase}.png`);
}

export function trimmedAsset(url) {
  if (!url?.startsWith(ROOT) || !url.endsWith('.webp')) return url;
  const fileBase = url.slice(ROOT.length, -'.webp'.length);
  return asset(`processed/${fileBase}.trim.webp`);
}

export const MAP_ASSETS = {
  region: asset('map-region-settlement-playable.webp')
};

export const UI_ASSETS = {
  topbar: sprite('ui/hud/top-hud-bar-frame'),
  profile: sprite('ui/hud/profile-card-frame'),
  profileAvatarFrame: sprite('ui/hud/profile-avatar-frame'),
  profileLevelBadge: sprite('ui/hud/profile-level-badge'),
  settlementPlaque: sprite('ui/hud/settlement-title-plaque'),
  resourcePill: sprite('ui/hud/resource-pill-idle'),
  resourcePillActive: sprite('ui/hud/resource-pill-active'),
  resourceIconSlot: sprite('ui/hud/resource-icon-slot'),
  plus: sprite('ui-resource-plus-button'),
  iconButton: sprite('ui-small-icon-button-9slice'),
  leftDock: sprite('ui-left-dock-frame'),
  dockButton: sprite('ui/hud/leftdock-button-idle'),
  dockButtonActive: sprite('ui/hud/leftdock-button-active'),
  badge: sprite('ui/hud/notification-badge'),
  bottomFrame: sprite('ui/hud/bottom-nav-frame'),
  bottomButton: sprite('ui/hud/bottom-nav-button-idle'),
  bottomButtonActive: sprite('ui/hud/bottom-nav-button-active'),
  bottomButtonPressed: sprite('ui/hud/bottom-nav-button-active'),
  primaryBuildButton: sprite('ui/hud/primary-build-button-idle'),
  primaryBuildButtonActive: sprite('ui/hud/primary-build-button-active'),
  collectButton: sprite('ui/hud/collect-button-idle'),
  collectButtonActive: sprite('ui/hud/collect-button-active'),
  tabIdle: sprite('ui/tabs/panel-tab-idle'),
  tabActive: sprite('ui/tabs/panel-tab-active'),
  panel: sprite('ui-panel-large-9slice'),
  smallPanel: sprite('ui-panel-small-9slice'),
  sidePanelFancy: sprite('ui-side-panel-fancy'),
  rightPanelOverview: sprite('ui/panel/right-panel-overview-shell'),
  rightPanelBuilding: sprite('ui/panel/right-panel-building-shell'),
  panelHeaderStrip: sprite('ui/panel/right-panel-header-strip'),
  overviewIntroCard: sprite('ui/panel/overview-intro-card'),
  overviewSectionCard: sprite('ui/panel/overview-section-card'),
  overviewGoalRow: sprite('ui/panel/overview-goal-row'),
  collectToast: sprite('ui/toast/collect-ready-toast'),
  ribbon: sprite('ui-panel-header-ribbon'),
  close: sprite('ui-close-button'),
  progressFrame: sprite('ui/status/progress-frame'),
  progressGold: sprite('ui/status/progress-fill-gold'),
  progressGreen: sprite('ui/status/progress-fill-green'),
  rewardBadge: sprite('ui/status/reward-badge-shell'),
  buildingHeaderIconSlot: sprite('ui/panel/right-panel-header-icon-slot'),
  buildingDescription: sprite('ui/panel/building-description-block'),
  buildingLevelRow: sprite('ui/panel/building-level-row'),
  buildingStatsCard: sprite('ui/panel/building-stats-card'),
  buildingStatRow: sprite('ui/panel/building-stat-row'),
  buildingUpgradeIdle: sprite('ui/button/building-upgrade-idle'),
  buildingUpgradeDisabled: sprite('ui/button/building-upgrade-disabled'),
  buildingUpgradeInProgress: sprite('ui/button/building-upgrade-in-progress'),
  buildingTimerPill: sprite('ui/button/building-timer-pill'),
  buildingFooterCard: sprite('ui/panel/building-footer-card'),
  buildingFooterIconSlot: sprite('ui/panel/building-footer-icon-slot'),
  upgradeToast: sprite('ui/toast/upgrade-start-toast'),
  toastClose: sprite('ui/button/toast-close-button'),
  buildingHeaderGlow: sprite('ui/panel/building-header-glow'),
  rightPanelGoals: sprite('ui/panel/right-panel-goals-shell'),
  rightPanelInventory: sprite('ui/panel/right-panel-inventory-shell'),
  rightPanelCouncil: sprite('ui/panel/right-panel-council-shell'),
  rightPanelConstruction: sprite('ui/panel/right-panel-construction-shell'),
  rightPanelResearch: sprite('ui/panel/right-panel-research-shell'),
  rightPanelWorldMap: sprite('ui/panel/right-panel-world-map-shell'),
  goalsTitleStrip: sprite('ui/panel/right-panel-goals-title-strip'),
  goalsSummaryCard: sprite('ui/panel/goals-summary-card'),
  goalsLongtermRow: sprite('ui/panel/goals-longterm-row'),
  goalsDailyRow: sprite('ui/panel/goals-daily-row'),
  goalsIconSlot: sprite('ui/panel/goals-icon-slot'),
  goalsRewardBadge: sprite('ui/status/goals-reward-badge'),
  goalsClaimButtonIdle: sprite('ui/button/goals-claim-button-idle'),
  goalsClaimButtonDisabled: sprite('ui/button/goals-claim-button-disabled'),
  goalsClaimCountBadge: sprite('ui/status/goals-claim-count-badge'),
  goalsRefreshChip: sprite('ui/status/goals-refresh-chip'),
  goalsProgressRow: sprite('ui/status/goals-progress-row'),
  bottomGoalsButton: sprite('ui/hud/bottom-nav-button-goals-idle'),
  bottomGoalsButtonActive: sprite('ui/hud/bottom-nav-button-goals-active'),
  inventoryTitleStrip: sprite('ui/panel/right-panel-inventory-title-strip'),
  inventorySummaryCard: sprite('ui/panel/inventory-summary-card'),
  inventoryRowIdle: sprite('ui/panel/inventory-resource-row-idle'),
  inventoryRowSelected: sprite('ui/panel/inventory-resource-row-selected'),
  inventoryRowWarning: sprite('ui/panel/inventory-resource-row-warning'),
  inventoryResourceIconSlot: sprite('ui/panel/inventory-resource-icon-slot'),
  inventoryMinusIdle: sprite('ui/button/inventory-minus-idle'),
  inventoryMinusDisabled: sprite('ui/button/inventory-minus-disabled'),
  inventoryPlusIdle: sprite('ui/button/inventory-plus-idle'),
  inventoryPlusDisabled: sprite('ui/button/inventory-plus-disabled'),
  inventorySelectIdle: sprite('ui/button/inventory-select-idle'),
  inventoryItemCard: sprite('ui/panel/inventory-item-card-idle'),
  inventoryItemCountBadge: sprite('ui/status/inventory-item-count-badge'),
  inventoryManageButtonIdle: sprite('ui/button/inventory-manage-button-idle'),
  inventoryManageButtonDisabled: sprite('ui/button/inventory-manage-button-disabled'),
  councilHeaderIconSlot: sprite('ui/panel/right-panel-council-icon-slot'),
  councilRecommendationCard: sprite('ui/panel/council-recommendation-card-idle'),
  councilRecommendationCardHovered: sprite('ui/panel/council-recommendation-card-hovered'),
  councilAdvisorPortraitSlot: sprite('ui/panel/council-advisor-portrait-slot'),
  councilRecommendationIconSlot: sprite('ui/panel/council-recommendation-icon-slot'),
  councilFollowButtonIdle: sprite('ui/button/council-follow-button-idle'),
  councilFollowButtonDisabled: sprite('ui/button/council-follow-button-disabled'),
  councilStageCard: sprite('ui/panel/council-stage-card'),
  councilStageBadge: sprite('ui/panel/council-stage-badge'),
  councilPriorityRowIdle: sprite('ui/panel/council-priority-row-idle'),
  councilPriorityRowActive: sprite('ui/panel/council-priority-row-active'),
  councilOpenResearchButtonIdle: sprite('ui/button/council-open-research-button-idle'),
  councilOpenResearchButtonDisabled: sprite('ui/button/council-open-research-button-disabled'),
  constructionTitleStrip: sprite('ui/panel/right-panel-construction-title-strip'),
  constructionCategoryProductionIdle: sprite('ui/panel/construction-category-production-idle'),
  constructionCategoryProductionActive: sprite('ui/panel/construction-category-production-active'),
  constructionCategoryStorageIdle: sprite('ui/panel/construction-category-storage-idle'),
  constructionCategoryStorageActive: sprite('ui/panel/construction-category-storage-active'),
  constructionCategoryDecorIdle: sprite('ui/panel/construction-category-decor-idle'),
  constructionCategoryDecorActive: sprite('ui/panel/construction-category-decor-active'),
  constructionCategorySpecialIdle: sprite('ui/panel/construction-category-special-idle'),
  constructionCategorySpecialActive: sprite('ui/panel/construction-category-special-active'),
  constructionCardIdle: sprite('ui/panel/construction-card-idle'),
  constructionCardSelected: sprite('ui/panel/construction-card-selected'),
  constructionCardLocked: sprite('ui/panel/construction-card-locked'),
  constructionCardArtGlow: sprite('ui/panel/construction-card-art-glow'),
  constructionCostRow: sprite('ui/panel/construction-cost-row'),
  constructionPagerIdle: sprite('ui/button/construction-pager-idle'),
  constructionPagerDisabled: sprite('ui/button/construction-pager-disabled'),
  constructionPageIndicator: sprite('ui/status/construction-page-indicator'),
  constructionPlacementHint: sprite('ui/panel/construction-placement-hint'),
  constructionPlotRingIdle: sprite('ui/scene/construction-plot-ring-idle'),
  constructionPlotRingSelected: sprite('ui/scene/construction-plot-ring-selected'),
  constructionGhostOverlay: sprite('ui/scene/construction-building-ghost-overlay'),
  constructionConfirmIdle: sprite('ui/button/construction-confirm-idle'),
  constructionConfirmPressed: sprite('ui/button/construction-confirm-pressed'),
  constructionConfirmDisabled: sprite('ui/button/construction-confirm-disabled'),
  constructionConfirmToast: sprite('ui/toast/construction-confirm-toast'),
  researchTitleStrip: sprite('ui/panel/right-panel-research-title-strip'),
  researchIntroStrip: sprite('ui/panel/research-intro-strip'),
  researchCategoryFarmingIdle: sprite('ui/tabs/research-category-farming-idle'),
  researchCategoryFarmingActive: sprite('ui/tabs/research-category-farming-active'),
  researchCategoryTradeIdle: sprite('ui/tabs/research-category-trade-idle'),
  researchCategoryTradeActive: sprite('ui/tabs/research-category-trade-active'),
  researchCategoryCultureIdle: sprite('ui/tabs/research-category-culture-idle'),
  researchCategoryCultureActive: sprite('ui/tabs/research-category-culture-active'),
  researchNodeComplete: sprite('ui/panel/research-node-complete'),
  researchNodeAvailable: sprite('ui/panel/research-node-available'),
  researchNodeSelected: sprite('ui/panel/research-node-selected'),
  researchNodeResearching: sprite('ui/panel/research-node-researching'),
  researchNodeLocked: sprite('ui/panel/research-node-locked'),
  researchNodeIconSlot: sprite('ui/panel/research-node-icon-slot'),
  researchCheckBadge: sprite('ui/status/research-node-check-badge'),
  researchLockBadge: sprite('ui/status/research-node-lock-badge'),
  researchNodeProgressFrame: sprite('ui/status/research-node-progress-frame'),
  researchNodeProgressFill: sprite('ui/status/research-node-progress-fill'),
  researchConnectorHorizontal: sprite('ui/panel/research-connector-horizontal'),
  researchConnectorVertical: sprite('ui/panel/research-connector-vertical'),
  researchConnectorArrowhead: sprite('ui/panel/research-connector-arrowhead'),
  researchDetailCard: sprite('ui/panel/research-detail-card'),
  researchDetailDivider: sprite('ui/panel/research-detail-divider'),
  researchCostRow: sprite('ui/panel/research-cost-row'),
  researchCostItemOk: sprite('ui/status/research-cost-item-ok'),
  researchCostItemNeed: sprite('ui/status/research-cost-item-need'),
  researchStudyButtonIdle: sprite('ui/button/research-study-button-idle'),
  researchStudyButtonPressed: sprite('ui/button/research-study-button-pressed'),
  researchStudyButtonDisabled: sprite('ui/button/research-study-button-disabled'),
  researchTimerIcon: sprite('ui/status/research-timer-hourglass'),
  researchStartedToast: sprite('ui/toast/research-started-toast'),
  researchCompleteToast: sprite('ui/toast/research-complete-toast'),
  worldMapTitleStrip: sprite('ui/panel/right-panel-world-map-title-strip'),
  worldMapParchmentFrame: sprite('ui/panel/world-map-parchment-frame'),
  worldMapBase: sprite('ui/map/world-map-archipelago-base'),
  worldMapCompass: sprite('ui/map/world-map-compass'),
  worldMapMarkerHome: sprite('ui/map/world-map-marker-home'),
  worldMapMarkerAvailable: sprite('ui/map/world-map-marker-available'),
  worldMapMarkerSelected: sprite('ui/map/world-map-marker-selected'),
  worldMapMarkerLocked: sprite('ui/map/world-map-marker-locked'),
  worldMapFilterIdle: sprite('ui/tabs/world-map-filter-idle'),
  worldMapFilterActive: sprite('ui/tabs/world-map-filter-active'),
  worldMapFilterDisabled: sprite('ui/tabs/world-map-filter-disabled'),
  worldExpeditionCardIdle: sprite('ui/panel/world-expedition-card-idle'),
  worldExpeditionCardSelected: sprite('ui/panel/world-expedition-card-selected'),
  worldExpeditionCardActive: sprite('ui/panel/world-expedition-card-active'),
  worldExpeditionCardLocked: sprite('ui/panel/world-expedition-card-locked'),
  worldThumbForest: sprite('ui/map/expedition-thumb-ancient-forest'),
  worldThumbRuins: sprite('ui/map/expedition-thumb-drowned-ruins'),
  worldThumbVolcano: sprite('ui/map/expedition-thumb-volcanic-mountains'),
  worldThumbIce: sprite('ui/map/expedition-thumb-ice-wastes'),
  worldDifficultyEasy: sprite('ui/status/world-difficulty-easy'),
  worldDifficultyMedium: sprite('ui/status/world-difficulty-medium'),
  worldDifficultyHard: sprite('ui/status/world-difficulty-hard'),
  worldDifficultyLocked: sprite('ui/status/world-difficulty-locked'),
  worldRewardChip: sprite('ui/status/world-expedition-reward-chip'),
  worldSendButtonIdle: sprite('ui/button/world-expedition-send-idle'),
  worldSendButtonPressed: sprite('ui/button/world-expedition-send-pressed'),
  worldSendButtonDisabled: sprite('ui/button/world-expedition-send-disabled'),
  worldTimerIcon: sprite('ui/status/world-expedition-hourglass'),
  worldStartedToast: sprite('ui/toast/world-expedition-started-toast'),
  worldCompleteToast: sprite('ui/toast/world-expedition-complete-toast'),
  bottomWorldButton: sprite('ui/hud/bottom-nav-button-world-idle'),
  bottomWorldButtonActive: sprite('ui/hud/bottom-nav-button-world-active')
};

export const ICONS = {
  quest: sprite('icon-quest-scroll'),
  inbox: sprite('icon-inbox-envelope'),
  build: sprite('icon-build-hammer'),
  map: sprite('icon-map-folded'),
  rank: sprite('icon-rank-trophy'),
  store: sprite('icon-store-building'),
  inventory: sprite('icon-inventory-bag'),
  buildLarge: sprite('icon-build-hammer-large'),
  research: sprite('icon-research-flask'),
  world: sprite('icon-world-compass'),
  food: sprite('icon-resource-food'),
  wood: sprite('icon-resource-wood'),
  stone: sprite('icon-resource-stone'),
  goods: sprite('icon-resource-goods'),
  culture: sprite('icon-resource-culture'),
  gold: sprite('icon-resource-gold'),
  gems: sprite('icon-resource-gems'),
  prestige: sprite('icon-resource-prestige'),
  population: sprite('icon-resource-population'),
  morale: sprite('icon-resource-morale'),
  settings: sprite('icon-settings-gear'),
  mail: sprite('icon-mail'),
  gift: sprite('icon-gift'),
  calendar: sprite('icon-calendar'),
  event: sprite('icon-event-present'),
  starterPack: sprite('icon-starter-pack-chest'),
  achievement: sprite('icon-achievement-star'),
  shield: sprite('icon-shield-rank')
};

export function buildingAsset(id, level) {
  const milestone = level >= 12 ? '12' : level >= 8 ? '08' : level >= 4 ? '04' : '01';
  return sprite(`building-${id}-level-${milestone}`);
}


export const BUILDING_IDS = [
  'hearth-hall',
  'cottage-ring',
  'common-garden',
  'lumber-camp',
  'stone-quarry',
  'craft-workshop',
  'market-green',
  'way-shrine',
  'river-bridge',
  'council-manor'
];
export const BUILDING_MILESTONES = ['01', '04', '08', '12'];
export const BUILDING_ASSETS = BUILDING_IDS.flatMap((id) =>
  BUILDING_MILESTONES.map((level) => sprite(`building-${id}-level-${level}`))
);

export const PROP_ASSETS = {
  oakSmall: sprite('prop-tree-oak-small'),
  oakLarge: sprite('prop-tree-oak-large'),
  pineSmall: sprite('prop-tree-pine-small'),
  pineLarge: sprite('prop-tree-pine-large'),
  birchSmall: sprite('prop-tree-birch-small'),
  bush: sprite('prop-bush-round'),
  flowerWhite: sprite('prop-flower-patch-white'),
  flowerYellow: sprite('prop-flower-patch-yellow'),
  flowerBlue: sprite('prop-flower-patch-blue'),
  hedge: sprite('prop-hedge-segment'),
  well: sprite('prop-well-small'),
  bench: sprite('prop-bench-small'),
  barrel: sprite('prop-barrel-small'),
  crate: sprite('prop-crate-small'),
  sack: sprite('prop-sack-small'),
  cart: sprite('prop-cart-small'),
  lantern: sprite('prop-lantern-post-small'),
  signpost: sprite('prop-signpost-small'),
  fence: sprite('prop-fence-segment-small'),
  stone: sprite('prop-stone-small'),
  rocks: sprite('prop-rock-cluster-small'),
  oakHero: sprite('prop-tree-oak-1'),
  pineHero: sprite('prop-tree-pine-1'),
  birchHero: sprite('prop-tree-birch-1'),
  rockLarge: sprite('prop-rock-large-1'),
  rockSmall: sprite('prop-rock-small-1'),
  crateStack: sprite('prop-crate-stack'),
  flowerBed: sprite('prop-flower-bed'),
  wellFull: sprite('prop-well'),
  benchFull: sprite('prop-bench'),
  barrelFull: sprite('prop-barrel'),
  sackFull: sprite('prop-sack'),
  cartFull: sprite('prop-cart'),
  lanternFull: sprite('prop-lantern-post'),
  signpostFull: sprite('prop-signpost')
};

export const VILLAGER_ASSETS = {
  farmerWalk: sprite('villager-farmer-walk-4f'),
  lumberjackWalk: sprite('villager-lumberjack-walk-4f'),
  masonWalk: sprite('villager-mason-walk-4f'),
  merchantWalk: sprite('villager-merchant-walk-4f'),
  builderCarry: sprite('villager-builder-carry-4f'),
  courierWalk: sprite('villager-courier-walk-4f'),
  elderWalk: sprite('villager-elder-walk-4f'),
  guardWalk: sprite('villager-guard-walk-4f'),
  childWalk: sprite('villager-child-walk-4f'),
  traderCartWalk: sprite('villager-trader-cart-walk-4f'),
  farmerHarvest: sprite('villager-farmer-harvest-4f'),
  builderHammer: sprite('villager-builder-hammer-4f'),
  merchantWave: sprite('villager-merchant-wave-4f'),
  masonChipstone: sprite('villager-mason-chipstone-4f'),
  lumberjackSaw: sprite('villager-lumberjack-saw-4f')
};

export const VFX_ASSETS = {
  chimneySmoke: sprite('vfx-chimney-smoke-6f'),
  marketSparkle: sprite('vfx-market-sparkle-6f'),
  buildDust: sprite('vfx-build-dust-6f'),
  levelupRays: sprite('vfx-levelup-rays'),
  questReady: sprite('vfx-quest-ready-pulse'),
  goldPop: sprite('vfx-resource-pop-gold'),
  foodPop: sprite('vfx-resource-pop-food'),
  waterGlint: sprite('vfx-water-glint-6f'),
  selectionRing: sprite('vfx-selection-ring'),
  buildingUpgradeGlow: sprite('vfx-building-upgrade-glow')
};

export const ALL_PIXI_ASSETS = [
  MAP_ASSETS.region,
  ...BUILDING_ASSETS,
  ...Object.values(PROP_ASSETS),
  ...Object.values(VILLAGER_ASSETS),
  ...Object.values(VFX_ASSETS)
];
