// Settlement display copy only. Domain data and persisted state stay unchanged.
export const SETTLEMENT_EN = {
  "Производственные и складские бонусы пока не подключены.": "Production and storage bonuses are not available yet.",
  "Престиж за завершение (до лимита)": "Completion prestige (up to capacity)",
  "Изучение повышает уровень технологии. Зависимые исследования проверяют этот уровень.": "Research raises this technology’s level. Dependent technologies check that level.",
  "Не удалось отправить экспедицию. Проверьте маршрут и повторите попытку.": "Could not send the expedition. Check the route and try again.",
  "Маршрут пока недоступен": "This route is not available yet",
  "Учёт особых предметов пока не подключён. Здесь показаны только реальные ресурсы склада.": "Special-item tracking is not available yet. This warehouse shows your actual resources only.",
  "Доступно": "Available",
  "Получено": "Claimed",
  "Награды из прежней версии доступны один раз. Они не означают выполнение текущих заданий и не обновляются ежедневно.": "Rewards from the previous version can be claimed once. They do not represent current task completion and do not reset daily.",
  "Один раз": "One time",
  "Сохранённые разовые награды": "Saved one-time rewards",
  "Текущий прогресс поселения. Награды за эти цели пока не подключены.": "Current settlement progress. Rewards for these targets are not available yet.",
  "Деревня процветает": "The village is thriving",
  "Сейчас новых вестей нет.": "No new village news right now.",
  "Магазин пока недоступен": "Shop is not available yet",
  "Покупки и ежедневные подарки ещё не подключены. Ресурсы можно получать во вкладке «Выпуск» и за заказы жителей.": "Purchases and daily gifts are not available yet. Collect production batches and deliver resident orders to earn resources.",
  "Доставленные заказы": "Orders delivered",
  "Развивайте поселение во вкладке «Развитие».": "Develop your settlement in the Growth tab.",

  "Еда": "Food",
  "Дерево": "Wood",
  "Камень": "Stone",
  "Товары": "Goods",
  "Культура": "Culture",
  "Золото": "Gold",
  "Кристаллы": "Gems",
  "Престиж": "Prestige",
  "Мораль": "Morale",
  "Жители": "Residents",
  "Здание": "Building",
  "Цели": "Goals",
  "Инвентарь": "Inventory",
  "Склад": "Storage",
  "Совет": "Council",
  "Событие": "Event",
  "3д 12ч": "3d 12h",
  "Подарок": "Gift",
  "готов": "ready",
  "Набор": "Pack",
  "1д 6ч": "1d 6h",
  "Почта": "Mail",
  "Управление": "Civic",
  "Жильё": "Homes",
  "Производство": "Production",
  "Торговля": "Trade",
  "Инфраструктура": "Infrastructure",
  "Построено на площадке «{0}». Эту постройку можно снести и освободить место под другой объект.": "Built at {0}. Demolish it to free the plot.",
  "склад": "storage",
  "новая постройка": "new building",
  "Готовая постройка: {0}. Площадка: {1}.": "Building: {0}. Plot: {1}.",
  "Обзор": "Overview",
  "Обзор деревни": "Village overview",
  "Поселение": "Settlement",
  "Состояние поселения и текущие задачи": "Village status and current tasks",
  "Уровень, производство и улучшение": "Level, output and upgrades",
  "Цели поселения": "Village goals",
  "Прогресс": "Progress",
  "Цели и награды": "Goals and rewards",
  "Инвентарь и склад": "Inventory and storage",
  "Ресурсы, вместимость и особые предметы": "Resources, capacity and special items",
  "Совет и исследования": "Council and research",
  "Рекомендации, стадия и приоритеты": "Advice, stage and priorities",
  "Исследования": "Research",
  "Технологии": "Technology",
  "Исследуйте технологии и открывайте возможности": "Research technologies and unlock opportunities",
  "Магазин": "Shop",
  "Предложения": "Offers",
  "Награды, подарки и наборы": "Rewards, gifts and packs",
  "Вести": "News",
  "Вести деревни": "Village news",
  "Сообщения": "Messages",
  "Почта, события и новости поселения": "Mail, events and village news",
  "Карта": "Map",
  "Карта мира": "World map",
  "Мир": "World",
  "Маршруты и экспедиции": "Routes and expeditions",
  "Ранг": "Rank",
  "Ранг поселения": "Village rank",
  "Репутация, стадия и престиж поселения": "Reputation, stage and prestige",
  "Строительство": "Build",
  "Каталог": "Catalogue",
  "Выбор зданий и свободных площадок": "Buildings and available plots",
  "Экспедиции": "Expeditions",
  "Доступные регионы, риски и награды": "Regions, risks and rewards",
  "Уровень {0}/{1} · {2}": "Level {0}/{1} · {2}",
  "{0}{1}/мин": "{0}{1}/min",
  "{0}м {1}с": "{0}m {1}s",
  "{0}: выбрано": "{0}: selected",
  "Пополнить {0}": "Add {0}",
  "Уровень": "Level",
  "Поселение · {0}": "Settlement · {0}",
  "Строить": "Build",
  "Наука": "Science",
  "Собрать": "Collect",
  "Постройте Лесопилку": "Build a Sawmill",
  "Улучшите Дом до ур. 3": "Upgrade a Home to level 3",
  "Развитие поселения": "Settlement progress",
  "Собирайте партии, доставляйте заказы и развивайте поселение.": "Collect batches, deliver orders and develop the settlement.",
  "Выпуск партии · каждые 20 с": "Batch output · every 20s",
  "Мораль жителей": "Resident morale",
  "Подробнее": "Details",
  "Текущие цели": "Current goals",
  "Все цели": "All goals",
  "· Очажный зал": "· Hearth Hall",
  "ур.": "Lv",
  "Максимум": "Maximum",
  "Уровень {0}": "Level {0}",
  "Производство в минуту": "Output per minute",
  "Эффект": "Effect",
  "Пассивный": "Passive",
  "Стоимость улучшения": "Upgrade cost",
  "Статус": "Status",
  "Снести постройку и освободить площадку": "Demolish and free this plot",
  "Здание улучшено полностью": "Fully upgraded",
  "Улучшить здание": "Upgrade building",
  "Недостаточно ресурсов": "Not enough resources",
  "Пассивный доход": "Passive income",
  "/мин": "/min",
  "награды готовы к сбору": "rewards ready",
  "Долгосрочные цели": "Long-term goals",
  "задачи": "tasks",
  "Награда": "Reward",
  "Ежедневные задачи": "Daily tasks",
  "Обновление через:": "Refresh in:",
  "Забрать награды": "Claim rewards",
  "Ресурсы": "Resources",
  "Выбранный ресурс": "Selected resource",
  "{0}: {1} из {2}": "{0}: {1} of {2}",
  "из": "of",
  "Уменьшить вместимость: {0}": "Reduce capacity: {0}",
  "Увеличить вместимость: {0}": "Increase capacity: {0}",
  "Выбрать ресурс: {0}": "Select resource: {0}",
  "Выбрано": "Selected",
  "Выбрать": "Select",
  "Изделия и особые предметы": "Crafted and special items",
  "Управление складом": "Manage storage",
  "Рекомендации совета": "Council advice",
  "Стадия поселения": "Village stage",
  "Что построить дальше?": "What to build next?",
  "Открыть исследования": "Open research",
  "Категории строительства": "Building categories",
  "Площадка": "Plot",
  "Занято: {0}. Тапните постройку на карте, чтобы открыть снос.": "Occupied: {0}. Tap the building on the map to demolish it.",
  "постройка": "building",
  "Свободно: выбрано место для {0}.": "Available: selected for {0}.",
  "постройки": "a building",
  "Страницы каталога": "Catalogue pages",
  "Предыдущая страница": "Previous page",
  "Следующая страница": "Next page",
  ": тапните свободную площадку на карте, затем подтвердите зелёной кнопкой на самой площадке.": ": tap an empty plot on the map, then confirm with its green button.",
  "Недоступно": "Unavailable",
  "Изучено": "Researched",
  "Изучается": "Researching",
  "Изучить": "Research",
  "Выберите исследование, чтобы увидеть цену и бонусы.": "Choose research to see its cost and bonuses.",
  "Категории исследований": "Research categories",
  "Древо технологий": "Technology tree",
  "Требования не выполнены": "Requirements not met",
  "Стоимость исследования": "Research cost",
  "Карта архипелага": "Archipelago map",
  "Маршрут": "Route",
  ", закрыто": ", locked",
  "{0}, закрыто": "{0}, locked",
  "Фильтры экспедиций": "Expedition filters",
  "Доступные экспедиции": "Available expeditions",
  "Маршрут закрыт": "Route locked",
  "Награды": "Rewards",
  "Награды:": "Rewards:",
  "В пути": "Travelling",
  "Отправить экспедицию": "Send expedition",
  "Сезонный рынок": "Seasonal market",
  "Караван прибудет после накопления товаров.": "The caravan arrives when enough goods are stored.",
  "Подарок готов": "Gift ready",
  "Можно забрать малый бонус ресурсов.": "Collect a small resource bonus.",
  "Событие деревни": "Village event",
  "Следите за моралью и культурой.": "Keep an eye on morale and culture.",
  "Инвентарь поселения": "Village inventory",
  "еда": "food",
  "дерево": "wood",
  "камень": "stone",
  "товары": "goods",
  "культура": "culture",
  "кристаллы": "gems",
  "Магазин и предложения": "Shop and offers",
  "Стартовый набор": "Starter pack",
  "Сундук, золото, товары": "Chest, gold and goods",
  "Ежедневный подарок": "Daily gift",
  "Бесплатная награда": "Free reward",
  "Безопасность": "Security",
  "Престиж:": "Prestige:",
  "Выберите здание или раздел меню.": "Select a building or a menu section.",
  "Закрыть панель": "Close panel",
  "Пассивно / мин": "Passive / min",
  "Ресурсы поселения": "Village resources",
  "Раздел": "Section",
  "Закрыть уведомление": "Dismiss notification",
  ": улучшение начато": ": upgrade started",
  "Завершится через": "Ready in",
  "Поверните экран": "Rotate your screen",
  "Для этого раздела лучше подходит горизонтальный режим.": "This section works best in landscape.",
  "Включить координатную сетку разработчика": "Enable developer coordinate grid",
  "Сетка: 100 px · жирные линии: 500 px · координаты ниже = значения для": "Grid: 100px · bold lines: 500px · coordinates for",
  "Мэр Александр": "Mayor Alexander",
  "Зелёная деревня": "Green Village",
  "Очажный зал": "Hearth Hall",
  "Ратуша": "Town Hall",
  "Сердце поселения. Открывает новые стадии, дома, жителей и городские решения.": "The centre of the village, home to civic decisions.",
  "управление": "civic",
  "Главное здание поселения.": "Main settlement building.",
  "Кольцо домов": "Courtyard Homes",
  "Жилые дворы повышают население, мораль и лимит работников.": "Homes increase the village population.",
  "Общий сад": "Community Garden",
  "Ферма": "Farm",
  "Пассивно выращивает еду и запускает сезонные задачи сбора урожая.": "Grows food for production batches.",
  "Лесная артель": "Lumber Camp",
  "Лес": "Forest",
  "Медленно пополняет дерево. Видимо меняется от навеса до лесопилки.": "Produces wood. Upgrades change the camp into a sawmill.",
  "Каменоломня": "Stone Quarry",
  "Добывает камень для дорог, ратуши, мостов и поздних улучшений.": "Produces stone for roads, bridges and upgrades.",
  "Мастерская": "Workshop",
  "Ремесло": "Crafts",
  "Превращает сырьё в товары и ускоряет городское развитие.": "Produces goods for village development.",
  "Торговая площадь": "Market Square",
  "Рынок": "Market",
  "Собирает золото, создаёт заявки, подарки и редкие торговые события.": "The village trading centre.",
  "Дорожное святилище": "Wayside Shrine",
  "Святилище": "Shrine",
  "Культурная точка поселения. Улучшает мораль и открывает благословения.": "A cultural meeting place for residents.",
  "Речной мост": "River Bridge",
  "Мост": "Bridge",
  "Расширяет карту, снижает логистические штрафы и визуально связывает районы.": "Connects the village districts across the river.",
  "Усадьба совета": "Council Manor",
  "Административное здание для долгих целей, указов и городских проектов.": "Home to the council and its village projects.",
  "Хранение": "Storage",
  "Декор": "Decoration",
  "Особые": "Special",
  "Лесопилка": "Sawmill",
  "Рудник": "Mine",
  "Пекарня": "Bakery",
  "Кузница": "Smithy",
  "Мельница": "Windmill",
  "Рыбацкий домик": "Fishing Hut",
  "Пивоварня": "Brewery",
  "Угольная печь": "Charcoal Kiln",
  "Пасека": "Apiary",
  "Кирпичный двор": "Brick Yard",
  "Амбар": "Granary",
  "Погреб товаров": "Goods Cellar",
  "Цветочная площадь": "Flower Square",
  "Роща статуй": "Statue Grove",
  "Праздничная арка": "Festival Arch",
  "Сторожевая башня": "Watchtower",
  "Башня оракула": "Oracle Tower",
  "Кристальный сад": "Crystal Garden",
  "Деревня": "Village",
  "Городок": "Town",
  "Город": "City",
  "Столица": "Capital",
  "Собрать 1000 еды": "Collect 1,000 food",
  "Улучшить Очажный зал до 4 ур.": "Upgrade Hearth Hall to level 4",
  "Довести население до 20": "Reach 20 residents",
  "Накопить 250 культуры": "Store 250 culture",
  "Открыть стадию Городок": "Reach the Town stage",
  "12ч. 45м.": "12h 45m",
  "Достигнуть уровня поселения 15": "Reach village level 15",
  "Развивайте поселение, повышайте уровень.": "Develop your village and increase its level.",
  "Улучшить Ратушу до уровня 10": "Upgrade Town Hall to level 10",
  "Повышайте уровень Ратуши.": "Increase the Town Hall level.",
  "Население 600 жителей": "Reach 600 residents",
  "Увеличьте количество жителей в поселении.": "Increase the village population.",
  "Заработать 5 000 престижа": "Earn 5,000 prestige",
  "Выполняйте цели и развивайте поселение.": "Complete goals and develop your village.",
  "Соберите дерево": "Collect wood",
  "Соберите 800 ед. дерева.": "Collect 800 wood.",
  "Добыть камень": "Mine stone",
  "Добыть 600 ед. камня.": "Mine 600 stone.",
  "Победите врагов": "Defeat enemies",
  "Победите врагов в приключениях: 3": "Defeat 3 enemies in adventures.",
  "Транспортный сундук": "Transport Chest",
  "Бочка хранения": "Storage Barrel",
  "Опечатанный свиток": "Sealed Scroll",
  "Навигационный компас": "Navigation Compass",
  "Памятный знак": "Commemorative Token",
  "Устойчивая деревня": "Established village",
  "Этап 3 из 5": "Stage 3 of 5",
  "Развивайте поселение, выполняя цели и следуя советам.": "Complete goals and follow council advice.",
  "Мастер-строитель": "Master Builder",
  "Улучшите лесопилку до ур. 3": "Upgrade the Sawmill to level 3",
  "Повысит добычу дерева на 25% и ускорит строительство.": "Improve the Sawmill output.",
  "Следовать совету": "Follow advice",
  "Хранительница запасов": "Storekeeper",
  "Увеличьте производство еды": "Increase food output",
  "Запасы еды низкие. Постройте ферму или улучшите существующие.": "Build a farm or upgrade an existing one.",
  "Капитан стражи": "Guard Captain",
  "Укрепите оборону": "Strengthen defences",
  "Постройте сторожевую башню для защиты поселения.": "Build a watchtower to guard the village.",
  "Лесопилка ур. 3": "Sawmill level 3",
  "Высокий приоритет": "High priority",
  "Средний приоритет": "Medium priority",
  "Хозяйство": "Farming",
  "Улучшенные поля": "Improved Fields",
  "Повышает базовую урожайность и подготавливает поля к орошению.": "Prepares fields for better harvests and irrigation.",
  "+8% к производству еды": "+8% food output",
  "+1 к лимиту фермерских участков": "+1 farm plot limit",
  "Ирригация": "Irrigation",
  "Каналы и водосборы снижают потери урожая в сухой сезон.": "Canals and reservoirs support crops in dry weather.",
  "+12% к стабильности еды": "+12% food stability",
  "+1 к запасу воды для ферм": "+1 farm water reserve",
  "Плодородие почв": "Soil Fertility",
  "Требуется Ирригация": "Requires Irrigation",
  "Полевые удобрения открывают поздние бонусы хозяйства.": "Field fertilisers support later farming development.",
  "+15% к росту еды": "+15% food growth",
  "+2 к вместимости амбаров": "+2 granary capacity",
  "Лесопиление": "Lumber Processing",
  "Улучшенная обработка дерева ускоряет плотников и стройку.": "Better wood processing supports carpenters and construction.",
  "+10% к добыче дерева": "+10% wood output",
  "-5% к деревянной стоимости зданий": "-5% wood building cost",
  "Каменная кладка": "Stone masonry",
  "Улучшенные методы обработки камня позволяют строить более прочные и надежные здания.": "Better stonework supports stronger buildings.",
  "+10% к прочности зданий": "+10% building strength",
  "+1 к вместимости Каменоломни": "+1 Stone Quarry capacity",
  "Улучшенные инструменты": "Improved Tools",
  "Требуется Каменная кладка": "Requires Stone masonry",
  "Инструменты мастеров повышают эффективность всех производств.": "Master tools improve production.",
  "+8% к скорости строительства": "+8% construction speed",
  "+6% к добыче ресурсов": "+6% resource output",
  "Хранилища": "Storage Yards",
  "Расширяет безопасные склады для дерева, камня и еды.": "Expands secure stores for wood, stone and food.",
  "+1000 к лимиту склада": "+1,000 storage limit",
  "-10% к потерям при переполнении": "-10% overflow loss",
  "Управление ресурсами": "Resource Management",
  "Учит жителей распределять запасы между складами без простоев.": "Residents learn to distribute stock between stores.",
  "+6% к пассивной добыче": "+6% passive output",
  "+1 к лимиту активных поручений": "+1 active errand limit",
  "Мастерство земледелия": "Farming Mastery",
  "Требуется Управление ресурсами": "Requires Resource Management",
  "Финальный хозяйственный узел для стабильного роста еды.": "Advanced farming knowledge for reliable harvests.",
  "+20% к производству еды": "+20% food output",
  "+2 к поселковому запасу рабочих": "+2 village workers",
  "Торговые меры": "Trade Measures",
  "Единые меры упрощают обмен товаров между кварталами.": "Common measures make trading between districts easier.",
  "+7% к товарам": "+7% goods",
  "+4% к доходу рынка": "+4% market income",
  "Караваны": "Caravans",
  "Открывает безопасные правила для торговых обозов.": "Establishes safe routes for merchant caravans.",
  "+1 к торговым поручениям": "+1 trade errand",
  "+5% к золоту": "+5% gold",
  "Биржевые записи": "Exchange Records",
  "Требуются Караваны": "Requires Caravans",
  "Сводит большие сделки и редкие заявки в одну систему.": "Keeps records of large trades and rare orders.",
  "+12% к крупным заказам": "+12% large order rewards",
  "+1 к лимиту рынка": "+1 market limit",
  "Договоры": "Contracts",
  "Городские договоры ускоряют поставки сырья.": "Village contracts support raw material deliveries.",
  "-6% к цене обмена": "-6% exchange cost",
  "+5% к товарам": "+5% goods",
  "Торговые связи": "Trade Routes",
  "Связывает рынок с внешними поставщиками и повышает доходность заказов.": "Connects the market to outside suppliers.",
  "+10% к золоту рынка": "+10% market gold",
  "+1 к активному торговому заказу": "+1 active trade order",
  "Гильдейские лавки": "Guild Shops",
  "Требуются Торговые связи": "Requires Trade Routes",
  "Лавки гильдий открывают редкие товары и бонусы рынка.": "Guild shops offer rare goods and market bonuses.",
  "+8% к товарам": "+8% goods",
  "+1 редкое предложение": "+1 rare offer",
  "Рыночные склады": "Market Warehouses",
  "Защищает товары от переполнения и задержек.": "Protects goods from overflow and delays.",
  "+800 к лимиту товаров": "+800 goods limit",
  "+5% к скорости сбора": "+5% collection speed",
  "Казначейство": "Treasury",
  "Наводит порядок в налогах и резервах поселения.": "Organises village taxes and reserves.",
  "+6% к золоту": "+6% gold",
  "+1200 к лимиту золота": "+1,200 gold limit",
  "Дальние контракты": "Distant Contracts",
  "Требуется Казначейство": "Requires Treasury",
  "Открывает внешние сделки для поздней стадии поселения.": "Supports foreign trade as the village grows.",
  "+15% к торговым наградам": "+15% trade rewards",
  "+1 маршрут каравана": "+1 caravan route",
  "Праздничный календарь": "Festival Calendar",
  "Упорядочивает праздники, повышая мораль жителей.": "Organises festivals for village residents.",
  "+5% к морали": "+5% morale",
  "+4% к культуре": "+4% culture",
  "Мастерские искусств": "Art Workshops",
  "Ремесленники создают украшения и культурные товары.": "Craftspeople make decorations and cultural goods.",
  "+7% к культуре": "+7% culture",
  "+3% к товарам": "+3% goods",
  "Академия": "Academy",
  "Требуются Мастерские искусств": "Requires Art Workshops",
  "Обучает мастеров и открывает поздние культурные решения.": "Trains craftspeople in advanced cultural skills.",
  "+10% к исследованиям": "+10% research",
  "+1 советник": "+1 advisor",
  "Народные песни": "Folk Songs",
  "Общие песни снижают усталость рабочих.": "Shared songs lighten the workers' day.",
  "+4% к морали": "+4% morale",
  "+4% к скорости сбора": "+4% collection speed",
  "Городская летопись": "Civic Chronicles",
  "Летописцы фиксируют достижения и ускоряют рост престижа.": "Chroniclers record achievements and build prestige.",
  "+8% к престижу": "+8% prestige",
  "+1 к культурному поручению": "+1 cultural errand",
  "Архивы": "Archives",
  "Требуется Городская летопись": "Requires Civic Chronicles",
  "Хранит знания совета и редкие культурные решения.": "Stores council knowledge and rare cultural records.",
  "+12% к культуре": "+12% culture",
  "+1 слот решения": "+1 decision slot",
  "Усадьбы совета": "Council Manors",
  "Улучшает работу советников и снижает задержки поручений.": "Supports advisors and village errands.",
  "+6% к решениям совета": "+6% council decisions",
  "+3% к престижу": "+3% prestige",
  "Наставники": "Mentors",
  "Опытные жители обучают новых рабочих и ускоряют рост поселения.": "Experienced residents train new workers.",
  "+1 к населению от жилья": "+1 resident from homes",
  "Мастерство культуры": "Cultural Mastery",
  "Требуются Наставники": "Requires Mentors",
  "Финальный культурный узел для роста престижа и морали.": "Advanced cultural knowledge for prestige and morale.",
  "+18% к культуре": "+18% culture",
  "+10% к престижу": "+10% prestige",
  "Все": "All",
  "Леса": "Forests",
  "Руины": "Ruins",
  "Опасно": "Danger",
  "Древний лес": "Ancient Forest",
  "Затонувшие руины": "Sunken Ruins",
  "Вулканические горы": "Volcanic Mountains",
  "Ледяные пустоши": "Frozen Wastes",
  "Лёгкая": "Easy",
  "Богатая флора и дикие существа. Много дерева и трав.": "A wild forest rich in wood and herbs.",
  "Средняя": "Medium",
  "Руины старой цивилизации под водой.": "The flooded ruins of an ancient civilisation.",
  "Сложная": "Hard",
  "Опасные земли, но полные редких ресурсов.": "Dangerous land with rare resources.",
  "Закрыто": "Locked",
  "Северный маршрут откроется после роста поселения.": "The northern route opens as the village grows.",
  "Требуется уровень поселения 15": "Requires village level 15",
  "Склад: {0} {1}": "Storage: {0} {1}",
  "{0}: улучшение завершено": "{0}: upgrade complete",
  "Улучшение не завершено: проверьте ресурсы": "Upgrade incomplete: check resources",
  "{0}: изучение завершено": "{0}: research complete",
  "Исследование не завершено: проверьте состояние узла": "Research incomplete: check requirements",
  "{0}: экспедиция вернулась": "{0}: expedition returned",
  "Награды уже забраны": "Rewards already claimed",
  "Цели: забрано {0}": "Goals: claimed {0}",
  "{0}: площадка уже занята": "{0}: plot occupied",
  "{0}: не хватает ресурсов": "{0}: not enough resources",
  "{0} построен: {1}": "{0} built: {1}",
  "{0} снесён: {1}": "{0} demolished: {1}",
  "{0}: требования не выполнены": "{0}: requirements not met",
  "{0}: уже изучено": "{0}: already researched",
  "Исследование уже выполняется": "Research already in progress",
  "{0}: изучение начато": "{0}: research started",
  "{0}: маршрут закрыт": "{0}: route locked",
  "{0} уже в пути": "{0} is already travelling",
  "Экспедиция": "Expedition",
  "{0}: экспедиция отправлена": "{0}: expedition sent",
  "Не хватает ресурсов": "Not enough resources",
  "{0}: улучшение начато": "{0}: upgrade started",
  "Южная терраса": "South Terrace",
  "Западный луг": "West Meadow",
  "Торговый угол": "Market Corner",
  "Речной изгиб": "River Bend",
  "{0}: исследование завершено": "{0}: research complete",
  "Выпуск поселения": "Village batch output",
  "Бонус выпуска": "Output bonus",
  "Улучшение уже выполняется": "Upgrade already in progress"
};

const escape = text => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const patterns = Object.entries(SETTLEMENT_EN)
  .filter(([source]) => /\{\d+\}/.test(source))
  .sort(([a], [b]) => b.replace(/\{\d+\}/g, '').length - a.replace(/\{\d+\}/g, '').length)
  .map(([source, target]) => {
    const slots = [];
    const parts = source.split(/(\{\d+\})/g).map(part => {
      const slot = /^\{(\d+)\}$/.exec(part);
      if (!slot) return escape(part);
      slots.push(slot[1]);
      return '(.*?)';
    });
    return { regex: new RegExp('^' + parts.join('') + '$'), target, slots };
  });

export function translateSettlement(language, value) {
  if (language === 'ru' || typeof value !== 'string' || !/[а-яё]/i.test(value)) return value;
  const source = value.trim();
  let translated = SETTLEMENT_EN[source];
  if (!translated) {
    for (const pattern of patterns) {
      const match = pattern.regex.exec(source);
      if (!match) continue;
      const values = Object.fromEntries(pattern.slots.map((slot, i) => [slot, translateSettlement(language, match[i + 1])]));
      translated = pattern.target.replace(/\{(\d+)\}/g, (_part, slot) => values[slot]);
      break;
    }
  }
  if (!translated) return value;
  return value.slice(0, value.indexOf(source)) + translated + value.slice(value.indexOf(source) + source.length);
}
