/** Bounded diagnostics. No game state, clocks, rewards or persistence are changed. */
export class FrameTelemetry{
 constructor({now=()=>performance.now(),limit=240}={}){this.now=now;this.start=now();this.limit=limit;this.events=[];this.lastPose=null;this.wait=null;this.stats={visibleRafCount:0,maxRafDeltaMs:0,rafOver50Ms:0,rafOver100Ms:0,clampedWallMs:0,maxIdenticalPoseMs:0,mediaWaitCount:0,totalMediaWaitMs:0,maxMediaWaitMs:0,atlasLoads:0,maxAtlasFetchMs:0,maxAtlasDecodeMs:0};}
 push(type,data={}){this.events.push({type,atMs:Math.round((this.now()-this.start)*100)/100,...data});if(this.events.length>this.limit)this.events.splice(0,this.events.length-this.limit);}
 raf(delta,active){if(!active)return;this.stats.visibleRafCount++;this.stats.maxRafDeltaMs=Math.max(this.stats.maxRafDeltaMs,delta);if(delta>50)this.stats.rafOver50Ms++;if(delta>100){this.stats.rafOver100Ms++;this.stats.clampedWallMs+=delta-100;this.push('raf-gap',{deltaMs:delta});}}
 atlas(event){if(event.type==='atlas-ready'){this.stats.atlasLoads++;this.stats.maxAtlasFetchMs=Math.max(this.stats.maxAtlasFetchMs,event.fetchMs);this.stats.maxAtlasDecodeMs=Math.max(this.stats.maxAtlasDecodeMs,event.decodeMs);}this.push(event.type,event);}
 mediaWait(screenMs,hint){if(!this.wait){this.wait={wall:this.now(),screenMs,...hint};this.stats.mediaWaitCount++;this.push('media-wait-start',{screenMs,...hint});}}
 mediaReady(screenMs){if(!this.wait)return;const durationMs=this.now()-this.wait.wall;this.stats.totalMediaWaitMs+=durationMs;this.stats.maxMediaWaitMs=Math.max(this.stats.maxMediaWaitMs,durationMs);this.push('media-wait-end',{durationMs,screenStartMs:this.wait.screenMs,screenEndBeforeAdvanceMs:screenMs,clockHeld:screenMs===this.wait.screenMs,mediaId:this.wait.mediaId,page:this.wait.page});this.wait=null;}
 presented(poses,screenMs){const now=this.now();if(!poses.length){this.lastPose=null;return;}const key=JSON.stringify(poses),media=poses.map(p=>p.mediaId).join('|');if(this.lastPose?.key===key){this.stats.maxIdenticalPoseMs=Math.max(this.stats.maxIdenticalPoseMs,now-this.lastPose.since);return;}if(this.lastPose){const holdMs=now-this.lastPose.since;this.stats.maxIdenticalPoseMs=Math.max(this.stats.maxIdenticalPoseMs,holdMs);if(holdMs>125)this.push('identical-pose-hold',{durationMs:holdMs,mediaId:this.lastPose.media,screenMs});if(this.lastPose.media!==media)this.push('media-switch',{from:this.lastPose.media,to:media,screenMs,poses});}else this.push('first-pose',{screenMs,poses});this.lastPose={key,media,since:now};}
 suspend(reason){this.lastPose=null;if(this.wait){this.push('media-wait-interrupted',{reason,elapsedMs:this.now()-this.wait.wall,screenMs:this.wait.screenMs});this.wait=null;}this.push('timing-suspended',{reason});}
 snapshot(){return{schemaVersion:1,scope:'Local synthetic preview only',timingLimit:'RAF and CPU/canvas submission clocks; GPU/compositor presentation is not measured',eventLimit:this.limit,stats:{...this.stats},activeMediaWait:this.wait?{...this.wait,elapsedMs:this.now()-this.wait.wall}:null,events:this.events.map(e=>({...e}))};}
}
