/** Pure UI controller. Production API remains authoritative; no scoring or answer generation here. */
export class TriviaClock {
  constructor(now = Date.now) { this.now = now; this.reset(null); }
  reset(question) { this.limit = Math.max(1000, (Number(question?.timeLimit) || 15) * 1000); this.elapsed = 0; this.last = this.now(); this.running = !!question; }
  sample() { const at = this.now(); if (this.running) this.elapsed = Math.min(this.limit, this.elapsed + Math.max(0, at - this.last)); this.last = at; return { timeMs: Math.round(this.elapsed), remainingMs: Math.max(0, this.limit - this.elapsed), progress: Math.max(0, 1 - this.elapsed / this.limit) }; }
  freeze() { this.sample(); this.running = false; }
  resume() { this.last = this.now(); this.running = true; }
}
const initial = () => ({ view: 'menu', question: null, mode: 'solo', score: 0, streak: 0, correctCount: 0, paused: false, busy: '', feedback: null, error: null, uncertain: false, uncertainLifeline: false, lifelines: { audience: 1, fifty: 1, reveal: 1 }, hiddenAnswers: [], hintAnswer: '', audiencePoll: {}, roomId: '', duel: null, history: [], historyError: false, historyBusy: false, simulation: false, result: null, timing: { remainingMs: 15000, timeMs: 0, progress: 1 } });
export class TriviaController {
  constructor({ request, now = Date.now, onSnapshot = () => {}, onExit = () => {} }) { this.request = request; this.onSnapshot = onSnapshot; this.onExit = onExit; this.clock = new TriviaClock(now); this.state = initial(); this.listeners = new Set(); this.epoch = 0; this.pollSerial = 0; this.historySerial = 0; this.lock = false; this.disposed = false; this.retryAction = null; this.seenQuestions = new Set(); this.nextIndex = 0; this.roundTotal = 0; this.background = false; }
  subscribe = fn => { this.listeners.add(fn); return () => this.listeners.delete(fn); };
  getSnapshot = () => this.state;
  update(patch) { if (this.disposed) return; this.state = { ...this.state, ...patch }; for (const fn of this.listeners) fn(); }
  activate() { this.disposed = false; this.lock = false; }
  dispose() { this.disposed = true; this.epoch++; this.historySerial++; this.pollSerial++; this.clock.freeze(); this.listeners.clear(); }
  tick() { if (this.state.question && !this.state.paused && !this.state.feedback && !this.state.busy && !this.state.uncertain) this.update({ timing: this.clock.sample() }); }
  setBackground(value) { this.background = !!value; if (this.background) this.pause(); }
  pause() { if (!this.state.question || this.state.paused) return; this.clock.freeze(); this.update({ paused: true, timing: this.clock.sample() }); }
  resume() { if (!this.state.paused) return; if (!this.state.feedback && !this.state.busy && !this.state.uncertain) this.clock.resume(); this.update({ paused: false }); }
  async read(path, body) { try { return await this.request(path, body); } catch { return { error: 'NETWORK_ERROR' }; } }
  async refreshSnapshot() { try { await this.onSnapshot(); } catch { /* Game result is authoritative; shared store owns snapshot retry. */ } }
  fail(data, retry, { answer = false, lifeline = false } = {}) { const uncertain = ['NETWORK_ERROR', 'TIMEOUT'].includes(data?.error) || Number(data?._httpStatus) >= 500 || data?.error === 'INVALID_RESPONSE'; this.retryAction = uncertain && (answer || lifeline) ? null : retry; this.update({ error: { code: String(data?.message || data?.error || 'INVALID_RESPONSE'), uncertain, canRetry: !!this.retryAction, kind: answer ? 'answer' : lifeline ? 'lifeline' : 'request' }, uncertain: this.state.uncertain || (answer && uncertain), uncertainLifeline: this.state.uncertainLifeline || (lifeline && uncertain) }); }
  clearError() { this.retryAction = null; this.update({ error: null }); }
  retry() { if (this.lock) return; const action = this.retryAction; if (action) { this.clearError(); return action(); } }
  async mutate(label, path, body, success, retry, risk = {}) {
    if (this.lock || this.disposed) return false;
    this.lock = true; const epoch = this.epoch; this.clock.freeze(); this.update({ busy: label, error: null, timing: this.clock.sample() });
    let data = await this.read(path, body);
    if (label === 'leave' && path === '/api/trivia/forfeit' && data?.error === 'no session') data = { success: true };
    if (this.disposed || epoch !== this.epoch) return false;
    this.lock = false; this.update({ busy: '' });
    if (data?.error || !data) { this.fail(data || { error: 'INVALID_RESPONSE' }, retry, risk); if (!this.state.paused && !this.state.feedback && !this.state.uncertain) this.clock.resume(); return false; }
    await success(data);
    if (this.state.question && !this.state.paused && !this.state.feedback && !this.state.uncertain) this.clock.resume();
    return true;
  }
  resetQuestionSequence() { this.seenQuestions.clear(); this.nextIndex = 0; this.roundTotal = 0; }
  setQuestion(question, extra = {}) { if (typeof question?.question !== 'string' || !question.question.trim() || !Array.isArray(question.answers) || question.answers.length !== 4 || question.answers.some(a => typeof a !== 'string' || !a.trim()) || new Set(question.answers).size !== 4 || !Number.isInteger(question.index) || !Number.isInteger(question.total) || question.total < 1 || question.index < 0 || question.index >= question.total || question.index !== this.nextIndex || (this.roundTotal && question.total !== this.roundTotal) || this.seenQuestions.has(question.question.trim())) { this.update({ feedback: null }); this.fail({ error: 'INVALID_RESPONSE' }, null, { answer: true }); return; } this.seenQuestions.add(question.question.trim()); this.nextIndex++; this.roundTotal = question.total; this.clock.reset(question); if (this.background) extra = { ...extra, paused: true }; this.update({ question, feedback: null, hiddenAnswers: [], hintAnswer: '', audiencePoll: {}, error: null, uncertain: false, uncertainLifeline: false, timing: this.clock.sample(), ...extra }); if (this.state.paused) this.clock.freeze(); }
  startSolo(difficulty = 'medium') { if (this.state.view !== 'menu') return; return this.mutate('start', '/api/trivia/start', { difficulty }, async data => { this.epoch++; this.resetQuestionSequence(); this.update({ ...initial(), simulation: !!data._offlinePreview, view: 'solo' }); this.setQuestion(data.question); await this.refreshSnapshot(); }, () => this.startSolo(difficulty)); }
  answer(answer) { const s = this.state; if (!s.question || s.paused || s.feedback || s.uncertain || s.hiddenAnswers.includes(answer) || !s.question.answers.includes(answer)) return; const timing = this.clock.sample(); const timeMs = Math.max(1, timing.timeMs); const duel = s.mode === 'duel'; return this.mutate('answer', duel ? '/api/trivia/duel/answer' : '/api/trivia/answer', { ...(duel ? { roomId: s.roomId } : {}), answer, timeMs }, data => { if (typeof data.correct !== 'boolean' || typeof data.correctAnswer !== 'string') { this.fail({ error: 'INVALID_RESPONSE' }, null, { answer: true }); return; } this.update({ score: data.sessionScore ?? s.score, streak: data.streak ?? 0, correctCount: s.correctCount + Number(data.correct), feedback: { ...data, answer, timeMs }, timing }); }, () => this.answer(answer), { answer: true }); }
  next() { const s = this.state; if (!s.feedback || s.paused || this.lock) return; const data = s.feedback; if (data.nextQuestion) { this.setQuestion(data.nextQuestion); return; } this.clock.freeze(); this.update({ view: s.mode === 'duel' ? 'duel-results' : 'results', question: null, feedback: null, result: data, paused: false }); this.refreshSnapshot(); if (s.mode === 'duel') this.poll(); }
  lifeline(type) { const s = this.state; if (s.mode !== 'solo' || !s.question || s.paused || s.feedback || s.uncertain || s.uncertainLifeline || !(s.lifelines[type] > 0)) return; return this.mutate(type, '/api/trivia/lifeline', { type }, data => this.update({ lifelines: data.lifelines || s.lifelines, hiddenAnswers: data.hiddenAnswers || s.hiddenAnswers, hintAnswer: data.correctAnswer || s.hintAnswer, audiencePoll: data.audiencePoll || s.audiencePoll }), () => this.lifeline(type), { lifeline: true }); }
  createDuel(difficulty = 'medium') { if (this.state.view !== 'menu') return; return this.enterRoom('/api/trivia/duel/create', { difficulty }, () => this.createDuel(difficulty)); }
  joinDuel(code) { if (this.state.view !== 'menu') return; const inviteCode = String(code || '').trim().toUpperCase(); if (!inviteCode || inviteCode.length > 32) { this.fail({ error: 'inviteCode required' }, null); return; } return this.enterRoom('/api/trivia/duel/join', { inviteCode }, () => this.joinDuel(code)); }
  enterRoom(path, body, retry) { return this.mutate('room', path, body, data => { if (!data.roomId) { this.fail({ error: 'INVALID_RESPONSE' }, null); return; } this.epoch++; this.resetQuestionSequence(); this.update({ ...initial(), mode: 'duel', view: 'duel-room', roomId: data.roomId, duel: { status: 'waiting', ...data }, simulation: !!data._offlinePreview }); this.poll(); }, retry); }
  ready() { const s = this.state; if (s.view !== 'duel-room' || !s.roomId) return; return this.mutate('ready', '/api/trivia/duel/ready', { roomId: s.roomId }, data => { this.update({ duel: { ...s.duel, ...data } }); this.poll(); }, () => this.ready()); }
  async poll() { const s = this.state; if (!['duel-room', 'duel-results'].includes(s.view) || !s.roomId || this.disposed) return; const epoch = this.epoch, serial = ++this.pollSerial, id = s.roomId; const data = await this.read(`/api/trivia/duel/status/${encodeURIComponent(id)}`); if (this.disposed || epoch !== this.epoch || serial !== this.pollSerial || this.state.roomId !== id) return; if (data?.error) { this.fail(data, () => this.poll()); return; } this.update({ duel: { ...this.state.duel, ...data }, error: this.state.error?.kind === 'request' ? null : this.state.error }); if (data.status === 'active' && this.state.view === 'duel-room' && !this.lock) return this.startDuel(); }
  startDuel() { const s = this.state; if (s.view !== 'duel-room' || s.duel?.status !== 'active') return; return this.mutate('duel-start', '/api/trivia/duel/start', { roomId: s.roomId }, data => { this.update({ view: 'duel-play', score: 0, streak: 0, correctCount: 0, paused: false }); this.setQuestion(data.question); }, () => this.startDuel()); }
  async history() { if (this.disposed) return; const serial = ++this.historySerial; this.update({ historyBusy: true }); const data = await this.read('/api/trivia/duel/history'); if (this.disposed || serial !== this.historySerial) return; this.update({ historyBusy: false, historyError: !!data?.error, history: data?.entries || data?.items || data?.history || [] }); }
  back() { if (this.state.paused) return this.resume(); if (this.state.question) return this.pause(); return this.leave(); }
  async leave(exit = false) { if (this.lock) return; const s = this.state; const finish = async () => { this.epoch++; this.pollSerial++; this.historySerial++; this.clock.reset(null); this.update({ ...initial(), simulation: s.simulation }); await this.refreshSnapshot(); if (exit) this.onExit(); else this.history(); }; if (s.roomId) return this.mutate('leave', '/api/trivia/duel/leave', { roomId: s.roomId }, finish, () => this.leave(exit)); if (s.view === 'solo' && s.mode === 'solo' && !s.feedback?.isComplete) return this.mutate('leave', '/api/trivia/forfeit', {}, finish, () => this.leave(exit)); return finish(); }
}
