import test from 'node:test';import assert from 'node:assert/strict';
import { createDefaultPlayer } from '../game-logic/player.js';
import { createGardenEconomyState, getGardenXpRequired } from '../game-logic/garden-economy.js';
import { getUpgradeCost } from '../game-logic/garden-shelf-plants.js';
import { applyGardenTransaction, getGardenAccounting, reconcileGardenIntent, validateGardenSync, GARDEN_RECEIPT_WINDOW_MS } from '../game-logic/garden-transactions.js';
const now=Date.UTC(2026,9,2,12),stream='test_stream_0123456789';
function player(){const p=createDefaultPlayer('garden-atomic','test',now);p.resources.gold=10000;p.garden={...createGardenEconomyState(now),level:30,xpRequired:getGardenXpRequired(30),shelvesUnlocked:2};return p;}
function payload(p,fields={},sequence=1,createdAt=now){return {...fields,expectedRevision:getGardenAccounting(p).revision,intent:{accountId:p.id,streamId:stream,sequence,createdAt}};}
const id=sequence=>`garden:${stream}:${sequence}`;
function run(p,action,data,sequence=1,time=now){const result=applyGardenTransaction(p,action,data,{clientActionId:id(sequence),now:time,makePlantId:()=>`plant-${sequence}`});if(!result.error){p.garden=result.garden;p.resources.gold=result.gold;p.gardenAccounting=result.accounting;}return result;}
const buy=p=>payload(p,{type:'daisy',shelfIndex:0,spotIndex:0});

test('atomic buy derives debit and creates the plant with one revision',()=>{const p=player(),r=run(p,'garden.buyPlant',buy(p));assert.equal(r.goldDelta,-25);assert.equal(p.resources.gold,9975);assert.equal(p.garden.plants.length,1);assert.equal(p.garden.economicRevision,1);assert.equal(r.receiptConfirmed,true);});
test('insufficient balance and invalid/occupied spots change no player field',()=>{for(const fields of [{type:'daisy',shelfIndex:99,spotIndex:0},{type:'unknown',shelfIndex:0,spotIndex:0}]){const p=player(),before=structuredClone(p);assert.ok(run(p,'garden.buyPlant',payload(p,fields)).error);assert.deepEqual(p,before);}const p=player();p.resources.gold=0;const before=structuredClone(p);assert.equal(run(p,'garden.buyPlant',buy(p)).error,'GARDEN_INSUFFICIENT_GOLD');assert.deepEqual(p,before);});
test('lost response replay debits exactly once, including beyond generic receipt retention',()=>{const p=player(),data=buy(p);run(p,'garden.buyPlant',data);const r=run(p,'garden.buyPlant',data,1,now+10*86400000);assert.equal(r.duplicate,true);assert.equal(p.resources.gold,9975);assert.equal(p.garden.plants.length,1);const status=reconcileGardenIntent(p,{action:'garden.buyPlant',payload:data,clientActionId:id(1)},now+10*86400000);assert.equal(status.intentStatus,'applied');});
test('same ID with changed payload is rejected without another debit',()=>{const p=player(),data=buy(p);run(p,'garden.buyPlant',data);const before=structuredClone(p);assert.equal(run(p,'garden.buyPlant',{...data,spotIndex:1}).error,'GARDEN_INTENT_CONFLICT');assert.deepEqual(p,before);});
test('old unknown intents fail closed instead of guessing whether money moved',()=>{const p=player(),data=payload(p,{type:'daisy',shelfIndex:0,spotIndex:0},1,now-GARDEN_RECEIPT_WINDOW_MS-1);assert.equal(run(p,'garden.buyPlant',data).error,'GARDEN_INTENT_AMBIGUOUS');assert.equal(reconcileGardenIntent(p,{action:'garden.buyPlant',payload:data,clientActionId:id(1)},now).error,'GARDEN_INTENT_AMBIGUOUS');assert.equal(p.resources.gold,10000);});
test('known stream next sequence can be reconciled as not applied after 72h',()=>{const p=player();run(p,'garden.buyPlant',buy(p));const data=payload(p,{type:'daisy',shelfIndex:0,spotIndex:1},2,now);const status=reconcileGardenIntent(p,{action:'garden.buyPlant',payload:data,clientActionId:id(2)},now+10*86400000);assert.equal(status.intentStatus,'notApplied');assert.equal(run(p,'garden.buyPlant',data,2,now+10*86400000).goldDelta,-25);});
test('stale full state cannot erase an atomic purchase',()=>{const p=player(),before=structuredClone(p.garden);run(p,'garden.buyPlant',buy(p));assert.equal(validateGardenSync(p.garden,before,p.gardenAccounting).error,'GARDEN_REVISION_CONFLICT');const forged={...before,economicRevision:1};assert.equal(validateGardenSync(p.garden,forged,p.gardenAccounting).error,'GARDEN_ECONOMIC_STATE_CONFLICT');});
test('upgrade and sell derive server amounts and change entities with money',()=>{const p=player();run(p,'garden.buyPlant',buy(p));p.garden.plants[0].phase=3;const up=payload(p,{plantId:'plant-1',cost:0},2);const r=run(p,'garden.upgradePlant',up,2);assert.equal(r.goldDelta,-getUpgradeCost(25,1));assert.equal(p.garden.plants[0].level,2);const sale=run(p,'garden.sellPlant',payload(p,{plantId:'plant-1',refund:999999},3),3);assert.equal(sale.goldDelta,12);assert.equal(p.garden.plants.length,0);});
test('quest reward and claim marker commit together and cannot be erased by sync',()=>{const p=player();run(p,'garden.buyPlant',buy(p));const claim=payload(p,{questId:'first_plant',reward:999999},2);const r=run(p,'garden.claimQuest',claim,2);assert.ok(r.goldDelta>0&&r.goldDelta<999999);assert.ok(p.garden.claimedQuests.includes('first_plant'));const balance=p.resources.gold;assert.equal(run(p,'garden.claimQuest',claim,2).duplicate,true);assert.equal(p.resources.gold,balance);const stale={...p.garden,claimedQuests:[]};assert.equal(validateGardenSync(p.garden,stale,p.gardenAccounting).error,'GARDEN_ECONOMIC_STATE_CONFLICT');});
test('claim readiness and mature upgrade requirements are enforced',()=>{const p=player();assert.equal(run(p,'garden.claimQuest',payload(p,{questId:'first_plant'})).error,'GARDEN_QUEST_NOT_READY');run(p,'garden.buyPlant',buy(p));assert.equal(run(p,'garden.upgradePlant',payload(p,{plantId:'plant-1'},2),2).error,'GARDEN_PLANT_NOT_MATURE');});
test('earned credit atomically checkpoints growth and uses an independent high-water total',()=>{const p=player();p.gardenAccounting=getGardenAccounting(p);const checkpoint={...p.garden,totalGoldEarned:17,lastTick:now+1000};const data=payload(p,{throughTotal:17,state:checkpoint});const r=run(p,'garden.creditEarned',data);assert.equal(r.goldDelta,17);assert.equal(p.garden.totalGoldEarned,17);assert.equal(p.garden.lastTick,now+1000);assert.equal(p.gardenAccounting.creditedTotal,17);assert.equal(p.gardenAccounting.revision,0);assert.equal(run(p,'garden.creditEarned',data).duplicate,true);assert.equal(p.resources.gold,10017);});
test('concurrent equal cumulative earnings on distinct streams cannot double-credit',()=>{const p=player();p.gardenAccounting=getGardenAccounting(p);const checkpoint={...p.garden,totalGoldEarned:23};run(p,'garden.creditEarned',payload(p,{throughTotal:23,state:checkpoint}));const data={...payload(p,{throughTotal:23,state:checkpoint}),intent:{accountId:p.id,streamId:'other_stream_0123456',sequence:1,createdAt:now}};const result=applyGardenTransaction(p,'garden.creditEarned',data,{clientActionId:'garden:other_stream_0123456:1',now});assert.equal(result.goldDelta,0);assert.equal(result.gold,10023);});
test('a stale earnings checkpoint cannot rewind time or resurrect a sold plant',()=>{const p=player();run(p,'garden.buyPlant',buy(p));const saved=structuredClone(p.garden);run(p,'garden.sellPlant',payload(p,{plantId:'plant-1'},2),2);const r=run(p,'garden.creditEarned',payload(p,{throughTotal:5,state:{...saved,totalGoldEarned:5}},3),3);assert.equal(r.error,'GARDEN_REVISION_CONFLICT');assert.equal(p.garden.plants.length,0);});
test('old saves initialize metadata without changing their state or balance',()=>{const p=player();delete p.garden.economicRevision;delete p.garden.acknowledgedEarnedTotal;p.garden.totalGoldEarned=750;const before=structuredClone(p);const metadata=getGardenAccounting(p);assert.equal(metadata.creditedTotal,750);assert.equal(metadata.revision,0);assert.deepEqual(p,before);});
test('two commands against one economic revision cannot both spend against stale state',()=>{const p=player(),first=buy(p),second={...payload(p,{type:'daisy',shelfIndex:0,spotIndex:1}),intent:{accountId:p.id,streamId:'other_stream_0123456',sequence:1,createdAt:now}};run(p,'garden.buyPlant',first);const r=applyGardenTransaction(p,'garden.buyPlant',second,{clientActionId:'garden:other_stream_0123456:1',now});assert.equal(r.error,'GARDEN_REVISION_CONFLICT');assert.equal(p.resources.gold,9975);assert.equal(p.garden.plants.length,1);});
test('server rejects a durable intent authenticated as a different account',()=>{const p=player(),data=buy(p);data.intent.accountId='another-account';assert.equal(run(p,'garden.buyPlant',data).error,'GARDEN_ACCOUNT_MISMATCH');assert.equal(p.resources.gold,10000);assert.equal(p.garden.plants.length,0);});
test('existing level reward and level transition are atomic and not re-credited as passive earnings',()=>{const p=player();p.garden.xp=p.garden.xpRequired;p.garden.levelReady=true;const result=run(p,'garden.levelUp',payload(p));assert.equal(result.reward,27060);assert.equal(p.garden.level,31);assert.equal(p.garden.xp,0);assert.equal(p.gardenAccounting.creditedTotal,27060);assert.equal(p.resources.gold,37060);assert.equal(run(p,'garden.levelUp',payload({...p,gardenAccounting:{...p.gardenAccounting,revision:0}})).duplicate,true);assert.equal(p.resources.gold,37060);});
test('large earned totals use bounded acknowledged batches without changing the cumulative entitlement',()=>{const p=player();p.gardenAccounting=getGardenAccounting(p);const checkpoint={...p.garden,totalGoldEarned:1_000_000_037};const a=run(p,'garden.creditEarned',payload(p,{throughTotal:checkpoint.totalGoldEarned,state:checkpoint}));assert.equal(a.goldDelta,1_000_000_000);assert.equal(p.gardenAccounting.creditedTotal,1_000_000_000);const b=run(p,'garden.creditEarned',payload(p,{throughTotal:checkpoint.totalGoldEarned,state:checkpoint},2),2);assert.equal(b.goldDelta,37);assert.equal(p.gardenAccounting.creditedTotal,checkpoint.totalGoldEarned);assert.equal(p.resources.gold,1_000_010_037);});
test('inactive stream records are retired at capacity without creating a lifetime lockout',()=>{const p=player();p.gardenAccounting=getGardenAccounting(p);for(let i=0;i<128;i++)p.gardenAccounting.streams[`inactive_stream_${String(i).padStart(8,'0')}`]={sequence:1,appliedAt:now-GARDEN_RECEIPT_WINDOW_MS-6*60000,clientActionId:'historical',hash:'retained',result:{goldDelta:0}};const result=run(p,'garden.buyPlant',buy(p));assert.equal(result.receiptConfirmed,true);assert.equal(Object.keys(p.gardenAccounting.streams).length,1);const old=payload(p,{type:'daisy',shelfIndex:0,spotIndex:1},1,now-GARDEN_RECEIPT_WINDOW_MS-6*60000);old.intent.streamId='inactive_stream_00000000';const replay=applyGardenTransaction(p,'garden.buyPlant',old,{clientActionId:'garden:inactive_stream_00000000:1',now});assert.equal(replay.error,'GARDEN_INTENT_AMBIGUOUS');assert.equal(p.resources.gold,9975);});
test('recent stream capacity is a temporary fail-closed limit, never a partial debit',()=>{const p=player();p.gardenAccounting=getGardenAccounting(p);for(let i=0;i<128;i++)p.gardenAccounting.streams[`recent_stream_${i}`]={sequence:1,appliedAt:now};const before=structuredClone(p);assert.equal(run(p,'garden.buyPlant',buy(p)).error,'GARDEN_ACCOUNTING_CAPACITY');assert.deepEqual(p,before);});
test('future intent timestamps cannot evade the retired-stream age fence',()=>{const p=player(),data=payload(p,{type:'daisy',shelfIndex:0,spotIndex:0},1,now+121000);assert.equal(run(p,'garden.buyPlant',data).error,'GARDEN_CLOCK_INVALID');assert.equal(p.resources.gold,10000);});
