import test from 'node:test';import assert from 'node:assert/strict';
import {createGardenTransactionCoordinator,reconcileGardenCheckpoint,GARDEN_RECEIPT_WINDOW_MS} from '../src/games/garden-shelf/lib/gardenTransactions.js';
const now=Date.UTC(2026,9,2),uuid=()=> 'ledger_stream_01234567';
function storage(){const values=new Map();return {getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value),values};}
const ok=(payload,options)=>({success:true,receiptConfirmed:true,clientActionId:options.clientActionId,snapshot:{garden:{acknowledgedEarnedTotal:payload.throughTotal||0}}});
function create(store,transport,extra={}){return createGardenTransactionCoordinator({accountId:'account-a',storage:store,transport,reconcile:async()=>({intentStatus:'notApplied'}),now:()=>now,uuid,...extra});}
test('intent is durably persisted before the first network call',async()=>{const store=storage();const c=create(store,async(_action,payload,options)=>{const persisted=JSON.parse(store.values.values().next().value);assert.equal(persisted.pending.clientActionId,options.clientActionId);assert.deepEqual(persisted.pending.payload,payload);return ok(payload,options);});const result=await c.execute('garden.buyPlant',{type:'daisy'});assert.equal(result.receiptConfirmed,true);assert.equal(c.inspect().pending,null);assert.equal(c.inspect().nextSequence,2);});
test('failed request survives reload and retries with identical ID and payload',async()=>{const store=storage(),seen=[];const first=create(store,async(a,p,o)=>(seen.push([a,p,o.clientActionId]),{error:'NETWORK_ERROR'}));await first.execute('garden.buyPlant',{type:'daisy'});assert.ok(first.inspect().pending);const second=create(store,async(a,p,o)=>(seen.push([a,p,o.clientActionId]),ok(p,o)));await second.recover();assert.deepEqual(seen[0],seen[1]);assert.equal(second.inspect().pending,null);});
test('lost response is retried with the original immutable payload instead of a new purchase',async()=>{const store=storage(),seen=[];let calls=0;const c=create(store,async(a,p,o)=>{seen.push([a,p,o.clientActionId]);return ++calls===1?{error:'TIMEOUT'}:ok(p,o);});await c.execute('garden.buyPlant',{type:'daisy'});const result=await c.execute('garden.buyPlant',{type:'basil'});assert.equal(result.recoveredIntent,true);assert.deepEqual(seen[0],seen[1]);assert.equal(seen.length,2);});
test('pending true or missing receipt confirmation never clears a durable intent',async()=>{for(const result of [{success:true,pending:true},{success:true}]){const c=create(storage(),async()=>result);assert.equal((await c.execute('garden.creditEarned',{throughTotal:10})).error,'GARDEN_REQUEST_UNCONFIRMED');assert.ok(c.inspect().pending);}});
test('wrong receipt identity cannot acknowledge another credit batch',async()=>{const c=create(storage(),async()=>({success:true,receiptConfirmed:true,clientActionId:'wrong'}));assert.equal((await c.execute('garden.creditEarned',{throughTotal:10})).error,'GARDEN_REQUEST_UNCONFIRMED');assert.ok(c.inspect().pending);});
test('storage failure prevents sending any economic request',async()=>{let sent=0;const c=create({getItem:()=>null,setItem:()=>{throw Error('quota');}},async()=>{sent++;});assert.equal((await c.execute('garden.buyPlant',{})).error,'GARDEN_STORAGE_UNAVAILABLE');assert.equal(sent,0);});
test('definite server rejection clears payload but does not consume stream sequence',async()=>{const c=create(storage(),async()=>({error:'GARDEN_INSUFFICIENT_GOLD',_httpStatus:400}));await c.execute('garden.buyPlant',{});assert.equal(c.inspect().pending,null);assert.equal(c.inspect().nextSequence,1);});
test('ambiguity beyond retention triggers reconciliation and never blind replay',async()=>{const store=storage();const first=create(store,async()=>({error:'TIMEOUT'}));await first.execute('garden.buyPlant',{});let sends=0,queries=0;const next=create(store,async()=>{sends++;},{now:()=>now+GARDEN_RECEIPT_WINDOW_MS+1,reconcile:async()=>{queries++;return {error:'GARDEN_INTENT_AMBIGUOUS'};}});assert.equal((await next.recover()).error,'GARDEN_INTENT_AMBIGUOUS');assert.equal(sends,0);assert.equal(queries,1);assert.ok(next.inspect().pending);});
test('long-delayed applied receipt is acknowledged without sending the mutation again',async()=>{const store=storage();const first=create(store,async()=>({error:'TIMEOUT'}));await first.execute('garden.buyPlant',{});const pending=first.inspect().pending;const next=create(store,async()=>{throw Error('must not send');},{now:()=>now+GARDEN_RECEIPT_WINDOW_MS+1,reconcile:async()=>({intentStatus:'applied',clientActionId:pending.clientActionId})});assert.equal((await next.recover()).receiptConfirmed,true);assert.equal(next.inspect().pending,null);});
test('account-scoped storage never replays another account intent',async()=>{const store=storage();await create(store,async()=>({error:'TIMEOUT'})).execute('garden.buyPlant',{});let sent=0;const other=create(store,async()=>{sent++;},{accountId:'account-b'});assert.equal((await other.recover()).noPending,true);assert.equal(sent,0);});
test('concurrent calls are serialized and receive distinct acknowledged sequences',async()=>{const seen=[];const c=create(storage(),async(a,p,o)=>{seen.push(o.clientActionId);await new Promise(r=>setTimeout(r,5));return ok(p,o);});await Promise.all([c.execute('garden.buyPlant',{spot:0}),c.execute('garden.buyPlant',{spot:1})]);assert.equal(new Set(seen).size,2);assert.equal(c.inspect().nextSequence,3);});
test('reconciliation keeps server economic fields and monotonic surviving-plant growth',()=>{const local={plants:[{id:'kept',type:'daisy',level:1,phase:2,phaseProgress:20},{id:'sold',type:'daisy',level:1,phase:3}],totalGoldEarned:20,lastTick:100,level:1,xp:10};const server={plants:[{id:'kept',type:'daisy',level:2,phase:1,phaseProgress:5},{id:'new',type:'fern',level:1,phase:0}],totalGoldEarned:30,lastTick:90,level:1,xp:5,xpRequired:90,economicRevision:2};const r=reconcileGardenCheckpoint(local,server);assert.deepEqual(r.plants.map(p=>p.id),['kept','new']);assert.equal(r.plants[0].level,2);assert.equal(r.plants[0].phase,2);assert.equal(r.totalGoldEarned,30);assert.equal(r.lastTick,100);assert.equal(r.economicRevision,2);});
test('acknowledgment storage failure retains the original intent for later reconciliation',async()=>{const store=storage();let writes=0;const original=store.setItem;store.setItem=(key,value)=>{if(++writes===2)throw Error('quota after commit');original(key,value);};const c=create(store,async(a,p,o)=>ok(p,o));assert.equal((await c.execute('garden.buyPlant',{})).error,'GARDEN_STORAGE_UNAVAILABLE');assert.ok(c.inspect().pending);const recovered=await c.recover();assert.equal(recovered.receiptConfirmed,true);assert.equal(c.inspect().pending,null);});
test('account switch cannot transmit or discard a previous account pending intent',async()=>{const store=storage();let current=true,sent=0;const c=create(store,async()=>{sent++;return {error:'TIMEOUT'};},{isCurrentAccount:()=>current});await c.execute('garden.buyPlant',{});current=false;assert.equal((await c.recover()).error,'GARDEN_ACCOUNT_CHANGED');assert.equal(sent,1);assert.ok(c.inspect().pending);assert.equal((await c.execute('garden.sellPlant',{})).error,'GARDEN_ACCOUNT_CHANGED');assert.equal(sent,1);});
test('a rejected lock acquisition cannot send or throw an unhandled promise',async()=>{let sent=0;const c=create(storage(),async()=>{sent++;},{withLock:async()=>{throw Error('storage denied');}});assert.equal((await c.recover()).error,'GARDEN_STORAGE_UNAVAILABLE');assert.equal((await c.execute('garden.buyPlant',{})).error,'GARDEN_STORAGE_UNAVAILABLE');assert.equal(sent,0);});
test('acknowledged inactive browser streams rotate safely before a new intent',async()=>{let time=now,number=0;const ids=[],c=create(storage(),async(a,p,o)=>(ids.push(o.clientActionId),ok(p,o)),{now:()=>time,uuid:()=>`rotation_stream_${++number}`});await c.execute('garden.buyPlant',{});time+=GARDEN_RECEIPT_WINDOW_MS+1;await c.execute('garden.buyPlant',{});assert.notEqual(ids[0],ids[1]);assert.ok(ids.every(id=>id.endsWith(':1')));});
test('archiving an ambiguous intent requires explicit confirmation and sends no charge',async()=>{const store=storage();let sent=0,number=0;const c=create(store,async()=>{sent++;return {error:'TIMEOUT'};},{uuid:()=>`archive_stream_${++number}`});await c.execute('garden.buyPlant',{});const original=c.inspect().pending;assert.equal((await c.abandonPending()).error,'GARDEN_CONFIRMATION_REQUIRED');assert.deepEqual(c.inspect().pending,original);const result=await c.abandonPending({confirmed:true,expectedClientActionId:original.clientActionId});assert.equal(result.success,true);assert.equal(c.inspect().pending,null);assert.notEqual(c.inspect().streamId,original.payload.intent.streamId);assert.equal(JSON.parse(store.getItem(`${c.key}:archive:${original.clientActionId}`)).pending.clientActionId,original.clientActionId);assert.equal(sent,1);});
test('monotonic server clock estimates produce integer intent timestamps',async()=>{const c=create(storage(),async(a,p,o)=>{assert.equal(Number.isSafeInteger(p.intent.createdAt),true);return ok(p,o);},{now:()=>now+.9});await c.execute('garden.buyPlant',{});});

test('confirmation cannot archive a different pending intent replaced by another tab',async()=>{const store=storage(),c=create(store,async()=>({error:'TIMEOUT'}));await c.execute('garden.buyPlant',{});const pending=c.inspect().pending;const result=await c.abandonPending({confirmed:true,expectedClientActionId:'an-older-intent'});assert.equal(result.error,'GARDEN_INTENT_CHANGED');assert.deepEqual(c.inspect().pending,pending);});
