import { sampleRig, rigEventsBetween } from '/_rig/rig-motion.js';
const canvas=document.querySelector('#scene'),context=canvas.getContext('2d'),status=document.querySelector('#status'),modeInput=document.querySelector('#mode'),rateInput=document.querySelector('#rate'),timeline=document.querySelector('#timeline'),boneInput=document.querySelector('#bones');
const manifest=await(await fetch('/games/yard-v2-rig-prototype/rig-manifest.json')).json();
const load=url=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Failed local asset '+url));i.src=url;});
const images=Object.fromEntries(await Promise.all(Object.entries(manifest.parts).map(async([k,v])=>[k,await load(v.url)])));const stage=await load(manifest.stage.url);
let running=true,elapsed=0,previous=0,last=performance.now(),contacts=0,raf=0,cssW=1,cssH=1;
const mode=()=>modeInput.value;
const rigOptions=()=>({mode:mode(),origin:{x:mode()==='walk'?420:710,y:mode()==='walk'?805:865},speed:75,scale:1.5,ankleOffset:manifest.ankleOffset});
function resize(){const r=canvas.getBoundingClientRect();cssW=r.width;cssH=r.height;const dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.round(cssW*dpr));canvas.height=Math.max(1,Math.round(cssH*dpr));context.setTransform(dpr,0,0,dpr,0,0);draw();}
const depth=a=>a.limbId?.startsWith('near')?(a.kind==='upperLeg'?25:a.kind==='lowerLeg'?35:34):(a.kind==='paw'?a.depth-1.5:a.depth);
function sprite(key,position,pivot,scale,rotation,far=false){const im=images[key];context.save();context.translate(position.x,position.y);context.rotate(rotation);context.scale(scale,scale);if(far)context.filter='brightness(84%)';context.drawImage(im,-pivot[0]*im.width,-pivot[1]*im.height);context.restore();}
function draw(){if(!stage)return;context.clearRect(0,0,cssW,cssH);const fit=Math.min(cssW/stage.width,cssH/stage.height),ox=(cssW-stage.width*fit)/2,oy=(cssH-stage.height*fit)/2;context.save();context.translate(ox,oy);context.scale(fit,fit);context.drawImage(stage,0,0);
 const opts=rigOptions();const rig=sampleRig(elapsed,opts);
 context.fillStyle='rgba(40,53,27,.17)';for(const l of rig.limbs)if(l.planted){context.beginPath();context.ellipse(l.foot.x,l.foot.y+1,12,4,0,0,Math.PI*2);context.fill();}
 for(const a of [...rig.attachments].sort((a,b)=>depth(a)-depth(b))){const key=a.kind==='upperLeg'?(a.family==='fore'?'fore-upper':'hind-upper'):a.kind==='lowerLeg'?'shin':a.kind;const m=manifest.parts[key],im=images[key];let pivot,sc,rot;
 if(a.kind==='upperLeg'||a.kind==='lowerLeg'){pivot=m.jointA;const dx=(m.jointB[0]-pivot[0])*im.width,dy=(m.jointB[1]-pivot[1])*im.height;sc=a.length/Math.hypot(dx,dy);rot=a.rotation-Math.atan2(dy,dx);}else{pivot=m.pivot;sc=(m.displayWidth?m.displayWidth/im.width:m.displayHeight/im.height)*rig.scale;rot=a.rotation-(m.referenceAngle||0);}sprite(key,a.position,pivot,sc,rot,a.limbId?.startsWith('far'));}
 if(rig.mouse){const m=manifest.parts.mouse;sprite('mouse',rig.mouse.contactPoint||rig.mouse.position,m.pivot,m.displayWidth/images.mouse.width*rig.scale,rig.mouse.rotation||0);}
 if(boneInput.checked){context.lineWidth=2/fit;for(const l of rig.limbs){context.strokeStyle=context.fillStyle=l.planted?'#00efba':'#ff54d9';context.beginPath();context.moveTo(l.hip.x,l.hip.y);context.lineTo(l.knee.x,l.knee.y);context.lineTo(l.foot.x,l.foot.y);context.stroke();for(const p of[l.hip,l.knee,l.foot]){context.beginPath();context.arc(p.x,p.y,3/fit,0,Math.PI*2);context.fill();}}}
 context.restore();status.textContent=`${rig.phase} • ${Math.round(elapsed)} ms • contacts ${contacts} • ${rig.reachable?'all IK targets reachable':'UNREACHABLE TARGET'} • frame-independent world-space supports`;
 canvas.dataset.phase=rig.phase;canvas.dataset.elapsedMs=String(Math.round(elapsed));canvas.dataset.reachable=String(rig.reachable);canvas.dataset.contacts=String(contacts);timeline.value=String(Math.round(elapsed));}
function reset(){elapsed=previous=contacts=0;timeline.max=mode()==='play'?'1800':'4000';last=performance.now();draw();}
function tick(now){const dt=Math.min(60,Math.max(0,now-last));last=now;if(running&&!document.hidden){previous=elapsed;elapsed+=dt*Number(rateInput.value);if(mode()==='play'){contacts+=rigEventsBetween(previous,elapsed,rigOptions()).length;elapsed=Math.min(1800,elapsed);}else if(elapsed>=4000){elapsed%=4000;contacts=0;}}draw();raf=requestAnimationFrame(tick);}
document.querySelector('#toggle').onclick=()=>{running=!running;document.querySelector('#toggle').textContent=running?'Pause':'Resume';};document.querySelector('#restart').onclick=reset;modeInput.onchange=reset;timeline.oninput=()=>{running=false;document.querySelector('#toggle').textContent='Resume';elapsed=previous=Number(timeline.value);contacts=mode()==='play'&&elapsed>=900?1:0;draw();};boneInput.onchange=draw;rateInput.onchange=()=>{last=performance.now();};document.addEventListener('visibilitychange',()=>{last=performance.now();});new ResizeObserver(resize).observe(canvas.parentElement);window.addEventListener('pagehide',()=>cancelAnimationFrame(raf),{once:true});reset();resize();raf=requestAnimationFrame(tick);
