import {createCourtyardAdapter,SAVE_KEY,PREVIEW_SCENE} from '../../prototype/yard-courtyard-preview-r5/adapter.mjs';
import {browserKernel as kernel} from '../../prototype/yard-courtyard-preview-r5/browser/kernel.mjs';
import {createProjection,footprintPolygon} from './projection.mjs';
import {AtlasCache,atlasPageFor} from './atlas.mjs';
import {FrameTelemetry} from './telemetry.mjs';
import {nextMediaHint} from './media-lookahead.mjs';
import {WALK_PHASE_UNITS_96} from '../../prototype/yard-courtyard-preview-r5/walk-phase-lookup.mjs';
import {edgeOpacity} from './edge-opacity.mjs';
import {selectPetPose} from './pose-selection.mjs';
import {demoRunId,demoSaveKey,beginDemoReplay} from './demo-save.mjs';
const $=id=>document.getElementById(id),canvas=$('yard'),ctx=canvas.getContext('2d'),panel=$('panel');
const trace=[],errors=[];window.addEventListener('error',e=>errors.push({message:e.message,source:e.filename,line:e.lineno}));window.addEventListener('unhandledrejection',e=>errors.push({message:String(e.reason)}));
const requestedScenario=new URLSearchParams(location.search).get('scenario')==='cushion'?'cushion':'mouse';const currentDemoRun=(()=>{try{return demoRunId(localStorage,SAVE_KEY,requestedScenario)}catch{return 'initial'}})(),HOST_SAVE_KEY=demoSaveKey(SAVE_KEY,requestedScenario,currentDemoRun);
const knownNames={yarn_mouse:'Мышка',sun_cushion:'Подушка',kibble:'Корм',berry_plate:'Ягоды',bonito_bowl:'Бонито',alchemy_living_arbor:'Живая беседка',alchemy_echo_chimes:'Колокольчики эха'};
const name=id=>knownNames[id]||id;let rawSaveText=null,rawBackupText=null;let session,backup,adapter,view,media,stillMeta,projection,selected=null,ghost=null,drag=null,paused=false,last=performance.now(),lastPersist=0,clockRemainder=0,lastUi='',firstFrameReady=false;
const timing=new FrameTelemetry(),images=new Map(),atlas=new AtlasCache(undefined,3,{onEvent:e=>timing.atlas(e)});const config=PREVIEW_SCENE;
async function image(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error(`Missing image ${src}`));im.src=src;});}
function log(type,data={}){trace.push({at:Math.round(performance.now()),type,...data});if(trace.length>500)trace.shift();}
function fatal(error){paused=true;const box=$('fatal');box.hidden=false;box.replaceChildren();const title=document.createElement('h2');title.textContent='Preview остановлен';const message=document.createElement('p');message.textContent=String(error?.message||error);const detail=document.createElement('p');detail.textContent='Сохранение оставлено без изменений. Его можно приложить к отчёту проверки.';const b=document.createElement('button');b.textContent='Скачать отчёт';b.className='wide-button';b.onclick=exportQA;box.append(title,message,detail,b);log('fatal',{message:String(error)});}
function persist(){if(!session)return;try{const key=`${SAVE_KEY}:origin:${backup.id}`;if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(backup));const encoded=adapter.encode(session);localStorage.setItem(HOST_SAVE_KEY,encoded.value);}catch(e){log('save-failed',{message:String(e)});$('status').textContent='Не удалось сохранить: хранилище недоступно';}}
function download(filename,text){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportQA(){download(`yard-preview-qa-${Date.now()}.json`,JSON.stringify({build:'courtyard-preview-r2b-cadence',userAgent:navigator.userAgent,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},scene:canvas.getBoundingClientRect().toJSON(),errors,trace,rawSaveText,rawBackupText,save:session?adapter.encode(session):null,backup,timing:timing.snapshot(),checks:{actualBrowserRun:true,artApproved:false,productionConnected:false}},null,2));}
function action(type,payload={}){if(!session)return;const nonce=globalThis.crypto?.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint32Array(3))).map(v=>v.toString(36)).join('-');const id=`preview:${Date.now().toString(36)}:${nonce}`;const result=adapter.action(session,{action:type,payload,actionId:id});session=result.session;view=adapter.view(session);log(type,{status:result.status,details:result.details});persist();refresh();if(type==='yard.setFood'&&result.status===200)warmWalkPages();return result;}
function status(){if(view.blocker)return 'Анимация недоступна: состояние визита сохранено';if(ghost)return ghost.valid?'Место свободно · нажмите «Поставить»':'Здесь нельзя поставить предмет';if(view.pendingGifts.length)return 'Mika оставила подарок · откройте «Гости»';if(view.pets.length){const p=view.pets[0];return p.motion?.kind==='turn'?'Mika поворачивается · движения 1×':p.phase==='active-clip'?(p.clipId.includes('cushion')?'Mika отдыхает · движения 1×':'Mika играет · движения 1×'):'Mika во дворе · движения 1×';}if(view.episodeComplete)return 'Встреча завершена · подарки и предметы сохранены';if(view.bowls.some(b=>b.foodId&&b.servings>0))return 'Ждём гостя · ожидание ускорено';return 'Положите корм, чтобы начать встречу';}
function refresh(){if(!view)return;$('wallet').textContent=`● ${view.currencies.treats}`;$('food-summary').textContent=view.bowls.some(b=>b.foodId&&b.servings>0)?'Миска полна':'Добавить корм';$('decor-summary').textContent=`${view.props.length} предмета`;$('guest-summary').textContent=view.pendingGifts.length?`Подарок · ${view.pendingGifts.length}`:view.pets.length?'Mika':'Ждём друзей';const text=status();if(text!==lastUi){$('status').textContent=text;lastUi=text;}}
function openPanel(kind){$('panel-content').replaceChildren();$('panel-title').textContent={food:'Еда',decor:'Предметы',guests:'Гости'}[kind];const body=$('panel-content');const p=document.createElement('p');p.className='muted';
 if(kind==='food'){p.textContent='В этой пробе ожидание сокращено. Походка и взаимодействия идут с обычной скоростью.';body.append(p);const count=view.foodInventory.kibble||0;row(body,'Корм',`В запасе: ${count} · одна встреча Mika`,'Наполнить',()=>{const r=action('yard.setFood',{foodId:'kibble',bowlId:'bowl-1'});if(r.status===200)panel.close();else p.textContent=r.error||'Корм пока недоступен';},!view.canFeed);}
 if(kind==='decor'){p.textContent='Выберите предмет, затем место в траве. Во время взаимодействия предмет занят.';body.append(p);for(const prop of view.props)row(body,name(prop.goodieId),prop.reserved?'Mika заняла предмет':'Можно переместить','Выбрать',()=>{panel.close();selectProp(prop);},prop.reserved);const inventory=session.kernel.player.yard.goodieInventory||{};const h=document.createElement('h3');h.textContent='Весь сохранённый инвентарь';body.append(h);for(const [id,count]of Object.entries(inventory)){const line=document.createElement('p');line.className='muted';line.textContent=`${name(id)} × ${count}${!['yarn_mouse','sun_cushion'].includes(id)?' · визуальная сцена ещё не готова':''}`;body.append(line);}}
 if(kind==='guests'){p.textContent=view.episodeComplete?'Mika заглянула в гости. Эта ограниченная проба завершена; двор можно обустраивать дальше.':'Поставьте корм. Эта проба использует объявленный тестовый seed для первой встречи Mika.';body.append(p);row(body,'Подарки',`${view.pendingGifts.length} ждут сбора`,'Забрать',()=>{action('yard.collectGifts');openPanel('guests');},!view.pendingGifts.length);const note=document.createElement('p');note.className='notice';note.textContent='Предпросмотр: один питомец, две пробы взаимодействия. Стиль дорабатывается. Продакшен-сохранения не подключены. Корм, подарки и каталог пока используют исходные правила. r2b хранит отдельный тестовый прогресс; прежние пробы сохранены.';body.append(note);if(view.episodeComplete)row(body,'Повторная тестовая встреча','Текущий результат сохранится. Новая проба начнётся с тестовым балансом.','Повторить',()=>{try{beginDemoReplay(localStorage,{base:SAVE_KEY,scenario:requestedScenario,currentRun:currentDemoRun,encoded:adapter.encode(session).value,runId:crypto.randomUUID()});location.reload();}catch(error){p.textContent='Не удалось начать новую пробу: '+error.message;}},view.pendingGifts.length>0);const b=document.createElement('button');b.className='wide-button';b.textContent='Скачать отчёт проверки';b.onclick=exportQA;body.append(b);for(const [id,label] of [['mouse','Проба с мышкой'],['cushion','Проба с подушкой']]){const link=document.createElement('button');link.className='wide-button';link.textContent=label;link.disabled=id===requestedScenario;link.onclick=()=>{persist();location.href=`?scenario=${id}`};body.append(link);}}
 if(!panel.open)panel.showModal();}
function row(parent,title,subtitle,label,click,disabled=false){const row=document.createElement('div'),left=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('small'),button=document.createElement('button');row.className='row';strong.textContent=title;small.textContent=subtitle;button.textContent=label;button.onclick=click;button.disabled=disabled;left.append(strong,small);row.append(left,button);parent.append(row);}
function selectProp(prop){selected=prop.slotId;ghost={...prop.transform,slotId:prop.slotId,goodieId:prop.goodieId,valid:true};$('placement-tools').hidden=false;canvas.focus();refresh();}
function cancelPlacement(){selected=null;ghost=null;drag=null;$('placement-tools').hidden=true;refresh();}
function checkGhost(){const r=adapter.placementCheck(session,'yard.moveGoodie',{slotId:ghost.slotId,x:ghost.x,y:ghost.y});ghost.valid=r.ok;$('confirm-placement').disabled=!r.ok;refresh();}
function pointer(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
canvas.addEventListener('pointerdown',e=>{if(!view)return;const p=pointer(e);if(ghost){drag={pointer:e.pointerId};canvas.setPointerCapture(e.pointerId);const q=projection.unproject(p);ghost.x=q.x;ghost.y=q.y;checkGhost();return;}const hits=view.props.map(prop=>({prop,p:projection.project(prop.transform)})).filter(v=>Math.hypot(v.p.x-p.x,v.p.y-p.y)<28).sort((a,b)=>Math.hypot(a.p.x-p.x,a.p.y-p.y)-Math.hypot(b.p.x-p.x,b.p.y-p.y));if(hits[0]&&!hits[0].prop.reserved)selectProp(hits[0].prop);});
canvas.addEventListener('pointermove',e=>{if(!ghost||!drag)return;Object.assign(ghost,projection.unproject(pointer(e)));checkGhost();});canvas.addEventListener('pointerup',()=>{drag=null;});canvas.addEventListener('pointercancel',cancelPlacement);window.addEventListener('blur',()=>{cancelPlacement();persist();timing.suspend('window-blur');last=performance.now();});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelPlacement();persist();timing.suspend('document-hidden');}last=performance.now();});$('cancel-placement').onclick=cancelPlacement;$('confirm-placement').onclick=()=>{if(!ghost?.valid)return;const r=action('yard.moveGoodie',{slotId:ghost.slotId,x:ghost.x,y:ghost.y});if(r.status===200)cancelPlacement();else checkGhost();};$('close-panel').onclick=()=>panel.close();document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));
function sprite(name,p){const im=images.get(name),meta=stillMeta[name];if(!im||!meta)return;const k=projection.ppu/meta.worldPixelScale;ctx.drawImage(im,p.x-meta.pivotPx[0]*k,p.y-meta.pivotPx[1]*k,im.width*k,im.height*k);}
function contactShadow(p,rx,ry,opacity=.2){ctx.save();ctx.translate(p.x,p.y);ctx.scale(rx,ry);const g=ctx.createRadialGradient(0,0,0,0,0,1);g.addColorStop(0,`rgba(39,54,27,${opacity})`);g.addColorStop(1,'rgba(39,54,27,0)');ctx.fillStyle=g;ctx.fillRect(-1,-1,2,2);ctx.restore();}
function petEdgeAlpha(pet){const plan=session.render.plans[pet.visitId];if(!plan)return 1;const route=pet.phase==='approach'?plan.entryRoute:plan.exitRoute;return edgeOpacity(route,pet.phase,pet.groundDistance);}
function draw(){if(!projection||!view)return;const {width:w,height:h}=projection;ctx.clearRect(0,0,w,h);const bg=images.get('background'),scale=Math.max(w/bg.width,h/bg.height),iw=bg.width*scale,ih=bg.height*scale;ctx.drawImage(bg,(w-iw)*.52,(h-ih)*(w/h>2?.67:.5),iw,ih);
 const bowl=projection.project(config.bowlAnchor||{x:25,y:83});contactShadow(bowl,projection.ppu*.43,projection.ppu*.16,.25);sprite(view.bowls.some(b=>b.foodId&&b.servings>0)?'kibble-bowl-clean':'kibble-bowl-empty',bowl);
 const layers=[];for(const pet of view.pets){const active=pet.phase==='active-clip';const pose=selectPetPose(media,pet),c=pose.clip,index=pose.index;const base=active?pet.clipOrigin:pet.position,origin=active?c.originWorld:[0,0,0];for(const p of c?.groundContacts?.[index]||[]){const point=projection.project({x:base.x+(p[0]-origin[0])*8,y:base.y+(p[1]-origin[1])*8});contactShadow(point,projection.ppu*.19,projection.ppu*.065,active?.22:.22*petEdgeAlpha(pet));}}for(const prop of view.props){if(ghost?.slotId===prop.slotId)continue;const p=projection.project(prop.transform);contactShadow(p,projection.ppu*(prop.goodieId==='sun_cushion'?1.1:.32),projection.ppu*(prop.goodieId==='sun_cushion'?.35:.10),.14);if(!prop.drawStandalone)continue;layers.push({y:p.y,draw:()=>sprite(prop.goodieId==='sun_cushion'?'sun-cushion-clean':Math.abs(prop.transform.rotationZ)>.05?'yarn-mouse-settled-clean':'yarn-mouse-clean',p)});}
 for(const pet of view.pets){const active=pet.phase==='active-clip',clip=media.clips[pet.clipId];if(active&&clip){const p=projection.project(pet.clipOrigin);layers.push({y:p.y,draw:()=>atlas.draw(ctx,clip,Math.floor(pet.clipAtMs*clip.fps/1000),p,projection.ppu)});}else{const p=projection.project(pet.position);layers.push({y:p.y,draw:()=>drawFreePet(pet,p)});}}
 layers.sort((a,b)=>a.y-b.y).forEach(l=>l.draw());if(ghost){const fp=kernel.footprint(ghost,config),poly=footprintPolygon(fp,projection);ctx.beginPath();poly.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=ghost.valid?'#86ae7190':'#c3696590';ctx.fill();ctx.strokeStyle=ghost.valid?'#416c35':'#9d3c36';ctx.lineWidth=2;ctx.stroke();ctx.globalAlpha=.65;sprite(ghost.goodieId==='sun_cushion'?'sun-cushion-clean':'yarn-mouse-clean',projection.project(ghost));ctx.globalAlpha=1;}}
function drawFreePet(pet,p){const pose=selectPetPose(media,pet);ctx.save();ctx.globalAlpha=petEdgeAlpha(pet);atlas.draw(ctx,pose.clip,pose.index,p,projection.ppu);ctx.restore();}

function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);projection=createProjection(r.width,r.height);log('resize',{width:r.width,height:r.height,dpr});}new ResizeObserver(resize).observe($('scene'));
function warmWalkPages(){const pages=new Set([0,2,4,6].flatMap(i=>media.walk.facings[i].pages.map(p=>p.src)));for(const src of pages)atlas.load(src,'feed-walk-warmup').catch(()=>{});}
function preloadNext(){for(const pet of view?.pets||[]){const hint=nextMediaHint(media,pet,session.render.plans[pet.visitId]);if(hint?.clip)atlas.prefetch(hint.clip,hint.index,'route-lookahead');}}
async function warmCurrentFrame(){for(const pet of view.pets){const pose=selectPetPose(media,pet),{page}=atlasPageFor(pose.clip,pose.index);await atlas.load(page.src,'restore-current-frame');}}
function missingMedia(v){for(const pet of v.pets){const pose=selectPetPose(media,pet);if(!atlas.frame(pose.clip,pose.index))return{mediaId:pose.mediaId,index:pose.index,page:atlasPageFor(pose.clip,pose.index).page.src};}return null;}
function displayedPoses(){return(view?.pets||[]).map(p=>{const q=selectPetPose(media,p);return{visitId:p.visitId,mediaId:q.mediaId,index:q.index,position:p.phase==='active-clip'?p.clipOrigin:p.position};});}
function loop(now){try{const rawDelta=now-last,dt=Math.min(100,rawDelta);last=now;timing.raf(rawDelta,!paused&&!document.hidden);if(!paused&&!document.hidden){preloadNext();clockRemainder+=dt;if(clockRemainder>=50){const elapsed=Math.floor(clockRemainder/50)*50;const next=adapter.advancePresentation(session,session.clock.screenMs+elapsed),v=adapter.view(next),missing=missingMedia(v);if(!missing){timing.mediaReady(session.clock.screenMs);session=next;view=v;clockRemainder%=50;refresh();}else{timing.mediaWait(session.clock.screenMs,missing);clockRemainder=0;}}if(now-lastPersist>1500){persist();lastPersist=now;}}draw();firstFrameReady=true;if(!document.hidden&&!paused)timing.presented(displayedPoses(),session.clock.screenMs);if(atlas.error)throw atlas.error;}catch(e){fatal(e);return;}requestAnimationFrame(loop);}

try{const [clips,turns,runtime,stills]=await Promise.all([fetch('../../prototype/yard-courtyard-preview-r5/clip-contracts.json').then(r=>r.json()),fetch('../../prototype/yard-courtyard-preview-r5/turn-contracts.json').then(r=>r.json()),fetch('./assets/runtime-media.json').then(r=>r.json()),fetch('./assets/still-layer-contract.json').then(r=>r.json())]);media=runtime;for(const facing of[0,2,4,6])if(JSON.stringify(media.walk.facings[facing].phaseUnits96)!==JSON.stringify(WALK_PHASE_UNITS_96))throw Error('Authored walk media and root phase table disagree');stillMeta=stills;adapter=createCourtyardAdapter(kernel,{clips,turns,scene:config,unitsPerWorld:8});for(const key of ['sun-cushion-clean','yarn-mouse-clean','yarn-mouse-settled-clean','kibble-bowl-clean','kibble-bowl-empty'])images.set(key,await image(`./assets/${key}.png`));images.set('background',await image('./assets/background.webp'));const raw=localStorage.getItem(HOST_SAVE_KEY);rawSaveText=raw;if(raw){const p=JSON.parse(raw),id=p.payload?.kernel?.migration?.backupId;rawBackupText=localStorage.getItem(`${SAVE_KEY}:origin:${id}`);backup=JSON.parse(rawBackupText||'null');const restored=adapter.restore(raw,backup);if(!restored.ok)throw new Error(`Сохранение не изменено: ${restored.reason}`);session=restored.session;}else{({session,backup}=adapter.create({scenario:requestedScenario}));persist();}view=adapter.view(session);resize();refresh();await warmCurrentFrame();last=performance.now();requestAnimationFrame(loop);log('ready',{scenario:session.scenario});}catch(e){fatal(e);}

// User-run diagnostics only: synthetic preview data, no setters or game actions.
Object.defineProperty(window,'__yardQA',{configurable:false,writable:false,value:Object.freeze({snapshot(){const rect=canvas.getBoundingClientRect();return structuredClone({scenario:requestedScenario,demoRun:currentDemoRun,build:'courtyard-preview-r2b-cadence',syntheticPreviewOnly:true,renderReady:firstFrameReady,clock:session?.clock||null,modelTime:session?.kernel?.runtime?.cursorMs??null,episodeComplete:session?.episodeComplete||false,view:view||null,presentationPoses:media?(view?.pets||[]).map(p=>{const q=selectPetPose(media,p);return{visitId:p.visitId,kind:q.kind,mediaId:q.mediaId,index:q.index};}):[],ghost,selected,paused,fatal:$('fatal').hidden?null:$('fatal').textContent,atlas:{loaded:[...atlas.entries.keys()],pending:[...atlas.pending.keys()],error:atlas.error?String(atlas.error):null,maxPages:atlas.limit},scene:{rect:rect.toJSON(),ppu:projection?.ppu||0,props:(view?.props||[]).map(p=>({slotId:p.slotId,anchor:projection?.project(p.transform),validMove:projection?.project({x:p.transform.x+2,y:p.transform.y})})),entry:projection?.project({x:90,y:68})},ownership:session?.kernel?.player?.yard?.goodieInventory||{},timing:timing.snapshot(),errors,trace,saveKey:HOST_SAVE_KEY});}})});

canvas.addEventListener('keydown',event=>{if(!ghost||event.repeat)return;if(event.key==='Escape'){event.preventDefault();cancelPlacement();return;}if(event.key==='Enter'){event.preventDefault();if(ghost.valid)$('confirm-placement').click();return;}const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,1],ArrowDown:[0,-1]}[event.key];if(delta){event.preventDefault();ghost.x+=delta[0];ghost.y+=delta[1];checkGhost();}});
