import {animationSnapshot} from './animation-readiness.mjs';
import {writeFile} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {delay,until} from './core.mjs';
const json=JSON.stringify;
function finder(locator){const l=typeof locator==='string'?{css:locator}:locator;return `(()=>{const q=${json(l)};let nodes=[...d.querySelectorAll(q.css||(q.role==='button'?'button,[role="button"]':q.role==='textbox'?'input,textarea':q.role?'[role="'+q.role+'"]':'*'))];if(q.name!==undefined)nodes=nodes.filter(e=>(e.getAttribute('aria-label')||e.labels?.[0]?.textContent||e.textContent||'').trim()===q.name);if(q.text!==undefined)nodes=nodes.filter(e=>(e.textContent||'').includes(q.text));return nodes[q.index||0]||null;})()`;}
export class Actor {
 constructor(cdp,sessionId,baseUrl,record,directory,signal){Object.assign(this,{cdp,sessionId,baseUrl,record,directory,signal});this.captureIndex=0;this.touch=false;}
 send(method,params={}){return this.cdp.send(method,params,this.sessionId,{signal:this.signal});}
 async evaluate(body){const expression=`(async()=>{if(location.origin!==${json(this.baseUrl)})throw Error('Refusing non-preview origin');const f=document.getElementById('game-frame');const d=f?.contentDocument||document;const w=d.defaultView;return (async()=>{${body}})();})()`;const response=await this.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description||response.exceptionDetails.text||'Page evaluation failed');return response.result?.value;}
 async navigate(profile,{fixture='progress',language='ru',width=390,height=844,chrome='clean',dpr=1,touch=true}={}){this.touch=touch;this.profile=profile;this.record.viewport={width,height,dpr,touch,chrome,language,fixture,kind:'CSS iframe viewport in desktop Chrome/Edge; not a real phone or Telegram client'};await this.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:dpr,mobile:false});await this.send('Emulation.setTouchEmulationEnabled',{enabled:touch,maxTouchPoints:1});const params=new URLSearchParams({fixture,lang:language,viewport:`${width}x${height}`,controls:'hidden',chrome,landscape:width>height?'1':'0'});await this.send('Page.navigate',{url:`${this.baseUrl}/__qa_host.html?${params}`});await until(()=>this.evaluate(`return Boolean(d.querySelector(${json(profile.ready)}));`),{message:'Game did not mount',signal:this.signal});await this.evaluate("await Promise.race([d.fonts?.ready||Promise.resolve(),new Promise(r=>setTimeout(r,1500))]);await Promise.race([Promise.all([...d.images].map(i=>i.decode?.().catch(()=>{})||Promise.resolve())),new Promise(r=>setTimeout(r,1500))]);return true;");const frame=await this.frameMetrics();this.record.measured=frame;const expected=chrome==='clean'?{width,height}:{width:width-(chrome==='telegram-safe'&&width>height?48:0),height:height-(chrome==='telegram'?56:104)};if(Math.abs(frame.width-expected.width)>1.1||Math.abs(frame.height-expected.height)>1.1)throw new Error(`Viewport mismatch: expected${expected.width}x${expected.height}, measured${frame.width}x${frame.height}`);await this.check('No horizontal document overflow',"return d.documentElement.scrollWidth<=w.innerWidth+1;");await this.check('All image assets loaded',"return [...d.images].filter(i=>i.getAttribute('src')).every(i=>i.complete&&i.naturalWidth>0);");}
 async frameMetrics(){return this.evaluate("const r=f?f.getBoundingClientRect():document.documentElement.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,innerWidth:w.innerWidth,innerHeight:w.innerHeight,dpr:w.devicePixelRatio,timeOrigin:w.performance.timeOrigin};");}
 async click(locator){const point=await this.evaluate(`const e=${finder(locator)};if(!e)throw Error('Missing click target');if(e.disabled||e.closest('[inert]'))throw Error('Disabled/inert click target');e.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'});const r=e.getBoundingClientRect(),fr=f?f.getBoundingClientRect():{x:0,y:0};if(!r.width||!r.height)throw Error('Hidden click target');const x=r.x+r.width/2,y=r.y+r.height/2,hit=d.elementFromPoint(x,y);if(!hit||!(hit===e||e.contains(hit)))throw Error('Click target obscured');return {x:fr.x+x,y:fr.y+y,width:r.width,height:r.height};`);if(this.touch){await this.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:point.x,y:point.y,id:1,radiusX:1,radiusY:1,force:1}]});await this.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await this.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:point.x,y:point.y,button:'none'});await this.send('Input.dispatchMouseEvent',{type:'mousePressed',x:point.x,y:point.y,button:'left',buttons:1,clickCount:1});await this.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:point.x,y:point.y,button:'left',buttons:0,clickCount:1});}this.record.actions.push({type:'pointerClick',locator,point});await delay(80,this.signal);}
 async key(key,extra={}){const codes={ArrowLeft:['ArrowLeft',37],ArrowRight:['ArrowRight',39],' ':['Space',32],Escape:['Escape',27],Enter:['Enter',13],Tab:['Tab',9],PageDown:['PageDown',34],Home:['Home',36],a:['KeyA',65]};const [code,windowsVirtualKeyCode]=codes[key]||[key,0];await this.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key,code,windowsVirtualKeyCode,...extra});await this.send('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode,...extra});this.record.actions.push({type:'key',key});await delay(60,this.signal);}
 async fill(locator,text){await this.click(locator);await this.key('a',{modifiers:2,commands:['selectAll']});await this.send('Input.insertText',{text});this.record.actions.push({type:'insertText',locator,text});await delay(80,this.signal);}
 async select(locator,value){await this.evaluate(`const e=${finder(locator)};if(!e||e.tagName!=='SELECT')throw Error('Missing select');if(![...e.options].some(o=>o.value===${json(value)}))throw Error('Missing option');e.value=${json(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));return true;`);this.record.actions.push({type:'selectValueWithDOMEvents',locator,value});await delay(80,this.signal);}
 async waitFor(body,label='State did not appear'){return until(()=>this.evaluate(body),{message:label,signal:this.signal});}
 async check(label,body){const actual=await this.evaluate(body),passed=actual===true;this.record.assertions.push({label,passed,actual});if(!passed)throw new Error(`Assertion failed: ${label}: ${json(actual)}`);return actual;}
 async exists(locator){return this.evaluate(`return Boolean(${finder(locator)});`);}
 async count(selector){return this.evaluate(`return d.querySelectorAll(${json(selector)}).length;`);}
 async bounds(selector){return this.evaluate(`const e=d.querySelector(${json(selector)});if(!e)return null;const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};`);}
 async checkDialog(){await this.waitFor("return Boolean(d.querySelector('[role=dialog]'));",'Dialog did not open');await this.check('Dialog is inside usable game viewport',"const e=d.querySelector('[role=dialog]'),r=e.getBoundingClientRect();return r.x>=-1&&r.y>=-1&&r.right<=w.innerWidth+1&&r.bottom<=w.innerHeight+1;");await this.check('Dialog has visible close route',"return [...d.querySelectorAll('[role=dialog] button')].some(e=>/Close|Закрыть/.test(e.getAttribute('aria-label')||e.textContent||''));");}
 async screenshot(name){await this.evaluate("await Promise.race([Promise.all([...d.images].map(i=>i.decode?.().catch(()=>{})||Promise.resolve())),new Promise(r=>setTimeout(r,1500))]);return true;");const readiness=await this.evaluate(`const collect=${animationSnapshot.toString()};const deadline=Date.now()+2000;let sample;do{sample=collect(d);if(!sample.finite.length)break;await Promise.race([Promise.allSettled(sample.finite.map(a=>a.finished)),new Promise(r=>setTimeout(r,Math.max(1,deadline-Date.now())))]);}while(Date.now()<deadline);sample=collect(d);return{finiteAnimationsSettled:sample.finite.length===0,remainingFinite:sample.finite.length,remainingDetails:sample.details.slice(0,20),ignoredInfinite:sample.ignoredInfinite.length,ignoredLiveTimers:sample.ignoredLive.length,ignoredLiveDetails:sample.ignoredLive.slice(0,20),limitMs:2000,appState:d.querySelector('[data-research-state]')?.dataset.researchState||'not-exposed'};`);this.record.assertions.push({label:'Finite transient animations settled before capture (infinite and identified live timers ignored)',passed:readiness.finiteAnimationsSettled,actual:readiness});const r=await this.frameMetrics();const {data}=await this.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:true,clip:{x:Math.max(0,r.x),y:Math.max(0,r.y),width:r.width,height:r.height,scale:1}});const bytes=Buffer.from(data,'base64');if(bytes.length<100||bytes.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw new Error('Browser did not return a real PNG');const filename=`${String(++this.captureIndex).padStart(2,'0')}-${name.replace(/[^a-z0-9_-]/gi,'-')}.png`;await writeFile(path.join(this.directory,filename),bytes);this.record.screenshots.push({file:filename,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),source:'Chrome DevTools Page.captureScreenshot',readiness,pngWidth:bytes.readUInt32BE(16),pngHeight:bytes.readUInt32BE(20),viewport:r});return filename;}
 async drag(selector,dy){const p=await this.evaluate(`const e=d.querySelector(${json(selector)});if(!e)throw Error('Missing drag target');const r=e.getBoundingClientRect(),fr=f?f.getBoundingClientRect():{x:0,y:0};return{x:fr.x+r.x+r.width/2,y:fr.y+r.y+r.height/2};`);await this.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:p.x,y:p.y,button:'none'});await this.send('Input.dispatchMouseEvent',{type:'mousePressed',x:p.x,y:p.y,button:'left',buttons:1,clickCount:1});for(let i=1;i<=8;i++){await this.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:p.x,y:p.y+dy*i/8,button:'left',buttons:1});await delay(20,this.signal);}await this.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.x,y:p.y+dy,button:'left',buttons:0,clickCount:1});this.record.actions.push({type:'pointerDrag',selector,dy});await delay(100,this.signal);}
 async resize(width,height){const before=await this.frameMetrics(),old=this.record.viewport;await this.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:old.dpr,mobile:false});const insets=old.chrome==='telegram-safe'?[84,width>height?24:0,20,width>height?24:0]:old.chrome==='telegram'?[56,0,0,0]:[0,0,0,0];await this.evaluate(`document.getElementById('qa-reserve').style.inset=${json(insets.map(v=>v+'px').join(' '))};return true;`);await this.waitFor(`return w.innerWidth===${width-insets[1]-insets[3]}&&w.innerHeight===${height-insets[0]-insets[2]};`,'Resize did not reach game');const after=await this.frameMetrics();this.record.actions.push({type:'viewportResize',width,height,before,after});await this.check('Resize keeps the same live iframe',`return w.performance.timeOrigin===${before.timeOrigin};`);}
 async dismiss(){await this.key('Escape');await this.waitFor("return !d.querySelector('[role=dialog]');",'Dialog failed to dismiss');}
}
