// Runs only inside the user's explicit local QA invocation. No game state injection.
const t=id=>`[data-testid="${id}"]`;
const fieldPoint="const e=d.querySelector('[data-testid=bb-field]'),r=e.getBoundingClientRect(),fr=f.getBoundingClientRect();return{x:fr.x+r.x+r.width*.58,y:fr.y+r.y+r.height*.45};";
const framesReady="return d.querySelector('[data-testid=bb-field]')?.dataset.ready==='true';";
const playing="return d.querySelector('[data-testid=bb-stage]')?.dataset.bbPhase==='playing';";
const targets="return [...d.querySelectorAll('button')].filter(e=>{const r=e.getBoundingClientRect();return !e.closest('[inert]')&&r.width&&r.height&&r.bottom>0&&r.right>0&&r.top<w.innerHeight&&r.left<w.innerWidth;}).every(e=>{const r=e.getBoundingClientRect();return r.width>=43.5&&r.height>=43.5;});";
const shots="return Number(d.querySelector('[data-testid=bb-field]').dataset.shots);";
const waitMs=ms=>`await new Promise(resolve=>setTimeout(resolve,${ms}));return true;`;
async function start(a,mode='classic'){if(mode==='timed')await a.click(t('bb-mode-timed'));await a.click(t('bb-start'));await a.waitFor(playing,'Bubbo did not start');await a.waitFor(framesReady,'Real game art did not load');}
async function fire(a){const count=await a.evaluate(shots);await a.click(t('bb-fire'));await a.waitFor(`return Number(d.querySelector('[data-testid=bb-field]').dataset.shots)===${count+1};`,'Shot did not resolve exactly once');await a.evaluate(waitMs(850));await a.check('Alternate Fire button did not also submit a canvas pointerup',`return Number(d.querySelector('[data-testid=bb-field]').dataset.shots)===${count+1};`);return count+1;}
async function pause(a){await a.click(t('bb-pause'));await a.checkDialog();}
export function bubboCases(matrix,{quick=false}={}){const sizes=quick?[[320,568],[390,844],[568,320],[1280,720]]:matrix,cases=sizes.map(([width,height])=>({id:`bubbo-${width}x${height}-ru`,options:{width,height,dpr:width===390||width===568?2:1,touch:width<1100,fixture:'progress',language:'ru'},run:async a=>{await a.check('Both real modes and a visible exit route',"return Boolean(d.querySelector('[data-testid=bb-mode-classic]')&&d.querySelector('[data-testid=bb-mode-timed]')&&d.querySelector('[data-testid=bb-exit]'));");await a.screenshot('menu');await start(a);await a.check('Exactly nine columns and eleven rows',"const g=JSON.parse(d.querySelector('[data-testid=bb-field]').dataset.bubboGeometry);return g.cols===9&&g.rows===11;");await a.check('All visible controls meet44px',targets);await a.screenshot('classic-field');await fire(a);await pause(a);await a.screenshot('paused-after-shot');await a.click(t('bb-resume'));await a.waitFor(playing);}}));
 for(const [width,height]of [[390,844],[568,320]])cases.push({id:`bubbo-${width}x${height}-simulated-insets`,options:{width,height,dpr:2,touch:true,fixture:'starter',language:'ru',chrome:'telegram-safe'},run:async a=>{await start(a);await a.check('Usable-inset HUD controls remain44px',targets);await a.check('Field and powers have separate hit areas',"const f=d.querySelector('.bb-playfield').getBoundingClientRect(),p=d.querySelector('.bb-powers').getBoundingClientRect();return f.right<=p.left+1||f.bottom<=p.top+1;");if(height<350){await a.check('Short viewport preserves minimum playfield via bounded scroll',"const s=d.querySelector('.bb-scroll-surface'),g=JSON.parse(d.querySelector('[data-testid=bb-field]').dataset.bubboGeometry);return s.dataset.scroll==='true'&&s.scrollHeight>s.clientHeight&&g.cell>=20;");await a.screenshot('short-height-field-top');await a.click({role:'button',name:'↓ К пушке'});await a.waitFor("return d.querySelector('.bb-scroll-surface').scrollTop>0;");await a.check('Launcher becomes visible after explicit navigation',"const c=d.querySelector('[data-testid=bb-field]'),r=c.getBoundingClientRect(),g=JSON.parse(c.dataset.bubboGeometry);return r.top+g.cannonY>=0&&r.top+g.cannonY<w.innerHeight;");await a.screenshot('short-height-launcher');await a.click({role:'button',name:'↑ К полю'});await a.waitFor("return d.querySelector('.bb-scroll-surface').scrollTop===0;");}await a.screenshot('safe-inset-field');await pause(a);await a.screenshot('safe-inset-pause');}});
 cases.push(
 {id:'bubbo-touch-cancel-drag-and-powers',options:{width:390,height:844,dpr:2,touch:true,language:'en',fixture:'starter'},run:async a=>{await start(a);const before=await a.evaluate(shots),p=await a.evaluate(fieldPoint);await a.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p,id:1,radiusX:1,radiusY:1}]});await a.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:p.x+30,y:p.y-40,id:1,radiusX:1,radiusY:1}]});await a.screenshot('dragging-real-aim');await a.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await a.evaluate(waitMs(850));await a.check('Cancelled gesture never fires',`return Number(d.querySelector('[data-testid=bb-field]').dataset.shots)===${before};`);await a.click(t('bb-swap'));await a.check('Swap spent exactly one charge',"return d.querySelector('[data-testid=bb-swap]').disabled&&d.querySelector('[data-testid=bb-swap] b').textContent==='0';");for(const power of ['bomb','rainbow','lightning']){const charge=await a.evaluate(`return Number(d.querySelector('[data-testid=bb-${power}] b').textContent);`);await a.click(t('bb-'+power));await a.check('Selected power is visibly armed',`return d.querySelector('[data-testid=bb-${power}]').getAttribute('aria-pressed')==='true';`);await fire(a);await a.check('Power spent once on landing',`return Number(d.querySelector('[data-testid=bb-${power}] b').textContent)===${charge-1}&&d.querySelector('[data-testid=bb-${power}]').getAttribute('aria-pressed')==='false';`);}await a.screenshot('after-three-powers');await pause(a);await a.click(t('bb-finish'));await a.waitFor("return d.querySelector('[data-testid=bb-stage]').dataset.bbPhase==='result';");await a.screenshot('result');}},
 {id:'bubbo-flight-pause-rotation-keyboard',options:{width:390,height:844,dpr:2,touch:false,language:'en',fixture:'starter'},run:async a=>{await start(a);await a.evaluate("d.querySelector('[data-testid=bb-field]').focus();return true;");for(let i=0;i<5;i++)await a.key('ArrowRight');await a.screenshot('keyboard-aim');const before=await a.evaluate(shots);await a.key(' ');await a.waitFor("return d.querySelector('[data-testid=bb-field]').dataset.flight==='true';",'Flying shot was not observed');await a.key('Escape');await a.checkDialog();await a.evaluate(waitMs(1200));await a.check('Paused flight does not resolve early',`return Number(d.querySelector('[data-testid=bb-field]').dataset.shots)===${before}&&d.querySelector('[data-testid=bb-field]').dataset.flight==='true';`);await a.resize(568,320);await a.screenshot('flight-paused-after-rotation');await a.click(t('bb-resume'));await a.waitFor(`return Number(d.querySelector('[data-testid=bb-field]').dataset.shots)===${before+1};`);await a.evaluate(waitMs(350));await a.check('Flight resolves once after resume and resize',`return Number(d.querySelector('[data-testid=bb-field]').dataset.shots)===${before+1};`);await a.screenshot('resized-after-landing');}},
 {id:'bubbo-timed-clock-pause-and-restart',options:{width:568,height:320,dpr:2,touch:true,language:'en',fixture:'starter'},run:async a=>{await start(a,'timed');await a.evaluate(waitMs(1100));await pause(a);const before=await a.evaluate("return d.querySelector('.bb-hud .bb-metric:nth-child(2) strong').textContent;");await a.evaluate(waitMs(1500));await a.check('Timed clock stays frozen during pause',`return d.querySelector('.bb-hud .bb-metric:nth-child(2) strong').textContent===${JSON.stringify(before)};`);await a.screenshot('timed-paused');await a.click(t('bb-resume'));await fire(a);await a.check('Timed mode reports seconds rather than shot budget',"return d.querySelector('.bb-hud .bb-metric:nth-child(2) strong').textContent.endsWith('s');");await pause(a);await a.click(t('bb-restart'));await a.waitFor(playing);await a.check('Restart resets fired shots exactly to zero',"return Number(d.querySelector('[data-testid=bb-field]').dataset.shots)===0;");await a.screenshot('timed-restart');}},
 {id:'bubbo-visibility-loss-pauses',options:{width:390,height:844,dpr:2,touch:false,language:'en',fixture:'starter'},run:async a=>{await start(a,'timed');await a.evaluate(waitMs(600));const {targetId}=await a.cdp.send('Target.createTarget',{url:'about:blank'});try{await a.cdp.send('Target.activateTarget',{targetId});await a.waitFor("return d.querySelector('[data-testid=bb-stage]').dataset.bbPhase==='paused';",'Background visibility did not pause');const before=await a.evaluate("return d.querySelector('.bb-hud .bb-metric:nth-child(2) strong').textContent;");await a.evaluate(waitMs(1400));await a.send('Page.bringToFront');await a.check('Hidden time was not charged to the run',`return d.querySelector('.bb-hud .bb-metric:nth-child(2) strong').textContent===${JSON.stringify(before)};`);await a.screenshot('paused-after-tab-return');await a.click(t('bb-resume'));await a.waitFor(playing);}finally{await a.cdp.send('Target.closeTarget',{targetId});}}},
 {id:'bubbo-saved-run-resume-and-exit',options:{width:320,height:568,dpr:1,touch:true,language:'ru',fixture:'saved'},run:async a=>{await a.check('Saved run is offered deliberately',"return Boolean(d.querySelector('[data-testid=bb-resume-saved]'));");await a.screenshot('resume-offer');await a.click(t('bb-resume-saved'));await a.waitFor(playing);await a.waitFor(framesReady);await a.check('Saved shots and score restored',"return d.querySelector('[data-testid=bb-field]').dataset.shots==='12'&&d.querySelector('.bb-hud .bb-metric strong').textContent==='240';");await fire(a);await pause(a);await a.click(t('bb-exit'));await a.waitFor("return Boolean(d.querySelector('.preview-state'))&&!d.querySelector('[data-testid=bb-stage]');",'Exit did not leave the game');await a.screenshot('local-exit');}}
 );return cases;}
