// User-run only: real pointer/keyboard input and browser screenshots. No controller injection.
const t=id=>`[data-testid="trv2-${id}"]`;
const active="return ['solo','duel-play'].includes(d.querySelector('[data-testid=trv2-root]')?.dataset.triviaView);";
const targets="return [...d.querySelectorAll('button,input,select')].filter(e=>{const r=e.getBoundingClientRect();return !e.closest('[inert]')&&r.width&&r.height&&r.bottom>0&&r.right>0&&r.top<w.innerHeight&&r.left<w.innerWidth;}).every(e=>{const r=e.getBoundingClientRect();return r.width>=43.5&&r.height>=43.5;});";
const wait=ms=>`await new Promise(r=>setTimeout(r,${ms}));return true;`;
async function start(a){await a.click(t('start'));await a.waitFor(active);await a.check('Four actual answer buttons',"return d.querySelectorAll('.trv2-answer').length===4;");}
async function pause(a){await a.click(t('pause'));await a.checkDialog();}
async function resumed(a){await a.waitFor("return !d.querySelector('[role=dialog]')&&d.querySelector('[data-testid=trv2-root]').dataset.paused==='false';",'Resume did not finish');await a.evaluate("await new Promise(resolve=>w.requestAnimationFrame(()=>w.requestAnimationFrame(resolve)));return true;");await a.check('Resume clears gameplay inert and enables a real answer',"const scroll=d.querySelector('.trv2-scroll'),answer=d.querySelector('.trv2-answer:not(:disabled)');return Boolean(scroll&&!scroll.inert&&!scroll.hasAttribute('inert')&&answer&&!answer.closest('[inert]'));");}
async function answer(a){await a.click('.trv2-answer:not(:disabled)');await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-next]'));",'Answer feedback did not appear');}
async function finish(a){for(let i=0;i<10;i++){if(await a.exists(t('results')))return;await answer(a);await a.click(t('next'));}throw Error('Trivia did not finish its bounded real question bank');}
export function triviaCases(matrix,{quick=false}={}){
 const sizes=quick?[[320,568],[390,844],[568,320],[1280,720]]:matrix;
 const cases=sizes.map(([width,height])=>({id:`trivia-${width}x${height}-ru`,options:{width,height,dpr:width===390||width===568?2:1,touch:width<1100,fixture:'starter',language:'ru'},run:async a=>{
  await a.check('Create, join and history are non-overlapping normal flow',"const h=d.querySelector('[data-testid=trv2-history]').getBoundingClientRect(),j=d.querySelector('[data-testid=trv2-join]').getBoundingClientRect(),c=d.querySelector('[data-testid=trv2-create]').getBoundingClientRect();return h.top>=Math.max(j.bottom,c.bottom);");await a.screenshot('setup');await start(a);await a.check('Controls have44px targets',targets);await a.check('No false countdown-to-loss label',"return d.querySelector('.trv2-speed').textContent.includes('Бонус за скорость');");await a.screenshot('question');await pause(a);const time=await a.evaluate("return d.querySelector('[data-testid=trv2-time]').textContent;");await a.evaluate(wait(1100));await a.check('Pause keeps speed clock frozen',`return d.querySelector('[data-testid=trv2-time]').textContent===${JSON.stringify(time)};`);await a.key('Tab');await a.check('Keyboard focus stays in the modal',"return Boolean(d.activeElement.closest('[role=dialog]'));");await a.screenshot('pause');await a.dismiss();await resumed(a);await a.check('Pause trigger regains focus',"return d.activeElement.matches('[data-testid=trv2-pause]');");await answer(a);await a.screenshot('answer-feedback');
 }}));
 for(const[width,height]of[[390,844],[568,320]])cases.push({id:`trivia-${width}x${height}-simulated-insets`,options:{width,height,dpr:2,touch:true,fixture:'starter',language:'ru',chrome:'telegram-safe'},run:async a=>{await start(a);await a.check('All controls remain unscaled44px',targets);await a.screenshot('safe-area-question');await a.evaluate("const s=d.querySelector('.trv2-scroll');s.scrollTop=s.scrollHeight;return true;");await a.check('All four answer targets remain at least58px',"return [...d.querySelectorAll('.trv2-answer')].every(e=>e.getBoundingClientRect().height>=57.5);");await a.screenshot('safe-area-bottom-controls');await pause(a);await a.screenshot('safe-area-dialog');}});
 cases.push(
 {id:'trivia-resume-close-routes-and-repeat',options:{width:390,height:844,dpr:1,touch:false,fixture:'starter',language:'en'},run:async a=>{await start(a);for(const route of ['escape','close','resume','escape']){await pause(a);if(route==='escape')await a.dismiss();else if(route==='close')await a.click({css:'[role=dialog] button[aria-label="Close"]'});else await a.click(t('resume'));await resumed(a);await a.check('Pause trigger regains focus after '+route,"return d.activeElement.matches('[data-testid=trv2-pause]');");await answer(a);await a.click(t('next'));if(!await a.exists('.trv2-answer')){await a.click(t('another'));await start(a);}}await a.screenshot('multiple-resume-routes');}},
 {id:'trivia-all-lifelines-next-and-results',options:{width:390,height:844,dpr:2,touch:true,fixture:'starter',language:'en'},run:async a=>{await start(a);await a.click(t('audience'));await a.check('Audience displays four server percentages',"return d.querySelectorAll('.trv2-poll').length===4;");await a.screenshot('audience');await a.click(t('fifty'));await a.check('50/50 removes two real wrong choices and spends one charge',"return d.querySelectorAll('.trv2-answer[data-answer-state=removed]').length===2&&d.querySelector('[data-testid=trv2-fifty]').disabled;");await a.click(t('reveal'));await a.check('Reveal identifies one remaining answer',"return d.querySelectorAll('.trv2-answer[data-answer-state=hinted]').length===1;");await a.screenshot('three-lifelines');await a.click('.trv2-answer[data-answer-state=hinted]');await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-next]'));");const before=await a.evaluate("return d.querySelector('[data-testid=trv2-question-number]').textContent;");await a.evaluate(wait(1500));await a.check('Feedback never advances on a hidden reading deadline',`return d.querySelector('[data-testid=trv2-question-number]').textContent===${JSON.stringify(before)};`);await a.screenshot('correct-answer');await a.click(t('next'));await a.check('Charges stay spent on the next question',"return ['audience','fifty','reveal'].every(x=>d.querySelector(`[data-testid=trv2-${x}]`).disabled);");await finish(a);await a.screenshot('solo-result');await a.click(t('another'));await start(a);await a.check('A new round resets lifelines',"return ['audience','fifty','reveal'].every(x=>!d.querySelector(`[data-testid=trv2-${x}]`).disabled);");}},
 {id:'trivia-duplicate-click-and-rotation',options:{width:390,height:844,dpr:2,touch:false,fixture:'starter',language:'en'},run:async a=>{await start(a);const p=await a.evaluate("const e=d.querySelector('[data-testid=trv2-answer-0]');e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect(),fr=f.getBoundingClientRect();return{x:fr.x+r.x+r.width/2,y:fr.y+r.y+r.height/2};");for(let i=0;i<2;i++){await a.send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',buttons:1,clickCount:1});await a.send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',buttons:0,clickCount:1});}await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-next]'));");await a.resize(568,320);await a.check('Rotation preserves the same answered question',"return d.querySelector('[data-testid=trv2-question-number]').textContent==='Question 1 of 4'&&d.querySelectorAll('.trv2-answer:disabled').length===4;");await a.screenshot('feedback-after-double-click-and-rotation');await a.click(t('next'));await a.check('Next advances exactly one question',"return d.querySelector('[data-testid=trv2-question-number]').textContent==='Question 2 of 4';");}},
 {id:'trivia-create-simulated-duel-history-and-leave',options:{width:390,height:844,dpr:2,touch:true,fixture:'starter',language:'ru'},run:async a=>{await a.click(t('create'));await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-ready]'));");await a.check('Simulation disclosure is explicit before ready',"return d.querySelector('.trv2-room').textContent.includes('нет игроков онлайн');");await a.screenshot('simulated-room');await a.click(t('leave'));await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-create]'));");await a.click(t('create'));await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-ready]'));");await a.click(t('ready'));await a.waitFor(active);await a.check('Duel has no solo lifelines and labels the simulated opponent',"return !d.querySelector('.trv2-lifelines')&&d.querySelector('[data-testid=trv2-simulation]').textContent.includes('Смоделированный');");await finish(a);await a.waitFor("return d.querySelector('[data-testid=trv2-results]').textContent.includes('SIMULATED OPPONENT');");await a.screenshot('simulated-duel-results');await a.click(t('another'));await a.waitFor("return d.querySelectorAll('.trv2-history li').length===1;");await a.screenshot('real-entries-history-shape');}},
 {id:'trivia-join-error-and-demo-room',options:{width:320,height:568,dpr:1,touch:true,fixture:'starter',language:'en'},run:async a=>{await a.fill(t('code'),'INVALID');await a.click(t('join'));await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-error]'));");await a.screenshot('invalid-code');await a.click({css:'.trv2-error button',text:'Close'});await a.fill(t('code'),'DEMO');await a.click(t('join'));await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-ready]'));");await a.screenshot('joined-simulated-room');await a.click(t('ready'));await a.waitFor(active);await pause(a);await a.click(t('finish'));await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-start]'));");}},
 {id:'trivia-long-questions-and-answers',options:{width:320,height:568,dpr:2,touch:true,fixture:'long-text',language:'ru'},run:async a=>{await start(a);await a.check('Long question and all long answers remain complete',"return d.querySelector('[data-testid=trv2-question]').textContent.length>170&&[...d.querySelectorAll('.trv2-answer-label')].every(e=>e.textContent.length>60&&e.scrollWidth<=e.clientWidth+1);");await a.screenshot('long-question-top');await a.click(t('reveal'));await a.screenshot('long-answer-bottom');await a.resize(568,320);await a.check('Landscape grows long answer cards rather than truncating text',"return [...d.querySelectorAll('.trv2-answer-label')].every(e=>e.scrollHeight<=e.clientHeight+1&&e.scrollWidth<=e.clientWidth+1);");await a.screenshot('long-landscape');await pause(a);await a.checkDialog();await a.screenshot('long-pause');}},
 {id:'trivia-start-error-safe-retry',options:{width:390,height:844,dpr:1,touch:true,fixture:'retry-start',language:'en'},run:async a=>{await a.click(t('start'));await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-retry]'));");await a.screenshot('start-error');await a.click(t('retry'));await a.waitFor(active);await a.screenshot('start-recovered');}},
 {id:'trivia-uncertain-answer-no-resend',options:{width:390,height:844,dpr:2,touch:true,fixture:'uncertain-answer',language:'en'},run:async a=>{await start(a);await a.click(t('answer-0'));await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-recover]'));");await a.check('Uncertain commit disables answers and offers no blind retry',"return [...d.querySelectorAll('.trv2-answer')].every(e=>e.disabled)&&!d.querySelector('[data-testid=trv2-retry]');");await a.screenshot('uncertain-commit');await a.click(t('recover'));await a.waitFor("return Boolean(d.querySelector('[data-testid=trv2-start]'));");await a.screenshot('safe-recovery-setup');}},
 {id:'trivia-hidden-tab-clock-and-zero-bonus',options:{width:390,height:844,dpr:2,touch:false,fixture:'starter',language:'en'},run:async a=>{await a.select(t('difficulty'),'easy');await start(a);const {targetId}=await a.cdp.send('Target.createTarget',{url:'about:blank'});try{await a.cdp.send('Target.activateTarget',{targetId});await a.waitFor("return d.querySelector('[data-testid=trv2-root]').dataset.paused==='true';");const before=await a.evaluate("return d.querySelector('[data-testid=trv2-time]').textContent;");await a.evaluate(wait(1200));await a.send('Page.bringToFront');await a.check('Hidden time never consumes the speed bonus',`return d.querySelector('[data-testid=trv2-time]').textContent===${JSON.stringify(before)};`);await a.screenshot('paused-after-background');await a.click(t('resume'));await resumed(a);const seconds=await a.evaluate("return parseInt(d.querySelector('[data-testid=trv2-time]').textContent,10);");await a.evaluate(wait((seconds+1)*1000));await a.check('Zero bonus does not invent a loss or disable answers',"return d.querySelector('[data-testid=trv2-time]').textContent==='0s'&&d.querySelector('[data-testid=trv2-answer-0]').disabled===false&&d.querySelector('.trv2-time-note').textContent.includes('still answer');");await a.screenshot('zero-speed-bonus');await answer(a);}finally{await a.cdp.send('Target.closeTarget',{targetId});}}}
 );return cases;
}
