import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{triviaCore}from'./helpers/triviaCore.js';import{createTriviaBackend,LONG_QUESTIONS}from'../preview/trivia/backend.js';import{triviaSourcePin,extractTriviaCore}from'../preview/trivia/server-core.mjs';import pin from'../preview/trivia/server-core-pin.json'with{type:'json'};import questions from'../data/questions.json'with{type:'json'};
const createRoutes=await triviaCore();const backend=fixture=>createTriviaBackend({createRoutes,fixture});
function correct(q){return [...questions,...LONG_QUESTIONS].find(x=>x.question===q.question).correctAnswer;}
test('preview pins all authoritative dependencies and fails on drift',()=>{assert.deepEqual(triviaSourcePin(process.cwd()),pin);assert.throws(()=>extractTriviaCore({...pin,'routes/trivia.js':'bad'},process.cwd()),/source changed/);});
test('actual solo routes preserve score, time bonus, totals, lifeline charges and reward',async()=>{const b=backend('starter');let r=await b.request('/api/trivia/start',{difficulty:'medium'}),total=0;const count=r.question.total;assert.equal(r.question.answers.length,4);const life=await b.request('/api/trivia/lifeline',{type:'fifty'});assert.equal(life.hiddenAnswers.length,2);assert.equal(life.lifelines.fifty,0);assert.equal((await b.request('/api/trivia/lifeline',{type:'fifty'})).error,'lifeline unavailable');for(let i=0;i<count;i++){const q=r.question||r.nextQuestion;r=await b.request('/api/trivia/answer',{answer:correct(q),timeMs:15000});total+=r.points;assert.equal(r.sessionScore,total);}assert.equal(r.isComplete,true);assert.ok(r.goldReward>0);const snap=await b.request('/api/player/snapshot');assert.equal(snap.trivia.totalPlayed,1);assert.equal(snap.trivia.totalCorrect,count);assert.equal(snap.trivia.totalScore,total);assert.equal(snap.resources.gold,r.goldReward);assert.equal(snap._offlinePreview,true);});
test('production category is not a filter; preview does not invent one',async()=>{const b=backend('starter');const r=await b.request('/api/trivia/start',{difficulty:'easy',category:'IMPOSSIBLE_CATEGORY'});assert.equal(r.question.difficulty,'easy');assert.ok(r.question.question);});
test('forfeit uses actual production handler and creates no completion reward',async()=>{const b=backend('starter');const r=await b.request('/api/trivia/start',{difficulty:'easy'});const answer=await b.request('/api/trivia/answer',{answer:correct(r.question),timeMs:5000});const f=await b.request('/api/trivia/forfeit',{});assert.equal(f.score,answer.points);const snap=await b.request('/api/player/snapshot');assert.equal(snap.trivia.totalPlayed,1);assert.equal(snap.resources.gold,0);assert.equal((await b.request('/api/trivia/forfeit',{})).error,'no session');});
test('simulated duel executes real create/join/ready/start/answer/status/history shapes',async()=>{const b=backend('starter');const room=await b.request('/api/trivia/duel/create',{difficulty:'easy'});assert.ok(room.roomId);assert.equal(room.status,undefined);assert.equal((await b.request(`/api/trivia/duel/status/${room.roomId}`)).status,'waiting');const ready=await b.request('/api/trivia/duel/ready',{roomId:room.roomId});assert.equal(ready.status,'active');assert.ok(ready.players.some(p=>p.username==='SIMULATED OPPONENT'));let r=await b.request('/api/trivia/duel/start',{roomId:room.roomId});for(let i=0;i<5;i++){const q=r.question||r.nextQuestion;r=await b.request('/api/trivia/duel/answer',{roomId:room.roomId,answer:correct(q),timeMs:5000});}assert.equal(r.isComplete,true);assert.equal(r.results,undefined);const status=await b.request(`/api/trivia/duel/status/${room.roomId}`);assert.equal(status.status,'finished');assert.ok(status.winner);const history=await b.request('/api/trivia/duel/history');assert.equal(history.entries.length,1);assert.equal(history.items,undefined);assert.equal(history.entries[0].players.length,2);assert.equal((await b.request('/api/player/snapshot')).resources.gold,0);});
test('join DEMO is explicitly simulated but invalid code stays an error',async()=>{const b=backend('starter');assert.equal((await b.request('/api/trivia/duel/join',{inviteCode:'NOTAROOM'})).error,'Room not found');const room=await b.request('/api/trivia/duel/join',{inviteCode:'DEMO'});assert.equal(room.status,'lobby');assert.ok(room.players.includes('SIMULATED OPPONENT'));assert.equal(room._offlinePreview,true);});
test('actual waiting-room quota is cleared by explicit leave',async()=>{const b=backend('starter');const room=await b.request('/api/trivia/duel/create',{});assert.equal((await b.request('/api/trivia/duel/create',{})).error,'ACTIVE_ROOM_EXISTS');await b.request('/api/trivia/duel/leave',{roomId:room.roomId});assert.ok((await b.request('/api/trivia/duel/create',{})).roomId);});
test('test fixtures expose actual retry and uncertain commit without persistent writes',async()=>{const b=backend('retry-start');assert.equal((await b.request('/api/trivia/start',{})).error,'LOCAL_TEST_START_REJECTED');assert.ok((await b.request('/api/trivia/start',{})).question);const u=backend('uncertain-answer');const s=await u.request('/api/trivia/start',{});assert.equal((await u.request('/api/trivia/answer',{answer:correct(s.question),timeMs:1000})).error,'TIMEOUT');assert.equal(u.getInspection().players.get('local-reviewer').trivia.session.index,1);});
test('long text fixture is clearly synthetic and still exercises all four actual answer choices',async()=>{const b=backend('long-text');const s=await b.request('/api/trivia/start',{difficulty:'medium'});assert.equal(s.question.answers.length,4);assert.ok(s.question.question.length>170);assert.ok(s.question.answers.every(a=>a.length>60));assert.match(s.question.category,/Синтетический/);});
test('build entry only imports new isolated Trivia CSS, namespace and no server transports',()=>{const source=readFileSync('src/games/trivia/TriviaGame.jsx','utf8');assert.ok(!source.includes('PanelButton'));assert.ok(!source.includes('trivia-live-responsive.css'));assert.ok(source.includes('trivia-presentation.css'));const css=readFileSync('src/games/trivia/trivia-presentation.css','utf8');assert.doesNotMatch(css,/text-overflow:\s*ellipsis|line-clamp/);assert.match(css,/min-height: 44px/);assert.match(css,/overflow-y: auto/);assert.doesNotMatch(css,/\.side-panel|\.panel-button|\.game-shell/);});
test('actual question bank has unique prompts and answers; small difficulty pools remain explicit',async()=>{assert.equal(new Set(questions.map(q=>q.question)).size,questions.length);for(const q of questions){assert.equal(new Set([q.correctAnswer,...q.wrongAnswers]).size,4);assert.ok(q.category.trim());}for(const [difficulty,expected]of[['easy',5],['medium',4],['hard',2]]){const b=backend('starter');const first=await b.request('/api/trivia/start',{difficulty});assert.equal(first.question.total,expected);const seen=new Set();let r=first;while(r.question||r.nextQuestion){const q=r.question||r.nextQuestion;assert.ok(!seen.has(q.question));seen.add(q.question);r=await b.request('/api/trivia/answer',{answer:correct(q),timeMs:15000});}assert.equal(seen.size,expected);}});
test('real leave endpoint is idempotent when a room is already gone',async()=>{const b=backend('starter');const room=await b.request('/api/trivia/duel/create',{});const body={roomId:room.roomId};assert.equal((await b.request('/api/trivia/duel/leave',body)).success,true);assert.equal((await b.request('/api/trivia/duel/leave',body)).success,true);assert.ok((await b.request('/api/trivia/duel/create',{})).roomId);});
