import test from 'node:test';
import assert from 'node:assert/strict';
import {MERGE_LAB_CATALOG as catalog} from '../game-logic/merge-lab-catalog.js';
import {createMergeLabState,createMergeLabAction,createMergeLabQuote,hashMergeLabAction} from '../game-logic/merge-lab-domain.js';
import {MERGE_LAB_RELEASE_POLICY,ensureMergeLabState,executeMergeLab,quoteMergeLab,planMergeCleanStart,publicMergeLabState} from '../game-logic/merge-lab-service.js';
const now=1790928000000,epoch='epoch_test_123456789';
// Preserve remains an explicitly selected compatibility option, independent of the release default.
const policy={...MERGE_LAB_RELEASE_POLICY,enabled:true,migrationMode:'preserve'};
const options={now,policy,newEpoch:()=>epoch};
function legacy(){return {id:'test-account',unknownAccount:{keep:7},resources:{gold:123,gachaTokens:20,paidTokenGrant:5},farm:{harvested:{strawberry:7}},purchases:{order1:{delivered:true}},yard:{currencies:{treats:77,shinyTreats:5},goodieInventory:{alchemy_echo_chimes:2,alchemy_living_arbor:3},placedGoodies:[{keep:true}],activeVisitors:[{keep:true}],unknownYard:'retained'},merge:{board:JSON.stringify([[{id:'seed'},{id:'dew'}]]),inventory:{seed:3},unknownMerge:{keep:'yes'},alchemyEssence:23,freeTapCharges:2,lastFreeTaps:now,lastFreePull:0,discoveredItems:['seed'],discoveredRecipes:[]},mergeBoard:'mirror-do-not-delete',mergeInventory:{seed:3},inventory:{mergeItems:{seed:2},mergeInventory:{seed:3},other:'preserved'}};}
function prepared(){const p=legacy();ensureMergeLabState(p,options);return p;}
function rich(){const p=prepared();p.merge.knowledge.itemIds=catalog.items.map(x=>x.id);p.merge.knowledge.recipeIds=catalog.recipes.map(x=>x.id);p.merge.stock=Object.fromEntries(catalog.items.map(x=>[x.id,1000]));p.merge.alchemyEssence=1000;return p;}
function command(player,type,payload,id='request1',quoted=false,opts=options){const parameters=quoted?{...payload,quote:createMergeLabQuote(player,type,payload,catalog,{now:opts.now})}:payload;return {command:createMergeLabAction(player,type,parameters,catalog,{actionId:id}),expectedMergeEpoch:player.merge.serverEpoch};}

test('a disabled release policy fails closed',()=>{const p=legacy(),before=structuredClone(p);assert.throws(()=>ensureMergeLabState(p,{now,policy:{...MERGE_LAB_RELEASE_POLICY,enabled:false}}),{code:'MERGE_LAB_DISABLED'});assert.deepEqual(p,before);});
test('preserve migration is additive, idempotent, backs up and fences old board',()=>{const p=legacy(),before=structuredClone(p);ensureMergeLabState(p,options);assert.equal(p.merge.stock.seed,4);assert.equal(p.merge.stock.dew,1);for(const key of ['board','inventory','unknownMerge'])assert.deepEqual(p.merge[key],before.merge[key]);for(const key of Object.keys(before).filter(k=>k!=='merge'))assert.deepEqual(p[key],before[key]);assert.equal(p.merge.migration.legacyStateFrozen,true);const once=structuredClone(p);ensureMergeLabState(p,{...options,newEpoch:()=>{throw Error('must not rotate');}});assert.deepEqual(p,once);});
test('clean-start OPTION archives Merge and preserves unrelated currency, purchases and Yard exactly',()=>{const p=legacy(),before=structuredClone(p);const plan=planMergeCleanStart(p);assert.equal(plan.approvalRequired,true);assert.deepEqual(p,before);ensureMergeLabState(p,{...options,policy:{...policy,migrationMode:'clean-start'}});assert.deepEqual(p.merge.stock,{});assert.equal(p.merge.alchemyEssence,0);assert.equal(p.merge.freeTapCharges,0);assert.deepEqual(p.merge.migration.archive.merge,before.merge);for(const key of Object.keys(before).filter(k=>k!=='merge'))assert.deepEqual(p[key],before[key]);assert.equal(p._mergeLabFence.epoch,epoch);});
test('malformed preserved balances fail closed without partial migration',()=>{const p=legacy();p.merge.alchemyEssence=1.5;const before=structuredClone(p);assert.throws(()=>ensureMergeLabState(p,options),{code:'INVALID_INTEGER'});assert.deepEqual(p,before);});
test('two future Yard projects are blocked before quote and debit; existing inventory stays',()=>{for(const project of catalog.projects.filter(p=>p.requiresYardV3)){const p=rich(),before=structuredClone(p);assert.throws(()=>quoteMergeLab(p,'craftProject',{projectId:project.id,quantity:1},{...options,expectedMergeEpoch:epoch}),{code:'YARD_UPDATE_REQUIRED'});const result=executeMergeLab(p,command(p,'craftProject',{projectId:project.id,quantity:1},'blocked',true),options);assert.equal(result.error.code,'YARD_UPDATE_REQUIRED');assert.deepEqual(p,before);}});
test('four available project outputs retain preview economics and grant exactly once',()=>{const projects=catalog.projects.filter(p=>!p.requiresYardV3);assert.equal(projects.length,4);for(const project of projects){const p=rich(),before=structuredClone(p);const q=quoteMergeLab(p,'craftProject',{projectId:project.id,quantity:2},{...options,expectedMergeEpoch:epoch});const request=command(p,'craftProject',{...q.parameters,quote:q},`craft-${project.id}`);const first=executeMergeLab(p,request,options);assert.equal(first.ok,true,JSON.stringify(first.error));assert.equal(p.yard.goodieInventory[project.output.itemId],(before.yard.goodieInventory[project.output.itemId]||0)+2);assert.equal(p.merge.projects.crafted[project.id],2);assert.equal(p.merge.alchemyEssence,before.merge.alchemyEssence-q.terms.essenceCost);const once=structuredClone(p);assert.equal(executeMergeLab(p,request,{...options,now:now+999999}).replayed,true);assert.deepEqual(p,once);assert.deepEqual(p.yard.activeVisitors,before.yard.activeVisitors);assert.deepEqual(p.yard.placedGoodies,before.yard.placedGoodies);}});
test('exchange keeps essence, Yard treats, shiny treats, tokens and shared gold distinct',()=>{const p=rich(),before=structuredClone(p);assert.equal(executeMergeLab(p,command(p,'exchange',{offerId:'yard_treats_small'},'exchange',true),options).ok,true);assert.equal(p.merge.alchemyEssence,before.merge.alchemyEssence-50);assert.equal(p.yard.currencies.treats,before.yard.currencies.treats+120);assert.equal(p.yard.currencies.shinyTreats,before.yard.currencies.shinyTreats);assert.deepEqual(p.resources,before.resources);assert.deepEqual(p.farm,before.farm);});
test('replay requires identical original payload; missing ID/epoch, forged hash and stale revision reject',()=>{const p=rich();const a=command(p,'claimFreeCharges',{},'receipt');assert.equal(executeMergeLab(p,a,options).ok,true);const b=structuredClone(a);b.command.payload={unexpected:true};b.command.payloadHash=hashMergeLabAction(b.command);assert.equal(executeMergeLab(p,b,options).error.code,'ACTION_ID_CONFLICT');const before=structuredClone(p);for(const invalid of [{...a,expectedMergeEpoch:'wrong'},{command:{...a.command,actionId:'bad'},expectedMergeEpoch:epoch},{command:{...a.command,payloadHash:'bad'},expectedMergeEpoch:epoch}])assert.equal(executeMergeLab(p,invalid,options).ok,false);const stale=structuredClone(a);stale.command.actionId='0:different';stale.command.payloadHash=hashMergeLabAction(stale.command);assert.equal(executeMergeLab(p,stale,options).error.code,'REVISION_CONFLICT');assert.deepEqual(p,before);});
test('expired quotes and insufficient input never partially debit',()=>{const p=prepared();p.merge.stock={};const a=command(p,'craft',{recipeId:catalog.starterRecipeIds[0],quantity:1},'poor',true);const before=structuredClone(p);assert.equal(executeMergeLab(p,a,options).error.code,'INSUFFICIENT_STOCK');assert.deepEqual(p,before);assert.equal(executeMergeLab(p,a,{...options,now:a.command.payload.quote.expiresAt}).error.code,'QUOTE_EXPIRED');assert.deepEqual(p,before);});
test('stale duplicate outside 128 receipts cannot spend again',()=>{const p=rich(),old=command(p,'claimFreeCharges',{},'old');executeMergeLab(p,old,options);for(let i=0;i<130;i++)assert.equal(executeMergeLab(p,command(p,'selectProject',{projectId:catalog.projects[0].id},`later-${i}`),options).ok,true);assert.equal(p.merge.actionLedger.length,128);const before=structuredClone(p);assert.equal(executeMergeLab(p,old,options).error.code,'REVISION_CONFLICT');assert.deepEqual(p,before);});
test('reset/lowered revision or lost merge state is fenced; old epoch rejects after approved external rotation',()=>{const p=rich(),old=command(p,'claimFreeCharges',{},'prior-reset');executeMergeLab(p,old,options);for(const corrupt of [{...structuredClone(p),merge:createMergeLabState(catalog,{now})},{...structuredClone(p),merge:{...p.merge,mergeRevision:0}},{...structuredClone(p),merge:{board:[]}}]){const before=structuredClone(corrupt);assert.equal(executeMergeLab(corrupt,old,options).error.code,'MERGE_RESET_FENCED');assert.deepEqual(corrupt,before);}const rotated=structuredClone(p);rotated._mergeLabFence.epoch='new_epoch_123456789';rotated.merge.serverEpoch=rotated._mergeLabFence.epoch;assert.equal(executeMergeLab(rotated,old,options).error.code,'MERGE_EPOCH_CONFLICT');});
test('public view omits private receipts and raw backups but carries release policy and epoch',()=>{const p=prepared();const publicState=publicMergeLabState(p.merge,policy);assert.equal(publicState.actionLedger,undefined);assert.equal(publicState.migration.rawBackup,undefined);assert.equal(publicState.serverEpoch,epoch);assert.equal(publicState.releasePolicy.yardV3ProjectsEnabled,false);});

test('policy changes block new future-project crafts but still confirm already-committed exact receipts',()=>{
 const p=rich(),request=command(p,'craftProject',{projectId:'echo_chimes',quantity:1},'previously-allowed',true);
 const enabled={...options,policy:{...policy,yardV3ProjectsEnabled:true}};
 assert.equal(executeMergeLab(p,request,enabled).ok,true);const once=structuredClone(p);
 const replay=executeMergeLab(p,request,options);assert.equal(replay.ok,true);assert.equal(replay.replayed,true);assert.deepEqual(p,once);
 const fresh=command(p,'craftProject',{projectId:'echo_chimes',quantity:1},'new-blocked',true);assert.equal(executeMergeLab(p,fresh,options).error.code,'YARD_UPDATE_REQUIRED');assert.deepEqual(p,once);
});

test('unknown namespace metadata survives but malformed/newer schemas never auto-downgrade in either mode',()=>{
 const p=legacy();p.merge.projects={selectedId:'echo_chimes',extension:{custom:'keep'}};p.merge.supply={extension:{custom:'keep'}};ensureMergeLabState(p,options);assert.deepEqual(p.merge.projects.extension,{custom:'keep'});assert.deepEqual(p.merge.supply.extension,{custom:'keep'});
 for(const migrationMode of ['preserve','clean-start'])for(const schemaVersion of [4,'3',1.5]){const future=legacy();future.merge.schemaVersion=schemaVersion;const before=structuredClone(future);assert.throws(()=>ensureMergeLabState(future,{...options,policy:{...policy,migrationMode}}),{code:'MERGE_SCHEMA_REVIEW_REQUIRED'});assert.deepEqual(future,before);}
});
