import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {deflateRawSync} from 'node:zlib';
import {parseMaintenanceRecord,verifyMaintenanceTree,sha256,RECORD_PATH} from '../scripts/yard-active-maintenance.mjs';
import {BOOTSTRAP_PATHS,SETTLEMENT_QA_PATHS,verifyMaintenanceBootstrap} from '../scripts/yard-maintenance-bootstrap.mjs';
import {maintenanceCapability} from '../scripts/yard-maintenance-capability.mjs';
import {verifyYardRollbackTarget,KNOWN_LEGACY_YARD_BUILD} from '../scripts/verify-yard-rollback-target.mjs';
import {receiptInventory,normalizeAcceptedReceipt,verifyGithubMaintenancePredecessor,collectGithubMaintenancePredecessor,readReceiptZip} from '../scripts/yard-maintenance-receipt.mjs';
import {parseMaintenanceRequest,parseMaintenanceBuildRequest,loadMaintenanceInputs,assertMaintenanceCaseResults,outboxPresenceForPoll,assertMaintenanceDeliveredMedia} from './helpers/yard-maintenance-guard.mjs';
import {affectedUnitFiles} from '../scripts/yard-maintenance-cli.mjs';
const root=resolve(import.meta.dirname,'..'),read=p=>readFileSync(resolve(root,p),'utf8'),c=x=>x.repeat(40),d=x=>'sha256:'+x.repeat(64),h=x=>x.repeat(64);
const blob=text=>({mode:'100644',type:'blob',objectId:createHash('sha1').update(`blob ${Buffer.byteLength(text)}\0`).update(text).digest('hex')});
const record=()=>({format:'cc-gh-yard-active-maintenance/v1',repository:'le-who/cc-gh',anchor:{commit:c('a'),tree:c('b'),imageDigest:d('c'),contractSha256:h('d'),closedBuildId:c('e'),closedImageDigest:d('f')},predecessor:{commit:c('a'),tree:c('b'),imageDigest:d('c'),imageId:d('1'),compatibilitySha256:h('2'),acceptanceReceiptSha256:h('3')},storage:{format:'yard-persistent/v1',mode:'same-format-no-migration'},affectedGames:['settlement'],changes:[{path:'src/settlement.js',before:blob('old'),after:blob('new')}]});
const seal=r=>({recordBytes:JSON.stringify(r),approvedRecordSha256:sha256(JSON.stringify(r))});
function zip(entries){const local=[],central=[];let offset=0;for(const [name,value]of entries){const file=Buffer.from(name),raw=Buffer.from(value),packed=deflateRawSync(raw),l=Buffer.alloc(30),c=Buffer.alloc(46);l.writeUInt32LE(0x04034b50);l.writeUInt16LE(8,8);l.writeUInt32LE(packed.length,18);l.writeUInt32LE(raw.length,22);l.writeUInt16LE(file.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(8,10);c.writeUInt32LE(packed.length,20);c.writeUInt32LE(raw.length,24);c.writeUInt16LE(file.length,28);c.writeUInt32LE(offset,42);local.push(l,file,packed);central.push(c,file);offset+=l.length+file.length+packed.length;}const cd=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(cd.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,cd,end]);}
function receiptFixture(){
 const r=record(),workflowBytes=Buffer.from('reviewed deployment workflow'),ciWorkflowBytes=Buffer.from('reviewed reusable workflow');
 const locator={mode:'artifact',kind:'activation',runId:41,runAttempt:2,artifactId:51,workflowPath:'.github/workflows/deploy.yml',workflowSha256:sha256(workflowBytes),ciWorkflowSha256:sha256(ciWorkflowBytes)};
 const cap={format:'cc-gh-yard-release-compatibility/v1',buildId:r.predecessor.commit,playerRolloutEnabled:true,readableStorageFormats:['yard-persistent/v1'],requiredClosedPredecessor:{buildId:r.anchor.closedBuildId,imageDigest:r.anchor.closedImageDigest}};r.predecessor.compatibilitySha256=sha256(JSON.stringify(cap)+'\n');
 const pass={format:'cc-gh-yard-production-acceptance/v1',runId:'12345678-1234-1234-1234-123456789abc',activeCommit:r.predecessor.commit,activeDigest:r.predecessor.imageDigest,activeImageId:r.predecessor.imageId,repository:'ghcr.io/le-who/cc-gh',closedCommit:r.anchor.closedBuildId,closedDigest:r.anchor.closedImageDigest,tests:9,retries:0};
 const identity={runId:pass.runId,inputs:{activeCommit:pass.activeCommit,activeDigest:pass.activeDigest},imageB:{Id:pass.activeImageId,RepoDigests:[`ghcr.io/le-who/cc-gh@${pass.activeDigest}`]},compatibility:{B:cap}};
 const passJson=JSON.stringify(pass),identityJson=JSON.stringify(identity),archive=zip([['PASS.json',passJson],['image-identity.json',identityJson]]);Object.assign(locator,{archiveSha256:sha256(archive),passSha256:sha256(passJson),identitySha256:sha256(identityJson)});
 const run={id:41,run_attempt:2,status:'completed',conclusion:'success',head_sha:pass.activeCommit,path:locator.workflowPath,event:'push',workflow_id:6,updated_at:'fixture-stable',repository:{id:1162268629,full_name:'Le-Who/CC-GH'},head_repository:{id:1162268629,full_name:'Le-Who/CC-GH'}};
 const jobs=receiptInventory('activation').map(([name,steps],i)=>({id:100+i,run_id:41,head_sha:run.head_sha,run_attempt:1,name,status:'completed',conclusion:'success',steps:steps.map(name=>({name,status:'completed',conclusion:'success'}))}));
 const artifact={id:51,expired:false,workflow_run:{id:41,head_sha:run.head_sha},name:`yard-published-production-${run.head_sha}-2`,digest:'sha256:'+locator.archiveSha256,size_in_bytes:archive.length};
 const f={record:r,locator,run,jobs,artifact,archive,workflowBytes,ciWorkflowBytes};r.predecessor.acceptanceReceiptSha256=sha256(JSON.stringify(normalizeAcceptedReceipt(f)));return f;
}
const cloneReceipt=f=>({...structuredClone(f),archive:Buffer.from(f.archive),workflowBytes:Buffer.from(f.workflowBytes),ciWorkflowBytes:Buffer.from(f.ciWorkflowBytes)});
function api(f,change=()=>{}){const calls=[];let reads=0;return {calls,fetchImpl:async(url,options)=>{url=String(url);calls.push({url,options});if(url.startsWith('https://fixture.blob.core.windows.net/')){assert.equal(options.headers,undefined);return {status:200,body:(async function*(){yield f.archive;})()};}assert.ok(url.startsWith('https://api.github.com/repos/le-who/cc-gh/'));let data;
 if(url.endsWith('/actions/runs/41')){reads++;data=structuredClone(f.run);}else if(url.includes('/attempts/'))data=structuredClone(f.run);else if(url.includes('/git/commits/'))data={sha:f.record.predecessor.commit,tree:{sha:f.record.predecessor.tree}};else if(url.includes('/contents/release-evidence/'))data={encoding:'base64',content:Buffer.from(f.durableBytes).toString('base64')};else if(url.includes('/contents/.github/workflows/ci.yml'))data={encoding:'base64',content:f.ciWorkflowBytes.toString('base64')};else if(url.includes('/contents/'))data={encoding:'base64',content:f.workflowBytes.toString('base64')};else if(url.includes('/jobs?'))data={total_count:f.jobs.length,jobs:structuredClone(f.jobs)};else if(url.endsWith('/zip'))return {status:302,headers:{get:()=>f.redirect||'https://fixture.blob.core.windows.net/proof.zip'}};else if(url.endsWith('/artifacts/51'))data=structuredClone(f.artifact);else throw Error('Unexpected fixture API '+url);
 const response={status:200,data};change({url,response,reads});return {status:response.status,text:async()=>JSON.stringify(response.data)};}};}

test('actual adapter binds successful run, tree, workflow, jobs, artifact and exact image proof',async()=>{const f=receiptFixture(),mock=api(f),result=await verifyGithubMaintenancePredecessor({...f,token:'fixture-read-token',...mock});assert.equal(result.receipt.status,'accepted');assert.equal(sha256(result.bytes),f.record.predecessor.acceptanceReceiptSha256);assert.equal(mock.calls.filter(x=>x.url.endsWith('/actions/runs/41')).length,2);assert.ok(mock.calls.every(x=>x.options.method==='GET'));});
test('every required predecessor job and proof step rejects failure, skip, omission and wrong source',()=>{const f=receiptFixture();for(let i=0;i<f.jobs.length;i++)for(const value of ['failure','skipped','cancelled','neutral']){const bad=cloneReceipt(f);assert.equal(normalizeAcceptedReceipt(bad).status,'accepted');bad.jobs[i].conclusion=value;assert.throws(()=>normalizeAcceptedReceipt(bad));}for(const mutate of [x=>x.jobs.pop(),x=>x.jobs[0].steps.pop(),x=>x.jobs[0].head_sha=c('0'),x=>x.jobs.push(structuredClone(x.jobs[0])),x=>x.jobs[0].steps[0].conclusion='skipped',x=>x.run.event='pull_request',x=>x.run.head_repository.id=1,x=>x.run.run_attempt=3,x=>x.workflowBytes=Buffer.from('changed')]){const bad=cloneReceipt(f);assert.equal(normalizeAcceptedReceipt(bad).status,'accepted');mutate(bad);assert.throws(()=>normalizeAcceptedReceipt(bad));}});
test('latest per-job replacement is authoritative and cannot hide a newer failure',()=>{const f=receiptFixture(),old={...structuredClone(f.jobs[0]),id:800,conclusion:'failure'};f.jobs[0].run_attempt=2;f.jobs.push(old);assert.equal(normalizeAcceptedReceipt(f).status,'accepted');f.jobs[0].conclusion='failure';assert.throws(()=>normalizeAcceptedReceipt(f));});
test('archive identity, stale image proof and malformed ZIP cannot be silently accepted',()=>{for(const mutate of [f=>f.artifact.expired=true,f=>f.artifact.workflow_run.head_sha=c('0'),f=>f.artifact.id=999,f=>f.artifact.digest='sha256:'+h('0'),f=>f.locator.passSha256=h('0'),f=>f.archive=Buffer.from('not ZIP'),f=>f.record.predecessor.imageId=d('0'),f=>f.record.predecessor.compatibilitySha256=h('0')]){const f=receiptFixture();mutate(f);assert.throws(()=>normalizeAcceptedReceipt(f));}for(const entries of [[['../PASS.json','{}'],['image-identity.json','{}']],[['PASS.json','{}'],['PASS.json','{}'],['image-identity.json','{}']],[['PASS.json','{}']]])assert.throws(()=>readReceiptZip(zip(entries)));});
test('an unfinished or partial ACTIVE candidate never becomes the accepted bootstrap anchor',()=>{for(const mutate of [f=>f.run.status='in_progress',f=>f.run.conclusion='failure',f=>f.jobs.find(x=>x.name==='deploy').conclusion='skipped']){const f=receiptFixture();mutate(f);assert.throws(()=>normalizeAcceptedReceipt(f));}const f=receiptFixture(),files=readReceiptZip(f.archive),pass=JSON.parse(files['PASS.json']);pass.tests=5;const passJson=JSON.stringify(pass);f.archive=zip([['PASS.json',passJson],['image-identity.json',files['image-identity.json']]]);f.locator.passSha256=sha256(passJson);f.locator.archiveSha256=sha256(f.archive);f.artifact.digest='sha256:'+f.locator.archiveSha256;assert.throws(()=>normalizeAcceptedReceipt(f));});
test('API faults, changing runs and foreign artifact redirect fail without fallback or credential forwarding',async()=>{for(const change of [({response})=>response.status=403,({url,response,reads})=>{if(url.endsWith('/actions/runs/41')&&reads===2)response.data.updated_at='changed';},({url,response})=>{if(url.includes('/jobs?'))response.data.total_count++;}]){const f=receiptFixture();await assert.rejects(()=>verifyGithubMaintenancePredecessor({...f,token:'fixture',...api(f,change)}));}const f=receiptFixture();f.redirect='https://untrusted.invalid/archive';await assert.rejects(()=>verifyGithubMaintenancePredecessor({...f,token:'fixture',...api(f)}),/Unrecognized/);});
test('collection yields an explicitly unapproved small archive; missing approval still blocks verification',async()=>{const f=receiptFixture();f.record.predecessor.acceptanceReceiptSha256=h('0');const value=await collectGithubMaintenancePredecessor({...f,token:'fixture',...api(f)});assert.equal(value.status,'collected-unapproved');assert.ok(Buffer.byteLength(JSON.stringify(value.durableArchive))<10000);await assert.rejects(()=>verifyGithubMaintenancePredecessor({...f,token:'fixture',...api(f)}),/approved identity/);});
test('explicit durable archive pins its source bytes while still rechecking live GitHub run/jobs',async()=>{const f=receiptFixture(),collected=await collectGithubMaintenancePredecessor({...f,token:'fixture',...api(f)});f.locator.mode='reviewed-archive';f.durableBytes=JSON.stringify(collected.durableArchive);f.locator.reviewedArchive={commit:c('9'),sha256:sha256(f.durableBytes)};const mock=api(f);assert.equal((await verifyGithubMaintenancePredecessor({...f,token:'fixture',...mock})).receipt.status,'accepted');assert.ok(!mock.calls.some(x=>x.url.includes('/artifacts/')));assert.ok(mock.calls.some(x=>x.url.includes('/jobs?')));f.durableBytes+=' ';await assert.rejects(()=>verifyGithubMaintenancePredecessor({...f,token:'fixture',...api(f)}),/archive changed/);});

test('one-time bootstrap admits only the complete independently pinned tooling capsule',()=>{const r=record(),before=new Map([[r.changes[0].path,r.changes[0].before]]),after=new Map([[r.changes[0].path,r.changes[0].after]]),paths=BOOTSTRAP_PATHS.map(path=>({path,before:null,after:blob('reviewed '+path)}));for(const row of paths)after.set(row.path,row.after);const bytes=JSON.stringify({format:'cc-gh-yard-maintenance-bootstrap/v1',anchorCommit:r.anchor.commit,paths});r.bootstrapSha256=sha256(bytes);const s=seal(r);after.set(RECORD_PATH,blob(s.recordBytes));const input={...s,before,after,bootstrapBytes:bytes,approvedBootstrapSha256:sha256(bytes),facts:{clean:true,candidateCommit:c('4'),candidateTree:c('5'),predecessorCommit:r.predecessor.commit,predecessorTree:r.predecessor.tree,anchorCommit:r.anchor.commit,anchorTree:r.anchor.tree,predecessorIsAncestor:true,anchorIsAncestor:true}};assert.equal(verifyMaintenanceTree(input).bootstrapFiles,BOOTSTRAP_PATHS.length);
 for(const mutate of [x=>delete x.approvedBootstrapSha256,x=>x.approvedBootstrapSha256=h('0'),x=>x.after.set(BOOTSTRAP_PATHS[0],blob('unreviewed')),x=>x.after.set('scripts/other-control.mjs',blob('extra')),x=>x.before.set(RECORD_PATH,blob('already bootstrapped'))]){const f={...input,before:new Map(before),after:new Map(after)};mutate(f);assert.throws(()=>verifyMaintenanceTree(f));}
 const altered=JSON.parse(bytes);altered.paths.pop();const bad=JSON.stringify(altered),rr={...r,bootstrapSha256:sha256(bad)},ss=seal(rr);assert.throws(()=>verifyMaintenanceTree({...input,...ss,after:new Map([...after,[RECORD_PATH,blob(ss.recordBytes)]]),bootstrapBytes:bad,approvedBootstrapSha256:sha256(bad)}));
});
test('image capability preserves v1 without a record and cannot enable CLOSED policy',()=>{const base={format:'cc-gh-yard-release-compatibility/v1',buildId:c('4'),playerRolloutEnabled:false,requiredClosedPredecessor:null};assert.equal(maintenanceCapability(base,{exists:()=>false}),base);assert.throws(()=>maintenanceCapability(base,{exists:()=>true,read:()=>seal(record()).recordBytes}),/cannot enable/);const r=record(),active={...base,playerRolloutEnabled:true,requiredClosedPredecessor:{buildId:r.anchor.closedBuildId,imageDigest:r.anchor.closedImageDigest}},cap=maintenanceCapability(active,{exists:()=>true,read:()=>seal(r).recordBytes});assert.equal(cap.format,'cc-gh-yard-release-compatibility/v2');assert.equal(cap.requiredActivePredecessor.buildId,r.predecessor.commit);assert.equal(cap.maintenanceRecordSha256,seal(r).approvedRecordSha256);assert.throws(()=>verifyYardRollbackTarget({candidate:cap}),/independently approved/);});
test('existing CLOSED and initial-activation verifier stays an independent mandatory branch',()=>{const priorDigest=d('c'),priorId=d('d'),build=c('a'),image=(id,revision,digest)=>({Id:id,RepoDigests:[`ghcr.io/le-who/cc-gh@${digest}`],Config:{Labels:{'org.opencontainers.image.revision':revision}}});const input={candidate:{format:'cc-gh-yard-release-compatibility/v1',buildId:build,playerRolloutEnabled:false,closedQuarantineVerified:true,readableStorageFormats:['yard-persistent/v1'],requiredLegacyPredecessor:{buildId:KNOWN_LEGACY_YARD_BUILD,imageDigest:priorDigest}},previous:null,previousHealth:{status:'ok',buildId:KNOWN_LEGACY_YARD_BUILD},candidateImage:image(d('e'),build,d('f')),previousImage:image(priorId,KNOWN_LEGACY_YARD_BUILD,priorDigest),repository:'le-who/cc-gh',candidateDigest:d('f'),candidateBuildId:build,previousImageId:priorId,previousBuildId:KNOWN_LEGACY_YARD_BUILD,persistentYardRows:0};assert.equal(verifyYardRollbackTarget(input).phase,'closed-compatible');assert.throws(()=>verifyYardRollbackTarget({...input,persistentYardRows:1}),/markers forbid/);const shell=read('scripts/yard-maintenance-pre-switch-guard.sh');assert.match(shell,/"\$#" -ne 11/);assert.match(shell,/maintenance-approved-sha256/);assert.match(shell,/default_transaction_read_only=on/);assert.doesNotMatch(shell,/compose .*up|UPDATE players|INSERT INTO|DATABASE_URL/);});
test('actual maintenance shell invokes the real v2 verifier and blocks changed approval or live image',()=>{
 const f=receiptFixture(),r=f.record,recordBytes=JSON.stringify(r),approved=sha256(recordBytes),receipt=JSON.stringify(normalizeAcceptedReceipt(f)),base={format:'cc-gh-yard-release-compatibility/v1',buildId:c('4'),playerRolloutEnabled:true,readableStorageFormats:['yard-persistent/v1'],requiredClosedPredecessor:{buildId:r.anchor.closedBuildId,imageDigest:r.anchor.closedImageDigest}};
 const candidate=maintenanceCapability(base,{exists:()=>true,read:()=>recordBytes});
 const metadata=(id,build,digest)=>({Id:id,RepoDigests:[`ghcr.io/le-who/cc-gh@${digest}`],Config:{Cmd:['node','server.js'],Env:['NODE_ENV=production',`APP_BUILD_ID=${build}`],Labels:{'org.opencontainers.image.revision':build}}});
 const fixture={candidate,previous:JSON.parse(readReceiptZip(f.archive)['image-identity.json']).compatibility.B,candidateImage:metadata(d('6'),c('4'),d('5')),previousImage:metadata(r.predecessor.imageId,r.predecessor.commit,r.predecessor.imageDigest),health:{status:'ok',buildId:r.predecessor.commit,postgres:true}};
 const docker=String.raw`#!/usr/bin/env node
const fs=require('node:fs'),cp=require('node:child_process'),a=process.argv.slice(2),f=JSON.parse(fs.readFileSync(process.env.FIXTURE+'/fixture.json'));const out=x=>process.stdout.write(JSON.stringify(x)+'\n');
if(a[0]==='image'&&a[1]==='inspect')out(a[2]===f.previousImage.Id?f.previousImage:f.candidateImage);
else if(a[0]==='run'&&a.includes('scripts/yard-release-compatibility.mjs'))out(f.candidate);
else if(a[0]==='run'&&a.includes('sh'))out(f.previous);
else if(a[0]==='run'&&a.includes('scripts/verify-yard-rollback-target.mjs')){const dir=a[a.indexOf('--mount')+1].match(/src=([^,]+)/)[1],p=cp.spawnSync(process.execPath,[process.env.VERIFIER,dir],{stdio:'inherit'});process.exit(p.status??1);}
else if(a[0]==='exec'){if(a[a.indexOf('-c')+1]!=="SELECT count(*) FROM players WHERE data ? '_yardV2';")process.exit(9);if(!a.includes('PGOPTIONS=-c default_transaction_read_only=on -c statement_timeout=10000 -c lock_timeout=3000'))process.exit(9);process.stdout.write('5\n');}
else if(a[0]==='inspect')process.stdout.write((f.liveChanged?'sha256:'+'0'.repeat(64):f.previousImage.Id)+'\n');else process.exit(9);
`;
 const curl=String.raw`#!/usr/bin/env node
const fs=require('node:fs');process.stdout.write(JSON.stringify(JSON.parse(fs.readFileSync(process.env.FIXTURE+'/fixture.json')).health)+'\n');`;
 const dir=mkdtempSync(join(tmpdir(),'maintenance-shell-'));try{mkdirSync(join(dir,'bin'));for(const [name,text]of [['docker',docker],['curl',curl]])writeFileSync(join(dir,'bin',name),text,{mode:0o700});writeFileSync(join(dir,'record.json'),recordBytes);writeFileSync(join(dir,'receipt.json'),receipt);
  for(const condition of ['valid','approval-changed','live-changed']){writeFileSync(join(dir,'fixture.json'),JSON.stringify({...fixture,liveChanged:condition==='live-changed'}));const p=spawnSync('bash',[resolve(root,'scripts/yard-maintenance-pre-switch-guard.sh'),'ghcr.io/le-who/cc-gh@'+d('5'),c('4'),r.predecessor.imageId,r.predecessor.commit,'8080','fixture-user','fixture-db','le-who/cc-gh',condition==='approval-changed'?h('0'):approved,join(dir,'record.json'),join(dir,'receipt.json')],{env:{PATH:join(dir,'bin')+':'+process.env.PATH,TMPDIR:dir,FIXTURE:dir,VERIFIER:resolve(root,'scripts/verify-yard-rollback-target.mjs')},encoding:'utf8',timeout:15000});if(condition==='valid'){assert.equal(p.status,0,p.stderr);assert.equal(JSON.parse(p.stdout).phase,'active-maintenance');}else assert.notEqual(p.status,0);}
 }finally{rmSync(dir,{recursive:true,force:true});}
});

test('no unknown B2 identity, digest or self-approved request can start the lane',()=>{for(const value of [undefined,'',h('0')])assert.throws(()=>parseMaintenanceRequest('{}',value));assert.throws(()=>loadMaintenanceInputs({CI:'true',YARD_MAINTENANCE_ACCEPTANCE:'1'},root));const p=spawnSync(process.execPath,['scripts/yard-maintenance-production.mjs'],{cwd:root,env:{PATH:process.env.PATH,CI:'true',YARD_MAINTENANCE_ACCEPTANCE:'1'},encoding:'utf8',timeout:5000});assert.notEqual(p.status,0);assert.doesNotMatch(p.stderr,/docker|PostgreSQL did not start/);});
test('source-only image build request cannot become acceptance or invent a candidate digest',()=>{const request={format:'cc-gh-yard-maintenance-build-request/v1',toolCommit:c('4'),candidateCommit:c('4'),candidateTree:c('5'),recordSha256:h('6'),predecessorReceipt:receiptFixture().locator,bootstrap:null},bytes=JSON.stringify(request);assert.equal(parseMaintenanceBuildRequest(bytes,sha256(bytes)).candidateDigest,undefined);assert.throws(()=>parseMaintenanceRequest(bytes,sha256(bytes)));const bad=JSON.stringify({...request,candidateDigest:d('7')});assert.throws(()=>parseMaintenanceBuildRequest(bad,sha256(bad)));const publish=read('.github/workflows/yard-maintenance-image.yml');assert.match(publish,/--build-plan/);assert.match(publish,/built-not-runtime-accepted/);assert.match(publish,/tags: ghcr.io\/le-who\/cc-gh:maintenance-/);assert.doesNotMatch(publish,/ssh-action|:latest\b|scripts\/yard-maintenance-production/);const f=receiptFixture();f.run.path='.github/workflows/yard-maintenance-image.yml';assert.throws(()=>normalizeAcceptedReceipt(f));});
test('navigation-only outbox retry cannot falsely prove a drained queue or hide other storage errors',async()=>{assert.equal(await outboxPresenceForPoll(async()=>({items:[{clientActionId:'owned'}]}),'owned'),'pending');assert.equal(await outboxPresenceForPoll(async()=>null,'owned'),'drained');assert.equal(await outboxPresenceForPoll(async()=>{throw Error('page.evaluate: Execution context was destroyed, most likely because of a navigation');},'owned'),'navigation-pending');for(const message of ['IndexedDB read failed','Target page has been closed','page.evaluate: arbitrary error'])await assert.rejects(()=>outboxPresenceForPoll(async()=>{throw Error(message);},'owned'),{message});const spec=read('tests/yard-maintenance-e2e/maintenance.spec.js');assert.match(spec,/outboxPresenceForPoll\(\(\)=>outbox\(page,f\.id\),lost\.command\.clientActionId\)\)\.toBe\('drained'\)/);});
test('affected-game discovery includes core Blox and Match3 logic and fails on missing suites',()=>{const dir=mkdtempSync(join(tmpdir(),'maintenance-unit-files-'));try{mkdirSync(join(dir,'tests'));for(const name of ['blox.test.js','blox-pause-visibility.test.js','match3.test.js','match3-render-budget.test.js'])writeFileSync(join(dir,'tests',name),'');assert.deepEqual(affectedUnitFiles(dir,['blox','match3']),['tests/blox-pause-visibility.test.js','tests/blox.test.js','tests/match3-render-budget.test.js','tests/match3.test.js']);assert.throws(()=>affectedUnitFiles(dir,['settlement']),/No actual/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('exact case inventory rejects missing, retried and fabricated browser success',()=>{const r=record(),inputs={record:r,activeCommit:c('4'),activeDigest:d('5'),closedCommit:r.predecessor.commit,closedDigest:r.predecessor.imageDigest,requestSha256:h('6')},runId='fixture';const base=['ACTIVE persistence P-C-P preserves progress and durable replay','same-origin ACTIVE P-C-P preserves lost-reply intent and service-worker state','ACTIVE storage rejects invalid and future markers without mutation','cross-game actual B: authentic Merge Moon Lamp enters Yard, places once and persists in PostgreSQL','cross-game actual B: three fixture-assisted real Blox finishes fund one Merge pack exactly once','cross-game actual B: seven available routes survive rapid Home ownership and reload','changed game settlement: actual image, viewport, navigation and reload'];const report={config:{metadata:{runId,activeCommit:inputs.activeCommit,activeDigest:inputs.activeDigest,predecessorCommit:inputs.closedCommit,predecessorDigest:inputs.closedDigest,requestSha256:inputs.requestSha256}},stats:{expected:7,unexpected:0,flaky:0,skipped:0},suites:[{specs:base.map(title=>({title,ok:true,tests:[{results:[{status:'passed',retry:0}]}]}))}]};assert.equal(assertMaintenanceCaseResults(report,{runId,inputs}),7);for(const mutate of [x=>x.suites[0].specs.pop(),x=>x.suites[0].specs[0].tests[0].results.push({status:'passed',retry:1}),x=>x.suites[0].specs[0].tests[0].results[0].status='skipped',x=>x.stats.skipped=1,x=>x.config.metadata.activeDigest=d('0')]){const bad=structuredClone(report);mutate(bad);assert.throws(()=>assertMaintenanceCaseResults(bad,{runId,inputs}));}});
test('maintenance aggregate permits only complete mode-specific results and rejects all required failures',()=>{const s=read('.github/workflows/ci.yml'),match=s.slice(s.indexOf('  release-ready:')).match(/node --input-type=module <<'JS'\n([\s\S]*?)          JS/);assert.ok(match);const code=match[1].split('\n').map(x=>x.slice(10)).join('\n');const skipped=['test','yard-player','yard-eight-player','browser-plan','browser','touch','mochi','docker','yard-closed-receipt','yard-active','yard-active-production'],needs=Object.fromEntries([...skipped.map(n=>[n,{result:'skipped'}]),['yard-release-mode',{result:'success'}],['yard-maintenance-preflight',{result:'success'}]]);const run=(results,reuse='true')=>spawnSync(process.execPath,['--input-type=module'],{input:code,env:{PATH:process.env.PATH,RELEASE_MODE:'MAINTENANCE',REUSE_CLOSED:reuse,RELEASE_RESULTS:JSON.stringify(results)},encoding:'utf8'}).status;assert.equal(run(needs),0);for(const name of Object.keys(needs))for(const outcome of ['failure','cancelled',needs[name].result==='success'?'skipped':'success'])assert.notEqual(run({...needs,[name]:{result:outcome}}),0);assert.notEqual(run(needs,'false'),0);});
test('the minimal release lane remains explicit, immutable-image-only and gated before its locked switch',()=>{const acceptance=read('.github/workflows/yard-maintenance-acceptance.yml'),release=read('.github/workflows/yard-maintenance-release.yml'),runner=read('scripts/yard-maintenance-production.mjs');assert.match(acceptance,/workflow_dispatch:/);assert.doesNotMatch(acceptance,/packages: write|docker build|docker push|ssh-action/);assert.match(release,/default: false/);assert.match(release,/needs: maintenance-acceptance/);assert.match(release,/if: inputs\.deploy == true && github\.ref == 'refs\/heads\/codex\/telegram-pixi-vps-migration'/);assert.match(release,/bash scripts\/yard-maintenance-pre-switch-guard\.sh/);assert.match(release,/"\$MAINTENANCE_RECORD_SHA256" "\$RELEASE_STAGING_PATH\/maintenance-proof\/preflight\/record\.json"/);assert.ok(release.indexOf('flock -n 9')<release.indexOf('bash scripts/yard-maintenance-pre-switch-guard.sh'));assert.ok(release.indexOf('bash scripts/yard-maintenance-pre-switch-guard.sh')<release.indexOf('RELEASE_SWITCH_STARTED=1'));assert.doesNotMatch(release,/continue-on-error:|docker build|docker push|packages: write/);assert.match(runner,/verifyMaintenanceRollback/);assert.match(runner,/assertMaintenanceCaseResults/);assert.match(runner,/completedProof&&!process\.exitCode/);assert.doesNotMatch(runner,/setSystemTime|registerHooks|DEV_AUTH_ENABLED:'true'/);});

test('warm browser and HTTP atlas proof rejects stale cache bytes, wrong type, missing bytes and wrong target',()=>{
 const disk=Buffer.from('exact immutable atlas bytes'),path='/assets/yard-mochi/canonical.webp',base={path,disk,browser:{path,status:200,contentType:'image/webp',bytes:disk.length,sha256:sha256(disk)},http:{status:200,contentType:'image/webp',bytes:disk}};
 assert.deepEqual(assertMaintenanceDeliveredMedia(base),{path,bytes:disk.length,sha256:sha256(disk)});
 for(const mutate of [x=>x.browser.sha256=h('0'),x=>x.browser.bytes--,x=>x.browser.status=404,x=>x.browser.contentType='text/html',x=>x.browser.path='/assets/foreign.webp',x=>x.http.status=404,x=>x.http.contentType='text/html',x=>x.http.bytes=Buffer.from('stale'),x=>x.disk=Buffer.from('changed image'),x=>x.disk=Buffer.alloc(0)]){const value={...base,browser:{...base.browser},http:{...base.http}};mutate(value);assert.throws(()=>assertMaintenanceDeliveredMedia(value));}
});
test('P-C-P warm proof reads each image metadata and requires delivered actor pixels at every transition',async()=>{
 const spec=read('tests/yard-maintenance-e2e/maintenance.spec.js');
 assert.match(spec,/metadata=\{A:JSON\.parse\(await readFile\(resolve\(out,'metadata-A\.json'/);assert.match(spec,/B:JSON\.parse\(await readFile\(resolve\(out,'metadata-B\.json'/);
 const helper=spec.match(/async function browserMetadata\(page,mode\)\{([\s\S]*?)\n\}/);assert.ok(helper);
 const mockExpect=actual=>({toBe:expected=>assert.equal(actual,expected)}),metadataUrls=['/assets/yard-mochi/runtime-media.json','/assets/yard-pebble/runtime-media.json'];
 const metadata=Object.fromEntries(['A','B'].map(mode=>[mode,Object.fromEntries(metadataUrls.map((path,i)=>[path.slice(1),JSON.stringify({playbackReady:true,runtimeActivated:i===0,identity:mode})]))]));
 const check=new Function('expect','metadataUrls','metadata','origin','sha',`return async function(page,mode){${helper[1]}}`)(mockExpect,metadataUrls,metadata,()=> 'http://127.0.0.1',sha256);
 const rows=mode=>metadataUrls.map(url=>({url,status:200,text:metadata[mode][url.slice(1)]}));
 assert.equal((await check({evaluate:async()=>rows('A')},'A')).length,2);
 await assert.rejects(()=>check({evaluate:async()=>rows('A')},'B'),'A stale browser/SW manifest must fail the C stage');
 for(const change of [x=>x[0].status=404,x=>x[0].text+=' ',x=>x[1].text='{}']){const value=rows('A');change(value);await assert.rejects(()=>check({evaluate:async()=>value},'A'));}
 const warm=spec.slice(spec.indexOf("test('same-origin ACTIVE P-C-P"),spec.indexOf("test('ACTIVE storage rejects"));
 for(const [mode,phase]of [['A','initial-P'],['B','candidate-C'],['A','rollback-P'],['B','restored-C']])assert.ok(warm.includes(`inspectWarmPixels(page,request,info,'mochi','${mode}','${phase}')`));
 assert.match(warm,/seed\('mochi'\)/);assert.match(warm,/warmAgain\.map\(row=>row\.sha256\)\)\.toEqual\(warmP/);assert.match(warm,/warmFinal\.map\(row=>row\.sha256\)\)\.toEqual\(warmC/);
 assert.match(spec,/row\.sceneCanvas&&attributedDraw\(row,pages\)/);assert.match(spec,/actorAtlasPages\(JSON\.parse\(manifestText\),actorPath\(actor\)\)/);assert.match(spec,/crypto\.subtle\.digest\('SHA-256',bytes\)/);assert.match(spec,/mode==='A'\?containerP:containerB,'cat'/);assert.match(spec,/assertMaintenanceDeliveredMedia\(\{browser,http:/);
});
test('long cross-version progress preserves every economic field and permits only bounded monotonic full-energy clocks',async()=>{
 const source=read('tests/yard-maintenance-e2e/maintenance.spec.js'),wallet=source.match(/function assertReplayWallet\(actual,expected,\{startedAt,finishedAt\}\)\{([\s\S]*?)\n\}/),progress=source.match(/const savedProgress=p=>\(([^\n]+)\);/),compare=source.match(/function assertSavedProgress\(actual,expected,window\)\{([\s\S]*?)\n\}/);assert.ok(wallet&&progress&&compare);
 const check=new Function('assert',`const savedProgress=p=>(${progress[1]});function assertReplayWallet(actual,expected,{startedAt,finishedAt}){${wallet[1]}}return function(actual,expected,window){${compare[1]}}`)(assert);
 const before={yard:{currencies:{treats:20,shinyTreats:4},foodInventory:{kibble:3},goodieInventory:{lamp:1},placedGoodies:[{id:'placed',uses:2}]},_yardV2:{runtime:{commandReceipts:{nonce:{ok:true}}},migration:{rawBackup:{yard:{preserved:true}}}},resources:{gold:500,gachaTokens:12,energy:{current:20,max:20,lastRegenTimestamp:10000}},garden:{owned:['seed']},farm:{harvested:{wheat:2}},merge:{stock:{glass:2}}},window={startedAt:11000,finishedAt:12000};
 const after=structuredClone(before);after.resources.energy.lastRegenTimestamp=11500;assert.doesNotThrow(()=>check(after,before,window));assert.doesNotThrow(()=>check(before,before,window));
 for(const change of [p=>p.yard.currencies.treats++,p=>p.yard.currencies.shinyTreats++,p=>p.yard.foodInventory.kibble++,p=>p.yard.goodieInventory.lamp++,p=>p.yard.placedGoodies[0].uses++,p=>delete p._yardV2.runtime.commandReceipts.nonce,p=>p._yardV2.migration.rawBackup.yard.preserved=false,p=>p.garden.owned.push('unearned'),p=>p.farm.harvested.wheat++,p=>p.merge.stock.glass++,p=>p.resources.gold++,p=>p.resources.gachaTokens++,p=>p.resources.energy.current--,p=>p.resources.energy.max++,p=>p.resources.energy.extra=1,p=>p.resources.extra=1,p=>delete p.resources.gold,p=>delete p.resources.energy.current,p=>delete p.resources.energy.lastRegenTimestamp,p=>p.resources.energy.lastRegenTimestamp='11500',p=>p.resources.energy.lastRegenTimestamp=9999,p=>p.resources.energy.lastRegenTimestamp=12001,p=>p.resources.energy.lastRegenTimestamp=10001]){const bad=structuredClone(after);change(bad);assert.throws(()=>check(bad,before,window));}
 const depleted=structuredClone(before);depleted.resources.energy.current--;assert.throws(()=>check(after,depleted,window));
 assert.throws(()=>check(before,after,{startedAt:12000,finishedAt:13000}),'Immediate prior observation prevents backward drift');
 assert.doesNotMatch(source,/expect\(savedProgress\(/);assert.doesNotMatch(source,/expect\([^\n]*\.resources\)\.toEqual\(savedOnce\.resources\)/);
 assert.match(source,/reply\.serverTime>=window\.startedAt&&reply\.serverTime<=window\.finishedAt/);assert.match(source,/toBeGreaterThanOrEqual\(reply\.resources\.energy\.lastRegenTimestamp\)/);
 const preserved=source.match(/async function preservedProgress\(f,prior,reply\)\{([\s\S]*?)\n\}/);assert.ok(preserved);
 const expected=actual=>({toBeLessThanOrEqual:value=>assert.ok(actual<=value),toBeGreaterThanOrEqual:value=>assert.ok(actual>=value)});
 const validate=new Function('assert','expect','Date','observedSaved',`const savedProgress=p=>(${progress[1]});function assertReplayWallet(actual,expected,{startedAt,finishedAt}){${wallet[1]}}function assertSavedProgress(actual,expected,window){${compare[1]}}return async function(f,prior,reply){${preserved[1]}}`)(assert,expected,{now:()=>12000},async()=>({value:after,startedAt:11900}));
 const reply={serverTime:11550,resources:{...structuredClone(after.resources),harvested:{wheat:2},harvestedCrops:{wheat:2}}},prior={value:before,startedAt:11000};
 await validate(null,prior,reply);
 for(const change of [x=>x.serverTime=13000,x=>x.serverTime=10000,x=>x.serverTime='11550',x=>x.serverTime=11499,x=>x.resources.energy.lastRegenTimestamp=11600,x=>x.resources.harvested.wheat++,x=>x.resources.harvestedCrops.wheat++,x=>delete x.resources.harvested,x=>x.resources.gold++,x=>x.resources.extra=1]){const bad=structuredClone(reply);change(bad);await assert.rejects(()=>validate(null,prior,bad));}
});
test('the first Settlement QA capsule is separately pinned and admits only all five exact reviewed paths',()=>{
 const r=record(),before=new Map(),after=new Map(),rows=paths=>paths.map(path=>{const row={path,before:null,after:blob('reviewed '+path)};after.set(path,row.after);return row;}),paths=rows(BOOTSTRAP_PATHS),qa={format:'cc-gh-yard-settlement-qa-bootstrap/v1',sourceManifestSha256:h('4'),paths:rows(SETTLEMENT_QA_PATHS)};
 const wrap=value=>{const bytes=JSON.stringify(value);return {bytes,sha256:sha256(bytes)};};
 const capsule={format:'cc-gh-yard-maintenance-bootstrap/v1',anchorCommit:r.anchor.commit,paths,settlementQa:wrap(qa)};
 const verify=(value,{b=before,a=after,rec=r}={})=>{const bytes=JSON.stringify(value),expectedSha256=sha256(bytes);return verifyMaintenanceBootstrap({bytes,expectedSha256,record:{...rec,bootstrapSha256:expectedSha256},before:b,after:a});};
 assert.deepEqual(verify(capsule),[...BOOTSTRAP_PATHS,...SETTLEMENT_QA_PATHS]);
 for(const change of [x=>x.settlementQa.sha256=h('0'),x=>x.settlementQa.bytes+=' ',x=>delete x.settlementQa.sha256,x=>{const q=structuredClone(qa);q.paths.pop();x.settlementQa=wrap(q);},x=>{const q=structuredClone(qa);q.paths[0].path='.github/workflows/deploy.yml';x.settlementQa=wrap(q);},x=>{const q=structuredClone(qa);q.paths[0].after.mode='100755';x.settlementQa=wrap(q);},x=>{const q=structuredClone(qa);q.paths.push(q.paths[0]);x.settlementQa=wrap(q);},x=>{const q=structuredClone(qa);delete q.sourceManifestSha256;x.settlementQa=wrap(q);},x=>{const q=structuredClone(qa);q.paths[0].before=blob('unreviewed base');x.settlementQa=wrap(q);}]){const bad=structuredClone(capsule);change(bad);assert.throws(()=>verify(bad));}
 assert.throws(()=>verify(capsule,{rec:{...r,affectedGames:['blox']}}));assert.throws(()=>verify(capsule,{b:new Map([[RECORD_PATH,blob('prior maintenance')]])}));
 const badTree=new Map(after);badTree.set(SETTLEMENT_QA_PATHS[0],blob('unreviewed workflow'));assert.throws(()=>verify(capsule,{a:badTree}));
 const omitted=structuredClone(capsule);delete omitted.settlementQa;const bytes=JSON.stringify(omitted);r.bootstrapSha256=sha256(bytes);const s=seal(r);after.set(RECORD_PATH,blob(s.recordBytes));after.set(r.changes[0].path,r.changes[0].after);before.set(r.changes[0].path,r.changes[0].before);
 assert.throws(()=>verifyMaintenanceTree({...s,before,after,bootstrapBytes:bytes,approvedBootstrapSha256:sha256(bytes),facts:{clean:true,candidateCommit:c('4'),candidateTree:c('5'),predecessorCommit:r.predecessor.commit,predecessorTree:r.predecessor.tree,anchorCommit:r.anchor.commit,anchorTree:r.anchor.tree,predecessorIsAncestor:true,anchorIsAncestor:true}}),/Full tree differs/,'Missing capsule cannot authorize these protected files');
 for(const path of SETTLEMENT_QA_PATHS){const changed=record();changed.changes=[{path,before:null,after:blob('unreviewed')}];assert.throws(()=>parseMaintenanceRecord(seal(changed).recordBytes,seal(changed).approvedRecordSha256),/Separate protocol/);}
});
test('the final Yard and Garden copy payload names both games and includes their actual focused suites',()=>{
 const r=record();r.affectedGames=['settlement','yard','garden'];assert.deepEqual(parseMaintenanceRecord(seal(r).recordBytes,seal(r).approvedRecordSha256).affectedGames,r.affectedGames);
 const dir=mkdtempSync(join(tmpdir(),'maintenance-garden-checks-'));try{mkdirSync(join(dir,'tests'));const expected=['garden-interaction.test.js','garden-local-state.test.js','garden-navigation-observation.test.js','garden-release-integration.test.js','yard-garden-player-copy.test.mjs'];for(const name of [...expected,'garden-r2-postgres.test.mjs','unrelated.test.js'])writeFileSync(join(dir,'tests',name),'');assert.deepEqual(affectedUnitFiles(dir,['garden']),expected.map(name=>'tests/'+name).sort());assert.deepEqual(affectedUnitFiles(dir,['yard']),['tests/yard-garden-player-copy.test.mjs']);}finally{rmSync(dir,{recursive:true,force:true});}
 assert.match(read('tests/yard-maintenance-e2e/maintenance.spec.js'),/room:'\.cy-app',garden:'\.gs2-stage'/);
});
test('Settlement discovery includes every canonical illustrated and Council mjs suite',()=>{
 const dir=mkdtempSync(join(tmpdir(),'maintenance-settlement-checks-'));try{
  mkdirSync(join(dir,'tests'));const suites=['settlement-expedition-ui.test.mjs','settlement-generated-art.test.mjs','settlement-goal-presentation.test.mjs','settlement-illustrated-kit.test.mjs','settlement-natural-raster-policy.test.mjs','settlement-nine-slice.test.mjs','settlement-secondary-truthfulness.test.mjs','settlement-council-truthfulness.test.mjs','settlement-existing.test.js'];
  for(const name of [...suites,'unrelated.test.mjs'])writeFileSync(join(dir,'tests',name),'');assert.deepEqual(affectedUnitFiles(dir,['settlement']),suites.map(name=>'tests/'+name).sort());
 }finally{rmSync(dir,{recursive:true,force:true});}
});

test('Home changes run catalogue, entry and retained-navigation foundations',()=>{
 const dir=mkdtempSync(join(tmpdir(),'maintenance-home-checks-'));try{mkdirSync(join(dir,'tests'));const expected=['game-entry-presentation.test.mjs','game-ux-foundations.test.js','home-navigation.test.js'];for(const name of [...expected,'settlement-cycle.test.js'])writeFileSync(join(dir,'tests',name),'');assert.deepEqual(affectedUnitFiles(dir,['home']),expected.map(name=>'tests/'+name));}finally{rmSync(dir,{recursive:true,force:true});}
});
test('hide-only browser oracle requires seven exact entries and preserves a real prior-image save without repair',()=>{
 const spec=read('tests/yard-maintenance-e2e/maintenance.spec.js');
 assert.match(spec,/seven available routes survive rapid Home ownership and reload/);assert.doesNotMatch(spec,/all eight real routes/);
 const moon=spec.slice(spec.indexOf("test('cross-game actual B: authentic"),spec.indexOf("test('cross-game actual B: three"));assert.match(moon,/crossSelect\(page,'garden'\)/);assert.doesNotMatch(moon,/crossSelect\(page,'settlement'\)/);
 const home=spec.slice(spec.indexOf("if(game==='home')"));assert.match(home,/setProxyState\(statePath,\{target:'A'\}\);await boot\(page,f\);await crossSelect\(page,'settlement'\)/);
 assert.match(home,/const townSave=await readTownSave\(page\)/);assert.ok((home.match(/expect\(await readTownSave\(page\)\)\.toBe\(townSave\)/g)||[]).length>=6);
 assert.doesNotMatch(spec,/localStorage\.setItem\(['"]village-ascend-v11-state/);assert.doesNotMatch(home,/addInitScript|removeItem/);
 assert.match(home,/width:320,height:568/);assert.match(home,/width:390,height:844/);assert.match(home,/width:568,height:320/);
 assert.match(home,/assertReplayWallet\(\(await saved\(f\)\)\.resources,before/);assert.match(home,/structuredClone\(\(await saved\(f\)\)\.resources\)/);
});
