import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
import fixture from './fixtures/canonical-saved-public.json' with{type:'json'};
import{canonicalSavedFoodReady as ready,canonicalSavedFoodCommandAllowed as allow}from'../src/games/companion-yard-v2/canonical-saved-food-actions.mjs';
const acts=['yard.buyFood','yard.setFood'];
function fixtureCase(){const snapshot=structuredClone(fixture);snapshot.player={id:'saved-food-owner'};Object.assign(snapshot.yardRuntime,{mutable:false,actionProtocol:'yard-v2:',supportedActions:[...acts],canonicalFoodActions:{protocol:'yard-canonical-food-actions/v1',enabled:true,actions:[...acts]},supportedBindings:{foods:{kibble:{buy:true,set:true},berry_plate:{buy:true,set:true},bonito_bowl:{buy:true,set:true}},bowls:{'bowl-1':{set:true}}}});snapshot.yard.currencies={treats:120,shinyTreats:2};snapshot.yard.foodInventory={kibble:3,berry_plate:1,bonito_bowl:1};
 const current={runtime:snapshot.yardRuntime,canonicalSavedVisits:true,canonicalItems:true,mutable:false,itemMutable:false,mediaReady:true,canonicalFood:{loading:false,reentryRequired:false,reserved:true,render:{available:true,state:'kibble'}},visualPrototype:{ready:true,canonicalSavedVisits:true,actorUnitsPerSource:16,restartPending:false,viewportBlocked:false,plannerWorkerActive:false,itemEditing:false,itemActionPending:false,pauseReasons:[],phase:'rest',savedVisit:{status:'ready',visitId:snapshot.yardRuntime.canonicalVisits[0].visitId}}};return{snapshot,current};}
test('only exact saved food authority enables three known foods through two ordinary commands',()=>{const{snapshot:s,current:v}=fixtureCase(),before=JSON.stringify({s,v});assert(ready(s,v));for(const foodId of['kibble','berry_plate','bonito_bowl']){assert(allow(s,v,'yard.buyFood',{foodId,qty:1}));assert(allow(s,v,'yard.setFood',{bowlId:'bowl-1',foodId}));}assert.equal(JSON.stringify({s,v}),before);assert.equal(s.yardRuntime.mutable,false);assert.equal(v.itemMutable,false);});
test('wrong/missing/expanded authority, pending and unknown versions stay disabled',()=>{for(const mutate of[
 s=>delete s.yardRuntime.canonicalFoodActions,s=>s.yardRuntime.canonicalFoodActions.enabled=false,s=>s.yardRuntime.canonicalFoodActions.protocol='unknown',s=>s.yardRuntime.canonicalFoodActions.actions.push('yard.buyGoodie'),s=>s.yardRuntime.canonicalFoodActions.extra=true,s=>s.yardRuntime.supportedActions=['yard.buyFood'],s=>s.yardRuntime.supportedActions.push('yard.moveGoodie'),s=>s.yardRuntime.status='reconciliation-pending',s=>s.yardRuntime.status='review-required',s=>s.yardRuntime.mutable=true,s=>s.yardRuntime.storageVersion=4,s=>s.yardRuntime.canonicalVisitProtocol='unknown',s=>s.yardRuntime.actionProtocol='yard-v3:',s=>s.yardRuntime.error='failed',s=>delete s.player.id,s=>s.yardRuntime.serverNow=NaN]){const{snapshot:s,current:v}=fixtureCase();mutate(s);assert.equal(ready(s,v),false);assert.equal(allow(s,v,'yard.buyFood',{foodId:'kibble',qty:1}),false);}});
test('actor, ownership and rendered food readiness fail closed',()=>{for(const mutate of[
 v=>v.canonicalSavedVisits=false,v=>v.canonicalItems=false,v=>v.mediaReady=false,v=>v.mutable=true,v=>v.itemMutable=true,v=>v.visualPrototype.ready=false,v=>v.visualPrototype.canonicalSavedVisits=false,v=>v.visualPrototype.actorUnitsPerSource=12,v=>v.visualPrototype.restartPending=true,v=>v.visualPrototype.viewportBlocked=true,v=>v.visualPrototype.plannerWorkerActive=true,v=>v.visualPrototype.itemEditing=true,v=>v.visualPrototype.itemActionPending=true,v=>v.visualPrototype.phase='failed',v=>v.visualPrototype.phase='loading',v=>v.visualPrototype.phase='departed',v=>v.visualPrototype.savedVisit.status='reconciliation-pending',v=>v.visualPrototype.savedVisit.visitId='foreign',v=>v.canonicalFood.loading=true,v=>v.canonicalFood.reentryRequired=true,v=>v.canonicalFood.reserved=false,v=>v.canonicalFood.render.available=false,v=>v.canonicalFood.render.state='berry_plate']){const{snapshot:s,current:v}=fixtureCase();mutate(v);assert.equal(ready(s,v),false);}});
test('no actor is necessary in an empty reconciled saved scene; latest scene signal is used',()=>{const{snapshot:s,current:v}=fixtureCase();s.yardRuntime.canonicalVisits=[];v.visualPrototype.savedVisit.visitId=null;v.visualPrototype.phase='empty';assert(ready(s,v));const latest={...v.visualPrototype,phase:'failed'};assert.equal(ready(s,v,latest),false);v.visualPrototype.phase='loading';assert(ready(s,v,{...latest,phase:'empty'}));});
test('missing wallet/inventory, malformed balances and insufficient cost never enable purchases',()=>{for(const mutate of[s=>delete s.yard.currencies,s=>delete s.yard.currencies.treats,s=>s.yard.currencies.treats='120',s=>s.yard.currencies.shinyTreats=NaN,s=>s.yard.currencies.treats=-1,s=>delete s.yard.foodInventory,s=>s.yard.foodInventory=[],s=>s.yard.foodInventory.berry_plate=null,s=>s.yard.foodInventory.berry_plate='1']){const{snapshot:s,current:v}=fixtureCase();mutate(s);assert.equal(allow(s,v,'yard.buyFood',{foodId:'berry_plate',qty:1}),false);}const{snapshot:s,current:v}=fixtureCase();s.yard.currencies.treats=119;assert.equal(allow(s,v,'yard.buyFood',{foodId:'berry_plate',qty:1}),false);s.yard.currencies.shinyTreats=1;assert.equal(allow(s,v,'yard.buyFood',{foodId:'bonito_bowl',qty:1}),false);assert(allow(s,v,'yard.buyFood',{foodId:'kibble',qty:1}));});
test('sparse zero stock may be purchased, but cannot fill a bowl; flags remain action-specific',()=>{const{snapshot:s,current:v}=fixtureCase();delete s.yard.foodInventory.berry_plate;assert(allow(s,v,'yard.buyFood',{foodId:'berry_plate',qty:1}));assert.equal(allow(s,v,'yard.setFood',{bowlId:'bowl-1',foodId:'berry_plate'}),false);s.yardRuntime.supportedBindings.foods.kibble.buy=false;assert.equal(allow(s,v,'yard.buyFood',{foodId:'kibble',qty:1}),false);assert(allow(s,v,'yard.setFood',{bowlId:'bowl-1',foodId:'kibble'}));s.yardRuntime.supportedBindings.bowls['bowl-1'].set=false;assert.equal(allow(s,v,'yard.setFood',{bowlId:'bowl-1',foodId:'kibble'}),false);});
test('extra payload fields, other bowls, bulk quantities, unknown foods and all other actions are blocked',()=>{const{snapshot:s,current:v}=fixtureCase();for(const[action,payload]of[['yard.buyFood',{foodId:'kibble',qty:2}],['yard.buyFood',{foodId:'kibble',qty:'1'}],['yard.buyFood',{foodId:'kibble',qty:1,price:0}],['yard.buyFood',{foodId:'constructor',qty:1}],['yard.buyFood',{foodId:'other',qty:1}],['yard.setFood',{bowlId:'bowl-2',foodId:'kibble'}],['yard.setFood',{bowlId:'bowl-1',foodId:'kibble',locationId:'pip-garden'}],['yard.buyGoodie',{goodieId:'leaf_pot'}],['yard.moveGoodie',{}],['yard.collectGifts',{}],['yard.configureCompanion',{}]])assert.equal(allow(s,v,action,payload),false);});
test('component keeps existing account fence, ordinary nonce, outbox and non-food read-only gates',()=>{const source=fs.readFileSync(new URL('../src/games/companion-yard-v2/CourtyardGame.jsx',import.meta.url),'utf8');assert.match(source,/state\.accountSession!==actionSession/);assert.match(source,/canonicalSavedFoodCommandAllowed\(state\.snapshot,current,action,payload,pipPreview\)/);assert.match(source,/canonical\?canonicalNoncePrefix\(state\.snapshot\):'yard-v2:'/);assert.match(source,/durability:'outbox'/);assert.match(source,/itemMutable=!savedMode&&/);assert.match(source,/canBuyGoodie=.*!savedMode/);assert.match(source,/!savedMode&&\(allowPipPrototype/);assert.match(source,/savedFoodDisabled\('yard.buyFood'/);assert.match(source,/savedFoodDisabled\('yard.setFood'/);});

test('context loss before restore blocks despite the old food view still reporting available',()=>{const{snapshot:s,current:v}=fixtureCase();assert(ready(s,v));const lost={...v.visualPrototype,pauseReasons:['context-lost'],ready:true,phase:'rest',restartPending:false};assert.equal(v.canonicalFood.render.available,true);assert.equal(ready(s,v,lost),false);assert.equal(allow(s,v,'yard.buyFood',{foodId:'kibble',qty:1},lost),false);for(const pause of ['ready','viewport','hidden','blur','future-pause'])assert.equal(ready(s,v,{...v.visualPrototype,pauseReasons:[pause]}),false);const missing={...v.visualPrototype};delete missing.pauseReasons;assert.equal(ready(s,v,missing),false);});
