import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {yardReleaseCompatibility} from '../scripts/yard-release-compatibility.mjs';
import {verifyYardRollbackTarget,KNOWN_LEGACY_YARD_BUILD} from '../scripts/verify-yard-rollback-target.mjs';
const root=fileURLToPath(new URL('..',import.meta.url)),build='a'.repeat(40),previousBuild=KNOWN_LEGACY_YARD_BUILD,digest='sha256:'+'c'.repeat(64),priorDigest='sha256:'+'d'.repeat(64),previousId='sha256:'+'e'.repeat(64),repo='le-who/cc-gh';
const image=(Id,sha,revision)=>({Id,RepoDigests:[`ghcr.io/${repo}@${sha}`],Config:{Labels:{'org.opencontainers.image.revision':revision}}});
function fixture(){return {candidate:{...yardReleaseCompatibility(build),requiredLegacyPredecessor:{buildId:previousBuild,imageDigest:priorDigest}},previous:null,previousHealth:{status:'ok',buildId:previousBuild},candidateImage:image('sha256:'+'f'.repeat(64),digest,build),previousImage:image(previousId,priorDigest,previousBuild),repository:repo,candidateDigest:digest,candidateBuildId:build,previousImageId:previousId,previousBuildId:previousBuild,persistentYardRows:0};}
function activation(){const f=fixture(),closedBuild='b'.repeat(40);f.previousBuildId=closedBuild;f.previousHealth.buildId=closedBuild;f.previousImage=image(previousId,priorDigest,closedBuild);f.candidate.playerRolloutEnabled=true;f.candidate.closedQuarantineVerified=false;f.candidate.requiredClosedPredecessor={buildId:closedBuild,imageDigest:priorDigest};f.previous=yardReleaseCompatibility(closedBuild);f.persistentYardRows=7;return f;}
test('image-owned command derives closed policy and proves quarantine without external state',()=>{const manifest=yardReleaseCompatibility(build);assert.equal(manifest.playerRolloutEnabled,false);assert.equal(manifest.closedQuarantineVerified,true);assert.equal(manifest.requiredClosedPredecessor,null);assert.deepEqual(manifest.requiredLegacyPredecessor,{buildId:KNOWN_LEGACY_YARD_BUILD,imageDigest:'sha256:729955b34481c629980e5a04606a88531d9ba1691e69312c9dcd366571e4380d'});assert.deepEqual(manifest.readableStorageFormats,['yard-persistent/v1']);assert.throws(()=>yardReleaseCompatibility('latest'));const source=fs.readFileSync(path.join(root,'scripts/yard-release-compatibility.mjs'),'utf8');assert.doesNotMatch(source,/DATABASE_URL|fetch\(|getDb\(|writeFile|process\.env\.(?:YARD|ROLLOUT)/);});
test('phase one permits an unaware rollback image only with exactly zero persistent markers',()=>{assert.deepEqual(verifyYardRollbackTarget(fixture()),{status:'ready',phase:'closed-compatible',persistentYardRows:0});for(const count of [1,100]){const f=fixture();f.persistentYardRows=count;assert.throws(()=>verifyYardRollbackTarget(f),/markers forbid/);}});
test('phase one rejects absent or arbitrary legacy bootstrap identities despite zero markers',()=>{for(const mutate of [f=>f.candidate.requiredLegacyPredecessor=null,f=>f.candidate.requiredLegacyPredecessor.buildId='8'.repeat(40),f=>f.candidate.requiredLegacyPredecessor.imageDigest='sha256:'+'8'.repeat(64),f=>f.previousBuildId='8'.repeat(40),f=>f.previousImage.RepoDigests=[],f=>f.previousImage.Config.Labels['org.opencontainers.image.revision']='8'.repeat(40)]){const f=fixture();mutate(f);assert.throws(()=>verifyYardRollbackTarget(f));}});
test('phase two requires the exact healthy closed and quarantine-proven predecessor',()=>{assert.deepEqual(verifyYardRollbackTarget(activation()),{status:'ready',phase:'activation',persistentYardRows:7});for(const mutate of [f=>f.previous=null,f=>f.previous.playerRolloutEnabled=true,f=>f.previous.closedQuarantineVerified=false,f=>f.candidate.requiredClosedPredecessor=null,f=>f.candidate.requiredClosedPredecessor.buildId='9'.repeat(40),f=>f.candidate.requiredClosedPredecessor.imageDigest='sha256:'+'9'.repeat(64),f=>f.previousHealth.status='degraded',f=>f.previousHealth.buildId='9'.repeat(40)]){const f=activation();mutate(f);assert.throws(()=>verifyYardRollbackTarget(f));}});
test('missing counts and mismatched immutable image/source identities fail closed',()=>{for(const mutate of [f=>f.persistentYardRows=-1,f=>f.persistentYardRows='0',f=>f.persistentYardRows=NaN,f=>f.persistentYardRows=Number.MAX_SAFE_INTEGER+1,f=>f.candidateImage.RepoDigests=[],f=>f.candidateImage.Config.Labels['org.opencontainers.image.revision']='9'.repeat(40),f=>f.previousImage.Id='sha256:'+'9'.repeat(64),f=>f.candidate.format='unknown',f=>f.candidate.closedQuarantineVerified=false,f=>f.repository='../../other']){const f=fixture();mutate(f);assert.throws(()=>verifyYardRollbackTarget(f));}});
test('deploy checks compatibility and pins rollback image strictly before any live switch',()=>{const deploy=fs.readFileSync(path.join(root,'.github/workflows/deploy.yml'),'utf8'),guard=deploy.indexOf('            bash scripts/yard-pre-switch-guard.sh'),stale=deploy.indexOf('            STALE_APP_CONTAINERS='),switchAt=deploy.indexOf('            RELEASE_SWITCH_STARTED=1');assert.ok(guard>deploy.indexOf('            compose -p ccgh pull app'));assert.ok(guard<stale&&stale<switchAt);assert.ok(deploy.indexOf('flock -n 9')<deploy.indexOf('            RELEASE_SWITCH_STARTED=0'));assert.match(deploy,/yard-rollback-\$\{PREVIOUS_BUILD_ID\}/);assert.match(deploy,/source: "docker-compose.yml,scripts\/yard-pre-switch-guard.sh"/);const shell=fs.readFileSync(path.join(root,'scripts/yard-pre-switch-guard.sh'),'utf8');assert.match(shell,/timeout --foreground --kill-after=5s 30s docker/);assert.equal((shell.match(/default_transaction_read_only=on -c statement_timeout=10000 -c lock_timeout=3000/g)||[]).length,2);assert.match(shell,/SELECT count\(\*\) FROM players WHERE data \? '_yardV2'/);assert.doesNotMatch(shell,/SELECT \* FROM|INSERT INTO|UPDATE players|DELETE FROM|pg_restore|compose.*up|DATABASE_URL|POSTGRES_PASSWORD/);});

const dockerStub=String.raw`#!/usr/bin/env node
const fs=require('node:fs'),cp=require('node:child_process'),p=process.env.TEST_FIXTURES,f=JSON.parse(fs.readFileSync(p+'/input.json','utf8')),a=process.argv.slice(2);fs.appendFileSync(p+'/calls.jsonl',JSON.stringify(a)+'\n');
const out=x=>process.stdout.write(JSON.stringify(x)+'\n');
if(a[0]==='image'&&a[1]==='inspect'){out(a[2]===f.previousImageId?f.previousImage:f.candidateImage);}
else if(a[0]==='run'&&a.includes('scripts/yard-release-compatibility.mjs'))out(f.candidate);
else if(a[0]==='run'&&a.includes('sh')){if(f.probeFailure)process.exit(125);if(!a.includes(f.previousImageId)||a.includes('--mount')||!a.includes('none'))process.exit(91);if(f.previous===null)process.exit(42);out(f.previous);}
else if(a[0]==='run'&&a.includes('scripts/verify-yard-rollback-target.mjs')){const mount=a[a.indexOf('--mount')+1],dir=mount.match(/src=([^,]+)/)[1],r=cp.spawnSync(process.execPath,[process.env.TEST_VERIFY_SCRIPT,dir],{encoding:'utf8'});process.stdout.write(r.stdout);process.stderr.write(r.stderr);process.exit(r.status??1);}
else if(a[0]==='exec'&&a.includes('ccgh-postgres')){if(!a.includes('PGOPTIONS=-c default_transaction_read_only=on -c statement_timeout=10000 -c lock_timeout=3000'))process.exit(89);if(f.queryFailure)process.exit(7);if(a[a.indexOf('-c')+1]!=="SELECT count(*) FROM players WHERE data ? '_yardV2';")process.exit(8);const countFile=p+'/count-calls',calls=fs.existsSync(countFile)?Number(fs.readFileSync(countFile,'utf8'))+1:1;fs.writeFileSync(countFile,String(calls));process.stdout.write(String(f.lateMarker&&calls>1?1:f.persistentYardRows)+'\n');}
else if(a[0]==='inspect')process.stdout.write((f.lateImageChange?'sha256:'+'0'.repeat(64):f.previousImageId)+'\n');
else process.exit(9);
`;
const timeoutStub=String.raw`#!/usr/bin/env node
const fs=require('node:fs'),cp=require('node:child_process'),f=JSON.parse(fs.readFileSync(process.env.TEST_FIXTURES+'/input.json','utf8')),a=process.argv.slice(2);if(a.slice(0,3).join(' ')!=='--foreground --kill-after=5s 30s')process.exit(88);if(f.clientTimeout)process.exit(124);const r=cp.spawnSync(a[3],a.slice(4),{stdio:'inherit'});process.exit(r.status??1);
`;
const curlStub=String.raw`#!/usr/bin/env node
const fs=require('node:fs'),f=JSON.parse(fs.readFileSync(process.env.TEST_FIXTURES+'/input.json','utf8'));process.stdout.write(JSON.stringify(f.previousHealth)+'\n');
`;
for(const [name,make,code]of [
 ['closed-zero',fixture,0],['closed-existing-marker',()=>({...fixture(),persistentYardRows:1}),1],['activation-exact',activation,0],
 ['activation-direct-from-legacy',()=>({...activation(),previous:null,persistentYardRows:0}),1],
 ['query-failure',()=>({...fixture(),queryFailure:true}),7],['probe-failure',()=>({...fixture(),probeFailure:true}),125],['docker-client-timeout',()=>({...fixture(),clientTimeout:true}),124],['marker-on-recheck',()=>({...fixture(),lateMarker:true}),1],['late-image-replacement',()=>({...fixture(),lateImageChange:true}),1]
])test(`actual pre-switch shell is bounded and fail-closed: ${name}`,()=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'yard-rollback-shell-test-')),bin=path.join(directory,'bin');
 try{const input=make();fs.mkdirSync(bin);fs.writeFileSync(path.join(directory,'input.json'),JSON.stringify(input));fs.writeFileSync(path.join(bin,'docker'),dockerStub,{mode:0o700});fs.writeFileSync(path.join(bin,'timeout'),timeoutStub,{mode:0o700});fs.writeFileSync(path.join(bin,'curl'),curlStub,{mode:0o700});const result=spawnSync('bash',[path.join(root,'scripts/yard-pre-switch-guard.sh'),`ghcr.io/${repo}@${digest}`,build,previousId,input.previousBuildId,'18080','fixture-user','fixture-db',repo],{env:{...process.env,PATH:bin+path.delimiter+process.env.PATH,TMPDIR:directory,TEST_FIXTURES:directory,TEST_VERIFY_SCRIPT:path.join(root,'scripts/verify-yard-rollback-target.mjs')},encoding:'utf8',timeout:15000});assert.ifError(result.error);assert.equal(result.status,code,result.stdout+result.stderr);if(code===0){assert.match(result.stdout,/"status":"ready"/);assert.doesNotMatch(result.stdout,/player|username|password|receipt/);}assert.equal(fs.readdirSync(directory).some(s=>s.startsWith('yard-release-preflight.')),false);const calls=fs.existsSync(path.join(directory,'calls.jsonl'))?fs.readFileSync(path.join(directory,'calls.jsonl'),'utf8'):'';assert.doesNotMatch(calls,/"up"|"stop"|"rm"|"tag"|"pg_restore"/);}
 finally{fs.rmSync(directory,{recursive:true,force:true});}
});

test('SCP stages by exact build/run and cannot replace effective deployment files before locking',()=>{
 const deploy=fs.readFileSync(path.join(root,'.github/workflows/deploy.yml'),'utf8');
 assert.match(deploy,/target: "\/opt\/game-hub\/releases\/\$\{\{ github.sha \}\}-\$\{\{ github.run_id \}\}-\$\{\{ github.run_attempt \}\}"/);
 const lock=deploy.indexOf('            flock -n 9'),compose=deploy.indexOf('            install -m 0644 "$RELEASE_STAGING_PATH/docker-compose.yml"'),helper=deploy.indexOf('            install -m 0700 "$RELEASE_STAGING_PATH/scripts/yard-pre-switch-guard.sh"');
 assert.ok(lock>0&&compose>lock&&helper>lock);assert.doesNotMatch(deploy,/target: "\/opt\/game-hub"/);
});
