import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {assertDevelopmentEnvironment,assertImageInputs,assertCurrentCapabilities,fixture,CAPS,CHECKS,requiredCheckClaims,assertTap,RELEASE_SMOKE_NAMES,createLedger,step,PREDECESSOR,BRANCH,projectedTargetMatches,assertStoredPlacement,assertNativeFoodPresentation} from './helpers/yard-development-acceptance.mjs';
import {releasedYardSnapshot,initializeReleasedPlayerYard} from '../game-logic/yard-v2/player-release.mjs';
const env={YARD_DEVELOPMENT_IMAGE_ACCEPTANCE:'1',CI:'true',GITHUB_ACTIONS:'true',GITHUB_RUN_ATTEMPT:'1',GITHUB_REF:'refs/heads/'+BRANCH,GITHUB_REPOSITORY:'le-who/cc-gh',GITHUB_SHA:'a'.repeat(40)};
test('only exact first branch attempt in real CI is admitted; inherited runtime authority fails closed',()=>{assert.equal(assertDevelopmentEnvironment(env),'a'.repeat(40));for(const patch of [{CI:'false'},{DOCKER_HOST:'tcp://external:2375'},{DOCKER_CONTEXT:'remote'},{GITHUB_RUN_ATTEMPT:'2'},{GITHUB_REF:'refs/heads/main'},{GITHUB_REF:'refs/heads/qa/yard-development-image-20261006'},{GITHUB_REPOSITORY:'fork/cc-gh'},{NODE_OPTIONS:'--import=loader'},{DATABASE_URL:'postgres://production'},{DEV_AUTH_ENABLED:'true'},{YARD_CANONICAL_API_TEST:'1'}])assert.throws(()=>assertDevelopmentEnvironment({...env,...patch}));});
test('published image input requires real immutable digest and reviewed predecessor',()=>{const id={commit:PREDECESSOR,tree:'b'.repeat(40),imageDigest:'sha256:'+'c'.repeat(64),imageId:'sha256:'+'d'.repeat(64)},v={repository:'ghcr.io/le-who/cc-gh',predecessor:id,candidate:{...id,commit:'a'.repeat(40)}};assert.equal(assertImageInputs(v),v);assert.throws(()=>assertImageInputs({...v,repository:'ghcr.io/new/package'}));assert.throws(()=>assertImageInputs({...v,candidate:{...v.candidate,imageDigest:'latest'}}));});
test('plain fixture uses normal source policy and saved overlap is explicit current format',()=>{const plain=fixture();assert.equal(plain.initial._yardV2,undefined);assert.equal(initializeReleasedPlayerYard(plain.initial).status,200);assertCurrentCapabilities(releasedYardSnapshot(plain.initial));const occupied=fixture({occupied:true,ownedPots:1});assert.equal(occupied.initial._yardV2.version,2);assert.equal(occupied.initial._yardV2.runtime.canonicalPlacements[0].x,80);assert.equal(occupied.initial.yard.goodieInventory.leaf_pot||0,0);const view=releasedYardSnapshot(plain.initial);view.yardRuntime.foodLocationCapabilities.enabled=false;assert.throws(()=>assertCurrentCapabilities(view));});
const cases=()=>{const api={status:'passed',cases:[{name:'api-and-warm',status:'passed',checks:['authenticated-capability-policy','warm-client-update']}]},native={status:'passed',cases:[...['320x568','390x844','568x320'].map(x=>({name:'occupied-'+x,status:'passed',checks:['occupied-food-socket','mobile-functional']})),{name:'current-v2-pending',status:'passed',checks:['canonical-placement-storage-v2','economy-inventory','lost-response-exactly-once','pending-intent-account-fences','receipt-security','prior-image-v2-quarantine-preserves-bytes']}],captures:["occupied-320x568-food.png", "occupied-320x568-decor.png", "occupied-320x568-escaped.png", "occupied-390x844-food.png", "occupied-390x844-decor.png", "occupied-390x844-escaped.png", "occupied-568x320-food.png", "occupied-568x320-decor.png", "occupied-568x320-escaped.png", "current-v2-recovered-390x844.png"]};return {api,native};};
test('every claimed check comes from its actual successful case and visual remains pending',()=>{const{api,native}=cases(),checks=requiredCheckClaims(api,native);assert.deepEqual(checks.map(c=>c.name),CHECKS);assert.equal(checks.find(c=>c.name==='mobile-visual').status,'review-required');assertTap('# tests 5\n# pass 5\n# fail 0\n# cancelled 0\n# skipped 0\n'+RELEASE_SMOKE_NAMES.map(n=>'# Subtest: '+n).join('\n'),5,RELEASE_SMOKE_NAMES);assert.throws(()=>assertTap('# tests 5\n# pass 5\n# fail 0',5,RELEASE_SMOKE_NAMES));for(const name of ['receipt-security','prior-image-v2-quarantine-preserves-bytes'])assert.deepEqual(checks.find(c=>c.name===name).evidence,['native-proof.json']);native.cases[0].status='failed';assert.throws(()=>requiredCheckClaims(api,native));});
test('missing viewport, lost check membership and duplicated captures cannot pass aggregate',()=>{for(const edit of [v=>v.native.cases.pop(),v=>v.native.cases[3].checks.pop(),v=>v.native.captures[9]=v.native.captures[0],v=>v.api.cases[0].checks=[]]){const v=cases();edit(v);assert.throws(()=>requiredCheckClaims(v.api,v.native));}});
test('failed action is written before throwing and prior diagnostics cannot be erased',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'yard-development-ledger-'));try{const file=path.join(root,'ledger.json'),ledger=createLedger(file,{commit:'a'.repeat(40)});await assert.rejects(step(null,ledger,'disabled commit',async()=>{throw Error('disabled');}),/disabled/);const report=JSON.parse(await fs.readFile(file));assert.deepEqual(report.events.map(e=>e.phase),['started','failed']);assert.match(report.events[1].error,/disabled/);await assert.rejects(ledger.record({text:'x'.repeat(CAPS.checkpointBytes)}),/cap/);assert.equal(JSON.parse(await fs.readFile(file)).events.length,2);}finally{await fs.rm(root,{recursive:true});}});
test('selectors match source semantics and every mutation helper has a finite response wait',async()=>{const s=await fs.readFile(new URL('./yard-development-e2e/development.spec.mjs',import.meta.url),'utf8'),hud=await fs.readFile(new URL('../src/app/hud-layout/HudRegion.jsx',import.meta.url),'utf8').catch(()=>''),component=await fs.readFile(new URL('../src/games/companion-yard-v2/CourtyardGame.jsx',import.meta.url),'utf8');assert(!s.includes('#yardVisitStatus'));assert(s.includes('[data-hud-region="yardVisitStatus"][role="status"]'));assert(component.includes('id="yardVisitStatus"'));assert(hud.includes('data-hud-region')||hud.includes('regionProps'));for(const marker of ['data-nav-item={id}','data-decor-tab={id}','data-yard-action="commit-placement"','data-yard-action="pickup"','data-pip-control="canonical-items"'])assert(component.includes(marker));assert(s.includes('timeout:CAPS.replyMs'));assert(s.includes('Commit precondition: actual scene ghost must be valid'));});

// Regression inputs are the observed failure shapes from run37552764801.
// Renderer absence is the real owner's documented null-binding representation;
// these pure checks do not claim new browser or GPU observations.
test('recorded occupied null-state excludes visible food but available food requires a bounded ledger',()=>{
 const occupied={available:false,state:null,reason:'CANONICAL_FOOD_SOCKET_OCCUPIED',occupiedSlotIds:['canonical:owned-overlap']},scene={peakRgba:1,knownCPUBufferPeak:1,canonicalFood:{...occupied,reserved:true,render:structuredClone(occupied),loading:false,reentryRequired:false},renderer:{canonicalFood:{enabled:true,pending:0,selection:structuredClone(occupied),binding:null,ledger:null}}};
 assert.equal(assertNativeFoodPresentation(scene).ledgerPresent,false);
 for(const change of [s=>s.canonicalFood.state='occupied',s=>s.canonicalFood.reason='CANONICAL_FOOD_UNAVAILABLE',s=>s.renderer.canonicalFood.binding={visible:true},s=>s.canonicalFood.occupiedSlotIds=[],s=>delete s.renderer.canonicalFood]){const invalid=structuredClone(scene);change(invalid);assert.throws(()=>assertNativeFoodPresentation(invalid));}
 for(const state of ['empty','kibble','berry_plate','bonito_bowl']){const selected={available:true,state},available=structuredClone(scene);available.canonicalFood={...selected,reserved:true,render:{...selected},loading:false,reentryRequired:false};available.renderer.canonicalFood={enabled:true,pending:0,selection:{...selected},binding:{visible:true,state},ledger:null};assert.throws(()=>assertNativeFoodPresentation(available),/requires its resource ledger/);available.renderer.canonicalFood.ledger={limits:{rgba:67108864,knownCPU:16777216,estimatedGPU:12582912},total:{rgba:1,knownCPU:1,estimatedGPU:1},peak:{rgba:1,knownCPU:1,estimatedGPU:1}};assert.equal(assertNativeFoodPresentation(available).state,state);available.renderer.canonicalFood.ledger.peak.estimatedGPU=12582913;assert.throws(()=>assertNativeFoodPresentation(available));}
});
test('recorded projected coordinates allow target rounding while stored command and later identity remain exact',()=>{
 const payload={slotId:'canonical:recorded',goodieId:'leaf_pot',x:98.00000137390423,y:117.99999688719761,locationId:'pip-garden',locationVersion:1,geometryRevision:'pip-garden-t2-food-r2'},command={action:'yard.placeGoodie',payload},row={...payload,geometryRevision:'pip-garden-t2-r1',itemGeometryRevision:'yard-succulent-T2'};
 assert(projectedTargetMatches(payload,{x:98,y:118}));assertStoredPlacement(row,command,{x:98,y:118});assertStoredPlacement(row,{action:'yard.moveGoodie',payload:Object.fromEntries(Object.entries(payload).filter(([k])=>k!=='goodieId'))},{x:98,y:118});
 assert(!projectedTargetMatches({...payload,x:98.001},{x:98,y:118}));assert(!projectedTargetMatches({...payload,x:NaN},{x:98,y:118}));assert.throws(()=>assertStoredPlacement({...row,x:98},command,{x:98,y:118}),/differs/);assert.throws(()=>assertStoredPlacement(row,{...command,payload:{...payload,y:118}},{x:98,y:118}),/differs/);assert.throws(()=>assertStoredPlacement({...row,slotId:'canonical:another'},command,{x:98,y:118}),/differs/);
});
