import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {execFileSync} from 'node:child_process';
import {RECORD_PATH,CHECKS,sha256,parseMaintenanceRecord,verifyMaintenanceTree,inspectMaintenanceSource,verifyMaintenanceRollback,assertMaintenanceChecks} from '../scripts/yard-active-maintenance.mjs';
const c=n=>n.repeat(40),d=n=>'sha256:'+n.repeat(64),s=n=>n.repeat(64);
const object=(text,mode='100644')=>({mode,type:'blob',objectId:createHash('sha1').update(`blob ${Buffer.byteLength(text)}\0`).update(text).digest('hex')});
function record(){return {format:'cc-gh-yard-active-maintenance/v1',repository:'le-who/cc-gh',anchor:{commit:c('a'),tree:c('b'),imageDigest:d('c'),contractSha256:s('d'),closedBuildId:c('e'),closedImageDigest:d('f')},predecessor:{commit:c('a'),tree:c('b'),imageDigest:d('c'),imageId:d('1'),compatibilitySha256:s('2'),acceptanceReceiptSha256:s('3')},storage:{format:'yard-persistent/v1',mode:'same-format-no-migration'},affectedGames:['settlement'],changes:[{path:'src/settlement.js',before:object('old'),after:object('new')}]};}
const seal=r=>{const recordBytes=JSON.stringify(r,null,2)+'\n';return {recordBytes,approvedRecordSha256:sha256(recordBytes)};};
function source(){const r=record(),sealed=seal(r);return {...sealed,before:new Map([[r.changes[0].path,r.changes[0].before],['unchanged.js',object('keep')]]),after:new Map([[r.changes[0].path,r.changes[0].after],['unchanged.js',object('keep')],[RECORD_PATH,object(sealed.recordBytes)]]),facts:{clean:true,candidateCommit:c('4'),candidateTree:c('5'),predecessorCommit:r.predecessor.commit,predecessorTree:r.predecessor.tree,anchorCommit:r.anchor.commit,anchorTree:r.anchor.tree,predecessorIsAncestor:true,anchorIsAncestor:true}};}
function image(id,commit,digest){return {Id:id,RepoDigests:[`ghcr.io/le-who/cc-gh@${digest}`],Config:{Cmd:['node','server.js'],Env:['NODE_ENV=production',`APP_BUILD_ID=${commit}`],Labels:{'org.opencontainers.image.revision':commit}}};}
function rollback(later=false){
 const r=record();if(later){r.predecessor.commit=c('6');r.predecessor.tree=c('7');r.predecessor.imageDigest=d('8');}
 const p=r.predecessor,previous={format:later?'cc-gh-yard-release-compatibility/v2':'cc-gh-yard-release-compatibility/v1',buildId:p.commit,playerRolloutEnabled:true,readableStorageFormats:['yard-persistent/v1'],...(later?{initialActivation:r.anchor,writableStorageFormats:['yard-persistent/v1'],storageMigration:'none'}:{requiredClosedPredecessor:{buildId:r.anchor.closedBuildId,imageDigest:r.anchor.closedImageDigest}})};
 const previousCompatibilityBytes=JSON.stringify(previous);p.compatibilitySha256=sha256(previousCompatibilityBytes);
 const proof={runId:123,runAttempt:1,status:'completed',conclusion:'success',headCommit:p.commit,artifactSha256:s('9')};
 const receipt={format:'cc-gh-yard-accepted-active/v1',repository:'le-who/cc-gh',repositoryId:1162268629,status:'accepted',release:{commit:p.commit,tree:p.tree,imageDigest:p.imageDigest,imageId:p.imageId},initialActivation:r.anchor,acceptance:proof,deployment:{...proof,runId:124}};
 const acceptedPredecessorReceiptBytes=JSON.stringify(receipt);p.acceptanceReceiptSha256=sha256(acceptedPredecessorReceiptBytes);
 const sealed=seal(r),candidateBuildId=c('4'),candidateDigest=d('5');
 return {...sealed,candidateBuildId,candidateDigest,candidateImage:image(d('6'),candidateBuildId,candidateDigest),candidate:{format:'cc-gh-yard-release-compatibility/v2',buildId:candidateBuildId,playerRolloutEnabled:true,readableStorageFormats:['yard-persistent/v1'],writableStorageFormats:['yard-persistent/v1'],storageMigration:'none',initialActivation:r.anchor,requiredActivePredecessor:{buildId:p.commit,imageDigest:p.imageDigest},maintenanceRecordSha256:sealed.approvedRecordSha256},previousImage:image(p.imageId,p.commit,p.imageDigest),previous,previousHealth:{status:'ok',buildId:p.commit,postgres:true},previousCompatibilityBytes,acceptedPredecessorReceiptBytes,persistentYardRows:11};
}
function checks(){const r=record(),sealed=seal(r),candidateCommit=c('4'),candidateTree=c('5'),candidateDigest=d('6');return {...sealed,candidateCommit,candidateTree,candidateDigest,checks:[...CHECKS,'game:settlement'].map(name=>({name,status:'completed',conclusion:'success',candidateCommit,candidateTree,candidateDigest,predecessorCommit:r.predecessor.commit,predecessorDigest:r.predecessor.imageDigest,recordSha256:sealed.approvedRecordSha256,attempts:1}))};}

test('exact independently approved record and full-tree source change succeed',()=>{assert.equal(verifyMaintenanceTree(source()).status,'source-verified');});
test('candidate cannot choose or recompute its own approved hash',()=>{const f=source();assert.throws(()=>verifyMaintenanceTree({...f,approvedRecordSha256:undefined}));assert.throws(()=>verifyMaintenanceTree({...f,recordBytes:f.recordBytes+' '}));const r=JSON.parse(f.recordBytes);r.changes[0].path='routes/player.js';assert.throws(()=>parseMaintenanceRecord(JSON.stringify(r),f.approvedRecordSha256));});
test('unrelated edits, additions, deletions and modes fail the complete tree comparison',()=>{for(const change of [f=>f.after.set('unreviewed.js',object('extra')),f=>f.after.delete('unchanged.js'),f=>f.after.set('unchanged.js',object('drift')),f=>f.after.set('src/settlement.js',object('new','100755')),f=>f.after.set('src/settlement.js',{mode:'120000',type:'blob',objectId:c('1')}),f=>f.after.set(RECORD_PATH,object('other'))]){const f=source();change(f);assert.throws(()=>verifyMaintenanceTree(f));}});
test('reviewed additions and removals require their exact absence/presence',()=>{for(const remove of [true,false]){const f=source(),r=JSON.parse(f.recordBytes);r.changes[0][remove?'after':'before']=null;Object.assign(f,seal(r));f.after.set(RECORD_PATH,object(f.recordBytes));(remove?f.after:f.before).delete('src/settlement.js');assert.equal(verifyMaintenanceTree(f).changedFiles,1);}});
test('dirty checkout, replaced tree, wrong parent and missing ancestry fail',()=>{for(const [key,value]of [['clean',false],['candidateCommit',c('a')],['candidateCommit','main'],['predecessorTree',c('9')],['anchorTree',c('9')],['predecessorCommit',c('9')],['anchorCommit',c('9')],['predecessorIsAncestor',false],['anchorIsAncestor',false]]){const f=source();f.facts[key]=value;assert.throws(()=>verifyMaintenanceTree(f),key);}});
test('anchor, storage, release controls and historical evidence cannot enter compatible maintenance',()=>{for(const path of ['.github/workflows/ci.yml','game-logic/yard-v2/release-policy.mjs','game-logic/yard-v2/active-release-contract.json','preview/yard-persistent-candidate/history/proof.json','recovery-tools/source.json','public/assets/yard-mochi/runtime-media.json','scripts/yard-ci-dispatch.mjs','scripts/yard-active-maintenance.mjs','tests/yard-production-contract.test.mjs','migrations/12.sql','package.json','pnpm-lock.yaml','Dockerfile','db.js',RECORD_PATH]){const r=record();r.changes[0].path=path;const f=seal(r);assert.throws(()=>parseMaintenanceRecord(f.recordBytes,f.approvedRecordSha256),path);}});
test('malformed inventories, storage declarations and path traversal fail even with approved bytes',()=>{for(const mutate of [r=>r.extra=true,r=>r.changes=[],r=>r.changes='paths',r=>r.changes.push({...r.changes[0]}),r=>r.changes[0].path='../file',r=>r.changes[0].path='/tmp/file',r=>r.changes[0].path='src//file',r=>r.changes[0].path='src/file\nother',r=>r.changes[0].after.type='commit',r=>r.changes[0].after.mode='120000',r=>r.changes[0].after.mode='100755',r=>r.affectedGames=[],r=>r.affectedGames=['settlement','settlement'],r=>r.storage.format='yard-persistent/v2',r=>r.storage.mode='migrate',r=>r.predecessor.commit=r.anchor.closedBuildId]){const r=record();mutate(r);const f=seal(r);assert.throws(()=>parseMaintenanceRecord(f.recordBytes,f.approvedRecordSha256));}});
test('first accepted ACTIVE predecessor bridges its v1 image declaration',()=>{const f=rollback();assert.equal(verifyMaintenanceRollback(f).phase,'active-maintenance');});
test('later accepted ACTIVE predecessor retains the same immutable activation anchor',()=>{assert.equal(verifyMaintenanceRollback(rollback(true)).status,'rollback-compatible');});
test('wrong or stale live image, source, health and storage capabilities block rollback readiness',()=>{for(const mutate of [f=>f.previousImage.Id=d('0'),f=>f.previousImage.RepoDigests=[],f=>f.previousImage.RepoDigests='not-an-array',f=>f.previousImage.Config.Labels['org.opencontainers.image.revision']=c('0'),f=>f.previousHealth.status='degraded',f=>f.previousHealth.buildId=c('0'),f=>f.previousHealth.postgres=false,f=>f.candidateImage.RepoDigests=[],f=>f.candidate.buildId=c('0'),f=>f.candidate.playerRolloutEnabled=false,f=>f.candidate.readableStorageFormats='yard-persistent/v1',f=>f.candidate.writableStorageFormats=['yard-persistent/v2'],f=>f.candidate.storageMigration='automatic',f=>f.candidate.requiredActivePredecessor.buildId=c('0'),f=>f.candidate.maintenanceRecordSha256=s('0'),f=>f.candidate.initialActivation={...f.candidate.initialActivation,commit:c('0')},f=>f.previousCompatibilityBytes+=' ',f=>f.acceptedPredecessorReceiptBytes+=' ',f=>f.persistentYardRows=-1,f=>f.persistentYardRows='11']){const f=rollback();mutate(f);assert.throws(()=>verifyMaintenanceRollback(f));}});
test('CLOSED or unaccepted prior image cannot be upgraded into maintenance by changing the record',()=>{for(const mutate of [f=>f.previous.playerRolloutEnabled=false,f=>f.previous.requiredClosedPredecessor.buildId=c('0'),f=>f.previous.readableStorageFormats=['yard-persistent/v2']]){const f=rollback();mutate(f);const r=JSON.parse(f.recordBytes);f.previousCompatibilityBytes=JSON.stringify(f.previous);r.predecessor.compatibilitySha256=sha256(f.previousCompatibilityBytes);Object.assign(f,seal(r));f.candidate.maintenanceRecordSha256=f.approvedRecordSha256;assert.throws(()=>verifyMaintenanceRollback(f));}});
test('an accepted record still cannot excuse missing, failed or wrong-source receipt evidence',()=>{for(const mutate of [r=>r.status='pending',r=>r.repositoryId=1,r=>r.release.imageDigest=d('0'),r=>r.deployment.conclusion='failure',r=>r.acceptance.headCommit=c('0'),r=>r.acceptance.runAttempt=0]){const f=rollback(),receipt=JSON.parse(f.acceptedPredecessorReceiptBytes);mutate(receipt);f.acceptedPredecessorReceiptBytes=JSON.stringify(receipt);const r=JSON.parse(f.recordBytes);r.predecessor.acceptanceReceiptSha256=sha256(f.acceptedPredecessorReceiptBytes);Object.assign(f,seal(r));f.candidate.maintenanceRecordSha256=f.approvedRecordSha256;assert.throws(()=>verifyMaintenanceRollback(f));}});
test('all changed-game, cross-game, durable rollback and service-worker checks are mandatory',()=>{const f=checks();assert.equal(assertMaintenanceChecks(f).checks,8);for(let index=0;index<f.checks.length;index++){for(const conclusion of ['failure','cancelled','skipped','neutral','timed_out']){const bad=structuredClone(f);bad.checks[index].conclusion=conclusion;assert.throws(()=>assertMaintenanceChecks(bad));}const bad=structuredClone(f);bad.checks.splice(index,1);assert.throws(()=>assertMaintenanceChecks(bad));}});
test('successful checks from another tree, image, predecessor, record or retried attempt fail',()=>{for(const [key,value]of [['candidateCommit',c('0')],['candidateTree',c('0')],['candidateDigest',d('0')],['predecessorCommit',c('0')],['predecessorDigest',d('0')],['recordSha256',s('0')],['attempts',2],['status','in_progress']]){const f=checks();f.checks[0][key]=value;assert.throws(()=>assertMaintenanceChecks(f),key);}const f=checks();f.checks[0]=structuredClone(f.checks[1]);assert.throws(()=>assertMaintenanceChecks(f));});
test('actual tiny Git checkout verifies two successive releases without replaying their history',()=>{
 const root=mkdtempSync(join(tmpdir(),'yard-maintenance-git-'));
 const git=(...args)=>execFileSync('git',['-c','core.hooksPath=/dev/null','-c','user.name=Maintenance test','-c','user.email=test@example.invalid','-c','commit.gpgsign=false',...args],{cwd:root,encoding:'utf8',timeout:10000}).trim();
 const write=(path,text)=>{mkdirSync(dirname(join(root,path)),{recursive:true});writeFileSync(join(root,path),text);};
 try{git('init','-q');const r=record(),contract={format:'yard-active-contract/v1',mode:'ACTIVE',inputs:{closed:{buildId:r.anchor.closedBuildId,imageDigest:r.anchor.closedImageDigest}}};write('game-logic/yard-v2/active-release-contract.json',JSON.stringify(contract));write('src/settlement.js','old');git('add','.');git('commit','-qm','Accepted activation fixture');r.anchor.commit=r.predecessor.commit=git('rev-parse','HEAD');r.anchor.tree=r.predecessor.tree=git('rev-parse','HEAD^{tree}');r.anchor.contractSha256=sha256(JSON.stringify(contract));const sealed=seal(r);write(RECORD_PATH,sealed.recordBytes);write('src/settlement.js','new');git('add','.');git('commit','-qm','Scoped maintenance fixture');assert.equal(inspectMaintenanceSource(root,sealed.approvedRecordSha256).status,'source-verified');write('extra.txt','unreviewed');assert.throws(()=>inspectMaintenanceSource(root,sealed.approvedRecordSha256),/clean/);rmSync(join(root,'extra.txt'));
  const first=git('rev-parse','HEAD');r.predecessor.commit=first;r.predecessor.tree=git('rev-parse','HEAD^{tree}');r.changes[0]={path:'src/settlement.js',before:object('new'),after:object('next fix')};const next=seal(r);write(RECORD_PATH,next.recordBytes);write('src/settlement.js','next fix');git('add','.');git('commit','-qm','Second scoped maintenance fixture');const result=inspectMaintenanceSource(root,next.approvedRecordSha256);assert.equal(result.predecessorCommit,first);assert.equal(result.anchorCommit,r.anchor.commit);assert.equal(result.changedFiles,1);
 }
 finally{rmSync(root,{recursive:true,force:true});}
});
