import {yardReleasePresentation} from '../src/games/companion-yard-v2/release-presentation.mjs';
import {canonicalItemState,canonicalCapability} from '../src/game-state/canonicalYardItems.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import fixture from './fixtures/canonical-saved-public.json' with{type:'json'};
import {createCanonicalSavedVisitClient,selectCanonicalSavedVisit} from '../src/games/companion-yard-v2/pip-prototype/canonical-saved-visit-client.mjs';
import {PresentationClock} from '../src/games/companion-yard-v2/presentation-clock.mjs';
const snapshot=()=>structuredClone(fixture),plan=fixture.yardRuntime.canonicalVisits[0].plan;
function env(){let now=0,id=0,wakes=0;const timers=new Map(),clock=new PresentationClock(()=>now),client=createCanonicalSavedVisitClient({clock,onWake:()=>wakes++,setTimer:(fn,ms)=>{timers.set(++id,{fn,at:now+ms});return id;},clearTimer:id=>timers.delete(id)});return{client,clock,timers,get wakes(){return wakes;},advance(ms){now+=ms;for(const [id,t]of [...timers])if(t.at<=now){timers.delete(id);t.fn();}}};}
test('source-projected v3 plan and worn rows are selected without changing input',()=>{const s=snapshot(),before=JSON.stringify(s),v=selectCanonicalSavedVisit(s);assert(v.available);assert.equal(v.plan.visitId,plan.visitId);assert.equal(v.rows[0].uses,1);v.plan.leavesAt++;v.rows[0].uses++;assert.equal(JSON.stringify(s),before);});
test('pending, wrong versions, mixed visitors, extra actor, malformed plan and changed layout fail closed',()=>{
 for(const mutate of[s=>s.yardRuntime.status='reconciliation-pending',s=>s.yardRuntime.storageVersion=2,s=>s.yardRuntime.canonicalVisitProtocol='unknown',s=>s.yardRuntime.serverNow=NaN,s=>s.yardRuntime.canonicalVisits.push(s.yardRuntime.canonicalVisits[0]),s=>s.yardRuntime.visits=[{}],s=>s.yardRuntime.canonicalVisits[0].visitId='wrong',s=>s.yardRuntime.canonicalVisits[0].plan.source.unitsPerSource=12,s=>s.yardRuntime.canonicalVisits[0].plan.inspectionPlan=null,s=>s.yardRuntime.canonicalPlacements[0].x+=1]){const s=snapshot();mutate(s);const selected=selectCanonicalSavedVisit(s);assert.equal(selected.available,false);assert.equal(selected.plan,null);}
});
test('empty genuine projection renders no fixture actor and has no timer',()=>{const e=env(),s=snapshot();s.yardRuntime.canonicalVisits=[];e.client.update(s);e.client.setDrawingEnabled(true);const r=e.client.sample();e.client.afterDraw(r);assert.equal(r.phase,'empty');assert.equal(r.sample,null);assert.equal(e.timers.size,0);});
test('quiet state owns exactly one next-change wake, motion uses RAF, paused wake is cancelled',()=>{const e=env(),s=snapshot();s.yardRuntime.serverNow=plan.inspectionPlan.phases[3].startMs+1000;e.client.update(s);e.client.setDrawingEnabled(true);const quiet=e.client.sample();assert.equal(quiet.needsAnimationFrame,false);for(let i=0;i<50;i++)e.client.afterDraw(quiet);assert.equal(e.timers.size,1);const deadline=quiet.nextChangeAt;e.advance(deadline-e.clock.read()-1);assert.equal(e.wakes,0);e.advance(1);assert.equal(e.wakes,1);const move=e.client.sample();assert.equal(move.needsAnimationFrame,true);e.client.afterDraw(move);assert.equal(e.timers.size,0);e.client.afterDraw(quiet);e.client.setDrawingEnabled(false);assert.equal(e.timers.size,0);});
test('hidden time, stale snapshots and renderer replacement cannot extend departure',()=>{const e=env(),s=snapshot();e.client.update(s);e.client.setDrawingEnabled(false);e.advance(plan.leavesAt-s.yardRuntime.serverNow+500);assert.equal(e.client.sample().phase,'departed');e.client.update(s);assert.equal(e.client.sample().phase,'departed');e.client.dispose();const replacement=createCanonicalSavedVisitClient({clock:e.clock});replacement.update(s);assert.equal(replacement.sample().phase,'departed');replacement.dispose();});
test('pending synchronously drops old presentation; disposal cancels wake and stale callbacks',()=>{const e=env(),s=snapshot();s.yardRuntime.serverNow=plan.releaseAt;e.client.update(s);e.client.setDrawingEnabled(true);e.client.afterDraw(e.client.sample());const old=[...e.timers.values()][0].fn;s.yardRuntime.status='reconciliation-pending';e.client.update(s);assert.equal(e.client.sample().sample,null);assert.equal(e.timers.size,0);old();assert.equal(e.wakes,0);e.client.dispose();assert.equal(e.client.state.disposed,true);});

test('component presentation accepts explicit v3 wear without granting legacy item mutation',()=>{const s=snapshot();assert.equal(canonicalItemState(s).available,true);assert.equal(canonicalItemState(s).status,'read-only');assert.equal(canonicalCapability(s),null);delete s.yardRuntime.storageVersion;delete s.yardRuntime.canonicalVisitProtocol;assert.equal(canonicalItemState(s).available,false);});

test('future placement storage cannot fall back to the legacy unused-row view',()=>{const s=snapshot();s.yardRuntime.storageVersion=4;delete s.yardRuntime.canonicalVisitProtocol;s.yardRuntime.canonicalPlacements[0].uses=0;assert.equal(canonicalItemState(s).available,false);});

test('malformed visitor arrays cannot masquerade as genuine empty saved state',()=>{for(const mutate of [s=>s.yardRuntime.canonicalVisits=[null],s=>s.yardRuntime.canonicalVisits=[false],s=>s.yardRuntime.canonicalVisits=[0],s=>s.yardRuntime.visits={},s=>delete s.yardRuntime.visits]){const s=snapshot();mutate(s);assert.equal(selectCanonicalSavedVisit(s).available,false);}});

test('normal game router mounts read-only v3 only behind the explicit saved build gate',()=>{const s=snapshot();assert.equal(s.yardRuntime.mutable,false);assert.equal(yardReleasePresentation(s),'read-only');assert.equal(yardReleasePresentation(s,{canonicalSavedVisitsEnabled:true}),'persistent');s.yardRuntime.status='reconciliation-pending';assert.equal(yardReleasePresentation(s,{canonicalSavedVisitsEnabled:true}),'persistent');for(const mutate of [s=>s.yardRuntime.storageVersion=4,s=>s.yardRuntime.canonicalVisitProtocol='unknown',s=>s.yardRuntime.status='corrupt']){const x=snapshot();mutate(x);assert.equal(yardReleasePresentation(x,{canonicalSavedVisitsEnabled:true}),'read-only');}});

test('v3/future quarantine cannot be bypassed by contradictory mutable:true metadata',()=>{for(const mutate of [s=>s.yardRuntime.status='review-required',s=>s.yardRuntime.canonicalVisitProtocol='unknown',s=>{s.yardRuntime.storageVersion=4;delete s.yardRuntime.canonicalVisitProtocol;}]){const s=snapshot();s.yardRuntime.mutable=true;mutate(s);assert.equal(yardReleasePresentation(s,{canonicalSavedVisitsEnabled:true}),'read-only');}});
