import savedFixture from './fixtures/canonical-saved-public.json' with{type:'json'};
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createPipYardScene} from '../src/games/companion-yard-v2/pip-prototype/yard-pip-scene.mjs';
import {createOptionalPipRenderer} from '../src/games/companion-yard-v2/pip-prototype/prototype/optional-pip-renderer.mjs';
import {planCanonicalInspection} from '../src/games/companion-yard-v2/pip-prototype/dynamic-prop-planner.mjs';
import {createUiImageReserve} from '../src/games/companion-yard-v2/ui-image-reserve.mjs';
import {CANONICAL_LOCATION,canonicalItemCapabilities} from '../game-logic/yard-v2/canonical-locations.mjs';
import {canonicalCommandScope,checkCanonicalPlacement} from '../src/game-state/canonicalYardItems.mjs';
import {createSceneOwner} from '../src/games/companion-yard-v2/scene-owner.mjs';

import {canonicalFoodCapabilities} from '../game-logic/yard-v2/canonical-food-protocol.mjs';
const historicalSnapshot={player:{id:'owner'},serverTime:1000,yard:{goodieInventory:{leaf_pot:2},foodInventory:{kibble:3,berry_plate:2,bonito_bowl:1},placedGoodies:[],bowls:[{id:'bowl-1',foodId:null,servings:0}]},yardRuntime:{version:1,status:'ready',mutable:true,actionProtocol:'yard-v2:',serverNow:1000,itemPlacementCapabilities:canonicalItemCapabilities({canonicalItemPlacementEnabled:true,canonicalFoodLocationEnabled:true}),canonicalPlacements:[],foodLocationCapabilities:canonicalFoodCapabilities({canonicalFoodLocationEnabled:true})}};
// Real Three objects, loaders, pose application, renderer traversal and type
// contracts. GL commands are no-ops: this does NOT test shaders or GPU pixels.
function contextStub(canvas){
 const names=new Map();let constant=1;
 return new Proxy({canvas,drawingBufferColorSpace:'srgb',getContextAttributes:()=>({alpha:true}),getExtension:name=>name==='WEBGL_lose_context'?{loseContext(){},restoreContext(){}}:null,getShaderPrecisionFormat:()=>({rangeMin:127,rangeMax:127,precision:23}),getSupportedExtensions:()=>[],
  getParameter:key=>{const name=names.get(key);return name==='VERSION'?'WebGL 2.0':name==='VIEWPORT'||name==='SCISSOR_BOX'?[0,0,390,648]:16;},getProgramParameter:(_p,key)=>names.get(key)==='LINK_STATUS',getShaderParameter:()=>true,getProgramInfoLog:()=>'',getShaderInfoLog:()=>''},
 {get(target,key){if(key in target)return target[key];if(key==='drawingBufferWidth')return canvas.width;if(key==='drawingBufferHeight')return canvas.height;
  if(/^[A-Z_0-9]+$/.test(key)){const value=constant++;names.set(value,key);return target[key]=value;}
  return target[key]=key.startsWith('create')?()=>({}):()=>{};}});
}
function environment({nativeRenderer=false,owned=false,failGhost=false,startupClockGap=0,foodPreview=true,groundingRecipe='baseline',delayFood=null,failFood=false,savedGate=false,failSaved=false}={}){
 const win=new EventTarget(),doc=new EventTarget();doc.hidden=false;doc.hasFocus=()=>true;
 globalThis.window=win;globalThis.document=doc;globalThis.devicePixelRatio=2;
 let observer,width=378,height=622,next=0,at=0,failureCount=0,clockStarted=false,interruptions=0;const frames=new Map(),timers=new Map(),failures=[],renders=[],notices=[],foodRequests=[],renderCanvases=[],restarts=[],views=[];
 globalThis.ResizeObserver=class{constructor(fn){observer=fn;}observe(){}disconnect(){}};
 const ctx={setTransform(a,b,c,d,e,f){this.transform={a,b,c,d,e,f};},getTransform(){return this.transform;},clearRect(){},fillRect(){},drawImage(){}};
 const rect=()=>({left:6,top:60,width,height}),canvas={style:{},width:0,height:0,getContext:()=>ctx,getBoundingClientRect:rect};
 const host={style:{},appendChild(c){c.parentNode=this;},getBoundingClientRect:rect};
 const fetchImpl=async (url,{signal}={})=>{if(String(url).includes('food-r2')){foodRequests.push({url:String(url),signal});if(delayFood)await delayFood;if(failFood)return{ok:false,status:500};}const relative=String(url).split('/src/')[1];const b=await fs.readFile(url).catch(error=>{if(!process.env.YARD_QA_ASSET_ROOT)throw error;return fs.readFile(process.env.YARD_QA_ASSET_ROOT+'/src/'+relative);});return{ok:true,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),json:async()=>JSON.parse(b),text:async()=>b.toString()};};
 const options={onView:value=>views.push(value),canonicalFoodPreview:foodPreview,groundingRecipe,onRestartRequired:()=>restarts.push(true),canonicalItems:true,canonicalSavedVisits:true,setTimer:(fn,ms)=>{timers.set(++next,{fn,at:at+ms});return next;},clearTimer:id=>timers.delete(id),directHost:host,uiImageOwner:createUiImageReserve(),onPointerInterrupt:()=>{interruptions++;scene.endPointer();scene.setGhost(null);},onFailure:(error,context)=>failures.push({message:error.message,stack:error.stack,context}),fetchImpl,decodeImage:async()=>({width:973,height:1616,close(){}}),now:()=>{const current=at;if(!clockStarted){clockStarted=true;at+=startupClockGap;}return current;},requestFrame:fn=>{frames.set(++next,fn);return next;},cancelFrame:id=>frames.delete(id),
  plannerWorkerFactory:()=>{throw Error('Manual planner must never own a saved visitor');},
  rendererFactory:args=>createOptionalPipRenderer({...args,canvasFactory:()=>{const c=new EventTarget();renderCanvases.push(c);c.style={};c.dataset={};c.remove=()=>{c.parentNode=null;};return c;},
   rendererFactory:({THREE,canvas})=>{const renderer=nativeRenderer?new THREE.WebGLRenderer({canvas,context:contextStub(canvas)}):({shadowMap:{},setClearColor(){},setPixelRatio(){},setSize(w,h){canvas.width=w;canvas.height=h;},dispose(){},forceContextLoss(){},render(world,camera){if(failSaved)throw Error('Injected saved renderer failure');world.updateMatrixWorld(true);renders.push({children:world.children.map(o=>({name:o.name,visible:o.visible})),camera:camera.matrixWorld.toArray()});}});
    const render=renderer.render.bind(renderer);renderer.render=(world,camera)=>{render(world,camera);if(failGhost&&!failureCount&&world.children.some(group=>group.visible&&group.children.some(o=>o.visible&&o.userData.ghost))){failureCount++;throw new TypeError('Injected first ghost submission failure');}};return renderer;}})};
 const scene=owned?createSceneOwner(canvas,{...options,canonicalSavedVisitsAllowed:savedGate,onError:error=>notices.push(error.code),onSceneFailure:detail=>notices.push(detail.mode),loadScene:async()=>({createPipYardScene:(target,props)=>createPipYardScene(target,{...props,plannerWorkerFactory:props.canonicalSavedVisits?options.plannerWorkerFactory:()=>({plan:args=>Promise.resolve(planCanonicalInspection(args)),dispose(){}})})})}):createPipYardScene(canvas,options);
 return{scene,canvas,host,options,frames,timers,doc,win,failures,renders,notices,foodRequests,renderCanvases,restarts,views,get interruptions(){return interruptions;},tick(ms=0){at+=ms;for(const [id,t]of [...timers])if(t.at<=at){timers.delete(id);t.fn();}const calls=[...frames.values()];frames.clear();calls.forEach(fn=>fn(at));},resize(w,h,{flush=true}={}){width=w;height=h;if(flush)observer();},flushResize(){observer();}};
}


const saved=(at=savedFixture.yardRuntime.serverNow)=>{const s=structuredClone(savedFixture);s.player={id:'saved-owner'};s.yardRuntime.serverNow=at;return s;};
const plan=savedFixture.yardRuntime.canonicalVisits[0].plan;
async function open(e,s=saved()){e.scene.update(s,{accountSession:1});await e.scene.ready;await e.scene.ready;e.tick();assert.deepEqual(e.failures,[]);assert.deepEqual(e.notices,[]);}
test('ordinary Scene owner auto-enters only behind saved build gate; no fixture click or planner',async()=>{
 for(const gate of [false,true]){const e=environment({owned:true,savedGate:gate});try{await open(e,saved(plan.inspectionPlan.phases[2].startMs+2600));const d=e.scene.diagnostics();assert.equal(d.mode,gate?'canonical-saved-visits':'unavailable');assert.equal(e.renderCanvases.length,gate?1:0);if(gate){assert.equal(d.scene.lastFrame.visibility,'both');assert.equal(d.scene.lastFrame.savedPhase,'interaction');assert.equal(d.scene.plannerWorkerActive,false);assert.equal(e.scene.inspectCanonicalSlot('canonical:a'),false);assert.equal(e.scene.setPrototypeEnabled,undefined);assert.equal(await e.scene.setCanonicalItemsEnabled(false),false);assert.equal(e.scene.inspectAgain,undefined);assert.equal(d.scene.inspectionCount,0);assert.equal(d.scene.canonicalRecords[0].uses,1);assert.equal(e.views.at(-1).pets[0].visitId,plan.visitId);assert.equal(e.views.at(-1).itemMutable,false);}}finally{await e.scene.dispose();}}
});
test('ordinary Scene quiet wake, hidden resume and departure use elapsed server clock',async()=>{const e=environment({owned:true,savedGate:true}),start=plan.releaseAt+100;try{await open(e,saved(start));assert.equal(e.scene.diagnostics().scene.lastFrame.savedPhase,'neutral-rest');assert.equal(e.frames.size,0);assert.equal(e.timers.size,1);e.doc.hidden=true;e.doc.dispatchEvent(new Event('visibilitychange'));assert.equal(e.timers.size,0);assert.equal(e.frames.size,0);e.tick(plan.leavesAt-start+1000);e.doc.hidden=false;e.doc.dispatchEvent(new Event('visibilitychange'));e.tick();const d=e.scene.diagnostics();assert.equal(d.scene.lastFrame.savedPhase,'departed');assert.equal(d.scene.lastFrame.visibility,'planter');assert.equal(e.views.at(-1).pets.length,0);assert.equal(e.timers.size,0);assert.deepEqual(e.failures,[]);}finally{await e.scene.dispose();}});
test('ordinary Scene pending hides old actor immediately and never falls back to manual fixture',async()=>{const e=environment({owned:true,savedGate:true});try{const s=saved(plan.inspectionPlan.phases[2].startMs+2600);await open(e,s);s.yardRuntime.status='reconciliation-pending';e.scene.update(s,{accountSession:1});assert.equal(e.host.style.visibility,'hidden');assert.equal(e.views.at(-1).pets.length,0);e.tick();assert.equal(e.scene.diagnostics().mode,'canonical-saved-visits');assert.equal(e.scene.diagnostics().scene.plannerWorkerActive,false);assert.equal(e.timers.size,0);assert.equal(e.scene.inspectCanonicalSlot('canonical:a'),false);s.yardRuntime.status='ready';e.scene.update(s,{accountSession:1});e.tick();assert.equal(e.scene.diagnostics().scene.lastFrame.visibility,'both');assert.deepEqual(e.failures,[]);}finally{await e.scene.dispose();}});
test('actual context-owner replacement keeps authoritative time rather than restarting old snapshot',async()=>{const e=environment({owned:true,savedGate:true}),start=plan.releaseAt+100;try{await open(e,saved(start));e.tick(plan.leavesAt-start+1000);const old=e.renderCanvases[0];old.dispatchEvent(new Event('webglcontextlost',{cancelable:true}));old.dispatchEvent(new Event('webglcontextrestored'));await e.scene.ready;await e.scene.ready;e.tick();const d=e.scene.diagnostics();assert.equal(e.renderCanvases.length,2);assert.notEqual(e.host.style.visibility,'hidden');assert.notEqual(e.canvas.style.visibility,'hidden');assert.equal(d.mode,'canonical-saved-visits');assert.equal(d.scene.lastFrame.savedPhase,'departed');assert.equal(d.scene.lastFrame.visibility,'planter');assert.equal(e.views.at(-1).pets.length,0);assert.deepEqual(e.failures,[]);}finally{await e.scene.dispose();}});
test('ordinary Scene owner returns after pagehide and rejects late fixture/ghost mutations',async()=>{const e=environment({owned:true,savedGate:true}),start=plan.releaseAt+100;try{await open(e,saved(start));e.win.dispatchEvent(new Event('pagehide'));await e.scene.ready;e.tick(plan.leavesAt-start+1000);const event=new Event('pageshow');Object.defineProperty(event,'persisted',{value:true});e.win.dispatchEvent(event);await e.scene.ready;await e.scene.ready;e.tick();assert.equal(e.scene.diagnostics().mode,'canonical-saved-visits');assert.equal(e.scene.diagnostics().scene.lastFrame.savedPhase,'departed');e.scene.setGhost({...savedFixture.yardRuntime.canonicalPlacements[0],valid:true});e.tick();assert.equal(e.scene.diagnostics().scene.itemEditing,false);assert.deepEqual(e.failures,[]);}finally{await e.scene.dispose();}assert.equal(e.frames.size,0);assert.equal(e.timers.size,0);});

test('leaving and remounting a normal Scene owner preserves the same monotonic clock domain',async()=>{const e=environment({owned:true,savedGate:true}),start=plan.releaseAt+100;let replacement;try{await open(e,saved(start));await e.scene.dispose();e.tick(plan.leavesAt-start+1000);replacement=createSceneOwner(e.canvas,{...e.options,uiImageOwner:createUiImageReserve(),canonicalSavedVisitsAllowed:true,loadScene:async()=>({createPipYardScene})});replacement.update(saved(start),{accountSession:1});await replacement.ready;await replacement.ready;e.tick();assert.equal(replacement.diagnostics().scene.lastFrame.savedPhase,'departed');assert.notEqual(e.host.style.visibility,'hidden');assert.notEqual(e.canvas.style.visibility,'hidden');assert.equal(replacement.diagnostics().scene.lastFrame.visibility,'planter');assert.deepEqual(e.failures,[]);}finally{await replacement?.dispose();await e.scene.dispose();}});
test('moving saved actor does not republish the React view on every animation frame',async()=>{const e=environment({owned:true,savedGate:true});try{await open(e,saved(plan.inspectionPlan.phases[2].startMs+1000));const before=e.views.length;for(let i=0;i<10;i++)e.tick(16);assert.equal(e.views.length,before);assert.equal(e.scene.diagnostics().scene.lastFrame.savedPhase,'interaction');}finally{await e.scene.dispose();}});

test('saved renderer failure stays hidden and cannot install a legacy fallback',async()=>{const e=environment({owned:true,savedGate:true,failSaved:true});try{e.scene.update(saved(plan.inspectionPlan.phases[2].startMs+2600),{accountSession:1});await e.scene.ready;await e.scene.ready;e.tick();const d=e.scene.diagnostics();assert.equal(d.mode,'unavailable');assert.equal(e.host.style.visibility,'hidden');assert.equal(d.scene,undefined);assert.equal(d.lastFailure.message,'Injected saved renderer failure');assert.equal(e.scene.setPrototypeEnabled,undefined);assert.equal(await e.scene.setCanonicalItemsEnabled(false),false);assert.equal(e.renderCanvases.length,1);}finally{await e.scene.dispose();}});
test('explicit account switch from saved v3 to canonical items retires the saved owner deliberately',async()=>{const e=environment({owned:true,savedGate:true});try{await open(e);const canonical=structuredClone(historicalSnapshot);canonical.player.id='canonical-owner';e.scene.update(canonical,{accountSession:2});await e.scene.ready;assert.equal(e.scene.diagnostics().mode,'canonical-items');assert.equal(e.scene.diagnostics().canonicalSavedVisits,false);assert.equal(e.scene.diagnostics().scene.canonicalItems,true);assert.equal(e.scene.diagnostics().scene.plannerWorkerActive,true);assert.equal(e.renderCanvases.length,2);}finally{await e.scene.dispose();}});

test('hidden saved account A can deliberately switch to canonical B and resume its owner',async()=>{const e=environment({owned:true,savedGate:true});try{await open(e);e.win.dispatchEvent(new Event('pagehide'));await e.scene.ready;const canonical=structuredClone(historicalSnapshot);canonical.player.id='canonical-B';e.scene.update(canonical,{accountSession:2});await e.scene.ready;const event=new Event('pageshow');Object.defineProperty(event,'persisted',{value:true});e.win.dispatchEvent(event);await e.scene.ready;assert.equal(e.scene.diagnostics().mode,'canonical-items');assert.equal(e.scene.diagnostics().canonicalSavedVisits,false);assert.equal(e.scene.diagnostics().scene.canonicalItems,true);assert.equal(e.scene.diagnostics().scene.plannerWorkerActive,true);assert.equal(e.renderCanvases.length,2);assert.notEqual(e.host.style.visibility,'hidden');assert.notEqual(e.canvas.style.visibility,'hidden');}finally{await e.scene.dispose();}});

