import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createPipSnackCandidate} from '../recovery-tools/yard-pip-snack-qa/source/game-logic/yard-v2/media/pip-snack-binding.mjs';
import {PIP_ACTOR_PROFILE,PIP_ACTOR_REFERENCE,PIP_RELEASE_GATE} from '../recovery-tools/yard-pip-snack-qa/source/game-logic/yard-v2/pip-actor-profile.mjs';
import {createPipActorMediaEntry} from '../recovery-tools/yard-pip-snack-qa/source/src/games/companion-yard-v2/pip-actor-media.mjs';
import {AtlasCache,atlasPageFor} from '../recovery-tools/yard-pip-snack-qa/source/src/games/companion-yard-v2/atlas.mjs';
import {YARD_VISITORS,YARD_GOODIES} from '../recovery-tools/yard-pip-snack-qa/source/game-logic/yard-catalog.js';
const read=p=>JSON.parse(readFileSync(new URL('../recovery-tools/yard-pip-snack-qa/'+(p.startsWith('integration/')?p.slice('integration/'.length):'evidence/'+p),import.meta.url)));
const dir='integration/source/game-logic/yard-v2/media/pip/';
const clip=read(dir+'snack-combined-binding.json'),strideContract=read(dir+'authored-stride.json'),motionContract=read(dir+'ground-motion.json');
const source=createPipSnackCandidate({clip,strideContract,motionContract}),fixture=read('integration/public/pip-visit-fixture.json'),plan=fixture.plan,placement=fixture.placement,manifest=read('integration/public/assets/yard-pip/runtime-media.json');
const profiles={pip:{...PIP_ACTOR_PROFILE,playbackReady:true}},entry=createPipActorMediaEntry(manifest,{source,assetBaseURL:'http://pip.fixture/assets/',profiles}),presenter=entry.presenter;
const input=()=>({at:0,leavesAt:180000,placement:structuredClone(placement),yard:{remodel:'meadow',placedGoodies:[structuredClone(placement)],goodieInventory:{snack_table:1,cloud_bed:1}},visitor:{id:'pip_hamster'},activity:{id:'nibble'},bowl:{id:'bowl-1',foodId:'kibble'},active:[],reserved:[]});
const props=()=>[{...placement,drawStandalone:true,transform:{x:placement.x,y:placement.y,rotationZ:0}}];
test('the existing roster, price and durability remain unchanged',()=>{assert.equal(Object.keys(YARD_VISITORS).length,8);assert.equal(Object.keys(YARD_GOODIES).length,11);assert.deepEqual(YARD_GOODIES.snack_table.cost,{treats:160,shinyTreats:0});assert.equal(YARD_GOODIES.snack_table.durability,9);});
test('production remains unavailable and an unregistered profile cannot decode Pip',()=>{assert.equal(PIP_ACTOR_PROFILE.playbackReady,false);assert.equal(PIP_RELEASE_GATE.accepted,false);assert.deepEqual(source.actorProfiles,{});assert.equal(source.preflight(input()).ok,false);assert.throws(()=>createPipActorMediaEntry(manifest,{source,assetBaseURL:'http://pip.fixture/assets/'}),/Registered exact Pip/);});
test('source frame clock, rest loop, rigid tabletop support and corrected clearance match',()=>{const a=read('pip-snack-clearance-audit.json');assert.equal(a.passed,true);assert.equal(a.sourceFramesChecked,521);assert.equal(a.unexpectedIntersections.length,0);assert.equal(a.measuredTabletopSoleChecks,8288);assert.ok(a.maxTabletopSoleToMeshError<.00005);assert.equal(clip.durationMs,20800);assert.equal(clip.sourceSampleMs,40);assert.equal(clip.restLoop.startMs,17920);assert.equal(clip.restLoop.endMs,19200);assert.deepEqual(clip.entry.root,[-.48,0,0]);assert.equal(clip.exit.facing,4);});
test('a full planned visit preserves input and has exact opposite-facing handoffs',()=>{assert.equal(plan.schedule.leavesAt,180000);assert.equal(plan.incoming.initialFacing,0);assert.equal(plan.outgoing.initialFacing,4);assert.equal(plan.requiresEndpointCommit,false);assert.deepEqual(plan.finalTransform,placement);assert.deepEqual(plan.propCommits,[]);assert.equal(plan.schedule.loop.cycles,74);assert.equal(source.sample(plan,180000),null);const outgoing=plan.schedule.segments.find(s=>s.role==='depart');assert.ok(Math.abs(source.sample(plan,outgoing.startAt).headingRadians-Math.PI)<1e-8);assert.equal(plan.actorProfile.revision,PIP_ACTOR_REFERENCE.revision);});
test('source admission validates food, target state, activity and preserved placements',()=>{
 for(const [change,code]of [[q=>q.placement.uses=8,'POST_ADMISSION_PROP_STATE_UNSUPPORTED'],[q=>q.placement.condition='worn','TARGET_PROP_STATE_UNSUPPORTED'],[q=>q.placement.rotationZ=.1,'TARGET_PROP_STATE_UNSUPPORTED'],[q=>q.visitor.id='mochi_bunny','ACTOR_PROFILE_UNAVAILABLE'],[q=>q.activity.id='sniff','ACTIVITY_MEDIA_UNAVAILABLE'],[q=>q.bowl.id='bowl-2','BOWL_PRESENTATION_UNAVAILABLE'],[q=>q.yard.placedGoodies.push({slotId:'unbound',goodieId:'cloud_bed',x:80,y:80}),'PLACEMENT_CALIBRATION_UNAVAILABLE'],[q=>q.yard.placedGoodies[0].x+=1,'TARGET_PLACEMENT_MISMATCH'],[q=>q.active.push({visitorId:'pip_hamster',leavesAt:99999}),'PIP_ALREADY_VISITING']]){const q=input();change(q);const before=JSON.stringify(q);assert.equal(source.preflightCandidate(q).code,code);assert.equal(JSON.stringify(q),before);}
});
test('route turns use 40ms samples, not the Mochi 50ms index',()=>{const turn=plan.incoming.legs.find(l=>l.kind==='turn');assert.ok(turn);assert.equal(source.routes.sample(plan.incoming,turn.startMs+39).motion.frameIndex,0);assert.equal(source.routes.sample(plan.incoming,turn.startMs+40).motion.frameIndex,1);assert.equal(source.routes.sample(plan.incoming,turn.startMs+79).motion.frameIndex,1);assert.equal(source.routes.sample(plan.incoming,turn.startMs+80).motion.frameIndex,2);});
test('every route sample shares its root row with its walking texture',()=>{for(const route of[plan.incoming,plan.outgoing])for(let t=0;t<route.durationMs;t+=13){const p=source.routes.sample(route,t);if(p.motion.kind==='walk'){assert.ok(Math.abs(p.gaitPhase-p.motion.frameIndex/20)<1e-8);assert.ok(p.motion.frameIndex>=0&&p.motion.frameIndex<20);}}});
test('target pixels hide only for the exact coherent source frame and revision',()=>{const at=plan.schedule.combinedStart+4800,p=source.sample(plan,at);assert.equal(source.compose(props(),plan,at).targetSlotHidden,null);assert.equal(source.compose(props(),plan,at,{readyFrame:{clipId:clip.id,frameIndex:p.frameIndex,sourceRevision:'stale'}}).targetSlotHidden,null);const ready={clipId:clip.id,frameIndex:p.frameIndex,sourceRevision:clip.revision},good=source.compose(props(),plan,at,{readyFrame:ready});assert.equal(good.targetSlotHidden,placement.slotId);assert.equal(good.props[0].drawStandalone,false);const moved=props();moved[0].transform.x+=1;assert.equal(source.compose(moved,plan,at,{readyFrame:ready}).issue,'TARGET_PROP_CHANGED');assert.equal(source.compose(moved,plan,at,{readyFrame:ready}).targetSlotHidden,null);});
test('raster loop endpoints match and walk roots were normalized in actual 3D',()=>{const a=read('pip-runtime-seam-pixel-audit.json'),b=read('pip-normalized-walk-render-audit.json');assert.equal(a.restLoopByteIdenticalRGBA,true);assert.equal(b.passed,true);for(const f of Object.values(b.facings))for(const row of f){assert.ok(row.rootError<1e-6);assert.ok(row.boneError<1e-5);}for(const row of Object.values(a.normalizedWalkEndpoints))assert.ok(row.meanChannelError<.0001);});
test('lookahead targets the nearest real page boundary rather than skipping a page',()=>{const at=plan.schedule.combinedStart+8*40,r=presenter.requests(plan,at);assert.equal(r.required.length,1);assert.equal(r.lookahead.length,1);assert.equal(atlasPageFor(r.required[0].clip,r.required[0].index).page.first,0);assert.equal(atlasPageFor(r.lookahead[0].clip,r.lookahead[0].index).page.first,16);assert.ok(r.lookahead[0].index<32);});
test('full-visit demand cache stays bounded and never preloads the 101-page pack',async()=>{
 const oldFetch=globalThis.fetch,oldBitmap=globalThis.createImageBitmap;const dimensions=new Map(),closed=[];for(const c of[...Object.values(entry.manifest.clips),...Object.values(entry.manifest.walk.facings),...Object.values(entry.manifest.turns)])for(const p of c.pages)dimensions.set(new URL(p.src,c.assetBaseURL).href+'?yard-media='+encodeURIComponent(c.assetRevision),p);
 const loaded=[],events=[];globalThis.fetch=async url=>({ok:true,blob:async()=>({url:String(url),size:123})});globalThis.createImageBitmap=async b=>{const p=dimensions.get(b.url);assert.ok(p,b.url);loaded.push(b.url);return{width:p.width,height:p.height,close:()=>closed.push(b.url)};};
 const cache=new AtlasCache('http://pip.fixture/assets/',3,{maxDecodedBytes:32*1024*1024,maxConcurrentDecodes:1,onEvent:e=>events.push(e)});let peak=0;
 try{for(let t=0;t<=180000;t+=160){const r=presenter.requests(plan,t);cache.prepare(r.required,r.lookahead);while(cache.pending.size)await Promise.all([...cache.pending.values()]);peak=Math.max(peak,cache.decodedBytes+cache.reservedBytes);assert.ok(cache.entries.size<=3);assert.ok(peak<=32*1024*1024);const v=presenter.compose(plan,t,props(),cache);assert.equal(v.requiresCoherentFrameHold,false);if(v.pose?.containsTargetProp)assert.equal(v.targetSlotHidden,placement.slotId);}
 assert.ok(new Set(loaded).size<manifest.exportAudit.atlasPages);assert.ok(new Set(loaded).size>10);assert.ok(events.every(e=>e.pendingDecodes===undefined||e.pendingDecodes<=1));assert.ok(closed.length>0);console.log('PIP_CACHE_EVIDENCE',JSON.stringify({peakBytes:peak,uniquePages:new Set(loaded).size,allPages:manifest.exportAudit.atlasPages,loads:loaded.length,closed:closed.length}));}finally{cache.dispose();assert.equal(cache.decodedBytes,0);globalThis.fetch=oldFetch;globalThis.createImageBitmap=oldBitmap;}
});
test('a fresh full-visit preflight reproduces the frozen plan without state mutation',()=>{const q=input(),before=JSON.stringify(q),r=source.preflightCandidate(q);assert.equal(r.ok,true);assert.equal(JSON.stringify(r.plan),JSON.stringify(plan));assert.equal(JSON.stringify(q),before);});
test('cache rejects mismatched decoded dimensions and closes the bad bitmap',async()=>{const oldFetch=globalThis.fetch,oldBitmap=globalThis.createImageBitmap;let closed=0;globalThis.fetch=async()=>({ok:true,blob:async()=>({size:1})});globalThis.createImageBitmap=async()=>({width:10,height:11,close(){closed++;}});const cache=new AtlasCache('http://pip.fixture/',3,{maxDecodedBytes:1024*1024});try{await assert.rejects(cache.load('bad.webp','demand',{width:10,height:10}),/dimensions differ/);assert.ok(cache.error);assert.equal(cache.decodedBytes,0);assert.equal(cache.reservedBytes,0);assert.equal(closed,1);}finally{cache.dispose();globalThis.fetch=oldFetch;globalThis.createImageBitmap=oldBitmap;}});
test('disposing during decode prevents a stale bitmap from entering the cache',async()=>{const oldFetch=globalThis.fetch,oldBitmap=globalThis.createImageBitmap;let resolveBitmap,closed=0;globalThis.fetch=async()=>({ok:true,blob:async()=>({size:1})});globalThis.createImageBitmap=async()=>new Promise(r=>resolveBitmap=r);const cache=new AtlasCache('http://pip.fixture/',3,{maxDecodedBytes:1024*1024});try{const request=cache.load('pending.webp','demand',{width:10,height:10});while(!resolveBitmap)await Promise.resolve();cache.dispose();resolveBitmap({width:10,height:10,close(){closed++;}});assert.equal(await request,null);assert.equal(cache.decodedBytes,0);assert.equal(cache.active,0);assert.equal(cache.reservedBytes,0);assert.equal(closed,1);}finally{cache.dispose();globalThis.fetch=oldFetch;globalThis.createImageBitmap=oldBitmap;}});

// Socket-free regression of the exact server path guard used in CI.
import {fixtureFilePath} from '../scripts/yard-pip-fixture-path.mjs';
test('fixture root normalization serves entry, modules and assets with either slash convention',()=>{
 for(const root of['/tmp/pip-fixture','/tmp/pip-fixture/'])for(const file of['index.html','source/src/games/companion-yard-v2/pip-fixture.mjs','public/assets/yard-pip/runtime-media.json'])assert.equal(fixtureFilePath(root,file),`/tmp/pip-fixture/${file}`);
});
test('fixture scope rejects traversal, absolute paths and sibling-prefix escapes',()=>{
 for(const file of['../secret','../../etc/passwd','/etc/passwd','../pip-fixture-other/index.html','public/../../../secret',decodeURIComponent('%2e%2e%2fsecret')])assert.equal(fixtureFilePath('/tmp/pip-fixture/',file),null,file);
});

test('the fixture nibble timestamp selects an actual nibble row after the brace boundary',()=>{assert.equal(source.sample(plan,plan.schedule.combinedStart+4800).sourceRole,'brace');assert.equal(source.sample(plan,plan.schedule.combinedStart+4840).sourceRole,'nibble');assert.equal(source.sample(plan,plan.schedule.combinedStart+5200).sourceRole,'nibble');});
