import test,{beforeEach}from'node:test';import assert from'node:assert/strict';import{registerHooks}from'node:module';
import{canonicalSavedFoodPendingResult,canonicalSavedFoodReplayAllowed}from'../src/game-state/canonicalSavedFoodProtocol.mjs';
const hooks=registerHooks({resolve(s,c,next){if(s==='idb-keyval')return{shortCircuit:true,url:'saved-food:idb'};return next(s,c);},load(u,c,next){if(u==='saved-food:idb')return{shortCircuit:true,format:'module',source:'export const values=new Map();export const get=async k=>structuredClone(values.get(k));export const set=async(k,v)=>{values.set(k,structuredClone(v));};'};return next(u,c);}});
const storage=await import('saved-food:idb'),{useGameHub:hub}=await import('../src/game-state/useGameHub.js');hooks.deregister();
const CODE='CANONICAL_ACTION_RECONCILIATION_PENDING',ACTIONS=['yard.buyFood','yard.setFood'];
const key=id=>`game_hub_yard_outbox_v2:${encodeURIComponent(id)}`;
function snap(id='food-owner',seq=10,time=1001){return {player:{id,syncSeq:seq},serverTime:time,resources:{gold:100},garden:{plants:[]},gardenR2:null,merge:{schemaVersion:3,board:[],itemCounts:{}},yard:{currencies:{treats:120,shinyTreats:2},foodInventory:{kibble:3,berry_plate:1},goodieInventory:{}},yardRuntime:{version:1,storageVersion:3,canonicalVisitProtocol:'yard-canonical-authoritative/v1',status:'ready',mutable:false,serverNow:time,actionProtocol:'yard-v2:',supportedActions:[...ACTIONS],canonicalFoodActions:{protocol:'yard-canonical-food-actions/v1',enabled:true,actions:[...ACTIONS]},supportedBindings:{foods:{kibble:{buy:true,set:true},berry_plate:{buy:true,set:true}},bowls:{'bowl-1':{set:true}}}}};}
const item=(extra={})=>({accountId:'food-owner',clientActionId:'yard-v2:saved-food-unchanged',action:'yard.buyFood',payload:{foodId:'berry_plate',qty:1},entityKey:'shop:food:berry_plate',status:'pending',attempts:0,createdAt:1000,intentServerTime:1000,nextAttemptAt:0,...extra});
const response=(body,status=200)=>({ok:status<400,status,text:async()=>JSON.stringify(body),json:async()=>body});
function reset(id='food-owner'){hub.setState({snapshot:null});hub.getState().applySnapshot(snap(id));hub.setState({status:'ready',message:'',busy:{},pendingActions:[],outboxLoaded:true,outboxAccountId:id,outboxStorageError:null,lastResult:null});}
beforeEach(t=>{t.mock.timers.enable({apis:['setTimeout']});storage.values.clear();const local=new Map();globalThis.localStorage={getItem:k=>local.get(k)??null,setItem:(k,v)=>local.set(k,String(v))};globalThis.fetch=async p=>{if(p==='/api/config')return response({devAuthEnabled:false});throw Error('Unexpected request '+p);};reset();});
test('exact pending denial persists original ordinary intent; only later fresh HTTP capability resumes',async t=>{let posts=0,reads=0;const bodies=[];globalThis.fetch=async(p,o)=>{if(p==='/api/config')return response({devAuthEnabled:false});if(new URL(p,'https://fixture.invalid').pathname==='/api/player/snapshot'){reads++;return response(snap('food-owner',20,2000));}bodies.push(JSON.parse(o.body));posts++;return posts===1?response({error:CODE},409):response({success:true,duplicate:true,snapshot:snap('food-owner',21,2100)});};
 await hub.getState().enqueueYardAction('yard.buyFood',{foodId:'berry_plate',qty:1},{clientActionId:item().clientActionId,feedback:false});await hub.getState().drainOutbox();const held=structuredClone(hub.getState().pendingActions[0]);assert.equal(held.status,'saved-food-pending');assert.equal(held.requiresSavedFoodResume,true);assert.equal(held.requiresYardResume,undefined);assert.equal(posts,1);assert.equal(reads,1);
 t.mock.timers.tick(600000);await hub.getState().drainOutbox();await hub.getState().drainOutbox();assert.equal(posts,1);assert.equal(reads,1);assert.deepEqual(storage.values.get(key('food-owner')).items[0],held);
 hub.getState().applySnapshot(snap('food-owner',20,2000));await hub.getState().drainOutbox();assert.equal(posts,1);await hub.getState().loadSnapshot();await hub.getState().drainOutbox();assert.equal(posts,2);assert.deepEqual(bodies[1],bodies[0]);assert.deepEqual(storage.values.get(key('food-owner')).items,[]);assert.equal(hub.getState().snapshot.yardRuntime.mutable,false);
});
test('rehydrated saved-food fence resumes without rechecking already-consumed money or stock',async()=>{const held=item({status:'saved-food-pending',requiresSavedFoodResume:true,attempts:2});storage.values.set(key('food-owner'),{version:2,accountId:'food-owner',items:[held]});hub.setState({outboxLoaded:false});let posts=0;const s=snap('food-owner',11,1100);s.yard.currencies={treats:0,shinyTreats:0};s.yard.foodInventory={};globalThis.fetch=async(p,o)=>{if(p==='/api/config')return response({devAuthEnabled:false});if(new URL(p,'https://fixture.invalid').pathname==='/api/player/snapshot')return response(s);posts++;assert.deepEqual(JSON.parse(o.body).payload,held.payload);return response({success:true,duplicate:true,snapshot:s});};await hub.getState().hydrateOutbox();await hub.getState().drainOutbox();assert.equal(posts,0);await hub.getState().loadSnapshot();await hub.getState().drainOutbox();assert.equal(posts,1);assert.equal(hub.getState().pendingActions.length,0);});
for(const [label,change]of[['pending',s=>s.yardRuntime.status='reconciliation-pending'],['missing capability',s=>delete s.yardRuntime.canonicalFoodActions],['wrong protocol',s=>s.yardRuntime.canonicalFoodActions.protocol='other'],['mutable broad authority',s=>s.yardRuntime.mutable=true],['unsupported binding',s=>s.yardRuntime.supportedBindings.foods.berry_plate.buy=false]])test(`fresh ${label} cannot resume food fence`,async()=>{const held=item({status:'saved-food-pending',requiresSavedFoodResume:true,attempts:1});hub.setState({pendingActions:[held]});let posts=0;const s=snap('food-owner',11,1100);change(s);globalThis.fetch=async p=>p==='/api/config'?response({}):new URL(p,'https://fixture.invalid').pathname==='/api/player/snapshot'?response(s):(posts++,response({success:true}));await hub.getState().loadSnapshot();await hub.getState().drainOutbox();assert.equal(posts,0);assert.equal(hub.getState().pendingActions[0].clientActionId,held.clientActionId);});
test('saved food capability does not bypass a general rollout-paused item',async()=>{const held=item({status:'rollout-paused',requiresYardResume:true,requiresSavedFoodResume:true,attempts:1});hub.setState({pendingActions:[held]});let posts=0;globalThis.fetch=async p=>p==='/api/config'?response({}):new URL(p,'https://fixture.invalid').pathname==='/api/player/snapshot'?response(snap('food-owner',11,1100)):(posts++,response({success:true}));await hub.getState().loadSnapshot();await hub.getState().drainOutbox();assert.equal(posts,0);});
test('same-account A-B-A replacement discards prior food resume authority until fresh HTTP',async()=>{let posts=0;globalThis.fetch=async p=>p==='/api/config'?response({}):new URL(p,'https://fixture.invalid').pathname==='/api/player/snapshot'?response(snap('food-owner',11,1100)):(posts++,response({success:true,snapshot:snap('food-owner',12,1200)}));await hub.getState().loadSnapshot();hub.getState().applySnapshot(snap('other-owner',20,2000));hub.getState().applySnapshot(snap('food-owner',11,1100));hub.setState({outboxLoaded:true,outboxAccountId:'food-owner',pendingActions:[item({status:'saved-food-pending',requiresSavedFoodResume:true})]});await hub.getState().drainOutbox();assert.equal(posts,0);await hub.getState().loadSnapshot();await hub.getState().drainOutbox();assert.equal(posts,1);});
test('pending classification is exact code+409+ordinary food intent, never arbitrary retryable',()=>{const i=item();assert(canonicalSavedFoodPendingResult(i,{error:CODE,_httpStatus:409}));for(const result of[{error:'other',_httpStatus:409,retryable:true},{error:CODE,_httpStatus:400},{error:CODE,retryable:true}])assert.equal(canonicalSavedFoodPendingResult(i,result),false);assert.equal(canonicalSavedFoodPendingResult({...i,action:'yard.collectGifts',payload:{}},{error:CODE,_httpStatus:409}),false);assert.equal(canonicalSavedFoodReplayAllowed({...i,accountId:'foreign'},snap()),false);assert.equal(canonicalSavedFoodReplayAllowed({...i,clientActionId:'yard-v2:canonical-v2/foreign'},snap()),false);});
test('older in-flight ready HTTP read cannot unpause a later saved-food denial',async()=>{
 let resolveOld,notifyOld,reads=0,posts=0;const oldReady=new Promise(r=>notifyOld=r),oldReply=new Promise(r=>resolveOld=r);hub.setState({pendingActions:[item()]});
 globalThis.fetch=async(p,o)=>{if(p==='/api/config')return response({});if(new URL(p,'https://fixture.invalid').pathname==='/api/player/snapshot'){reads++;if(reads===1){notifyOld();return oldReply;}return response(snap('food-owner',12,1200));}posts++;return response({error:CODE},409);};
 const old=hub.getState().loadSnapshot();await oldReady;await hub.getState().drainOutbox();assert.equal(posts,1);assert.equal(reads,2);resolveOld(response(snap('food-owner',11,1100)));await old;await hub.getState().drainOutbox();assert.equal(posts,1);assert.equal(hub.getState().pendingActions[0].status,'saved-food-pending');
});
test('a saved-food marker cannot authorize a different action or malformed payload on resume',async()=>{for(const held of[item({status:'saved-food-pending',requiresSavedFoodResume:true,action:'yard.collectGifts',payload:{}}),item({status:'saved-food-pending',requiresSavedFoodResume:true,payload:{foodId:'berry_plate',qty:2}})]){reset();hub.setState({pendingActions:[held]});let posts=0;globalThis.fetch=async p=>p==='/api/config'?response({}):new URL(p,'https://fixture.invalid').pathname==='/api/player/snapshot'?response(snap('food-owner',11,1100)):(posts++,response({success:true}));await hub.getState().loadSnapshot();await hub.getState().drainOutbox();assert.equal(posts,0);}});

test('broad writable snapshot cannot bypass the saved-food half of a doubly fenced intent',async()=>{const held=item({status:'rollout-paused',requiresYardResume:true,requiresSavedFoodResume:true,attempts:2});hub.setState({pendingActions:[held]});let posts=0;const s=snap('food-owner',11,1100);s.yardRuntime={version:1,status:'ready',mutable:true,actionProtocol:'yard-v2:',serverNow:1100};globalThis.fetch=async p=>p==='/api/config'?response({}):new URL(p,'https://fixture.invalid').pathname==='/api/player/snapshot'?response(s):(posts++,response({success:true}));await hub.getState().loadSnapshot();await hub.getState().drainOutbox();assert.equal(posts,0);assert.equal(hub.getState().pendingActions[0].clientActionId,held.clientActionId);});

test('cached binding enable cannot expand the actual HTTP food resume witness',async()=>{const held=item({status:'saved-food-pending',requiresSavedFoodResume:true,attempts:1});hub.setState({pendingActions:[held]});let posts=0,http=snap('food-owner',11,1100);http.yardRuntime.supportedBindings.foods.berry_plate.buy=false;globalThis.fetch=async p=>p==='/api/config'?response({}):new URL(p,'https://fixture.invalid').pathname==='/api/player/snapshot'?response(http):(posts++,response({success:true,snapshot:snap('food-owner',14,1400)}));await hub.getState().loadSnapshot();await hub.getState().drainOutbox();assert.equal(posts,0);hub.getState().applySnapshot(snap('food-owner',12,1200));await hub.getState().drainOutbox();assert.equal(posts,0);http=snap('food-owner',13,1300);await hub.getState().loadSnapshot();await hub.getState().drainOutbox();assert.equal(posts,1);});

test('a later permission disable retires the old HTTP witness before cache-only re-enable',async()=>{hub.setState({pendingActions:[item({status:'saved-food-pending',requiresSavedFoodResume:true,attempts:1})]});let posts=0,http=snap('food-owner',11,1100);globalThis.fetch=async p=>p==='/api/config'?response({}):new URL(p,'https://fixture.invalid').pathname==='/api/player/snapshot'?response(http):(posts++,response({success:true,snapshot:snap('food-owner',15,1500)}));await hub.getState().loadSnapshot();const denied=snap('food-owner',12,1200);denied.yardRuntime.supportedBindings.foods.berry_plate.buy=false;hub.getState().applySnapshot(denied);hub.getState().applySnapshot(snap('food-owner',13,1300));await hub.getState().drainOutbox();assert.equal(posts,0);http=snap('food-owner',14,1400);await hub.getState().loadSnapshot();await hub.getState().drainOutbox();assert.equal(posts,1);});
