import {installFoodAppearance} from '../src/games/companion-yard-v2/pip-prototype/prototype/painted-food-appearance.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import crypto from 'node:crypto';
import * as THREE from '../src/games/companion-yard-v2/pip-prototype/vendor/three/build/three.module.js';import {GLTFLoader} from '../src/games/companion-yard-v2/pip-prototype/vendor/three/addons/loaders/GLTFLoader.js';
import {PAINTED_FOOD_ASSET as A,PAINTED_FOOD_DESCRIPTOR as D,paintedFoodAssetURL,createPaintedFoodPreview,createPaintedFoodResourceOwner} from '../src/games/companion-yard-v2/pip-prototype/prototype/calibrated-food-painted.mjs';
import {CANONICAL_FOOD_CONTRACT,canonicalFoodCapabilities} from '../game-logic/yard-v2/canonical-food-contract.mjs';import {LIMITS,COMBINED_KNOWN_CPU_PEAK} from '../src/games/companion-yard-v2/pip-prototype/resources.mjs';
// Node-only image decoder boundary. Real Blob extraction/fetch and GLTFLoader run;
// browser decode/upload/color output are deliberately not claimed by these tests.
globalThis.self=globalThis;let imageCloses=0,decoded=0,decodeGate=null;
globalThis.createImageBitmap=async blob=>{const raw=await blob.arrayBuffer(),v=new DataView(raw);assert.equal(crypto.createHash('sha256').update(new Uint8Array(raw)).digest('hex'),A.imageSHA256);assert.equal(v.getUint32(16),128);assert.equal(v.getUint32(20),128);decoded++;if(decodeGate)await decodeGate;let closed=false;return{width:128,height:128,close(){assert.equal(closed,false,'image closed only once');closed=true;imageCloses++;}};};
const readBytes=async()=>{const b=await fs.readFile(paintedFoodAssetURL());return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);};
const base=()=>({rgba:4*1024*1024,knownCPU:COMBINED_KNOWN_CPU_PEAK+1024,estimatedGPU:10*1024*1024});
const ownerFor=(getBaseUsage=base)=>createPaintedFoodResourceOwner({getBaseUsage});
const create=(options={})=>createPaintedFoodPreview(THREE,{enabled:true,descriptor:D,loader:new GLTFLoader(),loadAssetBytes:readBytes,resourceOwner:ownerFor(),...options});
const snapshot=(id=null)=>({yard:{bowls:[{id:'bowl-1',foodId:id,servings:id?4:0,placedAt:1,expiresAt:2},{id:'bowl-2',foodId:'bonito_bowl',servings:6}],foodInventory:{kibble:1,berry_plate:2,bonito_bowl:3}},yardRuntime:{version:1,status:'ready',canonicalPlacements:[],foodLocationCapabilities:canonicalFoodCapabilities({canonicalFoodLocationEnabled:true})}});
function inventory(root){const geometries=new Set(),materials=new Set(),textures=new Set();root.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material){materials.add(o.material);if(o.material.map)textures.add(o.material.map)}});return{geometries,materials,textures};}

test('inactive import/factory do not load; economic descriptor and footprint are unchanged',async()=>{let touched=0;assert.equal(await createPaintedFoodPreview(null,{loadAssetBytes(){touched++}}),null);assert.equal(touched,0);assert.equal(CANONICAL_FOOD_CONTRACT.id,'canonical-food-r2/20261006');assert.equal(CANONICAL_FOOD_CONTRACT.unionHeightCanonical,2.09);assert.equal(D.unionHeightCanonical,3.14);assert.equal(D.unionRadiusCanonical,3.843);assert.deepEqual(D.anchorCanonicalXYZ,[80,82,0]);assert.throws(()=>paintedFoodAssetURL('old'),/identity/);});
test('pinned model uses one real extracted PNG/shared texture and exact buffer accounting',async()=>{const resourceOwner=ownerFor(),owner=await create({resourceOwner});try{assert.equal(owner.root.visible,false);assert.ok(owner.root.children.every(x=>!x.visible));const i=inventory(owner.root);assert.equal(i.textures.size,1);assert.equal(i.geometries.size,6);assert.equal(i.materials.size,4);assert.equal(owner.resources.knownCPUBufferPeakBytes,A.knownCPUBufferPeakBytes);assert.equal(owner.resources.geometryGPUBufferBytes,A.geometryGPUBufferBytes);assert.equal(owner.resources.contextRestoreGPUBufferPeakBytes,A.contextRestoreGPUBufferPeakBytes);assert.equal(resourceOwner.snapshot().total.rgba,base().rgba+A.rgbaImagePeakBytes);const contact=owner.root.getObjectByName('FoodContactLobe');assert.equal(contact.material.depthWrite,false);assert.equal(contact.renderOrder,-1);assert.equal(contact.geometry.attributes.color.itemSize,4);const alpha=contact.geometry.attributes.color;assert.equal(Math.min(...Array.from({length:alpha.count},(_,i)=>alpha.getW(i))),0);assert.ok(Math.max(...Array.from({length:alpha.count},(_,i)=>alpha.getW(i)))>.30);}finally{owner.dispose()}assert.deepEqual(resourceOwner.snapshot().total,base());});
test('four states select one shared vessel, preserve inventory, and stay in measured 3.14 envelope',async()=>{const owner=await create();try{const expected={empty:['BowlVessel'],kibble:['BowlVessel','KibbleContents'],berry_plate:['BowlVessel','BerryContents'],bonito_bowl:['BowlVessel','BonitoContents']};for(const state of Object.keys(expected)){const s=snapshot(state==='empty'?null:state),before=structuredClone(s);assert.equal(owner.selectSnapshot(s).state,state);assert.deepEqual(owner.diagnostics.visibleGroups,expected[state]);assert.deepEqual(s,before);owner.root.updateMatrixWorld(true);owner.root.traverseVisible(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position;for(let i=0;i<p.count;i++){const q=new THREE.Vector3().fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld);assert.ok(Math.hypot(q.x*12-80,-q.z*12-82)<=3.843+1e-6);assert.ok(q.y*12>=-1e-7&&q.y*12<=3.14)}})}assert.equal(owner.diagnostics.loads,1)}finally{owner.dispose()}});
test('unknown, duplicate and stale/disabled snapshots hide without mutation',async()=>{const o=await create();try{for(const mutate of [s=>s.yard.bowls.push({...s.yard.bowls[0]}),s=>s.yard.bowls[0].foodId='unknown',s=>s.yard.bowls[0].servings=-1,s=>s.yardRuntime.foodLocationCapabilities.enabled=false]){o.selectSnapshot(snapshot('kibble'));const s=snapshot('berry_plate');mutate(s);const before=structuredClone(s);assert.equal(o.selectSnapshot(s).available,false);assert.equal(o.root.visible,false);assert.deepEqual(s,before)}}finally{o.dispose()}});
test('identity and all global caps refuse before asset load',async()=>{let loads=0;await assert.rejects(create({descriptor:{...D,unionHeightCanonical:2.09},loadAssetBytes:async()=>{loads++;return readBytes()}}),/descriptor/);for(const key of ['rgba','knownCPU','estimatedGPU']){const usage={rgba:0,knownCPU:0,estimatedGPU:0,[key]:LIMITS[key]};await assert.rejects(create({resourceOwner:ownerFor(()=>usage),loadAssetBytes:async()=>{loads++;return readBytes()}}),/resource cap/)}assert.equal(loads,0);const wrong=await readBytes();new Uint8Array(wrong)[wrong.byteLength-1]^=1;await assert.rejects(create({loadAssetBytes:async()=>wrong}),/hash mismatch/);});
test('texture, bitmap, materials and geometry dispose once; visible GPU remains retired',async()=>{const r=ownerFor(),o=await create({resourceOwner:r}),i=inventory(o.root),counts={g:0,m:0,t:0},before=imageCloses;for(const g of i.geometries)g.addEventListener('dispose',()=>counts.g++);for(const m of i.materials)m.addEventListener('dispose',()=>counts.m++);for(const t of i.textures)t.addEventListener('dispose',()=>counts.t++);o.selectSnapshot(snapshot('bonito_bowl'));o.dispose();o.dispose();assert.deepEqual(counts,{g:6,m:4,t:1});assert.equal(imageCloses,before+1);assert.equal(r.snapshot().total.rgba,base().rgba);assert.equal(r.snapshot().total.knownCPU,base().knownCPU);assert.equal(r.snapshot().retiredOwners,1);assert.equal(r.snapshot().total.estimatedGPU,base().estimatedGPU+A.contextRestoreGPUBufferPeakBytes);r.releaseRetiredAfterRendererDisposal();assert.deepEqual(r.snapshot().total,base());});
test('late decode cancellation retains reservation until decode settles and then closes image',async()=>{let release;decodeGate=new Promise(r=>release=r);const controller=new AbortController(),r=ownerFor(),before=decoded,closed=imageCloses;const pending=create({resourceOwner:r,signal:controller.signal});try{while(decoded===before)await new Promise(r=>setTimeout(r,1));controller.abort();assert.equal(r.snapshot().loadingOrLiveOwners,1);release();await assert.rejects(pending,{name:'AbortError'});assert.equal(imageCloses,closed+1);assert.equal(r.snapshot().loadingOrLiveOwners,0);}finally{decodeGate=null;release();}});
test('post-decode parser rejection and bad loaded structure close tracked image',async()=>{for(const mode of ['reject','structure']){const loader=new GLTFLoader(),parse=loader.parseAsync.bind(loader),closed=imageCloses,r=ownerFor();loader.parseAsync=async(...args)=>{const g=await parse(...args);if(mode==='reject')throw Error('controlled parser rejection');g.scene.children[0].name='wrong';return g};await assert.rejects(create({loader,resourceOwner:r}),/parser rejection|source structure/);assert.equal(imageCloses,closed+1);assert.equal(r.snapshot().loadingOrLiveOwners,0);}});
test('context restore reuses the same shared image and requalifies latest state and caps',async()=>{let usage=base();const r=ownerFor(()=>usage),o=await create({resourceOwner:r}),before=decoded;try{o.selectSnapshot(snapshot('kibble'));const texture=[...inventory(o.root).textures][0];o.contextLost();assert.equal(o.root.visible,false);usage={...usage,rgba:LIMITS.rgba};assert.throws(()=>o.contextRestored(snapshot('bonito_bowl')),/resource cap/);assert.equal(o.diagnostics.contextLost,true);usage=base();assert.equal(o.contextRestored(snapshot('bonito_bowl')).available,true);assert.strictEqual([...inventory(o.root).textures][0],texture);assert.equal(decoded,before);}finally{o.dispose();r.releaseRetiredAfterRendererDisposal();}});
test('real host base refuses replacement preload before fetch; retired owner may then be replaced',async()=>{const r=ownerFor(),first=await create({resourceOwner:r});first.selectSnapshot(snapshot('kibble'));let touched=false;await assert.rejects(create({resourceOwner:r,loadAssetBytes:async()=>{touched=true;return readBytes()}}),/resource cap/);assert.equal(touched,false);first.dispose();const second=await create({resourceOwner:r});assert.equal(r.snapshot().retiredOwners,1);second.dispose();r.releaseRetiredAfterRendererDisposal();assert.deepEqual(r.snapshot().total,base());});

test('food fidelity probe keeps buffers, opaque transforms, shared texture and solid reservation unchanged',async()=>{const owner=await create(),all=inventory(owner.root),contact=owner.root.getObjectByName('FoodContactLobe');try{const hashes=[...all.geometries].map(g=>Object.values(g.attributes).map(a=>crypto.createHash('sha256').update(new Uint8Array(a.array.buffer,a.array.byteOffset,a.array.byteLength)).digest('hex')));const opaque=[];owner.root.traverse(o=>{if(o.isMesh&&o!==contact)opaque.push([o,o.matrix.clone()])});const texture=[...all.textures][0];for(const variant of ['baseline','authored-color','authored-color-contact']){const a=installFoodAppearance(owner.root,{variant});assert.equal(a.diagnostics.addedTextureBytes,0);assert.equal(a.diagnostics.addedGeometryBufferBytes,0);assert.equal(a.diagnostics.addedRenderTargetBytes,0);assert.equal(a.diagnostics.solidNavigationRadiusCanonical,3.843);for(const [o,m]of opaque)assert.deepEqual(o.matrix.elements,m.elements);assert.strictEqual([...inventory(owner.root).textures][0],texture);for(const m of all.materials){const shader={fragmentShader:THREE.ShaderLib.standard.fragmentShader};m.onBeforeCompile(shader,{});if(variant!=='baseline'&&m!==contact.material)assert(shader.fragmentShader.includes('outgoingLight = mix( outgoingLight, diffuseColor.rgb,'));if(variant==='authored-color-contact'&&m===contact.material)assert(shader.fragmentShader.includes('outgoingLight = diffuseColor.rgb;'));}if(variant==='authored-color-contact'){assert.deepEqual(contact.scale.toArray(),[1.25,1,1.18]);assert.equal(a.diagnostics.contactVisualRadiusUpperBoundCanonical,5.24);}a.dispose();a.dispose();assert.deepEqual(contact.scale.toArray(),[1,1,1]);}assert.deepEqual([...all.geometries].map(g=>Object.values(g.attributes).map(a=>crypto.createHash('sha256').update(new Uint8Array(a.array.buffer,a.array.byteOffset,a.array.byteLength)).digest('hex'))),hashes);}finally{owner.dispose()}});

test('isolated sampling allowance cannot silently raise the default resource cap',()=>{
 const getBaseUsage=()=>({rgba:40000000,knownCPU:15000000,estimatedGPU:18000000});
 assert.throws(()=>createPaintedFoodResourceOwner({getBaseUsage}).reserve(),/resource cap/);
 const owner=createPaintedFoodResourceOwner({getBaseUsage,resourceProfile:'isolated-native-sampling-1.5'});owner.reserve();
 assert.equal(owner.snapshot().limits.estimatedGPU,20*1024*1024);
 assert.throws(()=>createPaintedFoodResourceOwner({getBaseUsage,resourceProfile:'anything'}),/Unknown resource profile/);
});
