import {MAX_BYTES,validateInputs,sceneLayout,frameRect,foliagePlacements,coverRect} from './model.mjs';
const canvas=document.querySelector('#scene'),ctx=canvas.getContext('2d'),stage=document.querySelector('#stage'),status=document.querySelector('#status'),errorBox=document.querySelector('#error');
const state={scope:'one-static-native-source-frame; not animation/gameplay/API acceptance',ready:false,disposed:false,errors:[],http:[],draws:[],peakBytes:0,environmentBytes:0,subjectBytes:0,canvasBytes:0,pendingBytes:0,sourceFrame:101,sourceTimeMs:4000,clockAdvances:false,maskMethod:'conservativeMaskStrips',lawnMethod:'one continuous opaque plate; uniform cover/crop',startedAt:performance.now()};
const images=new Map();let layoutInput,frameInput,payload,disposed=false;
const snapshot=()=>JSON.parse(JSON.stringify(state));window.__yardFrame45={snapshot};
const fail=e=>{const text=String(e?.stack||e);state.errors.push(text);errorBox.textContent=text;state.ready=false;};
function reserve(extra=0){const bytes=state.environmentBytes+state.subjectBytes+state.canvasBytes+state.pendingBytes+extra;state.peakBytes=Math.max(state.peakBytes,bytes);if(bytes>MAX_BYTES)throw Error(`Decoded ledger exceeds 32 MiB: ${bytes}`);return bytes;}
async function json(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${path}: HTTP${r.status}`);return r.json();}
async function loadMedia(row){state.pendingBytes=row.decodedBytes;reserve();try{const response=await fetch(row.src,{cache:'no-store'});if(!response.ok)throw Error(`HTTP${response.status}: ${row.src}`);const bytes=await response.arrayBuffer(),digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');if(digest!==row.sha256||bytes.byteLength!==row.encodedBytes)throw Error(`Media hash mismatch: ${row.src}`);if(disposed)return false;const image=await createImageBitmap(new Blob([bytes],{type:'image/webp'}));if(disposed){image.close();return false;}if(image.width!==row.width||image.height!==row.height){image.close();throw Error(`Media dimensions mismatch: ${row.src}`);}images.set(row.id,image);if(row.id==='subject')state.subjectBytes+=row.decodedBytes;else state.environmentBytes+=row.decodedBytes;state.pendingBytes=0;reserve();state.http.push({src:row.src,status:response.status,sha256:digest,encodedBytes:bytes.byteLength});return true;}finally{state.pendingBytes=0;}}
function polygonsPath(polys){for(const p of polys){p.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();}}
function draw(){if(disposed||!state.ready)return;const box=stage.getBoundingClientRect(),width=box.width,height=box.height,dpr=Math.min(2,devicePixelRatio||1),cw=Math.round(width*dpr),ch=Math.round(height*dpr),nextBytes=cw*ch*4;if(!width||!height)return;
 if(canvas.width!==cw||canvas.height!==ch){reserve(nextBytes+Math.max(cw*canvas.height,canvas.width*ch)*4);canvas.width=cw;canvas.height=ch;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;state.canvasBytes=nextBytes;}
 ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);const layout=sceneLayout(layoutInput,width,height),plate=images.get('plate'),bg=coverRect(width,height,plate.width,plate.height);ctx.drawImage(plate,bg.x,bg.y,bg.width,bg.height);
 const foliage=foliagePlacements(layout),border=images.get('border');ctx.save();ctx.beginPath();ctx.rect(0,0,width,height);polygonsPath(layout.maskPolygons);ctx.clip('evenodd');ctx.beginPath();ctx.rect(0,0,width,height);const passage=layout.visualPassage;ctx.rect(passage.x,passage.y,passage.width,passage.height);ctx.clip('evenodd');for(const r of foliage)ctx.drawImage(border,r.x,r.y,r.width,r.height);ctx.restore();
 const f=layout.facade;ctx.drawImage(images.get('facade'),f.x,f.y,f.width,f.height);for(const g of layout.gateHalves)ctx.drawImage(images.get(g.id==='left'?'gateLeft':'gateRight'),g.x,g.y,g.width,g.height);
 const sprite=frameRect(frameInput,layout);ctx.drawImage(images.get('subject'),sprite.x,sprite.y,sprite.width,sprite.height);
 if(document.querySelector('#guides').checked){ctx.save();ctx.strokeStyle='rgba(255,255,230,.6)';ctx.lineWidth=1;ctx.beginPath();polygonsPath(layout.maskPolygons);ctx.stroke();ctx.strokeStyle='#ffbd68';ctx.strokeRect(passage.x,passage.y,passage.width,passage.height);ctx.strokeStyle='#d6faff';ctx.strokeRect(layout.door.x,layout.door.y,layout.door.width,layout.door.height);ctx.font='11px system-ui';for(const[k,p]of Object.entries(layout.anchors)){ctx.beginPath();ctx.moveTo(p.x-5,p.y);ctx.lineTo(p.x+5,p.y);ctx.moveTo(p.x,p.y-5);ctx.lineTo(p.x,p.y+5);ctx.stroke();ctx.fillStyle='#fff9df';ctx.fillText(k,p.x+7,p.y-5);}ctx.restore();}
 const bytes=reserve();state.current={preset:layout.preset,scene:{width,height,dpr,canvasWidth:cw,canvasHeight:ch},ppu:layout.projection.ppu,architectureScale:layout.architectureScale,sourceFrame:101,sourceTimeMs:4000,sprite,anchors:layout.anchors,door:layout.door,gateBounds:layout.gateBounds,gateOpening:layout.gateOpening,facade:layout.facade,visualPassage:layout.visualPassage,maskBounds:{minX:Math.min(...layout.maskPolygons.flat().map(p=>p.x)),maxX:Math.max(...layout.maskPolygons.flat().map(p=>p.x)),minY:Math.min(...layout.maskPolygons.flat().map(p=>p.y)),maxY:Math.max(...layout.maskPolygons.flat().map(p=>p.y))},foliageCount:foliage.length,budgetBytes:bytes,canvasBytes:state.canvasBytes,mediaBytes:state.environmentBytes+state.subjectBytes,guides:document.querySelector('#guides').checked,plate:bg};state.draws.push({at:performance.now(),sourceFrame:101,sourceTimeMs:4000,preset:layout.preset,guides:state.current.guides});state.firstDrawAt??=performance.now();status.textContent=`One frame · ${(bytes/1048576).toFixed(2)}MiB · ${layout.preset}`;
}
window.addEventListener('resize',()=>{try{draw();}catch(e){fail(e);}});document.querySelector('#guides').addEventListener('change',()=>{try{draw();}catch(e){fail(e);}});
window.addEventListener('pagehide',()=>{disposed=true;state.disposed=true;state.ready=false;for(const im of images.values())im.close();images.clear();state.environmentBytes=state.subjectBytes=state.pendingBytes=0;});
try{[payload,layoutInput,frameInput]=await Promise.all([json('./payload-manifest.json'),json('./layout.json'),json('./frame.json')]);validateInputs(layoutInput,frameInput);for(const row of payload.media){if(!await loadMedia(row)||disposed)break;}if(!disposed){state.ready=true;state.loadedAllAt=performance.now();draw();}}catch(e){if(!disposed)fail(e);}
