import {test,expect} from '@playwright/test';import {readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
const manifestBytes=await readFile(new URL('./payload-manifest.json',import.meta.url)),manifest=JSON.parse(manifestBytes),expected=new Map(manifest.files.map(r=>['/'+r.path,r]));const hash=b=>createHash('sha256').update(b).digest('hex');
const scenes=[{name:'portrait320',width:320,height:568,dpr:1,sceneWidth:320,sceneHeight:372},{name:'portrait390',width:390,height:844,dpr:2,sceneWidth:390,sceneHeight:648},{name:'landscape754',width:844,height:390,dpr:1,sceneWidth:754,sceneHeight:302}];
for(const spec of scenes)test.describe(spec.name,()=>{test.use({viewport:{width:spec.width,height:spec.height},deviceScaleFactor:spec.dpr,isMobile:true,hasTouch:true});test('actual static source frame, full scene composition and source identity',async({page},info)=>{
 const errors=[],requests=[],http=[],pending=[];page.on('pageerror',e=>errors.push(String(e)));page.on('requestfailed',r=>errors.push(r.url()+': '+r.failure()?.errorText));page.on('request',r=>requests.push({method:r.method(),url:r.url()}));page.on('response',r=>{const path=new URL(r.url()).pathname,row=expected.get(path);if(row)pending.push((async()=>{const b=await r.body();http.push({path,status:r.status(),bytes:b.length,sha256:hash(b),expectedSha256:row.sha256});})().catch(e=>errors.push(String(e))));});
 try{await page.goto('/preview/yard-coherent-frame/');await page.waitForFunction(()=>window.__yardFrame45?.snapshot().ready);await expect(page.locator('#error')).toBeEmpty();await expect(page.locator('header')).toContainText('One still');
 const before=await page.evaluate(()=>({snapshot:window.__yardFrame45.snapshot(),pixels:document.querySelector('canvas').toDataURL()}));expect(before.snapshot.current.scene.width).toBe(spec.sceneWidth);expect(before.snapshot.current.scene.height).toBe(spec.sceneHeight);expect(before.snapshot.current.preset).toBe(spec.name);
 await page.locator('canvas').screenshot({path:info.outputPath(`${spec.name}-canvas.png`)});await page.screenshot({path:info.outputPath(`${spec.name}-whole-viewport.png`),fullPage:true});await page.waitForTimeout(150);expect(await page.evaluate(()=>document.querySelector('canvas').toDataURL())).toBe(before.pixels);
 await page.locator('#guides').check();await page.locator('canvas').screenshot({path:info.outputPath(`${spec.name}-guides.png`)});const end=await page.evaluate(()=>window.__yardFrame45.snapshot());await Promise.all(pending);
 expect(end.errors).toEqual([]);expect(errors).toEqual([]);expect(end.sourceFrame).toBe(101);expect(end.sourceTimeMs).toBe(4000);expect(end.clockAdvances).toBe(false);expect(end.draws.every(r=>r.sourceFrame===101&&r.sourceTimeMs===4000)).toBe(true);expect(end.peakBytes).toBeLessThanOrEqual(32*1048576);expect(end.current.mediaBytes).toBe(8266616);expect(end.current.foliageCount).toBeGreaterThan(30);
 expect(requests.every(r=>r.method==='GET'&&new URL(r.url).origin==='http://127.0.0.1:4318'&&!new URL(r.url).pathname.startsWith('/api/'))).toBe(true);expect(http.every(r=>r.status===200&&r.sha256===r.expectedSha256)).toBe(true);const paths=new Set(http.map(r=>r.path));for(const row of manifest.files.filter(r=>r.path.endsWith('.webp')))expect(paths.has('/'+row.path)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }finally{await Promise.allSettled(pending);const evidence=await page.evaluate(()=>window.__yardFrame45?.snapshot()).catch(e=>({captureError:String(e)}));await writeFile(info.outputPath('source-media-projection-budget.json'),JSON.stringify({scope:'one static source-rendered frame; no animation/eight-actor/live-API acceptance',viewport:spec,commit:process.env.GITHUB_SHA||null,payloadManifestSha256:hash(manifestBytes),evidence,http,requests,errors},null,2));}
});});
test('portrait to landscape resize keeps the source pose and accounts for transient canvases',async({page},info)=>{await page.setViewportSize({width:390,height:844});await page.goto('/preview/yard-coherent-frame/');await page.waitForFunction(()=>window.__yardFrame45?.snapshot().ready);await page.setViewportSize({width:844,height:390});await page.waitForFunction(()=>window.__yardFrame45.snapshot().current.preset==='landscape754');const s=await page.evaluate(()=>window.__yardFrame45.snapshot());expect(s.errors).toEqual([]);expect(s.current.scene.width).toBe(754);expect(s.current.scene.height).toBe(302);expect(s.sourceFrame).toBe(101);expect(s.peakBytes).toBeLessThanOrEqual(32*1048576);await page.locator('canvas').screenshot({path:info.outputPath('resized-landscape-canvas.png')});await writeFile(info.outputPath('resize-evidence.json'),JSON.stringify(s,null,2));});
test('late real bitmap closes after disposal and never draws',async({page},info)=>{await page.addInitScript(()=>{const original=createImageBitmap;window.__late={started:0,closed:0};window.createImageBitmap=async(...args)=>{const im=await original(...args),close=im.close.bind(im);im.close=()=>{window.__late.closed++;close();};window.__late.started++;await new Promise(r=>window.__release=r);return im;};});try{await page.goto('/preview/yard-coherent-frame/',{waitUntil:'commit'});await page.waitForFunction(()=>window.__late.started===1);await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await page.evaluate(()=>window.__release());await page.waitForFunction(()=>window.__late.closed===1);const result=await page.evaluate(()=>({bitmap:window.__late,snapshot:window.__yardFrame45.snapshot()}));expect(result.bitmap).toEqual({started:1,closed:1});expect(result.snapshot.ready).toBe(false);expect(result.snapshot.disposed).toBe(true);expect(result.snapshot.draws).toEqual([]);await writeFile(info.outputPath('late-bitmap-evidence.json'),JSON.stringify(result,null,2));}finally{await page.evaluate(()=>window.__release?.()).catch(()=>{});}});
