/** Shared Canvas2D composition. Browser and local authoring call this same function.
 * No DOM, clock, fetch, persistence or saved-coordinate mutation. */
import {sceneLayout,frameRect,foliagePlacements,coverRect} from './model.mjs';
export function appendPolygons(ctx,polys){for(const p of polys){p.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();}}
const bounds=polys=>{const pts=polys.flat();return{x:Math.min(...pts.map(p=>p.x)),y:Math.min(...pts.map(p=>p.y)),width:Math.max(...pts.map(p=>p.x))-Math.min(...pts.map(p=>p.x)),height:Math.max(...pts.map(p=>p.y))-Math.min(...pts.map(p=>p.y))};};
export function worldPresentation(base,factor){
 const b=bounds(base.maskPolygons),center={x:b.x+b.width/2,y:b.y+b.height/2};const point=p=>({x:center.x+(p.x-center.x)*factor,y:center.y+(p.y-center.y)*factor});const box=b=>({...b,...point(b),width:b.width*factor,height:b.height*factor});
 return{...base,worldScale:factor,projection:{...base.projection,ppu:base.projection.ppu*factor,project:p=>point(base.projection.project(p)),unproject:p=>base.projection.unproject({x:center.x+(p.x-center.x)/factor,y:center.y+(p.y-center.y)/factor})},architectureScale:base.architectureScale*factor,maskPolygons:base.maskPolygons.map(p=>p.map(point)),anchors:Object.fromEntries(Object.entries(base.anchors).map(([k,p])=>[k,point(p)])),gateHalves:base.gateHalves.map(box),gateBounds:box(base.gateBounds),gateOpening:base.gateOpening*factor,visualPassage:box(base.visualPassage),entryClearance:base.entryClearance.map(point),bowlExclusion:base.bowlExclusion.map(point),door:box(base.door),facade:box(base.facade)};
}
export function createCottageLayer(image,createSurface){
 const layer=createSurface(448,448),mask=createSurface(448,448),m=mask.getContext('2d');m.fillStyle='#fff';m.shadowColor='#fff';m.shadowBlur=8;m.beginPath();const pts=[[0,0],[142,0],[150,50],[191,66],[287,165],[310,235],[357,274],[385,357],[327,409],[220,430],[80,408],[0,369]];pts.forEach(([x,y],i)=>i?m.lineTo(x,y):m.moveTo(x,y));m.closePath();m.fill();const c=layer.getContext('2d');c.drawImage(image,0,0,448,448,0,0,448,448);c.globalCompositeOperation='destination-in';c.drawImage(mask,0,0);c.globalCompositeOperation='source-over';return layer;
}
function sparseClusters(layout){const r=layout.architectureScale,up=layout.anchors.upstreamBoundary,gap=layout.gateOpening,ownWidth=52*r;return[-1,1].map(sign=>({x:up.x+sign*(gap/2+ownWidth*.60)-ownWidth/2,y:up.y+7*r,width:ownWidth,height:ownWidth*98/256}));}
export function drawComposition(ctx,images,input,frame,width,height,{dpr=1,guides=false,variant='baseline',showGate=true,staticProps=[]}={}){
 ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);const original=sceneLayout(input,width,height),layout=variant==='baseline'?original:worldPresentation(original,.90);let plate=images.get('plate'),bg=coverRect(width,height,plate.width,plate.height),facade=layout.facade,door=layout.door;
 if(variant==='cottage10'&&width<=height){plate=images.get('plate10');const s=Math.max(width/plate.width,height/plate.height)*1.35;bg={x:0,y:0,width:plate.width*s,height:plate.height*s,scale:s};door={x:113*s,y:218*s,width:74*s,height:117*s};facade=null;}
 if(variant==='fuller15'){const ratio=(input.backgroundArchitecturePpuByPreset?.[layout.preset]??layout.projection.ppu)/(30.96409928478869*.90),s=.14*ratio;facade={x:-4*ratio,y:-3*ratio,width:images.get('facade').width*s/.25,height:images.get('facade').height*s/.25};door={x:facade.x+354*s,y:facade.y+260*s,width:535*s,height:922*s};}
 ctx.drawImage(plate,bg.x,bg.y,bg.width,bg.height);
 let foliage;
 if(variant==='baseline'){
  foliage=foliagePlacements(layout);const border=images.get('border');ctx.save();ctx.beginPath();ctx.rect(0,0,width,height);appendPolygons(ctx,layout.maskPolygons);ctx.clip('evenodd');ctx.beginPath();ctx.rect(0,0,width,height);const p=layout.visualPassage;ctx.rect(p.x,p.y,p.width,p.height);ctx.clip('evenodd');for(const r of foliage)ctx.drawImage(border,r.x,r.y,r.width,r.height);ctx.restore();
 }else{foliage=showGate?sparseClusters(layout):[];for(const r of foliage)ctx.drawImage(images.get('border'),r.x,r.y,r.width,r.height);}
 if(variant==='cottage10'&&width>height){const ratio=(input.backgroundArchitecturePpuByPreset?.[layout.preset]??layout.projection.ppu)/(30.96409928478869*.90),s=(648/1536)*1.35*ratio;facade={x:0,y:0,width:448*s,height:448*s};ctx.drawImage(images.get('cottageLayer'),0,0,facade.width,facade.height);door={x:113*s,y:218*s,width:74*s,height:117*s};}
 else if(facade)ctx.drawImage(images.get('facade'),facade.x,facade.y,facade.width,facade.height);
 if(showGate)for(const g of layout.gateHalves)ctx.drawImage(images.get(g.id==='left'?'gateLeft':'gateRight'),g.x,g.y,g.width,g.height);
 const sprite=frameRect(frame,layout);const drawables=[{id:'basil-fountain',imageId:'subject',...sprite}];
 for(const prop of staticProps){const pivot=layout.projection.project({x:prop.placementWorldXY[0],y:prop.placementWorldXY[1]}),scale=layout.projection.ppu/prop.pixelsPerWorld;drawables.push({id:prop.id,imageId:prop.imageId??prop.id,x:pivot.x-prop.pivotPx[0]*scale,y:pivot.y-prop.pivotPx[1]*scale,width:prop.canvas[0]*scale,height:prop.canvas[1]*scale,scale,pivot});}
 drawables.sort((a,b)=>a.pivot.y-b.pivot.y);for(const r of drawables)ctx.drawImage(images.get(r.imageId),r.x,r.y,r.width,r.height);
 if(guides){ctx.save();ctx.strokeStyle='rgba(255,255,230,.6)';ctx.lineWidth=1;ctx.beginPath();appendPolygons(ctx,layout.maskPolygons);ctx.stroke();ctx.strokeStyle='#ffbd68';const p=layout.visualPassage;ctx.strokeRect(p.x,p.y,p.width,p.height);ctx.strokeStyle='#d6faff';if(door)ctx.strokeRect(door.x,door.y,door.width,door.height);ctx.font='11px system-ui';for(const[k,p]of Object.entries(layout.anchors)){ctx.beginPath();ctx.moveTo(p.x-5,p.y);ctx.lineTo(p.x+5,p.y);ctx.moveTo(p.x,p.y-5);ctx.lineTo(p.x,p.y+5);ctx.stroke();ctx.fillStyle='#fff9df';ctx.fillText(k,p.x+7,p.y-5);}ctx.restore();}
 return{variant,showGate,preset:layout.preset,width,height,dpr,ppu:layout.projection.ppu,worldScale:layout.worldScale??1,sourceFrame:frame.sourceFrame,sourceTimeMs:frame.sourceTimeMs,mask:bounds(layout.maskPolygons),maskPolygons:layout.maskPolygons,anchors:layout.anchors,sprite,drawables,plate:bg,facade,door,gateBounds:layout.gateBounds,gateOpening:layout.gateOpening,foliageCount:foliage.length,foliage,architectureScale:layout.architectureScale,drawCode:'composition-study.mjs:drawComposition',sourceSubjectPixelsUnchanged:true};
}
