/** Native purchase + actual durable outbox + real current Express/auth/PostgreSQL.
 * Only the old-v1 rejection uses the explicitly labelled pinned domain/HTTP fixture. */
import {test,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fixtureOwner,canonicalRows,economy,realMutation,ORIGIN} from './fixtures.mjs';
import {oldDomain} from './old-domain.mjs';
import {OUT,WORK,report,restoreEvidence,evidenceStatus,init,observe,boot,waitForYardReady,enter,scene,shot,capture,captureFailureDiagnostics,fonts,layout,checkLayout,closePanel,place,move,pickup,placedPanel} from './browser-helpers.mjs';
let owner;
test.beforeAll(async()=>{await fs.mkdir(OUT,{recursive:true});await fs.mkdir(WORK,{recursive:true});const prior=await fs.readFile(path.join(OUT,'browser.json'),'utf8').then(JSON.parse).catch(e=>{if(e.code==='ENOENT')return null;throw e;});restoreEvidence(report,prior,process.env.GITHUB_SHA);owner=await fixtureOwner();report.scope={fresh:'Purchase, native IndexedDB recovery, actual placement lifecycle and focused compact HUD.',historical:'db044 run37507167039 dynamic routes, cancellation, drag rotation, two raw clips and full eleven-viewport report; not rerun here.'};});
test.afterEach(async({},info)=>{if(info.status!=='passed'){const section=info.title.startsWith('independent')?'hud':'actions';report.sections[section]='failed';report.errors.push({type:'test-status',section,status:info.status,message:info.error?.message});}report.status=evidenceStatus(report);await fs.writeFile(path.join(OUT,'browser.json'),JSON.stringify(report,null,2)+'\n');});
test.afterAll(async()=>{try{await owner?.close();}catch(error){report.errors.push({type:'fixture-cleanup',message:String(error)});throw error;}finally{report.status=evidenceStatus(report);await fs.writeFile(path.join(OUT,'browser.json'),JSON.stringify(report,null,2)+'\n');}});
const pathname=r=>new URL(r.url()).pathname;
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});promise.catch(()=>{});return{promise,resolve,reject};};
async function context(browser,f,options={}){const {label='acquisition',language='ru',...opts}=options;const c=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,serviceWorkers:'block',...opts});await init(c,f,language);const p=await c.newPage();observe(p,label,['yard.buyGoodie']);await c.route(/^https?:\/\//,route=>{if(new URL(route.request().url()).origin===ORIGIN)return route.continue();report.errors.push({type:'external-request',url:route.request().url()});return route.abort('blockedbyclient');});try{await boot(p,f);await enter(p);await ready(p);return{c,p};}catch(error){await failure(p,label,error);await c.close();throw error;}}
async function failure(p,label,error){report.errors.push({type:label,message:String(error),stack:error.stack});await captureFailureDiagnostics(p,label+'-failure').catch(()=>{});await capture(p,label+'-failure').catch(()=>{});}
async function ready(p){await expect.poll(async()=>{const s=await scene(p);return s?.ready===true&&s.viewportBlocked===false&&s.lastFrame?.canonicalState==='ready';}).toBe(true);}
async function nativeOutbox(p,id){return p.evaluate(id=>new Promise((resolve,reject)=>{const key=`game_hub_yard_outbox_v2:${encodeURIComponent(id)}`;if(localStorage.getItem(key)!==null)return reject(Error('Native IndexedDB proof cannot use localStorage fallback'));const request=indexedDB.open('keyval-store');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result;const read=db.transaction('keyval','readonly').objectStore('keyval').get(key);read.onerror=()=>{db.close();reject(read.error);};read.onsuccess=()=>{db.close();resolve(read.result);};};}),id);}
async function shop(p){await p.locator('[data-nav-item="decor"]').click();await p.locator('[data-decor-tab="shop"]').click();await p.locator('.cy-catalog-choice[data-goodie-id="leaf_pot"]').click();await expect(p.locator('.cy-selected-actions')).toContainText('140');return p.locator('[data-yard-action="buy-goodie"]');}
async function emptyOutbox(p,f){await expect.poll(async()=>{const b=await nativeOutbox(p,f.id);return b?.accountId===f.id&&b.version===2&&b.items.length===0;}).toBe(true);}
function buyCommand(command,f){assert.equal(command.accountId,f.id);assert.equal(command.action,'yard.buyGoodie');assert.deepEqual(command.payload,{goodieId:'leaf_pot'});assert.match(command.clientActionId,/^yard-v2:[a-f0-9-]+$/);assert(!command.clientActionId.startsWith('yard-v2:canonical-v1/'));}
function receipt(saved,nonce){const r=saved._yardV2.runtime.commandReceipts[nonce];assert(r);assert.equal(r.action,'yard.buyGoodie');assert.equal(r.status,200);assert.equal(Object.values(saved._yardV2.runtime.commandReceipts).filter(r=>r.actionId===nonce).length,1);return r;}
async function savedRows(f,n){await expect.poll(async()=>canonicalRows(await owner.saved(f)).length).toBe(n);return canonicalRows(await owner.saved(f));}
async function visible(p,n){await expect.poll(async()=>{const s=await scene(p);return s.canonicalRecords.length===n&&JSON.stringify(s.canonicalRecords)===JSON.stringify(s.lastFrame.records);}).toBe(true);}
async function backend(p,browser){report.browserVersion=browser.version();report.renderingBackend=await p.locator('.cy-pip-direct-layer canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2');if(!gl)return{classification:'unavailable'};const d=gl.getExtension('WEBGL_debug_renderer_info'),vendor=gl.getParameter(d?d.UNMASKED_VENDOR_WEBGL:gl.VENDOR),renderer=gl.getParameter(d?d.UNMASKED_RENDERER_WEBGL:gl.RENDERER);return{vendor,renderer,version:gl.getParameter(gl.VERSION),classification:/swiftshader|llvmpipe|softpipe|software/i.test(vendor+' '+renderer)?'software-renderer-reported':'backend-not-classified'};});}

test('native genuine purchase, committed-loss recovery and placement lifecycle',async({browser})=>{
 test.setTimeout(115000);report.sections.actions='running';const errorStart=report.errors.length;let active;
 try{
  const f=await owner.seed({treats:280,pots:0});active=await context(browser,f);const {p}=active;await backend(p,browser);await capture(p,'acquisition-initial');const before=await owner.saved(f);assert.equal(before.yard.currencies.treats,280);assert.equal(before.yard.goodieInventory.leaf_pot??0,0);
  const commands=[],committed=deferred(),release=deferred();let firstReply;
  await p.route('**/api/player/mutate',async route=>{const command=route.request().postDataJSON();if(command.action!=='yard.buyGoodie')return route.continue();try{buyCommand(command,f);assert.equal(route.request().headers().authorization,`dev ${f.externalId}`);commands.push(command);if(commands.length===1){const response=await route.fetch();firstReply={status:response.status(),body:await response.json()};committed.resolve();await release.promise;return route.abort('failed');}return route.continue();}catch(error){committed.reject(error);throw error;}});
  const duplicate=p.waitForResponse(async r=>pathname(r)==='/api/player/mutate'&&r.request().postDataJSON()?.action==='yard.buyGoodie'&&r.status()===200&&(await r.json()).duplicate===true);duplicate.catch(()=>{});
  try{const button=await shop(p);await expect(button).toBeEnabled();await button.click();await committed.promise;assert.equal(firstReply.status,200);assert.equal(firstReply.body.duplicate,false);const held=await nativeOutbox(p,f.id);assert.equal(held.items.length,1);assert.equal(held.items[0].status,'sending');assert.equal(held.items[0].clientActionId,commands[0].clientActionId);assert.deepEqual(held.items[0].payload,{goodieId:'leaf_pot'});await expect(button).toBeDisabled();const saved=await owner.saved(f);assert.equal(saved.yard.currencies.treats,140);assert.equal(saved.yard.goodieInventory.leaf_pot,1);receipt(saved,commands[0].clientActionId);report.cases.push({name:'buy-real-commit-held',durable:held,balance:saved.yard.currencies.treats,owned:1});}finally{release.resolve();}
  const replay=await(await duplicate).json();assert.equal(replay.clientActionId,commands[0].clientActionId);assert(commands.length>=2);assert.equal(new Set(commands.map(c=>c.clientActionId)).size,1);await emptyOutbox(p,f);await expect(p.locator('.cy-wallet').first()).toHaveAttribute('title','140');await capture(p,'purchase-confirmed');await p.unroute('**/api/player/mutate');await closePanel(p);
  await place(p,98,118);await savedRows(f,1);await visible(p,1);assert.equal((await owner.saved(f)).yard.goodieInventory.leaf_pot??0,0);
  await waitForYardReady(p,f,()=>p.reload());await enter(p);await ready(p);await visible(p,1);await move(p,0,108,122);await expect.poll(async()=>Math.abs(canonicalRows(await owner.saved(f))[0].x-108)<.25).toBe(true);await pickup(p,0);await savedRows(f,0);await closePanel(p);await visible(p,0);
  const after=await owner.saved(f);assert.equal(after.yard.currencies.treats,140);assert.equal(after.yard.goodieInventory.leaf_pot,1);assert.equal(after._yardV2.version,2);const expected=economy(before);expected.currencies.treats=140;assert.deepEqual(economy(after),expected);report.cases.push({name:'genuine-buy-inventory-place-reload-move-pickup',nonce:commands[0].clientActionId,duplicate:replay.duplicate,balance:140,owned:1,receipt:receipt(after,commands[0].clientActionId)});

  // A second genuinely purchased pot commits on the active API, loses its reply,
  // then meets the pinned old domain. No endpoint or production state hook exists.
  const old=await oldDomain(),oldCommands=[],secondCommit=deferred(),secondRelease=deferred();let oldMode=false,secondReply;
  const oldSnapshot=async route=>{if(!oldMode)return route.continue();const response=await route.fetch();assert.equal(response.status(),200);const body=await response.json();assert.equal(body.player.id,f.id);assert.equal(route.request().headers().authorization,`dev ${f.externalId}`);const saved=await owner.saved(f);const envelope=structuredClone(body);body.yardRuntime=old.public(saved);const compared={...body,yardRuntime:envelope.yardRuntime};assert.deepEqual(compared,envelope,'Preserve every authenticated response field outside yardRuntime');return route.fulfill({response,json:body});};
  await p.route('**/api/player/snapshot*',oldSnapshot);
  await p.route('**/api/player/mutate',async route=>{const command=route.request().postDataJSON();if(command.action!=='yard.buyGoodie')return route.continue();buyCommand(command,f);assert.equal(route.request().headers().authorization,`dev ${f.externalId}`);oldCommands.push(command);if(oldCommands.length===1){try{const response=await route.fetch();secondReply=await response.json();assert.equal(response.status(),200);secondCommit.resolve();await secondRelease.promise;return route.abort('failed');}catch(error){secondCommit.reject(error);throw error;}}if(oldMode){const result=old.reject(await owner.saved(f),command);return route.fulfill({status:result.status,json:result.body});}return route.continue();});
  try{await(await shop(p)).click();await secondCommit.promise;assert.equal(secondReply.duplicate,false);assert.equal((await owner.saved(f)).yard.currencies.treats,0);assert.equal((await owner.saved(f)).yard.goodieInventory.leaf_pot,2);oldMode=true;}finally{secondRelease.resolve();}
  await expect.poll(async()=>{const b=await nativeOutbox(p,f.id);return b?.items[0]?.status;},{timeout:15000}).toBe('rollout-paused');const retained=await nativeOutbox(p,f.id);assert.equal(retained.items.length,1);assert.equal(retained.items[0].requiresYardResume,true);assert.equal(retained.items[0].blockedReason,'UNSUPPORTED_YARD_STORAGE_VERSION');assert.equal(retained.items[0].clientActionId,oldCommands[0].clientActionId);assert.deepEqual(retained.items[0].payload,{goodieId:'leaf_pot'});
  const oldRead=p.waitForResponse(r=>pathname(r)==='/api/player/snapshot'&&r.status()===200);await p.reload();assert.equal((await(await oldRead).json()).yardRuntime.error,'UNSUPPORTED_YARD_STORAGE_VERSION');const quarantine=p.locator('[data-yard-read-only="true"]');await expect(quarantine).toBeVisible();await expect(p.locator('.cy-app,.companion-yard-stage')).toHaveCount(0);const home=quarantine.getByRole('button',{name:'Вернуться к играм',exact:true});await expect(home).toBeEnabled();await reachable(home);await home.click({trial:true});await expect.poll(async()=>(await nativeOutbox(p,f.id))?.items[0]?.status).toBe('rollout-paused');const reloaded=await nativeOutbox(p,f.id);assert.deepEqual(reloaded.items,retained.items);await capture(p,'old-domain-quarantine');
  const resumed=p.waitForResponse(async r=>pathname(r)==='/api/player/mutate'&&r.request().postDataJSON()?.clientActionId===oldCommands[0].clientActionId&&r.status()===200&&(await r.json()).duplicate===true);resumed.catch(()=>{});oldMode=false;await p.unroute('**/api/player/snapshot*',oldSnapshot);await waitForYardReady(p,f,()=>p.reload());await expect(p.locator('[data-yard-read-only="true"]')).toHaveCount(0);await expect(p.locator('.cy-app[data-yard-version="persistent-mika-r1"]')).toBeVisible();const recovered=await(await resumed).json();await emptyOutbox(p,f);await expect(p.locator('.cy-wallet').first()).toHaveAttribute('title','0');assert(oldCommands.length>=3);for(const command of oldCommands)assert.deepEqual(command,oldCommands[0]);const final=await owner.saved(f);assert.equal(final.yard.currencies.treats,0);assert.equal(final.yard.goodieInventory.leaf_pot,2);assert.deepEqual(canonicalRows(final),canonicalRows(after));receipt(final,oldCommands[0].clientActionId);
  report.cases.push({name:'native-idb-committed-purchase-old-domain-reload-recovery',historicalRevision:old.revision,dependencyCount:old.dependencyCount,qualification:'Pinned old domain / HTTP interception, not an old Express deployment. Native IDB and current authenticated API/DB commit + duplicate recovery are real. Uncommitted loss and account switching are fresh source tests only.',retained,reloaded,nonce:oldCommands[0].clientActionId,duplicate:recovered.duplicate,balance:0,owned:2});await active.c.close();active=null;

  const poor=await owner.seed({treats:80,pots:0});active=await context(browser,poor,{label:'insufficient-funds'});let buys=0;active.p.on('request',r=>{if(pathname(r)==='/api/player/mutate'&&r.postDataJSON()?.action==='yard.buyGoodie')buys++;});const disabled=await shop(active.p);await expect(disabled).toBeDisabled();await expect(active.p.locator('.cy-selected-actions')).toContainText(/Не хватает лакомств/);await capture(active.p,'insufficient-funds');const unchanged=await owner.saved(poor);assert.equal(unchanged.yard.currencies.treats,80);assert.equal(unchanged.yard.goodieInventory.leaf_pot??0,0);assert.equal(buys,0);report.cases.push({name:'real-80-treat-starter-cannot-buy-140-pot',balance:80,owned:0,requests:buys});
  assert(!report.console.entries.some(e=>e.type==='error'&&/THREE\.WebGLProgram|VALIDATE_STATUS|shader.*error|shader.*compile|WebGL.*INVALID_OPERATION/i.test(e.text)));assert(report.requests.every(r=>r.status<400),'Native requested asset failed');assert.equal(report.errors.length,errorStart,JSON.stringify(report.errors.slice(errorStart)));report.sections.actions='passed';
 }catch(error){report.sections.actions='failed';if(active)await failure(active.p,'acquisition',error);throw error;}finally{await active?.c.close();}
});

async function reachable(locator){await locator.scrollIntoViewIfNeeded();const state=await locator.evaluate(e=>{const b=e.getBoundingClientRect(),x=b.x+b.width/2,y=b.y+b.height/2,hit=document.elementFromPoint(x,y);return{rect:{x:b.x,y:b.y,w:b.width,h:b.height},center:{x,y},hit:!!hit&&(e===hit||e.contains(hit)),within:x>=0&&x<innerWidth&&y>=0&&y<innerHeight};});assert(state.within&&state.hit,'Actual card/control center must be uncovered and hittable');return state;}
async function compactOtherPanels(p,name){
 const result={};
 for(const panelName of ['food','guests']){
  await p.locator(`[data-nav-item="${panelName}"]`).click();await expect(p.locator('.cy-dialog[open]')).toBeVisible();
  const panel=p.locator('.cy-dialog > .cy-panel'),hits=[];
  const check=async locator=>{const hit=await reachable(locator);assert(hit.rect.w>=43&&hit.rect.h>=43,'Compact real control needs a practical tap target');hits.push(hit);};
  const scrollStart=await panel.evaluate(e=>({top:e.scrollTop,height:e.clientHeight,contentHeight:e.scrollHeight,overflow:getComputedStyle(e).overflowY}));
  if(panelName==='food'){
   await check(panel.locator('select').first());await expect(panel.locator('select').first()).toBeDisabled();
   for(const button of [panel.locator('button').first(),panel.locator('button').last()]){await check(button);await expect(button).toBeDisabled();}
  }else{
   const tabs=p.locator('.cy-guest-tabs button');for(let i=0;i<3;i++)await check(tabs.nth(i));
   await tabs.first().click();for(let i=0;i<2;i++){const button=panel.locator('button').nth(i);await check(button);await expect(button).toBeDisabled();}
   await capture(p,name+'-guests-visits');await tabs.nth(1).click();await expect(panel.locator('.cy-empty')).toBeVisible();
   await tabs.nth(2).click();await check(panel.locator('input'));await panel.locator('input').focus();await expect(panel.locator('input')).toBeFocused();await check(panel.locator('button.cy-wide').first());await expect(panel.locator('button.cy-wide').first()).toBeDisabled();
  }
  const scrollEnd=await panel.evaluate(e=>({top:e.scrollTop,height:e.clientHeight,contentHeight:e.scrollHeight,overflow:getComputedStyle(e).overflowY}));
  assert.equal(scrollEnd.overflow,'auto');if(panelName==='food'){assert(scrollEnd.contentHeight>scrollEnd.height);assert(scrollEnd.top>0,'Last real food action must be reachable through panel scrolling');}
  const close=p.locator('.cy-dialog > header button');await check(close);await capture(p,name+'-'+panelName);await closePanel(p);result[panelName]={scrollStart,scrollEnd,hits};
 }
 return result;
}
test('independent focused HUD and acquisition controls',async({browser,request})=>{
 test.setTimeout(85000);report.sections.hud='running';const start=report.errors.length;let active;
 try{const f=await owner.seed({treats:280,pots:2});await realMutation(request,f,'yard.placeGoodie',{slotId:'canonical:hud-one',goodieId:'leaf_pot',x:98,y:118});
  for(const [width,height,dpr,language]of[[320,568,1,'en'],[390,844,2,'ru'],[568,320,1,'en'],[568,320,1,'ru'],[844,390,1,'ru']]){const name=`hud-${width}x${height}-dpr${dpr}-${language}`;try{active=await context(browser,f,{label:name,viewport:{width,height},deviceScaleFactor:dpr,language});const{p}=active;const screen=await layout(p);checkLayout(screen);assert(screen.stage.w>=280&&screen.stage.h>=192);const font=await fonts(p,language);await capture(p,name);if(dpr>=2)await p.locator('.cy-header').screenshot({path:path.join(OUT,name+'-header-native.png')});
   await p.locator('[data-pip-control="inventory"]').click();await expect(p.locator('.cy-dialog[open]')).toBeVisible();await expect.poll(()=>p.locator('.cy-dialog').evaluate(e=>e.contains(document.activeElement))).toBe(true);const card=p.locator('.cy-catalog-choice[data-goodie-id="leaf_pot"]'),inventoryHit=await reachable(card);await card.click();const placeButton=p.locator('[data-yard-action="place"]'),placeHit=await reachable(placeButton);await expect(placeButton).toBeEnabled();const dialog=await layout(p);checkLayout(dialog);await capture(p,name+'-inventory');if(dpr>=2)await p.locator('.cy-dialog').screenshot({path:path.join(OUT,name+'-dialog-native.png')});await placeButton.click();await expect.poll(async()=>(await scene(p))?.itemEditing).toBe(true);await p.locator('[data-yard-action="cancel-placement"]').click();await expect.poll(async()=>(await scene(p))?.itemEditing).toBe(false);
   await placedPanel(p);const placedHits={};for(const action of['move','pickup']){const button=p.locator(`[data-yard-action="${action}"]`);placedHits[action]=await reachable(button);await expect(button).toBeEnabled();await button.click({trial:true});}const inspect=p.locator('[data-pip-control="inspect-selected"]');placedHits.inspect=await reachable(inspect);await expect(inspect).toBeEnabled();await inspect.click({trial:true});checkLayout(await layout(p));await capture(p,name+'-placed');await closePanel(p);
   const buy=await shop(p);const shopHit=await reachable(p.locator('.cy-catalog-choice[data-goodie-id="leaf_pot"]')),buyHit=await reachable(buy);await expect(buy).toBeEnabled();await buy.click({trial:true});checkLayout(await layout(p));await closePanel(p);const otherPanels=width===568&&height===320?await compactOtherPanels(p,name):null;await ready(p);const s=await scene(p);assert(!report.console.entries.some(e=>e.scope===name&&e.type==='error'&&/THREE\.WebGLProgram|VALIDATE_STATUS|shader.*error|shader.*compile|WebGL.*INVALID_OPERATION/i.test(e.text)));report.matrix.push({name,status:'passed',viewport:screen,font,dialog,inventoryHit,placeHit,placedHits,shopHit,buyHit,otherPanels,scene:{ready:s.ready,viewportBlocked:s.viewportBlocked,projection:s.projection}});
  }catch(error){report.matrix.push({name,status:'failed'});if(active)await failure(active.p,name,error);else report.errors.push({type:name,message:String(error)});}finally{await active?.c.close();active=null;}}
  if(report.requests.some(r=>r.status>=400))report.errors.push({type:'asset-request',message:'Native requested asset failed'});const errors=report.errors.slice(start);report.sections.hud=errors.length?'failed':'passed';assert.equal(errors.length,0,JSON.stringify(errors));
 }catch(error){report.sections.hud='failed';throw error;}finally{await active?.c.close();}
});
