/** UI-only native qualification over the real current Express/auth/PostgreSQL.
 * Prior acquisition proof remains historical; no wallet actions are repeated. */
import {test,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fixtureOwner,realMutation,ORIGIN} from './fixtures.mjs';
import {OUT,WORK,report,restoreEvidence,init,observe,boot,enter,scene,capture,captureFailureDiagnostics,fonts,layout,checkLayout,closePanel,placedPanel} from './browser-helpers.mjs';
import {auditDialogControls,reachableControl} from './scroll-reachability.mjs';
let owner,currentHudName;
function hudStatus(){return report.errors.length||report.sections.hud==='failed'?'FAILED_OR_INCOMPLETE':report.sections.hud==='passed'&&report.reusedAcquisition?.verified===true?'MECHANICAL_ACCEPTANCE_PASSED_VISUAL_REVIEW_PENDING':'INCOMPLETE';}

test.beforeAll(async()=>{await fs.mkdir(OUT,{recursive:true});await fs.mkdir(WORK,{recursive:true});const prior=await fs.readFile(path.join(OUT,'browser.json'),'utf8').then(JSON.parse).catch(e=>{if(e.code==='ENOENT')return null;throw e;});restoreEvidence(report,prior,process.env.GITHUB_SHA);const proof=JSON.parse(await fs.readFile(path.join(OUT,'reused.json'),'utf8'));assert.equal(proof.verified,true);assert.equal(proof.acquisition.sections.actions,'passed');report.sections.actions='reused';report.reusedAcquisition={runId:proof.runId,head:proof.base,verified:true,qualification:'Prior native purchase/recovery passed; no wallet action is repeated in this UI-only pass.'};report.controlAudits??=[];owner=await fixtureOwner();report.scope={fresh:'Every declared scroll item/action and strict fixed HUD controls on eleven viewport/locale tuples.',historical:'770a acquisition passed; its HUD failed. db044 dynamic route clips and full eleven-viewport status remain historical.'};});
test.afterEach(async({},info)=>{if(info.status!=='passed'){const section=info.title.startsWith('independent')?'hud':'actions';report.sections[section]='failed';report.errors.push({type:'test-status',section,status:info.status,message:info.error?.message});}report.status=hudStatus();await fs.writeFile(path.join(OUT,'browser.json'),JSON.stringify(report,null,2)+'\n');});
test.afterAll(async()=>{try{await owner?.close();}catch(error){report.errors.push({type:'fixture-cleanup',message:String(error)});throw error;}finally{report.status=hudStatus();await fs.writeFile(path.join(OUT,'browser.json'),JSON.stringify(report,null,2)+'\n');}});
async function context(browser,f,options={}){const {label='hud',language='ru',...opts}=options;const c=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,serviceWorkers:'block',...opts});await init(c,f,language);const p=await c.newPage();observe(p,label);await c.route(/^https?:\/\//,route=>{if(new URL(route.request().url()).origin===ORIGIN)return route.continue();report.errors.push({type:'external-request',url:route.request().url()});return route.abort('blockedbyclient');});try{await boot(p,f);await enter(p);await ready(p);return{c,p};}catch(error){await failure(p,label,error);await c.close();throw error;}}
async function failure(p,label,error){report.errors.push({type:label,message:String(error),stack:error.stack});await captureFailureDiagnostics(p,label+'-failure').catch(()=>{});await capture(p,label+'-failure').catch(()=>{});}
async function ready(p){await expect.poll(async()=>{const s=await scene(p);return s?.ready===true&&s.viewportBlocked===false&&s.lastFrame?.canonicalState==='ready';}).toBe(true);}
async function shop(p){await p.locator('[data-nav-item="decor"]').click();await p.locator('[data-decor-tab="shop"]').click();await p.locator('.cy-catalog-choice[data-goodie-id="leaf_pot"]').click();await expect(p.locator('.cy-selected-actions')).toContainText('140');return p.locator('[data-yard-action="buy-goodie"]');}
async function backend(p,browser){report.browserVersion=browser.version();report.renderingBackend=await p.locator('.cy-pip-direct-layer canvas').evaluate(canvas=>{const gl=canvas.getContext('webgl2');if(!gl)return{classification:'unavailable'};const d=gl.getExtension('WEBGL_debug_renderer_info'),vendor=gl.getParameter(d?d.UNMASKED_VENDOR_WEBGL:gl.VENDOR),renderer=gl.getParameter(d?d.UNMASKED_RENDERER_WEBGL:gl.RENDERER);return{vendor,renderer,version:gl.getParameter(gl.VERSION),classification:/swiftshader|llvmpipe|softpipe|software/i.test(vendor+' '+renderer)?'software-renderer-reported':'backend-not-classified'};});}

async function reachable(locator){const record={label:currentHudName,phase:'pre-audit control',locator:String(locator)};report.controlAudits.push(record);await reachableControl(locator,record);return{...record.after,before:record.before};}
async function compactOtherPanels(p,name){
 const result={};
 for(const panelName of ['food','guests']){
  await p.locator(`[data-nav-item="${panelName}"]`).click();await expect(p.locator('.cy-dialog[open]')).toBeVisible();
  const panel=p.locator('.cy-dialog > .cy-panel'),hits=[];
  const check=async locator=>{const hit=await reachable(locator);assert(hit.rect.w>=43&&hit.rect.h>=43,'Compact real control needs a practical tap target');hits.push(hit);};
  const audit=await auditDialogControls(p,name+'-'+panelName,report.controlAudits);const scrollStart=await panel.evaluate(e=>({top:e.scrollTop,height:e.clientHeight,contentHeight:e.scrollHeight,overflow:getComputedStyle(e).overflowY}));
  if(panelName==='food'){
   await check(panel.locator('select').first());await expect(panel.locator('select').first()).toBeDisabled();
   for(const button of [panel.locator('button').first(),panel.locator('button').last()]){await check(button);await expect(button).toBeDisabled();}
  }else{
   const tabs=p.locator('.cy-guest-tabs button');for(let i=0;i<3;i++)await check(tabs.nth(i));
   await tabs.first().click();for(let i=0;i<2;i++){const button=panel.locator('button').nth(i);await check(button);await expect(button).toBeDisabled();}
   await capture(p,name+'-guests-visits');await tabs.nth(1).click();await expect(panel.locator('.cy-empty')).toBeVisible();await auditDialogControls(p,name+'-guests-album',report.controlAudits);
   await tabs.nth(2).click();await auditDialogControls(p,name+'-guests-helper',report.controlAudits);await check(panel.locator('input'));await panel.locator('input').focus();await expect(panel.locator('input')).toBeFocused();await check(panel.locator('button.cy-wide').first());await expect(panel.locator('button.cy-wide').first()).toBeDisabled();
  }
  const scrollEnd=await panel.evaluate(e=>({top:e.scrollTop,height:e.clientHeight,contentHeight:e.scrollHeight,overflow:getComputedStyle(e).overflowY}));
  assert.equal(scrollEnd.overflow,'auto');if(panelName==='food'){assert(scrollEnd.contentHeight>scrollEnd.height);assert(scrollEnd.top>0,'Last real food action must be reachable through panel scrolling');}
  const close=p.locator('.cy-dialog > header button');await check(close);await capture(p,name+'-'+panelName);await closePanel(p);result[panelName]={auditLabel:audit.label,scrollStart,scrollEnd,hits};
 }
 return result;
}
test('independent exhaustive HUD scroll qualification',async({browser,request})=>{
 test.setTimeout(200000);report.sections.hud='running';const hudStartedAt=Date.now();const start=report.errors.length;let active;
 try{const f=await owner.seed({treats:280,pots:2});await realMutation(request,f,'yard.placeGoodie',{slotId:'canonical:hud-one',goodieId:'leaf_pot',x:98,y:118});
  for(const [width,height,dpr,language,deviceClass]of[[320,568,1,'en','phone'],[360,800,1,'ru','phone'],[390,844,2,'ru','phone'],[414,896,1,'ru','phone'],[568,320,1,'en','phone'],[568,320,1,'ru','phone'],[844,390,1,'ru','phone'],[768,1024,1,'en','tablet'],[1024,768,1,'ru','tablet'],[1280,720,1,'en','desktop'],[375,812,1,'en','phone']]){const name=`hud-${width}x${height}-dpr${dpr}-${language}`,startedAt=Date.now();currentHudName=name;try{active=await context(browser,f,{label:name,viewport:{width,height},deviceScaleFactor:dpr,language,isMobile:deviceClass!=='desktop',hasTouch:deviceClass!=='desktop'});const{p}=active;await backend(p,browser);const screen=await layout(p);checkLayout(screen);assert(screen.stage.w>=280&&screen.stage.h>=192);const font=await fonts(p,language);await capture(p,name);if(dpr>=2)await p.locator('.cy-header').screenshot({path:path.join(OUT,name+'-header-native.png')});
   await p.locator('[data-pip-control="inventory"]').click();await expect(p.locator('.cy-dialog[open]')).toBeVisible();await expect.poll(()=>p.locator('.cy-dialog').evaluate(e=>e.contains(document.activeElement))).toBe(true);const card=p.locator('.cy-catalog-choice[data-goodie-id="leaf_pot"]'),inventoryHit=await reachable(card);await card.click();const placeButton=p.locator('[data-yard-action="place"]'),placeHit=await reachable(placeButton);await expect(placeButton).toBeEnabled();const dialog=await layout(p);await auditDialogControls(p,name+'-inventory',report.controlAudits);await capture(p,name+'-inventory');if(dpr>=2)await p.locator('.cy-dialog').screenshot({path:path.join(OUT,name+'-dialog-native.png')});await placeButton.click();await expect.poll(async()=>(await scene(p))?.itemEditing).toBe(true);await p.locator('[data-yard-action="cancel-placement"]').click();await expect.poll(async()=>(await scene(p))?.itemEditing).toBe(false);
   await placedPanel(p);const placedHits={};for(const action of['move','pickup']){const button=p.locator(`[data-yard-action="${action}"]`);placedHits[action]=await reachable(button);await expect(button).toBeEnabled();await button.click({trial:true});}const inspect=p.locator('[data-pip-control="inspect-selected"]');placedHits.inspect=await reachable(inspect);await expect(inspect).toBeEnabled();await inspect.click({trial:true});await auditDialogControls(p,name+'-placed',report.controlAudits);await capture(p,name+'-placed');await closePanel(p);
   const buy=await shop(p);const shopHit=await reachable(p.locator('.cy-catalog-choice[data-goodie-id="leaf_pot"]')),buyHit=await reachable(buy);await expect(buy).toBeEnabled();await buy.click({trial:true});await auditDialogControls(p,name+'-shop',report.controlAudits);await capture(p,name+'-shop-scroll-end');await closePanel(p);const otherPanels=width===568&&height===320?await compactOtherPanels(p,name):null;await ready(p);const s=await scene(p);assert(!report.console.entries.some(e=>e.scope===name&&e.type==='error'&&/THREE\.WebGLProgram|VALIDATE_STATUS|shader.*error|shader.*compile|WebGL.*INVALID_OPERATION/i.test(e.text)));report.matrix.push({name,status:'passed',deviceClass,isMobile:deviceClass!=='desktop',hasTouch:deviceClass!=='desktop',elapsedMs:Date.now()-startedAt,viewport:screen,font,dialog,inventoryHit,placeHit,placedHits,shopHit,buyHit,otherPanels,scene:{ready:s.ready,viewportBlocked:s.viewportBlocked,projection:s.projection}});
  }catch(error){report.matrix.push({name,status:'failed',deviceClass,elapsedMs:Date.now()-startedAt});if(active)await failure(active.p,name,error);else report.errors.push({type:name,message:String(error)});}finally{await active?.c.close();active=null;}}
  if(report.requests.some(r=>r.status>=400))report.errors.push({type:'asset-request',message:'Native requested asset failed'});const errors=report.errors.slice(start);report.sections.hud=errors.length?'failed':'passed';assert.equal(errors.length,0,JSON.stringify(errors));
 }catch(error){report.sections.hud='failed';throw error;}finally{await active?.c.close();report.hudElapsedMs=Date.now()-hudStartedAt;}
});
