import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import {here,resolveSource,sourceRoot,assetRoot,pip} from './config.mjs';
const load=relative=>import(pathToFileURL(resolveSource(relative)));
const player=JSON.parse(fs.readFileSync(process.env.QUALIFIED_PLAYER||path.join(sourceRoot,'test-results/saved-visit/qualified-player.json')));
const plan=JSON.parse(fs.readFileSync(path.join(here,'qualified-plan.json')));
const record=player._yardV2.runtime.canonicalVisits[plan.visitId];
assert.equal(record.status,'active');assert.equal(record.releaseAt,plan.releaseAt);
assert.equal(record.original.motionSeed,plan.inspectionPlan.motionSeed);
const {digest}=await load('game-logic/yard-v2/util.mjs');
assert.equal(record.proposal.presentationHash,digest(plan),'Supplied plan must match genuine saved proposal');
const rows=player._yardV2.runtime.canonicalPlacements;
assert.deepEqual(rows,record.proposal.after.rows);
const {selectCanonicalFoodState}=await load('game-logic/yard-v2/canonical-food-contract.mjs');
const snapshot=JSON.parse(fs.readFileSync(process.env.QUALIFIED_SNAPSHOT||path.join(sourceRoot,'test-results/saved-visit/qualified-snapshot.json')));
assert.equal(snapshot.yardRuntime.storageVersion,3);
assert.equal(snapshot.yardRuntime.canonicalVisitProtocol,'yard-canonical-authoritative/v1');
assert.equal(snapshot.yardRuntime.mutable,false);
assert.deepEqual(snapshot.yardRuntime.canonicalPlacements,rows);
assert.deepEqual(snapshot.yard.bowls,player.yard.bowls);
const foodSelection=selectCanonicalFoodState(snapshot);
assert.equal(foodSelection.state,player.yard.bowls[0].foodId);
fs.writeFileSync(path.join(here,'food-selector-result.json'),JSON.stringify({selection:foodSelection,expectedFoodId:player.yard.bowls[0].foodId,actualUses:rows[0].uses,storageVersion:snapshot.yardRuntime.storageVersion,canonicalVisitProtocol:snapshot.yardRuntime.canonicalVisitProtocol,passed:foodSelection.state===player.yard.bowls[0].foodId},null,2)+'\n');
fs.writeFileSync(path.join(here,'qualified-inputs.json'),JSON.stringify({notice:'Exact source-generated v3 reconciler projection after genuine committed local admission and replay; not a released API or integrated gameplay-host result.',visitId:plan.visitId,record,rows,snapshot},null,2)+'\n');
const phase=plan.inspectionPlan.phases;const gesture=kind=>plan.inspectionPlan.episodes.find(e=>e.kind===kind);const middle=e=>(e.startMs+e.endMs)/2;
const samples=[['before-arrival',plan.arrivedAt-1],['entrance-early',plan.arrivedAt+600],['entrance-mid',middle(phase[0])],['entrance-end',phase[0].endMs-1],['approach-mid',middle(phase[1])],['peek',middle(phase[2])],['quiet-rest',phase[3].startMs+12000],...['leaf-look','ear-listen','curiosity-tilt'].map(kind=>[kind,middle(gesture(kind))]),['before-retreat',plan.retreatAt-1],['retreat-start',plan.retreatAt],['retreat-mid',(plan.retreatAt+plan.releaseAt)/2],['before-release',plan.releaseAt-1],['at-release',plan.releaseAt],['neutral-rest',(plan.releaseAt+plan.departureAt)/2],['exit-start',plan.departureAt],['exit-mid',(plan.departureAt+plan.leavesAt)/2],['before-departure',plan.leavesAt-1],['departed',plan.leavesAt]];
const clips=[{name:'entrance-approach-peek',from:plan.arrivedAt-500,to:phase[2].endMs+1500},...['leaf-look','ear-listen','curiosity-tilt'].map(kind=>({name:kind,from:gesture(kind).startMs-1000,to:gesture(kind).endMs+1000})),{name:'retreat-release-neutral',from:plan.retreatAt-1500,to:plan.releaseAt+3000},{name:'neutral-rest',from:(plan.releaseAt+plan.departureAt)/2,to:(plan.releaseAt+plan.departureAt)/2+6000},{name:'exit',from:plan.departureAt-1000,to:plan.leavesAt+1000}].map(c=>({...c,rate:1}));
fs.writeFileSync(path.join(here,'capture-plan.json'),JSON.stringify({visitId:plan.visitId,samples,clips,viewports:[{width:320,height:568,deviceScaleFactor:1},{width:390,height:844,deviceScaleFactor:2},{width:844,height:390,deviceScaleFactor:1}],scope:'Isolated actual renderer at canonical gameplay density. No app HUD or full browser UI acceptance. Sampled native 1x segments, not continuous 45-minute validation.'},null,2)+'\n');
const assets=['assets/pip.glb','assets/planter-t2.glb','assets/clean-garden.png','assets/food-r2/yard-food-source-r2.glb'];
const hashes=assets.map(name=>{const relative=pip+name,data=fs.readFileSync(resolveSource(relative)),expected=execFileSync('git',['-C',assetRoot,'rev-parse',`9b6b96b4:${relative}`],{encoding:'utf8'}).trim(),actual=createHash('sha1').update(Buffer.from(`blob ${data.length}\0`)).update(data).digest('hex');assert.equal(actual,expected,relative);return {path:relative,bytes:data.length,gitBlob:actual,sha256:createHash('sha256').update(data).digest('hex'),exactLiveMatch:true};});
assert.equal(hashes[0].sha256,plan.source.modelSha256);
fs.writeFileSync(path.join(here,'asset-provenance.json'),JSON.stringify({commit:'9b6b96b4cd1b019d016a741f7300e3172192c3ee',artChanged:false,assets:hashes},null,2)+'\n');
console.log(JSON.stringify({visitId:plan.visitId,food:selectCanonicalFoodState(snapshot),rows:rows.length,samples:samples.length,clips:clips.length,assetHashes:hashes.length}));
