import {test,expect} from '@playwright/test';import {mkdir,writeFile} from 'node:fs/promises';import path from 'node:path';
const out=path.join(process.cwd(),'test-results-yard-eight/compact'),save=async(name,data)=>{await mkdir(out,{recursive:true});await writeFile(path.join(out,name),data);};
const viewports=[[320,568,1],[360,800,1],[390,844,1],[414,896,1],[568,320,1],[844,390,1],[768,1024,1],[1024,768,1],[1280,720,1],[393,873,2]];
async function open(page,base,actor='willow',suffix=''){await page.goto(`${base}/__yard_qa__/index.html?actor=${actor}${suffix}`);await page.waitForFunction(()=>window.yardQA?.ready);}
async function painted(page,at){await page.waitForFunction(at=>{const d=window.yardQA?.diagnostics();return d?.ready&&d.view?.now===at&&!d.pendingResize;},at);return page.evaluate(()=>window.yardQA.diagnostics());}
function check(d){expect(d.errors).toEqual([]);expect(d.horizontalOverflow).toBe(false);expect(d.releaseAccepted).toBe(false);expect(d.targetInstances).toBe(1);expect(d.pendingDecodes).toBeLessThanOrEqual(1);expect(d.retainedPages).toBeLessThanOrEqual(16);expect(d.globalDecodedBudget.totalBytes).toBeLessThanOrEqual(64*1048576);expect(d.globalDecodedBudget.peakBytes).toBeLessThanOrEqual(64*1048576);expect(d.globalDecodedBudget.maxConcurrentDecodes).toBeLessThanOrEqual(1);expect(d.globalDecodedBudget.heldFrameAdditionalBytes).toBe(0);expect(d.globalDecodedBudget.backgroundBytes).toBeGreaterThan(0);for(const b of d.buttons){expect(b.width).toBeGreaterThanOrEqual(44);expect(b.height).toBeGreaterThanOrEqual(44);}}
for(const[width,height,dpr]of viewports)test(`Actual native roster ${width}x${height} DPR ${dpr}`,async({browser},info)=>{
 test.setTimeout(180000);const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:dpr,isMobile:width<1100,hasTouch:width<1100}),page=await context.newPage(),errors=[],rows=[];page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
 try{await open(page,info.project.use.baseURL);const ids=await page.evaluate(()=>Object.keys(window.yardQA.fixture.actors));
 for(const id of ids){await page.evaluate(id=>window.yardQA.select(id),id);const a=await page.evaluate(()=>window.yardQA.fixture.actors[window.yardQA.actor()]);
  for(const key of ['approach','turn','entry','rest','wake','exit','leaving','finished']){await page.evaluate(at=>window.yardQA.seek(at),a.times[key]);const d=await painted(page,a.times[key]);check(d);if(key==='finished'){expect(d.view.pets).toHaveLength(0);expect(d.view.pendingGifts).toHaveLength(1);}else{expect(d.view.pets).toHaveLength(1);expect(d.view.pets[0].actorProfile.id).toBe(id);expect(d.view.pendingGifts).toHaveLength(0);}rows.push({id,phase:key,at:a.times[key],nativeSeed:a.seed,pet:d.view.pets[0]||null,props:d.view.props,budget:d.globalDecodedBudget,projection:d.projection});if(['entry','rest','exit'].includes(key)){const png=await page.screenshot();await save(`${width}x${height}-dpr${dpr}-${id}-${key}.png`,png);}}
 }
 await page.evaluate(()=>window.yardQA.select('sage'));const at=await page.evaluate(()=>window.yardQA.fixture.actors.sage.times.approach);check(await painted(page,at));await page.setViewportSize({width:height,height:width});await page.waitForFunction(()=>{const d=window.yardQA.diagnostics();return !d.pendingResize&&d.projection.width===d.canvasBounds.width&&d.projection.height===d.canvasBounds.height;});check(await page.evaluate(()=>window.yardQA.diagnostics()));await page.setViewportSize({width,height});await page.reload();await page.waitForFunction(()=>window.yardQA?.ready);expect(errors).toEqual([]);await save(`${width}x${height}-dpr${dpr}.json`,JSON.stringify({scope:'Eight native single-species witnesses in the actual shared scene; joint acceptance is separate.',rows},null,2));
 }finally{await context.close();}
});
test('closed production profiles fetch no family source pixels and preserve unrenderable saved visits',async({page},info)=>{
 const requests=[];page.on('request',r=>{if(/\/assets\/yard-(family|fox|turtles)\//.test(r.url()))requests.push(r.url());});await open(page,info.project.use.baseURL,'willow','&mode=closed');const at=await page.evaluate(()=>window.yardQA.fixture.actors.willow.times.approach),d=await painted(page,at);expect(d.view.pets).toHaveLength(0);expect(d.view.legacy).toHaveLength(1);expect(d.errors).toEqual([]);expect(requests).toEqual([]);
});
for(const first of ['pip','pebble'])test(`${first} first actual native joint visits keep exact owners and global pixels with eight registered profiles`,async({page},info)=>{
 await open(page,info.project.use.baseURL);await page.evaluate(id=>window.yardQA.select(id),`${first}-first`);const a=await page.evaluate(()=>window.yardQA.fixture.joint[window.yardQA.actor()]),rows=[];
 for(const at of [...new Set([a.times.approach,a.times.rest,a.times.firstRelease-1,a.times.firstRelease,a.times.firstRelease+1,a.times.firstCompletion-1,a.times.firstCompletion,a.times.firstCompletion+1,a.times.finished])].sort((a,b)=>a-b)){
  await page.evaluate(at=>window.yardQA.seek(at),at);const d=await painted(page,at);expect(d.errors).toEqual([]);expect(d.globalDecodedBudget.totalBytes).toBeLessThanOrEqual(64*1048576);expect(d.globalDecodedBudget.peakBytes).toBeLessThanOrEqual(64*1048576);expect(d.globalDecodedBudget.maxConcurrentDecodes).toBeLessThanOrEqual(1);expect(d.propInstances).toEqual({leaf:1,snack:1});expect(d.releaseAccepted).toBe(false);
  expect(d.view.pets.length).toBe(at<a.times.firstCompletion?2:at<a.times.finished?1:0);expect(d.view.pendingGifts.length).toBe(at<a.times.firstCompletion?0:at<a.times.finished?1:2);rows.push({at,pets:d.view.pets,props:d.view.props,pendingGifts:d.view.pendingGifts,budget:d.globalDecodedBudget});
  if(at===a.times.rest||at===a.times.firstRelease)await save(`joint-${first}-${at===a.times.rest?'rest':'release'}.png`,await page.screenshot());
 }
 await save(`joint-${first}.json`,JSON.stringify({scope:'Actual two-visitor native mixed witness; all eight registered. Does not establish maximal eight-species joint acceptance.',seed:a.seed,rows},null,2));
});
test('actual failed family still decode closes owned images on disposal without exceeding the global budget',async({page},info)=>{
 await page.route('**/assets/yard-fox/shared-props/moon/**',r=>r.abort('failed'));await open(page,info.project.use.baseURL);const d=await page.evaluate(()=>window.yardQA.diagnostics());expect(d.ready).toBe(false);expect(d.errors.length).toBeGreaterThan(0);expect(d.globalDecodedBudget.totalBytes).toBeLessThanOrEqual(64*1048576);expect(d.globalDecodedBudget.maxConcurrentDecodes).toBeLessThanOrEqual(1);expect(d.pendingDecodes).toBe(0);expect(d.globalDecodedBudget.stillPendingBytes).toBe(0);
 await page.evaluate(()=>window.yardQA.dispose());const disposed=await page.evaluate(()=>window.yardQA.diagnostics());expect(disposed.decodedBytesEstimate).toBe(0);expect(disposed.globalDecodedBudget.stillBytes).toBe(0);expect(disposed.globalDecodedBudget.bitmapOwners).toBe(0);expect(disposed.pendingDecodes).toBe(0);await save('family-decode-error-disposal.json',JSON.stringify({before:d,after:disposed},null,2));
});
test('oversized family canvas explicitly rejects resize, retains coherent pixels and recovers at a feasible size',async({page},info)=>{
 await open(page,info.project.use.baseURL);const at=await page.evaluate(()=>window.yardQA.fixture.actors.willow.times.rest);await page.evaluate(at=>window.yardQA.seek(at),at);const before=await painted(page,at);check(before);
 await page.evaluate(()=>{const canvas=document.querySelector('canvas');canvas.style.width='6000px';canvas.style.height='4000px';});
 await page.waitForFunction(()=>window.yardQA.diagnostics().resizeFailure?.code==='CANVAS_GLOBAL_BUDGET_UNAVAILABLE');
 const rejected=await page.evaluate(()=>window.yardQA.diagnostics());expect(rejected.pendingResize).toBe(false);expect(rejected.resizeFailure.requestedBackingBytes).toBeGreaterThan(64*1048576);expect(rejected.globalDecodedBudget.canvasBackingBytes).toBe(before.globalDecodedBudget.canvasBackingBytes);expect(rejected.globalDecodedBudget.totalBytes).toBeLessThanOrEqual(64*1048576);expect(rejected.projection).toEqual(before.projection);expect(rejected.errors).toHaveLength(1);
 await page.evaluate(()=>{const canvas=document.querySelector('canvas');canvas.style.width='';canvas.style.height='';});await page.waitForFunction(()=>{const d=window.yardQA.diagnostics();return !d.pendingResize&&!d.resizeFailure;});
 const recovered=await page.evaluate(()=>window.yardQA.diagnostics());expect(recovered.view.pets).toHaveLength(1);expect(recovered.globalDecodedBudget.totalBytes).toBeLessThanOrEqual(64*1048576);expect(recovered.globalDecodedBudget.maxConcurrentDecodes).toBeLessThanOrEqual(1);await save('family-oversized-resize.json',JSON.stringify({before,rejected,recovered},null,2));
});
for(const[actor,width,height,dpr]of [['willow',390,844,2],['starlit',768,1024,1],['basil',1280,720,1],['sage',1280,720,1]])test(`${actor} actual 1x walk/turn/combined/rest/wake/exit ${width}x${height}`,async({browser},info)=>{
 test.setTimeout(420000);const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:dpr,isMobile:width<1100,hasTouch:width<1100,recordVideo:{dir:info.outputPath('movie'),size:{width,height}}}),page=await context.newPage(),video=page.video();const frames=[];
 try{await open(page,info.project.use.baseURL,actor);const a=await page.evaluate(()=>window.yardQA.fixture.actors[window.yardQA.actor()]);let start=a.times.approach;const rest=a.times.rest+2400,approachDeadline=rest-start+30000,exitDeadline=a.times.leaving-a.times.wake+30000;test.setTimeout(approachDeadline+exitDeadline+60000);check(await painted(page,start));await page.evaluate(()=>window.yardQA.play());
  await expect.poll(async()=>{const d=await page.evaluate(()=>window.yardQA.diagnostics());if(frames.length===0||d.presentationTime-frames.at(-1).at>=1000){frames.push({at:d.presentationTime,pets:d.view?.pets,budget:d.globalDecodedBudget.totalBytes});await save(`1x-${actor}-frame-${frames.length}.png`,await page.screenshot());}check(d);return d.presentationTime;},{timeout:approachDeadline,intervals:[1000]}).toBeGreaterThanOrEqual(rest);await page.evaluate(()=>window.yardQA.pause());
  start=a.times.wake;await page.evaluate(at=>window.yardQA.seek(at),start);check(await painted(page,start));await page.evaluate(()=>window.yardQA.play());await expect.poll(async()=>{const d=await page.evaluate(()=>window.yardQA.diagnostics());check(d);return d.presentationTime;},{timeout:exitDeadline,intervals:[1000]}).toBeGreaterThanOrEqual(a.times.leaving);await page.evaluate(()=>window.yardQA.pause());const d=await page.evaluate(()=>window.yardQA.diagnostics());check(d);await save(`1x-${actor}.json`,JSON.stringify({nativeSeed:a.seed,scope:'Actual 1x browser segments; authoritative rest hold was skipped between segments.',sourceSegmentSeconds:{approach:(rest-a.times.approach)/1000,exit:(a.times.leaving-a.times.wake)/1000},frames,diagnostics:d},null,2));
 }finally{await context.close();if(video)await video.saveAs(path.join(out,`1x-${actor}.webm`));}
});

test('RAF telemetry starts from its own origin and preserves subsequent real gaps',async({page},info)=>{
 await page.addInitScript(()=>{let next=0;const queued=new Map();window.requestAnimationFrame=callback=>{queued.set(++next,callback);return next;};window.cancelAnimationFrame=id=>queued.delete(id);window.stepYardRaf=stamp=>{const frame=[...queued.values()];queued.clear();for(const callback of frame)callback(stamp);};});
 await page.goto(`${info.project.use.baseURL}/__yard_qa__/index.html?actor=willow`);await page.waitForFunction(()=>window.yardQA?.ready,null,{polling:50});
 const initial=await page.evaluate(()=>{window.stepYardRaf(123456);return window.yardQA.diagnostics();});
 expect(initial.timing.stats.visibleRafCount).toBe(1);expect(initial.timing.stats.maxRafDeltaMs).toBe(0);expect(initial.timing.stats.rafOver100Ms).toBe(0);
 const next=await page.evaluate(()=>{window.stepYardRaf(123772);return window.yardQA.diagnostics();});
 expect(next.timing.stats.visibleRafCount).toBe(2);expect(next.timing.stats.maxRafDeltaMs).toBe(316);expect(next.timing.stats.rafOver100Ms).toBe(1);expect(next.timing.events.filter(e=>e.type==='raf-gap').map(e=>e.deltaMs)).toEqual([316]);
 expect(next.presentationTime).toBe(initial.presentationTime);expect(next.errors).toEqual([]);expect(next.globalDecodedBudget.peakBytes).toBeLessThanOrEqual(64*1048576);
});
