/** Prepared bounded actual-UI QA. Execution requires the reviewed initial branch
 * push. Rendering uses the actual Yard source; no fixture renderer or pose setter.
 * Static passing checks never grant pixel, hardware or native-lifecycle acceptance. */
import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const exec=promisify(execFile),HERE=path.dirname(fileURLToPath(import.meta.url));
const OUT=path.join(HERE,'results'),DIST=path.join(HERE,'dist'),CAP=8*1024*1024;
const BRANCH='refs/heads/qa/yard-pip-integrated-m2-20261006',PARENT='20f61b1fb6e2cea42336a9ba2f4868a73c81895f';
const MODEL='pip-prototype/assets/pip.glb',OPTIONAL_PREFIX='pip-prototype/';
const report={format:'Actual-Yard-optional-Pip-QA/v1',status:'RUNNING',parent:PARENT,commit:process.env.GITHUB_SHA,retries:0,browserFlagsAdded:[],
 visualAcceptance:'PENDING_HUMAN_ACTUAL_STAGE_PORTRAIT_SCALE_FOREGROUND_DEPTH_AND_VIDEO_REVIEW',hardwareMobilePerformance:'NOT_TESTED',nativeLifecycle:'UNQUALIFIED_UNTIL_TRUSTED_EVENTS_OBSERVED',
 limits:{jobMinutes:8,browserSeconds:150,artifactBytes:CAP,retentionDays:3},errors:[],cases:[],requests:[],blockedRequests:[],failedResponses:[],
 boundaries:['Actual CourtyardGame, scene-owner and Canvas2D source; isolated disposable read-only snapshot and static HTTP transport.',
 'Known model CPU11,872,312 B plus2,888,036 B encoded-background copies =14,760,348 B /16 MiB policy and12 MiB estimated GPU policy are separate from owned image/backing RGBA ledger; browser RSS and driver allocation are unknown.',
 'The clean 200×220 domain cannot convert or mutate saved 0–100 Yard positions.',
 'The actual native scene has only Pip and the calibrated planter in shared depth. Fixed illustrated foreground overlap remains refused, not depth-solved.',
 'Native blur/visibility absent in earlier headed runs remain explicitly unqualified unless this browser emits trusted events.',
 'Software WebGL results cannot establish hardware GPU or real mobile performance.', 'Native context loss/restoration is not exercised by this bounded pass; source tests cannot qualify its browser behavior.']};
const assert=(v,m)=>{if(!v)throw Error(m);},sleep=ms=>new Promise(r=>setTimeout(r,ms)),sha=b=>createHash('sha256').update(b).digest('hex');
async function list(d,p=''){const a=[];for(const e of await fs.readdir(d,{withFileTypes:true})){assert(!e.isSymbolicLink(),'Symlink forbidden');const q=path.posix.join(p,e.name);if(e.isDirectory())a.push(...await list(path.join(d,e.name),q));else if(e.isFile())a.push(q);}return a.sort();}
async function verify(){const pin=JSON.parse(await fs.readFile(path.join(HERE,'candidate-pin.json')));for(const r of pin.files){const b=await fs.readFile(path.join(HERE,'candidate',r.path));assert(b.length===r.bytes&&sha(b)===r.sha256,'Candidate changed: '+r.path);}assert((await list(path.join(HERE,'candidate'))).length===pin.files.length,'Unpinned candidate files');return pin;}
function observe(){
 const d=window.__nativeYardQA={contexts:[],events:[],shaderErrors:[],programErrors:[],storageWrites:[]};
 const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){const c=Reflect.apply(get,this,[type,...args]);if(/^webgl/.test(type)&&c&&!d.contexts.includes(c))d.contexts.push(c);return c;};
 for(const C of [window.WebGLRenderingContext,window.WebGL2RenderingContext].filter(Boolean)){const p=C.prototype,compile=p.compileShader,link=p.linkProgram;p.compileShader=function(s){const r=Reflect.apply(compile,this,[s]);if(!this.getShaderParameter(s,this.COMPILE_STATUS))d.shaderErrors.push(this.getShaderInfoLog(s));return r;};p.linkProgram=function(s){const r=Reflect.apply(link,this,[s]);if(!this.getProgramParameter(s,this.LINK_STATUS))d.programErrors.push(this.getProgramInfoLog(s));return r;};}
 const write=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){d.storageWrites.push({key:String(k),at:performance.now()});return Reflect.apply(write,this,[k,v]);};
 const event=e=>{d.events.push({type:e.type,trusted:e.isTrusted,at:performance.now(),hidden:document.hidden,focus:document.hasFocus()});if(e.type==='pagehide')queueMicrotask(()=>console.log('__YARD_PAGEHIDE__'+JSON.stringify({events:d.events,owner:window.__yardPipIntegration?.snapshot()??null,canvases:document.querySelectorAll('.cy-pip-direct-layer canvas').length})));};
 for(const t of ['blur','focus','pagehide','pageshow'])window.addEventListener(t,event);document.addEventListener('visibilitychange',event);
}
function snapshot(){const d=window.__nativeYardQA;return{at:performance.now(),owner:window.__yardPipIntegration?.snapshot()??null,state:window.__yardQAState.snapshot(),observer:{events:d.events,shaderErrors:d.shaderErrors,programErrors:d.programErrors,storageWrites:d.storageWrites,contexts:d.contexts.map(gl=>{if(gl.isContextLost())return{lost:true};const e=gl.getExtension('WEBGL_debug_renderer_info'),vendor=gl.getParameter(e?e.UNMASKED_VENDOR_WEBGL:gl.VENDOR),renderer=gl.getParameter(e?e.UNMASKED_RENDERER_WEBGL:gl.RENDERER);return{lost:false,vendor,renderer,classification:/swiftshader|llvmpipe|softpipe|software/i.test(vendor+' '+renderer)?'software':'not-known-software; hardware not established'};})},directCanvases:document.querySelectorAll('.cy-pip-direct-layer canvas').length};}
async function still(page,name){
 if(report.captures?.some(c=>c.status==='FAILED'))throw Error('Screenshot capability already failed; no automatic capture retry');
 const pixelWitness=['active-A','actual-planter-alternate-depth','actual-foreground-route-only-refusal','capture-failure'].includes(name),format=pixelWitness?'png':'jpeg',file=name+(pixelWitness?'.png':'.jpg'),viewport=page.viewportSize(),capture={name,file,format,pixelEvidence:pixelWitness,at:Date.now(),viewport,options:{type:format,...(pixelWitness?{}:{quality:85}),scale:'css',fullPage:false,clip:viewport?{x:0,y:0,width:viewport.width,height:viewport.height}:null,timeout:10000},status:'PREPARING'};
 report.captures??=[];report.captures.push(capture);
 try{capture.context=await page.evaluate(()=>{const rect=e=>{if(!e)return null;const r=e.getBoundingClientRect(),c=getComputedStyle(e);return{x:r.x,y:r.y,width:r.width,height:r.height,display:c.display,visibility:c.visibility,overflow:c.overflow};};return{readyState:document.readyState,fontsStatus:document.fonts?.status??null,hidden:document.hidden,focus:document.hasFocus(),window:{innerWidth,innerHeight,outerWidth,outerHeight,devicePixelRatio,screenX,screenY},screen:{width:screen.width,height:screen.height,availWidth:screen.availWidth,availHeight:screen.availHeight},visualViewport:visualViewport?{width:visualViewport.width,height:visualViewport.height,scale:visualViewport.scale,pageLeft:visualViewport.pageLeft,pageTop:visualViewport.pageTop,offsetLeft:visualViewport.offsetLeft,offsetTop:visualViewport.offsetTop}:null,document:{width:document.documentElement.clientWidth,height:document.documentElement.clientHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight},app:rect(document.querySelector('.cy-app')),stage:rect(document.querySelector('.cy-scene')),canvases:[...document.querySelectorAll('canvas')].map(c=>({backing:[c.width,c.height],rect:rect(c)})),statusText:document.querySelector('.cy-status')?.textContent??null,dom:document.querySelector('.cy-app')?.outerHTML.slice(0,24000)??null};});}catch(error){capture.contextError=String(error);}
 try{capture.snapshot=await page.evaluate(snapshot);}catch(error){capture.snapshotError=String(error);}
 // Flush native state before the risky capture so a protocol failure cannot erase it.
 await fs.writeFile(path.join(OUT,'report.json'),JSON.stringify(report,null,2));
 try{assert(viewport&&viewport.width>0&&viewport.height>0,'No finite screenshot viewport');await page.screenshot({path:path.join(OUT,file),...capture.options});capture.bytes=(await fs.stat(path.join(OUT,file))).size;capture.status='CAPTURED';const used=report.captures.filter(c=>c.status==='CAPTURED'&&c.format===format).reduce((n,c)=>n+c.bytes,0);assert(used<=(pixelWitness?3:2)*1024*1024,'Evidence image budget exceeded; original capture preserved');return file;}
 catch(error){capture.status='FAILED';capture.error=String(error);report.errors.push('Screenshot '+name+': '+error);await fs.writeFile(path.join(OUT,'report.json'),JSON.stringify(report,null,2));throw error;}
}
const control=(page,name)=>page.locator(`[data-pip-control="${name}"]`);
async function settled(page){await page.waitForFunction(()=>{const s=window.__yardPipIntegration?.snapshot();return s?.mode==='pip-prototype'&&s.scene?.settled&&s.scene.renderer?.mounted;},null,{timeout:14000});}
function checkState(s){assert(s.state.unchanged&&!s.state.mutationAttempts.length&&!s.state.pendingActions.length,'Disposable Yard/economy/outbox state changed');assert(!s.observer.storageWrites.some(x=>/yard|outbox/i.test(x.key)),'Save or outbox storage write');assert(!s.observer.shaderErrors.length&&!s.observer.programErrors.length,'Actual native GL shader/link error');}
function checkResources(s,pin){const a=s.owner.scene;assert(a.savedStateUsedForGeometry===false&&a.domain==='pip-clean-garden-prototype-v1','Wrong domain or saved-coordinate mapping');assert(a.knownModelCPUBufferPeak===11872312&&a.encodedBackgroundCPUBytes===2888036&&a.knownCPUBufferPeak===14760348&&a.knownCPUBufferPeak<=a.limits.knownCPU&&a.limits.knownCPU===16777216&&a.limits.estimatedGPU===12582912,'CPU/GPU inventory policy mismatch');assert(a.rgba.uiBytes>=pin.uiLifetimeBytes&&a.rgba.legacyAtlasBytes===0&&a.rgba.legacySceneStaticBytes===0&&a.rgba.backgroundBytes===973*1616*4&&a.rgba.fits,'Owned image/backing ledger mismatch');assert(a.renderer.mode==='direct'&&a.renderer.copies===0&&s.directCanvases===1,'Optional direct canvas owner mismatch');assert(s.owner.retirements>=1&&s.owner.lastRetired.globalDecodedBudget.bitmapOwners===0&&s.owner.lastRetired.decodedBytesEstimate===0&&s.owner.lastRetired.pendingDecodes===0,'Legacy resources did not retire before activation');checkState(s);}
async function layout(page){return page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom};},stage=document.querySelector('.cy-scene');const visible=[...document.querySelectorAll('.cy-header button,.cy-actions button,.cy-pip-controls button')].filter(e=>e.getClientRects().length);return{viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},scrollWidth:document.documentElement.scrollWidth,stage:rect(stage),controls:visible.map(e=>({label:e.textContent.trim()||e.getAttribute('aria-label'),disabled:e.disabled,...rect(e)})),status:rect(document.querySelector('.cy-status')),activeDOMCanvases:document.querySelectorAll('.cy-pip-direct-layer canvas').length};});}
function checkLayout(l){assert(l.scrollWidth<=l.viewport.width,'Horizontal page overflow');assert(l.stage.x>=0&&l.stage.y>=0&&l.stage.right<=l.viewport.width+1&&l.stage.bottom<=l.viewport.height+1,'Stage cropped by viewport');for(const c of l.controls){assert(c.width>=44&&c.height>=44,'Tap target under 44 CSS px: '+c.label);assert(c.x>=-1&&c.y>=-1&&c.right<=l.viewport.width+1&&c.bottom<=l.viewport.height+1,'Control outside viewport: '+c.label);assert(c.bottom<=l.stage.y+1||c.y>=l.stage.bottom-1||c.right<=l.stage.x||c.x>=l.stage.right,'Control overlaps actual stage: '+c.label);}}
async function videoEvidence(raw,rect){
 const frames=JSON.parse((await exec('ffprobe',['-v','error','-select_streams','v:0','-show_frames','-show_entries','frame=best_effort_timestamp_time','-of','json',raw],{maxBuffer:2*CAP})).stdout).frames;
 const times=frames.map(f=>Number(f.best_effort_timestamp_time));const rgb=(await exec('ffmpeg',['-v','error','-i',raw,'-vf','crop=16:16:366:4,scale=1:1:flags=neighbor,format=rgb24','-f','rawvideo','pipe:1'],{encoding:'buffer',maxBuffer:CAP})).stdout;assert(rgb.length/3===times.length,'Native frame/marker timestamp mismatch');
 const find=(predicate,from=0)=>{for(let i=from;i<times.length;i++)if(predicate(...rgb.subarray(i*3,i*3+3)))return i;return-1;};const begin=find((r,g,b)=>r>150&&g<115&&b>150),end=find((r,g,b)=>r<115&&g>150&&b>150,Math.max(0,begin+1));assert(begin>=0&&end>begin,'Clean native route markers missing');
 const start=times[begin],duration=times[end]-start;assert(duration>=6&&duration<=9,'Clean native interval outside 6–9 seconds');const crop=`crop=${rect.width}:${rect.height}:${rect.x}:${rect.y}`,file='actual-yard-clean-route.webm';
 await exec('ffmpeg',['-v','error','-i',raw,'-ss',String(start),'-t',String(duration),'-vf',crop,'-an','-c:v','libvpx-vp9','-lossless','1','-row-mt','1','-y',path.join(OUT,file)],{maxBuffer:CAP});
 return{file,nativeStartSeconds:start,nativeDurationSeconds:duration,nativeFrameTimestamps:times.slice(begin,end),processing:'Native recording crop and time trim, lossless encode; no speed/fps interpolation or fabricated frames',cadenceQualification:'Compositor recording timestamps, not displayed GPU completion or hardware phone FPS'};
}
async function run(){
 await fs.mkdir(OUT,{recursive:true});let browser,server,timer,raw=null,rect=null;const pin=await verify();report.pin=pin.summary;for(const name of ['built-files.json','asset-url-closure.json','bundle-transfer-estimates.json'])await fs.copyFile(path.join(HERE,name),path.join(OUT,name));
 assert(process.env.GITHUB_ACTIONS==='true'&&process.env.GITHUB_REF===BRANCH&&process.env.GITHUB_RUN_ATTEMPT==='1','Only reviewed first-attempt job may execute');const event=JSON.parse(await fs.readFile(process.env.GITHUB_EVENT_PATH));assert(process.env.GITHUB_EVENT_NAME==='push'&&event.created===true&&!event.deleted&&!event.forced&&event.ref===BRANCH&&event.after===process.env.GITHUB_SHA,'Only initial reviewed branch creation may execute');
 const build=JSON.parse(await fs.readFile(path.join(HERE,'built-files.json'))),built=new Map(build.files.map(x=>[x.path,x]));for(const f of build.files){const b=await fs.readFile(path.join(DIST,f.path));assert(b.length===f.bytes&&sha(b)===f.sha256,'Built static file changed');}
 const closure=JSON.parse(await fs.readFile(path.join(HERE,'asset-url-closure.json')));assert(closure.format==='actual-yard-static-url-closure/v1'&&closure.complete===true,'Complete exact URL closure required before browser');for(const scope of ['off','on','fallback','portraits'])assert(closure.coverage?.[scope]==='complete','URL scope incomplete: '+scope);const allowed=new Map();for(const row of closure.rows){const u=new URL(row.url,'http://review.invalid'),f=built.get(row.file);assert(u.origin==='http://review.invalid'&&!u.hash&&u.pathname+u.search===row.url&&!allowed.has(row.url)&&f&&f.bytes===row.bytes&&f.sha256===row.sha256,'Invalid or unreadable exact URL closure row');allowed.set(row.url,row.file);}assert(allowed.size===closure.urlCount,'URL closure count mismatch');report.bundleTransfer=build.bundleTransfer;report.assetClosure={urlCount:closure.urlCount,uniqueFileCount:closure.uniqueFileCount,encodedUniqueBytes:closure.encodedUniqueBytes,requirementsSHA256:closure.requirementsSHA256};
 const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.webp':'image/webp','.glb':'model/gltf-binary','.glsl':'text/plain'};
 server=http.createServer(async(q,r)=>{try{const u=new URL(q.url,'http://127.0.0.1'),key=u.pathname+u.search,rel=allowed.get(key);if(q.method!=='GET'||!rel){r.writeHead(403);return r.end('Outside reviewed static scope');}const b=await fs.readFile(path.join(DIST,rel));r.writeHead(200,{'content-type':mime[path.extname(rel)]||'application/octet-stream','cache-control':'no-store'});r.end(b);}catch{r.writeHead(500);r.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
 try{
  const {chromium}=await import('@playwright/test');timer=setTimeout(()=>{report.errors.push('150-second browser deadline');void browser?.close();},150000);browser=await chromium.launch({headless:false});report.browserVersion=browser.version();report.displayInspection={requestedXvfbScreen:process.env.YARD_XVFB_SCREEN??null,requiredPhysicalBounds:[2560,2048],qualification:'Display geometry avoids a known possible extent mismatch; it does not establish the earlier capture failure cause.'};try{const display=(await exec('xdpyinfo',[],{timeout:2000,maxBuffer:1024*1024})).stdout,match=display.match(/dimensions:\s*(\d+)x(\d+) pixels/);report.displayInspection.nativeDimensions=match?[Number(match[1]),Number(match[2])]:null;}catch(error){report.displayInspection.error=String(error);}if(report.displayInspection.nativeDimensions)assert(report.displayInspection.nativeDimensions[0]>=2560&&report.displayInspection.nativeDimensions[1]>=2048,'Native Xvfb surface below full matrix physical bounds');
  async function open({record=false,optional=true,holdModel=false,viewport={width:390,height:844},mobile=true}={}){
   const context=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:mobile,hasTouch:mobile,serviceWorkers:'block',...(record?{recordVideo:{dir:path.join(OUT,'raw'),size:{width:390,height:844}}}:{})});await context.addInitScript(observe);let release,requested;const held=new Promise(r=>release=r),modelRequested=new Promise(r=>requested=r);const label=report.cases.length;
   await context.route('**/*',async route=>{const q=route.request(),u=new URL(q.url()),key=u.pathname+u.search,rel=allowed.get(key);if(q.method()!=='GET'||u.origin!==origin||!rel){report.blockedRequests.push({method:q.method(),url:q.url()});return route.abort();}report.requests.push({case:label,at:Date.now(),method:q.method(),path:rel,url:key});if(holdModel&&rel===MODEL){requested();await held;}try{return await route.continue();}catch(e){if(!(holdModel&&rel===MODEL))throw e;}});
   const page=await context.newPage(),receipts=[];page.setDefaultTimeout(6000);page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.text().startsWith('__YARD_PAGEHIDE__'))receipts.push(JSON.parse(m.text().slice('__YARD_PAGEHIDE__'.length)));else if(m.type()==='error')report.errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)report.failedResponses.push({status:r.status(),url:r.url()});});
   await page.goto(origin+'/?optional='+(optional?'1':'0'),{waitUntil:'networkidle'});await page.bringToFront();await page.waitForFunction(()=>Boolean(window.__yardQAState));if(optional)await page.waitForFunction(()=>window.__yardPipIntegration?.snapshot()?.scene?.ready===true,null,{timeout:16000});return{context,page,receipts,release,modelRequested,label};
  }
  // Production prop is false. Then local route is visible but still initially off.
  for(const optional of [false,true]){const x=await open({optional});try{const s=await x.page.evaluate(snapshot),requests=report.requests.filter(r=>r.case===x.label);assert(!requests.some(r=>r.path.startsWith(OPTIONAL_PREFIX))&&s.observer.contexts.length===0,'Default-off fetched optional module, Three, GLB, background or allocated WebGL');assert(await control(x.page,'toggle').count()===(optional?1:0),'Production/local opt-in UI mismatch');checkState(s);const earlyCase={name:optional?'local-route-default-off':'production-prop-default-off',snapshot:s,requests:requests.map(r=>r.path)};report.cases.push(earlyCase);earlyCase.still=await still(x.page,optional?'local-default-off':'production-default-off');}finally{await x.context.close();}}
  const x=await open({record:true});try{
   await control(x.page,'toggle').click();await settled(x.page);const active=await x.page.evaluate(snapshot);checkResources(active,pin);assert(await control(x.page,'goal-A').isDisabled()&&await control(x.page,'goal-B').isEnabled(),'Settled route controls wrong');
   report.cases.push({name:'actual-activation-A',snapshot:active,still:await still(x.page,'active-A')});
   const r=await x.page.locator('.cy-scene').boundingBox();rect={x:Math.floor(r.x),y:Math.floor(r.y),width:Math.floor(r.width/2)*2,height:Math.floor(r.height/2)*2};
   // Marker is outside the cropped game stage. It never changes stage layout.
   await x.page.evaluate(()=>{const m=document.createElement('div');m.id='qa-marker';Object.assign(m.style,{position:'fixed',left:'366px',top:'4px',width:'16px',height:'16px',background:'#fff',zIndex:'2147483647',pointerEvents:'none'});document.body.append(m);});await sleep(160);
   const begin=await x.page.evaluate(()=>{document.querySelector('#qa-marker').style.background='#ff00ff';return performance.now();});await control(x.page,'goal-B').click();
   // One uninterrupted native route: no screenshots, resize, focus, readback or polling.
   await sleep(7000);
   const end=await x.page.evaluate(()=>{document.querySelector('#qa-marker').style.background='#00ffff';return{at:performance.now(),owner:window.__yardPipIntegration.snapshot()};});await sleep(160);assert(end.owner.scene.settled&&end.owner.scene.goalIndex===1&&!end.owner.scene.scheduler.pending,'Recorded route B did not settle');const idle=await x.page.evaluate(snapshot);assert(idle.owner.scene.frameCount===end.owner.scene.frameCount,'Settled scene keeps drawing');report.cleanCapture={begin,end,idle,stageRect:rect};
   // Record only that uninterrupted phone route. Layout and screenshots are separate.
   const video=x.page.video();await x.context.close();raw=await video.path();
  }catch(e){report.errors.push(String(e));await still(x.page,'capture-failure').catch(()=>{});const video=x.page.video();await x.context.close();raw=await video?.path();}
  const y=await open();try{
   await control(y.page,'toggle').click();await settled(y.page);report.cases.push({name:'held-full-layout-matrix',viewports:[]});const matrix=report.cases.at(-1);
   for(const [width,height]of[[320,568],[360,800],[390,844],[414,896],[568,320],[844,390],[768,1024],[1024,768],[393,873]]){await y.page.setViewportSize({width,height});await sleep(160);let s=await y.page.evaluate(snapshot);if(s.owner.mode==='legacy'&&width>=320&&height>=568){await control(y.page,'toggle').click();await settled(y.page);s=await y.page.evaluate(snapshot);}const l=await layout(y.page),row={width,height,snapshot:s,layout:l,still:await still(y.page,`active-${width}x${height}`)};matrix.viewports.push(row);try{checkLayout(l);assert(l.stage.width>=280&&l.stage.height>=192,'UNRESOLVED_STAGE_CAPABILITY: actual stage below280×192');assert(s.owner.mode==='pip-prototype'&&s.owner.scene.settled&&!s.owner.scene.scheduler.pending,'Resize did not retain settled active scene');checkResources(s,pin);row.mechanicalAcceptance='PASS_VISUAL_REVIEW_PENDING';}catch(e){row.mechanicalAcceptance='FAILED_OR_UNRESOLVED_VIEWPORT';row.error=String(e);report.errors.push(`${width}x${height}: ${e}`);}}
   await y.page.setViewportSize({width:390,height:844});await sleep(160);if((await y.page.evaluate(snapshot)).owner.mode==='legacy'){await control(y.page,'toggle').click();await settled(y.page);}const before=await y.page.evaluate(snapshot),stage=await y.page.locator('.cy-scene').boundingBox();await y.page.mouse.click(stage.x+stage.width*.22,stage.y+stage.height*.15);const after=await y.page.evaluate(snapshot);assert(JSON.stringify(before.owner.scene.lastFrame.root)===JSON.stringify(after.owner.scene.lastFrame.root)&&after.owner.scene.goalIndex===before.owner.scene.goalIndex,'Unsupported fixed foreground tap changed route');report.foregroundRefusal={before,after,still:await still(y.page,'actual-foreground-route-only-refusal'),coverage:'Actual background tap is inert and cannot submit saved-coordinate placement. Illegal route composition rejection separately checked in CPU tests; no mutation diagnostic hook.'};
   const p0=await y.page.evaluate(snapshot);await control(y.page,'planter').click();await sleep(100);const p1=await y.page.evaluate(snapshot);assert(p1.owner.scene.placementIndex!==p0.owner.scene.placementIndex,'Planter control did not change admitted placement');report.actualPlanter={before:p0,after:p1,still:await still(y.page,'actual-planter-alternate-depth'),qualification:'Inspect this actual integrated scene and active-A; same renderer depth diagnostics are supporting data, not pixel acceptance.'};
   // Portrait appears in real Guests cards and retains its UI-lifetime reservation.
   await y.page.locator('.cy-actions button').nth(2).click();await y.page.locator('dialog[open]').waitFor();const portrait=y.page.locator('img[src*="/r1-pip/"]');await portrait.first().scrollIntoViewIfNeeded();await y.page.waitForFunction(()=>[...document.querySelectorAll('img[src*="/r1-pip/"]')].some(i=>i.complete&&i.naturalWidth>0));report.portrait={still:await still(y.page,'actual-guests-r1-portrait'),snapshot:await y.page.evaluate(snapshot),dialog:await y.page.evaluate(()=>{const d=document.querySelector('dialog[open]'),r=d.getBoundingClientRect(),b=d.querySelector('header button').getBoundingClientRect();return{open:d.open,focusWithin:d.contains(document.activeElement),rect:{x:r.x,y:r.y,width:r.width,height:r.height},close:{width:b.width,height:b.height,right:b.right,bottom:b.bottom}};})};assert(report.portrait.dialog.focusWithin&&report.portrait.dialog.close.width>=44&&report.portrait.dialog.close.height>=44,'Guests dialog lacks focused visible dismiss control');await y.page.locator('dialog header button').click();
   await control(y.page,'goal-B').click();await sleep(180);for(const goal of ['A','B','C'])assert(await control(y.page,'goal-'+goal).isDisabled(),'Mid-stride route replacement remained enabled');const beforePause=await y.page.evaluate(snapshot),other=await y.context.newPage();await other.goto('about:blank');await other.bringToFront();await sleep(120);const pausedStart=await y.page.evaluate(snapshot);await sleep(320);const pausedEnd=await y.page.evaluate(snapshot);await y.page.bringToFront();await other.close();await sleep(120);const resumed=await y.page.evaluate(snapshot),events=resumed.observer.events.filter(e=>e.trusted&&e.at>=beforePause.at),has=t=>events.some(e=>e.type===t),nativePause=has('blur')&&events.some(e=>e.type==='visibilitychange'&&e.hidden),nativeResume=has('focus')&&events.some(e=>e.type==='visibilitychange'&&!e.hidden);if(nativePause)assert(pausedStart.owner.scene.route.displayedElapsedMs===pausedEnd.owner.scene.route.displayedElapsedMs,'Trusted background event failed to pause');if(nativeResume&&!pausedEnd.owner.scene.settled)assert(resumed.owner.scene.route.activeElapsedMs>pausedEnd.owner.scene.route.activeElapsedMs,'Trusted resume failed to advance route');report.lifecycle={beforePause,pausedStart,pausedEnd,resumed,qualification:nativePause&&nativeResume?'TRUSTED_EVENT_VALUES_REQUIRE_REVIEW':'UNQUALIFIED_MISSING_TRUSTED_BLUR_VISIBILITY_OR_FOCUS'};
   await settled(y.page);await control(y.page,'goal-C').click();await settled(y.page);for(const goal of ['A','B','C'])assert(await control(y.page,'goal-'+goal).isDisabled(),'Terminal route control remained enabled');report.terminalRoute={snapshot:await y.page.evaluate(snapshot),still:await still(y.page,'actual-route-C-terminal')};
   await control(y.page,'toggle').click();await y.page.waitForFunction(()=>window.__yardPipIntegration.snapshot().mode==='legacy'&&window.__yardPipIntegration.snapshot().scene.ready);const disabled=await y.page.evaluate(snapshot);assert(!disabled.owner.enabled&&disabled.directCanvases===0,'Disable did not restore sole legacy owner');checkState(disabled);report.disable={snapshot:disabled,still:await still(y.page,'rollback-legacy')};
   await control(y.page,'toggle').click();await settled(y.page);await y.page.goto('about:blank');await sleep(120);report.pagehide={receipts:y.receipts,qualification:y.receipts.some(r=>r.events.some(e=>e.type==='pagehide'&&e.trusted)&&r.canvases===0)?'NATIVE_PAGEHIDE_CANVAS_REMOVAL_OBSERVED':'UNQUALIFIED_NO_POST_HIDE_DISPOSAL_RECEIPT'};
  }finally{await y.context.close();}
  const desktop=await open({viewport:{width:1280,height:720},mobile:false});try{await control(desktop.page,'toggle').click();await settled(desktop.page);const l=await layout(desktop.page);checkLayout(l);report.cases.push({name:'desktop1280x720',layout:l,snapshot:await desktop.page.evaluate(snapshot),still:await still(desktop.page,'active-1280x720')});}finally{await desktop.context.close();}
  const late=await open({holdModel:true});try{await control(late.page,'toggle').click();await Promise.race([late.modelRequested,sleep(10000).then(()=>{throw Error('Delayed GLB request not observed');})]);const pending=await late.page.evaluate(snapshot);await control(late.page,'toggle').click();late.release();await late.page.waitForFunction(()=>window.__yardPipIntegration.snapshot().mode==='legacy'&&window.__yardPipIntegration.snapshot().scene.ready,null,{timeout:12000});await sleep(180);const completed=await late.page.evaluate(snapshot);assert(!completed.owner.enabled&&completed.directCanvases===0,'Late initialization survived disable');checkState(completed);report.lateInitRollback={pending,completed,still:await still(late.page,'late-init-rollback'),fault:'Only exact GLB HTTP continuation delayed; byte content unchanged'};}finally{late.release();await late.context.close();}
 }catch(e){report.errors.push(String(e));}
 finally{clearTimeout(timer);await browser?.close();await new Promise(r=>server.close(r));}
 if(raw&&rect)try{report.cleanVideo=await videoEvidence(raw,rect);}catch(e){report.errors.push(String(e));}
 report.status=report.errors.length||report.blockedRequests.length||report.failedResponses.length?'FAILURE_OR_MISSING_EVIDENCE':'NATIVE_EVIDENCE_READY_VISUAL_REVIEW_PENDING';
 // Raw failure is retained when feasible. Evidence is never silently called complete.
 report.rawEvidence={retained:true,uniqueRecordingExpected:Boolean(raw),policy:'Preserve the single original native recording alongside the derived clip for human review; never delete unique evidence to satisfy the cap'};
 report.artifacts=[];for(const f of await list(OUT)){if(f==='report.json'||f==='index.html')continue;const b=await fs.readFile(path.join(OUT,f));report.artifacts.push({path:f,bytes:b.length,sha256:sha(b)});}
 const escaped=s=>s.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 await fs.writeFile(path.join(OUT,'index.html'),'<!doctype html><meta charset="utf-8"><title>Actual Yard QA evidence</title><h1>'+report.status+'</h1><p>Local offline evidence. Visual review remains pending. Open report.json for limits, failure details and resource/lifecycle observations.</p>'+report.errors.map(e=>'<pre>'+escaped(e)+'</pre>').join('')+report.artifacts.map(a=>/\.(?:png|jpg)$/.test(a.path)?'<figure><img style="max-width:100%" src="'+a.path+'"><figcaption>'+a.path+'</figcaption></figure>':a.path.endsWith('.webm')?'<video controls style="max-width:100%" src="'+a.path+'"></video>':'<p>'+a.path+'</p>').join(''));
 await fs.writeFile(path.join(OUT,'report.json'),JSON.stringify(report,null,2));let bytes=0;for(const f of await list(OUT))bytes+=(await fs.stat(path.join(OUT,f))).size;assert(bytes<=CAP,'Eight MiB cap exceeded: full evidence retained locally, upload forbidden');console.log(JSON.stringify({status:report.status,bytes}));if(report.status.startsWith('FAILURE'))process.exitCode=1;
}
if(process.argv.includes('--verify-only')){await verify();console.log('Frozen candidate verified; no browser/server/job started.');}else try{await run();}catch(error){report.errors.push(String(error));report.status='SETUP_OR_EARLY_FAILURE';await fs.mkdir(OUT,{recursive:true});await fs.writeFile(path.join(OUT,'report.json'),JSON.stringify(report,null,2));process.exitCode=1;}
