/** Prepared bounded actual-UI QA. Execution requires the reviewed initial branch
 * push. Rendering uses the actual Yard source; no fixture renderer or pose setter.
 * Static passing checks never grant pixel, hardware or native-lifecycle acceptance. */
import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const exec=promisify(execFile),HERE=path.dirname(fileURLToPath(import.meta.url));
const OUT=path.join(HERE,'results'),DIST=path.join(HERE,'dist'),CAP=8*1024*1024;
const BRANCH='refs/heads/qa/yard-pip-integrated-layout-20261006',PARENT='01145450550ee43eb2e50723df9aa1d9c28f17fb';
const MODEL='pip-prototype/assets/pip.glb',OPTIONAL_PREFIX='pip-prototype/';
const report={format:'Actual-Yard-focused-resize-QA/v1',status:'RUNNING',parent:PARENT,commit:process.env.GITHUB_SHA,retries:0,browserFlagsAdded:[],
 visualAcceptance:'PENDING_HUMAN_UPDATED_LAYOUT_AND_RESIZE_REVIEW',hardwareMobilePerformance:'NOT_TESTED',nativeLifecycle:'UNQUALIFIED_UNTIL_TRUSTED_EVENTS_OBSERVED',
 limits:{jobMinutes:8,browserSeconds:150,artifactBytes:CAP,retentionDays:3},errors:[],cases:[],requests:[],blockedRequests:[],failedResponses:[],
 boundaries:['Actual CourtyardGame, scene-owner and Canvas2D source; isolated disposable read-only snapshot and static HTTP transport.',
 'Known model CPU11,872,312 B plus2,888,036 B encoded-background copies =14,760,348 B /16 MiB policy and12 MiB estimated GPU policy are separate from owned image/backing RGBA ledger; browser RSS and driver allocation are unknown.',
 'The clean 200×220 domain cannot convert or mutate saved 0–100 Yard positions.',
 'The actual native scene has only Pip and the calibrated planter in shared depth. Fixed illustrated foreground overlap remains refused, not depth-solved.',
 'Native blur/visibility absent in earlier headed runs remain explicitly unqualified unless this browser emits trusted events.',
 'Software WebGL results cannot establish hardware GPU or real mobile performance.', 'Native context loss/restoration is not exercised by this bounded pass; source tests cannot qualify its browser behavior.']};
const assert=(v,m)=>{if(!v)throw Error(m);},sleep=ms=>new Promise(r=>setTimeout(r,ms)),sha=b=>createHash('sha256').update(b).digest('hex');
async function list(d,p=''){const a=[];for(const e of await fs.readdir(d,{withFileTypes:true})){assert(!e.isSymbolicLink(),'Symlink forbidden');const q=path.posix.join(p,e.name);if(e.isDirectory())a.push(...await list(path.join(d,e.name),q));else if(e.isFile())a.push(q);}return a.sort();}
async function verify(){const pin=JSON.parse(await fs.readFile(path.join(HERE,'candidate-pin.json')));for(const r of pin.files){const b=await fs.readFile(path.join(HERE,'candidate',r.path));assert(b.length===r.bytes&&sha(b)===r.sha256,'Candidate changed: '+r.path);}assert((await list(path.join(HERE,'candidate'))).length===pin.files.length,'Unpinned candidate files');const prior=JSON.parse(await fs.readFile(path.join(HERE,'reused-evidence.json')));assert(prior.format==='actual-yard-prior-native-evidence/v1'&&prior.commit===PARENT,'Prior evidence identity mismatch');for(const expected of prior.unchangedInputs){const actual=pin.files.find(row=>row.path===expected.path);assert(actual?.sha256===expected.sha256&&actual.bytes===expected.bytes,'Prior model/art input changed: '+expected.path);}return pin;}
function observe(){
 const d=window.__nativeYardQA={contexts:[],events:[],shaderErrors:[],programErrors:[],storageWrites:[]};
 const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){const c=Reflect.apply(get,this,[type,...args]);if(/^webgl/.test(type)&&c&&!d.contexts.includes(c))d.contexts.push(c);return c;};
 for(const C of [window.WebGLRenderingContext,window.WebGL2RenderingContext].filter(Boolean)){const p=C.prototype,compile=p.compileShader,link=p.linkProgram;p.compileShader=function(s){const r=Reflect.apply(compile,this,[s]);if(!this.getShaderParameter(s,this.COMPILE_STATUS))d.shaderErrors.push(this.getShaderInfoLog(s));return r;};p.linkProgram=function(s){const r=Reflect.apply(link,this,[s]);if(!this.getProgramParameter(s,this.LINK_STATUS))d.programErrors.push(this.getProgramInfoLog(s));return r;};}
 const write=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){d.storageWrites.push({key:String(k),at:performance.now()});return Reflect.apply(write,this,[k,v]);};
 const event=e=>{d.events.push({type:e.type,trusted:e.isTrusted,at:performance.now(),hidden:document.hidden,focus:document.hasFocus()});if(e.type==='pagehide')queueMicrotask(()=>console.log('__YARD_PAGEHIDE__'+JSON.stringify({events:d.events,owner:window.__yardPipIntegration?.snapshot()??null,canvases:document.querySelectorAll('.cy-pip-direct-layer canvas').length})));};
 for(const t of ['blur','focus','pagehide','pageshow'])window.addEventListener(t,event);document.addEventListener('visibilitychange',event);
}
function snapshot(){const d=window.__nativeYardQA;return{at:performance.now(),owner:window.__yardPipIntegration?.snapshot()??null,state:window.__yardQAState.snapshot(),observer:{events:d.events,shaderErrors:d.shaderErrors,programErrors:d.programErrors,storageWrites:d.storageWrites,contexts:d.contexts.map(gl=>{if(gl.isContextLost())return{lost:true};const e=gl.getExtension('WEBGL_debug_renderer_info'),vendor=gl.getParameter(e?e.UNMASKED_VENDOR_WEBGL:gl.VENDOR),renderer=gl.getParameter(e?e.UNMASKED_RENDERER_WEBGL:gl.RENDERER);return{lost:false,vendor,renderer,classification:/swiftshader|llvmpipe|softpipe|software/i.test(vendor+' '+renderer)?'software':'not-known-software; hardware not established'};})},directCanvases:document.querySelectorAll('.cy-pip-direct-layer canvas').length};}
async function still(page,name){
 if(report.captures?.some(c=>c.status==='FAILED'))throw Error('Screenshot capability already failed; no automatic capture retry');
 const pixelWitness=['active-A','actual-planter-alternate-depth','actual-foreground-route-only-refusal','capture-failure'].includes(name),format=pixelWitness?'png':'jpeg',file=name+(pixelWitness?'.png':'.jpg'),viewport=page.viewportSize(),capture={name,file,format,pixelEvidence:pixelWitness,at:Date.now(),viewport,options:{type:format,...(pixelWitness?{}:{quality:85}),scale:'css',fullPage:false,clip:viewport?{x:0,y:0,width:viewport.width,height:viewport.height}:null,timeout:10000},status:'PREPARING'};
 report.captures??=[];report.captures.push(capture);
 try{capture.context=await page.evaluate(()=>{const rect=e=>{if(!e)return null;const r=e.getBoundingClientRect(),c=getComputedStyle(e);return{x:r.x,y:r.y,width:r.width,height:r.height,display:c.display,visibility:c.visibility,overflow:c.overflow};};return{readyState:document.readyState,fontsStatus:document.fonts?.status??null,hidden:document.hidden,focus:document.hasFocus(),window:{innerWidth,innerHeight,outerWidth,outerHeight,devicePixelRatio,screenX,screenY},screen:{width:screen.width,height:screen.height,availWidth:screen.availWidth,availHeight:screen.availHeight},visualViewport:visualViewport?{width:visualViewport.width,height:visualViewport.height,scale:visualViewport.scale,pageLeft:visualViewport.pageLeft,pageTop:visualViewport.pageTop,offsetLeft:visualViewport.offsetLeft,offsetTop:visualViewport.offsetTop}:null,document:{width:document.documentElement.clientWidth,height:document.documentElement.clientHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight},app:rect(document.querySelector('.cy-app')),stage:rect(document.querySelector('.cy-scene')),canvases:[...document.querySelectorAll('canvas')].map(c=>({backing:[c.width,c.height],rect:rect(c)})),statusText:document.querySelector('.cy-status')?.textContent??null,dom:document.querySelector('.cy-app')?.outerHTML.slice(0,24000)??null};});}catch(error){capture.contextError=String(error);}
 try{capture.snapshot=await page.evaluate(snapshot);}catch(error){capture.snapshotError=String(error);}
 // Flush native state before the risky capture so a protocol failure cannot erase it.
 await fs.writeFile(path.join(OUT,'report.json'),JSON.stringify(report,null,2));
 try{assert(viewport&&viewport.width>0&&viewport.height>0,'No finite screenshot viewport');await page.screenshot({path:path.join(OUT,file),...capture.options});capture.bytes=(await fs.stat(path.join(OUT,file))).size;capture.status='CAPTURED';const used=report.captures.filter(c=>c.status==='CAPTURED'&&c.format===format).reduce((n,c)=>n+c.bytes,0);assert(used<=(pixelWitness?3:2)*1024*1024,'Evidence image budget exceeded; original capture preserved');return file;}
 catch(error){capture.status='FAILED';capture.error=String(error);report.errors.push('Screenshot '+name+': '+error);await fs.writeFile(path.join(OUT,'report.json'),JSON.stringify(report,null,2));throw error;}
}
const control=(page,name)=>page.locator(`[data-pip-control="${name}"]`);
async function settled(page){await page.waitForFunction(()=>{const s=window.__yardPipIntegration?.snapshot();return s?.mode==='pip-prototype'&&s.scene?.settled&&s.scene.renderer?.mounted;},null,{timeout:14000});}
function checkState(s){assert(s.state.unchanged&&!s.state.mutationAttempts.length&&!s.state.pendingActions.length,'Disposable Yard/economy/outbox state changed');assert(!s.observer.storageWrites.some(x=>/yard|outbox/i.test(x.key)),'Save or outbox storage write');assert(!s.observer.shaderErrors.length&&!s.observer.programErrors.length,'Actual native GL shader/link error');}
function checkResources(s,pin){const a=s.owner.scene;assert(a.savedStateUsedForGeometry===false&&a.domain==='pip-clean-garden-prototype-v1','Wrong domain or saved-coordinate mapping');assert(a.knownModelCPUBufferPeak===11872312&&a.encodedBackgroundCPUBytes===2888036&&a.knownCPUBufferPeak===14760348&&a.knownCPUBufferPeak<=a.limits.knownCPU&&a.limits.knownCPU===16777216&&a.limits.estimatedGPU===12582912,'CPU/GPU inventory policy mismatch');assert(a.rgba.uiBytes>=pin.uiLifetimeBytes&&a.rgba.legacyAtlasBytes===0&&a.rgba.legacySceneStaticBytes===0&&a.rgba.backgroundBytes===973*1616*4&&a.rgba.fits,'Owned image/backing ledger mismatch');assert(a.renderer.mode==='direct'&&a.renderer.copies===0&&s.directCanvases===1,'Optional direct canvas owner mismatch');assert(s.owner.retirements>=1&&s.owner.lastRetired.globalDecodedBudget.bitmapOwners===0&&s.owner.lastRetired.decodedBytesEstimate===0&&s.owner.lastRetired.pendingDecodes===0,'Legacy resources did not retire before activation');checkState(s);}
async function layout(page){return page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom};},stage=document.querySelector('.cy-scene');const visible=[...document.querySelectorAll('.cy-header button,.cy-actions button,.cy-pip-controls button')].filter(e=>e.getClientRects().length);return{viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},scrollWidth:document.documentElement.scrollWidth,stage:rect(stage),controls:visible.map(e=>({label:e.textContent.trim()||e.getAttribute('aria-label'),disabled:e.disabled,...rect(e)})),status:rect(document.querySelector('.cy-status')),activeDOMCanvases:document.querySelectorAll('.cy-pip-direct-layer canvas').length};});}
function checkLayout(l){assert(l.scrollWidth<=l.viewport.width,'Horizontal page overflow');assert(l.stage.x>=0&&l.stage.y>=0&&l.stage.right<=l.viewport.width+1&&l.stage.bottom<=l.viewport.height+1,'Stage cropped by viewport');for(const c of l.controls){assert(c.width>=44&&c.height>=44,'Tap target under 44 CSS px: '+c.label);assert(c.x>=-1&&c.y>=-1&&c.right<=l.viewport.width+1&&c.bottom<=l.viewport.height+1,'Control outside viewport: '+c.label);assert(c.bottom<=l.stage.y+1||c.y>=l.stage.bottom-1||c.right<=l.stage.x||c.x>=l.stage.right,'Control overlaps actual stage: '+c.label);}}
async function run(){
 await fs.mkdir(OUT,{recursive:true});let browser,server,timer,raw=null,rect=null;const pin=await verify();report.pin=pin.summary;for(const name of ['built-files.json','asset-url-closure.json','bundle-transfer-estimates.json'])await fs.copyFile(path.join(HERE,name),path.join(OUT,name));
 assert(process.env.GITHUB_ACTIONS==='true'&&process.env.GITHUB_REF===BRANCH&&process.env.GITHUB_RUN_ATTEMPT==='1','Only reviewed first-attempt job may execute');const event=JSON.parse(await fs.readFile(process.env.GITHUB_EVENT_PATH));assert(process.env.GITHUB_EVENT_NAME==='push'&&event.created===true&&!event.deleted&&!event.forced&&event.ref===BRANCH&&event.after===process.env.GITHUB_SHA,'Only initial reviewed branch creation may execute');
 const build=JSON.parse(await fs.readFile(path.join(HERE,'built-files.json'))),built=new Map(build.files.map(x=>[x.path,x]));for(const f of build.files){const b=await fs.readFile(path.join(DIST,f.path));assert(b.length===f.bytes&&sha(b)===f.sha256,'Built static file changed');}
 const closure=JSON.parse(await fs.readFile(path.join(HERE,'asset-url-closure.json')));assert(closure.format==='actual-yard-static-url-closure/v1'&&closure.complete===true,'Complete exact URL closure required before browser');for(const scope of ['off','on','fallback','portraits'])assert(closure.coverage?.[scope]==='complete','URL scope incomplete: '+scope);const allowed=new Map();for(const row of closure.rows){const u=new URL(row.url,'http://review.invalid'),f=built.get(row.file);assert(u.origin==='http://review.invalid'&&!u.hash&&u.pathname+u.search===row.url&&!allowed.has(row.url)&&f&&f.bytes===row.bytes&&f.sha256===row.sha256,'Invalid or unreadable exact URL closure row');allowed.set(row.url,row.file);}assert(allowed.size===closure.urlCount,'URL closure count mismatch');report.bundleTransfer=build.bundleTransfer;report.assetClosure={urlCount:closure.urlCount,uniqueFileCount:closure.uniqueFileCount,encodedUniqueBytes:closure.encodedUniqueBytes,requirementsSHA256:closure.requirementsSHA256};
 const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.webp':'image/webp','.glb':'model/gltf-binary','.glsl':'text/plain'};
 server=http.createServer(async(q,r)=>{try{const u=new URL(q.url,'http://127.0.0.1'),key=u.pathname+u.search,rel=allowed.get(key);if(q.method!=='GET'||!rel){r.writeHead(403);return r.end('Outside reviewed static scope');}const b=await fs.readFile(path.join(DIST,rel));r.writeHead(200,{'content-type':mime[path.extname(rel)]||'application/octet-stream','cache-control':'no-store'});r.end(b);}catch{r.writeHead(500);r.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
 try{
  const {chromium}=await import('@playwright/test');timer=setTimeout(()=>{report.errors.push('150-second browser deadline');void browser?.close();},150000);browser=await chromium.launch({headless:false});report.browserVersion=browser.version();report.displayInspection={requestedXvfbScreen:process.env.YARD_XVFB_SCREEN??null,requiredPhysicalBounds:[2560,2048],qualification:'Display geometry avoids a known possible extent mismatch; it does not establish the earlier capture failure cause.'};try{const display=(await exec('xdpyinfo',[],{timeout:2000,maxBuffer:1024*1024})).stdout,match=display.match(/dimensions:\s*(\d+)x(\d+) pixels/);report.displayInspection.nativeDimensions=match?[Number(match[1]),Number(match[2])]:null;}catch(error){report.displayInspection.error=String(error);}if(report.displayInspection.nativeDimensions)assert(report.displayInspection.nativeDimensions[0]>=2560&&report.displayInspection.nativeDimensions[1]>=2048,'Native Xvfb surface below full matrix physical bounds');
  async function open({optional=true,holdModel=false,viewport={width:390,height:844},mobile=true}={}){
   const context=await browser.newContext({viewport,deviceScaleFactor:2,isMobile:mobile,hasTouch:mobile,serviceWorkers:'block'});await context.addInitScript(observe);let release,requested;const held=new Promise(r=>release=r),modelRequested=new Promise(r=>requested=r);const label=report.cases.length;
   await context.route('**/*',async route=>{const q=route.request(),u=new URL(q.url()),key=u.pathname+u.search,rel=allowed.get(key);if(q.method()!=='GET'||u.origin!==origin||!rel){report.blockedRequests.push({method:q.method(),url:q.url()});return route.abort();}report.requests.push({case:label,at:Date.now(),method:q.method(),path:rel,url:key});if(holdModel&&rel===MODEL){requested();await held;}try{return await route.continue();}catch(e){if(!(holdModel&&rel===MODEL))throw e;}});
   const page=await context.newPage(),receipts=[];page.setDefaultTimeout(6000);page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.text().startsWith('__YARD_PAGEHIDE__'))receipts.push(JSON.parse(m.text().slice('__YARD_PAGEHIDE__'.length)));else if(m.type()==='error')report.errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)report.failedResponses.push({status:r.status(),url:r.url()});});
   await page.goto(origin+'/?optional='+(optional?'1':'0'),{waitUntil:'networkidle'});await page.bringToFront();await page.waitForFunction(()=>Boolean(window.__yardQAState));if(optional)await page.waitForFunction(()=>window.__yardPipIntegration?.snapshot()?.scene?.ready===true,null,{timeout:16000});return{context,page,receipts,release,modelRequested,label};
  }
  const prior=JSON.parse(await fs.readFile(path.join(HERE,'reused-evidence.json')));report.reusedEvidence=prior;
  for(const expected of prior.unchangedInputs){const actual=pin.files.find(row=>row.path===expected.path);assert(actual?.sha256===expected.sha256&&actual.bytes===expected.bytes,'Previously qualified model/art input changed: '+expected.path);}
  // One source owner at one held pose across all supported corrected layouts.
  const x=await open();try{
   const off=await x.page.evaluate(snapshot);assert(!report.requests.filter(r=>r.case===x.label).some(r=>r.path.startsWith(OPTIONAL_PREFIX))&&off.observer.contexts.length===0,'Initially-off route loaded optional assets');checkState(off);
   report.cases.push({name:'initial-off',snapshot:off});await control(x.page,'toggle').click();await settled(x.page);const baseline=await x.page.evaluate(snapshot);checkResources(baseline,pin);
   const samePose=(a,b)=>JSON.stringify(a.owner.scene.lastFrame.root)===JSON.stringify(b.owner.scene.lastFrame.root)&&a.owner.scene.route.displayedElapsedMs===b.owner.scene.route.displayedElapsedMs&&a.owner.scene.goalIndex===b.owner.scene.goalIndex;
   async function coherent(){await x.page.waitForFunction(()=>{const o=window.__yardPipIntegration?.snapshot(),s=o?.scene,c=document.querySelector('.cy-scene > canvas'),r=c?.getBoundingClientRect();return o?.mode==='pip-prototype'&&o.enabled&&s?.ready&&s.settled&&!s.viewportBlocked&&!s.scheduler.pending&&r&&c.checkVisibility({checkOpacity:true,checkVisibilityCSS:true})&&document.querySelector('.cy-pip-direct-layer canvas')?.checkVisibility({checkOpacity:true,checkVisibilityCSS:true})&&Math.abs(s.projection.width-r.width)<.5&&Math.abs(s.projection.height-r.height)<.5&&c.width===Math.round(r.width*Math.min(devicePixelRatio||1,2))&&c.height===Math.round(r.height*Math.min(devicePixelRatio||1,2));},null,{timeout:7000});}
   const matrix={name:'supported-held-resize-matrix',viewports:[]};report.cases.push(matrix);let previous=baseline;
   for(const[width,height]of[[390,844],[568,320],[844,390],[320,568],[390,844]]){
    const index=matrix.viewports.length,row={index,width,height};matrix.viewports.push(row);await x.page.setViewportSize({width,height});
    try{await coherent();const current=await x.page.evaluate(snapshot),l=await layout(x.page);row.snapshot=current;row.layout=l;row.still=await still(x.page,`focused-${index}-${width}x${height}`);checkLayout(l);assert(l.stage.width>=280&&l.stage.height>=192,'Supported viewport does not provide admitted stage');assert(samePose(baseline,current),'Supported resize changed held pose or route');assert(current.owner.transitions===baseline.owner.transitions&&current.owner.retirements===baseline.owner.retirements,'Supported resize replaced owner or silently restarted preview');checkResources(current,pin);if(index>0)assert(current.owner.scene.frameCount>previous.owner.scene.frameCount&&current.owner.scene.renderer.directPresentations>previous.owner.scene.renderer.directPresentations,'Changed viewport did not produce a fresh native presentation');previous=current;row.mechanicalAcceptance='PASS_UPDATED_PIXELS_REQUIRE_REVIEW';}
    catch(error){row.error=String(error);row.mechanicalAcceptance='FAILED_OR_UNRESOLVED';row.snapshot??=await x.page.evaluate(snapshot).catch(e=>({error:String(e)}));row.layout??=await layout(x.page).catch(e=>({error:String(e)}));if(!row.still)row.still=await still(x.page,`focused-failure-${index}-${width}x${height}`).catch(()=>null);report.errors.push(`${width}x${height}: ${error}`);}
   }
   // Product contract B: insufficient viewport pauses the same lease/pose.
   const beforeBlock=await x.page.evaluate(snapshot);await x.page.setViewportSize({width:568,height:240});await x.page.waitForFunction(()=>window.__yardPipIntegration?.snapshot()?.scene?.viewportBlocked===true,null,{timeout:7000});
   const blockedStart=await x.page.evaluate(snapshot);await sleep(180);const blockedEnd=await x.page.evaluate(snapshot),blockedLayout=await layout(x.page);
   assert(blockedEnd.owner.mode==='pip-prototype'&&blockedEnd.owner.enabled,'Recoverable viewport refusal lost preview intent');assert(blockedEnd.owner.scene.rejectedViewport.width<280||blockedEnd.owner.scene.rejectedViewport.height<192,'Negative viewport case did not actually violate stage capability');assert(samePose(beforeBlock,blockedEnd),'Blocked viewport changed held pose');assert(blockedEnd.owner.transitions===beforeBlock.owner.transitions&&blockedEnd.owner.retirements===beforeBlock.owner.retirements,'Blocked viewport changed owner');assert(blockedEnd.owner.scene.frameCount===blockedStart.owner.scene.frameCount&&!blockedEnd.owner.scene.scheduler.pending,'Blocked viewport kept rendering');
   const blockedSurface=await x.page.locator('.cy-pip-direct-layer').evaluate(e=>{const s=getComputedStyle(e),canvases=[...e.querySelectorAll('canvas')].map(c=>({visible:c.checkVisibility({checkOpacity:true,checkVisibilityCSS:true}),display:getComputedStyle(c).display,visibility:getComputedStyle(c).visibility}));return{hidden:canvases.length===0||canvases.every(c=>!c.visible),display:s.display,visibility:s.visibility,opacity:s.opacity,canvases};});assert(blockedSurface.hidden,'Invalid direct surface was not hidden');
   report.cases.push({name:'undersized-retains-intent-pose-owner',before:beforeBlock,start:blockedStart,end:blockedEnd,layout:blockedLayout,surface:blockedSurface,still:await still(x.page,'focused-undersized')});
   await x.page.setViewportSize({width:844,height:390});await coherent();const recovered=await x.page.evaluate(snapshot),recoveryLayout=await layout(x.page);checkLayout(recoveryLayout);checkResources(recovered,pin);assert(samePose(beforeBlock,recovered),'Automatic landscape resume changed held pose');assert(!recovered.owner.scene.pauseReasons.includes('viewport')&&recovered.owner.scene.frameCount>blockedEnd.owner.scene.frameCount,'Supported recovery did not clear pause and redraw');assert(recovered.owner.transitions===beforeBlock.owner.transitions&&recovered.owner.retirements===beforeBlock.owner.retirements,'Recovery restarted renderer or lease');report.cases.push({name:'automatic-landscape-recovery-no-click',snapshot:recovered,layout:recoveryLayout,still:await still(x.page,'focused-landscape-recovered')});
   await control(x.page,'toggle').click();await x.page.waitForFunction(()=>{const o=window.__yardPipIntegration.snapshot();return o.mode==='legacy'&&!o.enabled&&o.scene.ready;},null,{timeout:14000});const disabled=await x.page.evaluate(snapshot);assert(disabled.directCanvases===0,'Disable left direct surface mounted');checkState(disabled);report.cases.push({name:'explicit-disable-completed-legacy-restoration',snapshot:disabled,still:await still(x.page,'focused-disabled')});
   // Re-enable after real restoration at landscape; this is intentional new entry.
   await control(x.page,'toggle').click();await settled(x.page);await coherent();const reentered=await x.page.evaluate(snapshot);checkResources(reentered,pin);report.cases.push({name:'explicit-landscape-reentry',snapshot:reentered});
   // The new clock pause reason also runs through an actual moving route, without video.
   await control(x.page,'goal-B').click();await x.page.waitForFunction(()=>{const s=window.__yardPipIntegration.snapshot().scene;return s.route.displayedElapsedMs>0&&!s.settled;},null,{timeout:7000});const movingBefore=await x.page.evaluate(snapshot);
   await x.page.setViewportSize({width:568,height:240});await x.page.waitForFunction(()=>window.__yardPipIntegration.snapshot().scene.viewportBlocked,null,{timeout:7000});const movingBlockedStart=await x.page.evaluate(snapshot);await sleep(220);const movingBlockedEnd=await x.page.evaluate(snapshot);
   assert(movingBlockedStart.owner.scene.route.displayedElapsedMs===movingBlockedEnd.owner.scene.route.displayedElapsedMs&&movingBlockedStart.owner.scene.route.activeElapsedMs===movingBlockedEnd.owner.scene.route.activeElapsedMs,'Blocked native moving route did not pause');assert(movingBlockedStart.owner.scene.frameCount===movingBlockedEnd.owner.scene.frameCount&&!movingBlockedEnd.owner.scene.scheduler.pending,'Blocked moving route continued drawing');
   await x.page.setViewportSize({width:844,height:390});await x.page.waitForFunction(elapsed=>{const s=window.__yardPipIntegration.snapshot().scene;return !s.viewportBlocked&&!s.pauseReasons.includes('viewport')&&s.route.displayedElapsedMs>elapsed;},movingBlockedEnd.owner.scene.route.displayedElapsedMs,{timeout:7000});const movingResumed=await x.page.evaluate(snapshot);await settled(x.page);const movingSettled=await x.page.evaluate(snapshot);
   assert(movingSettled.owner.scene.goalIndex===1&&movingSettled.owner.transitions===movingBefore.owner.transitions&&movingSettled.owner.retirements===movingBefore.owner.retirements,'Moving resize recovery restarted route or owner');assert(!movingSettled.owner.scene.scheduler.pending,'Resumed route did not become idle');checkResources(movingSettled,pin);report.cases.push({name:'native-moving-viewport-pause-resume',before:movingBefore,blockedStart:movingBlockedStart,blockedEnd:movingBlockedEnd,resumed:movingResumed,settled:movingSettled,qualification:'Native displayed route clock/presentation observations; no new video, GPU-completion or hardware claim'});
  }finally{await x.context.close();}
  // Initial admission while undersized must wait before model/background loads.
  const small=await open({viewport:{width:568,height:240}});try{
   const offset=report.requests.length;await control(small.page,'toggle').click();await small.page.waitForFunction(()=>window.__yardPipIntegration?.snapshot()?.scene?.viewportBlocked===true,null,{timeout:7000});const waiting=await small.page.evaluate(snapshot);
   const lateRequests=report.requests.slice(offset);assert(!lateRequests.some(r=>r.path===MODEL||r.path==='pip-prototype/assets/clean-garden.png'||r.path.startsWith('pip-prototype/vendor/')),'Undersized initial admission loaded large optional resources');assert(waiting.owner.enabled&&waiting.owner.mode==='pip-prototype'&&waiting.directCanvases===0,'Initial undersized admission created a direct renderer');
   await control(small.page,'toggle').click();await small.page.waitForFunction(()=>{const o=window.__yardPipIntegration.snapshot();return o.mode==='legacy'&&!o.enabled&&o.scene.ready;},null,{timeout:14000});const cancelled=await small.page.evaluate(snapshot);assert(cancelled.directCanvases===0,'Cancelling viewport wait leaked renderer');checkState(cancelled);report.cases.push({name:'undersized-initial-wait-cancelled',waiting,cancelled,requests:lateRequests});
  }finally{await small.context.close();}
  const late=await open({holdModel:true,viewport:{width:844,height:390}});try{await control(late.page,'toggle').click();await Promise.race([late.modelRequested,sleep(10000).then(()=>{throw Error('Delayed GLB request not observed');})]);const pending=await late.page.evaluate(snapshot);await control(late.page,'toggle').click();late.release();await late.page.waitForFunction(()=>{const o=window.__yardPipIntegration.snapshot();return o.mode==='legacy'&&!o.enabled&&o.scene.ready;},null,{timeout:14000});const complete=await late.page.evaluate(snapshot);assert(complete.directCanvases===0,'Late init survived Disable');checkState(complete);report.cases.push({name:'landscape-late-init-disable',pending,complete,still:await still(late.page,'focused-late-init-disabled')});}finally{late.release();await late.context.close();}
 }catch(e){report.errors.push(String(e));}
 finally{clearTimeout(timer);await browser?.close();await new Promise(r=>server.close(r));}
 report.recording={newRecording:false,reusedNativeRun:37438559317,qualification:'The prior unmodified model/portrait/depth/7.68-second clip evidence is reused; this run checks changed layout and viewport recovery only.'};
 report.status=report.errors.length||report.blockedRequests.length||report.failedResponses.length?'FAILURE_OR_MISSING_EVIDENCE':'NATIVE_EVIDENCE_READY_VISUAL_REVIEW_PENDING';
 // Raw failure is retained when feasible. Evidence is never silently called complete.
 report.rawEvidence={newRecording:false,priorUniqueRecordingPreserved:true,sourceRun:37438559317};
 report.artifacts=[];for(const f of await list(OUT)){if(f==='report.json'||f==='index.html')continue;const b=await fs.readFile(path.join(OUT,f));report.artifacts.push({path:f,bytes:b.length,sha256:sha(b)});}
 const escaped=s=>s.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 await fs.writeFile(path.join(OUT,'index.html'),'<!doctype html><meta charset="utf-8"><title>Actual Yard QA evidence</title><h1>'+report.status+'</h1><p>Local offline evidence. Visual review remains pending. Open report.json for limits, failure details and resource/lifecycle observations.</p>'+report.errors.map(e=>'<pre>'+escaped(e)+'</pre>').join('')+report.artifacts.map(a=>/\.(?:png|jpg)$/.test(a.path)?'<figure><img style="max-width:100%" src="'+a.path+'"><figcaption>'+a.path+'</figcaption></figure>':a.path.endsWith('.webm')?'<video controls style="max-width:100%" src="'+a.path+'"></video>':'<p>'+a.path+'</p>').join(''));
 await fs.writeFile(path.join(OUT,'report.json'),JSON.stringify(report,null,2));let bytes=0;for(const f of await list(OUT))bytes+=(await fs.stat(path.join(OUT,f))).size;assert(bytes<=CAP,'Eight MiB cap exceeded: full evidence retained locally, upload forbidden');console.log(JSON.stringify({status:report.status,bytes}));if(report.status.startsWith('FAILURE'))process.exitCode=1;
}
if(process.argv.includes('--verify-only')){await verify();console.log('Frozen candidate verified; no browser/server/job started.');}else try{await run();}catch(error){report.errors.push(String(error));report.status='SETUP_OR_EARLY_FAILURE';await fs.mkdir(OUT,{recursive:true});await fs.writeFile(path.join(OUT,'report.json'),JSON.stringify(report,null,2));process.exitCode=1;}
