import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {fileURLToPath,pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const here=path.dirname(fileURLToPath(import.meta.url)),saved=process.env.YARD_SAVED_VISIT_QA||path.resolve(here,'../saved-pip-visit'),{assetRoot,resolveSource}=await import(pathToFileURL(path.join(saved,'config.mjs')));
const require=createRequire(path.join(process.env.YARD_DEPENDENCY_ROOT||assetRoot,'package.json')),{chromium}=require('@playwright/test');
const out=process.env.YARD_PAINTED_OUTPUT||path.join(here,'native-evidence');await fs.mkdir(out,{recursive:true});
const sourcePins=JSON.parse(await fs.readFile(path.join(saved,'source-provenance.json'))),assetPins=JSON.parse(await fs.readFile(path.join(saved,'asset-provenance.json'))),artPins=JSON.parse(await fs.readFile(path.join(here,'art-source-provenance.json')));
const pins=new Map([...sourcePins.baseline,...sourcePins.overlay,...assetPins.assets,...artPins.files].map(r=>[r.path,r.sha256]));const hash=b=>createHash('sha256').update(b).digest('hex');
for(const [relative,expected]of pins)assert.equal(hash(await fs.readFile(resolveSource(relative))),expected,'Source mismatch '+relative);
if(process.env.YARD_ART_SOURCE_ONLY==='1'){console.log(JSON.stringify({pinnedSources:pins.size,status:'source-identities-verified-browser-not-started'}));process.exit(0);}
const errors=[],served=new Map(),metrics=[],mime=f=>f.endsWith('.json')?'application/json':/\.(mjs|js)$/.test(f)?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.png')?'image/png':'application/octet-stream';
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox']});
try{for(const viewport of [{width:320,height:568,deviceScaleFactor:1},{width:390,height:844,deviceScaleFactor:2},{width:844,height:390,deviceScaleFactor:1}]){
 const {deviceScaleFactor,...size}=viewport,id=`${size.width}x${size.height}-dpr${deviceScaleFactor}`,context=await browser.newContext({viewport:size,deviceScaleFactor,isMobile:true,hasTouch:true,recordVideo:{dir:path.join(out,'raw-video'),size}}),page=await context.newPage();
 page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname==='/favicon.ico')return route.fulfill({status:204,body:''});try{assert.equal(u.origin,'https://yard-food-art.invalid');let file,body,role='pinned source';if(u.pathname.startsWith('/source/')){const relative=decodeURIComponent(u.pathname.slice(8));file=resolveSource(relative);body=await fs.readFile(file);assert.equal(hash(body),pins.get(relative),'Unpinned source '+relative);if(relative.endsWith('/prototype/calibrated-food.mjs')){body=await fs.readFile(path.join(here,'art-shim.mjs'));role='explicit isolated art shim; default source unchanged';}}else{const name=u.pathname==='/'?'index.html':path.basename(u.pathname);file=path.join(here,name);body=await fs.readFile(file);}served.set(u.pathname,{file,bytes:body.length,sha256:hash(body),role});await route.fulfill({status:200,contentType:mime(file),body});}catch(e){errors.push(u.pathname+': '+e.message);await route.fulfill({status:404,body:'Unavailable pinned input'})}});
 try{await page.goto('https://yard-food-art.invalid/');await page.waitForFunction(()=>window.paintedFoodQA?.ready,{},{timeout:30000});for(const state of ['empty','kibble','berry_plate','bonito_bowl']){const d=await page.evaluate(s=>window.paintedFoodQA.renderArtState(s),state);assert.equal(d.drawn,true);assert.equal(d.renderer.canonicalFood.selection.state,state);assert.equal(d.rgba.fits,true);const ledger=d.renderer.canonicalFood.ledger;for(const key of ['rgba','knownCPU','estimatedGPU'])assert(ledger.total[key]<=ledger.limits[key]);assert.equal(d.renderer.canonicalFood.resources.imageTextureBytes,65536);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:path.join(out,`${id}-${state}.png`)});metrics.push({viewport:id,state,...d});await page.waitForTimeout(350);}
 const before=await page.screenshot();await fs.writeFile(path.join(out,`${id}-before-loss.png`),before);await page.evaluate(()=>window.paintedFoodQA.contextCycle());await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const restored=await page.screenshot();await fs.writeFile(path.join(out,`${id}-after-retirement-recovery.png`),restored);assert(before.equals(restored),'Restored texture/native pixels differ');await page.evaluate(()=>window.paintedFoodQA.fresh());await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert(before.equals(await page.screenshot()),'Fresh owner pixels differ');metrics.push({viewport:id,contextRecoveryViaFullRetirementPixels:true,freshOwnerPixels:true});await page.screenshot({path:path.join(out,`${id}-restored.png`)});
 }finally{await context.close();} }
 assert.deepEqual(errors,[]);
}finally{await browser.close();await fs.writeFile(path.join(out,'painted-food-native-report.json'),JSON.stringify({scope:'Actual shared-depth Pip renderer and fixed garden camera; art pose fixture, not app-shell or mouth-contact acceptance',defaultEconomicDescriptorUnchanged:true,artHeightEnvelope:3.14,metrics,errors,served:[...served.entries()]},null,2)+'\n');}
