import {writeFile}from'node:fs/promises';import path from'node:path';import{createHash}from'node:crypto';import{delay,until}from'./core.mjs';import{animationSnapshot}from'./animation-readiness.mjs';
const json=JSON.stringify;
function finder(locator){const q=typeof locator==='string'?{css:locator}:locator;return`(()=>{const q=${json(q)};let a=[...d.querySelectorAll(q.css||'button')];if(q.text!==undefined)a=a.filter(e=>(e.textContent||'').includes(q.text));if(q.name!==undefined)a=a.filter(e=>(e.getAttribute('aria-label')||e.textContent||'').trim()===q.name);return a[q.index||0]||null;})()`;}
export class Actor{
 constructor(cdp,sessionId,baseUrl,record,directory,signal,browserContextId){Object.assign(this,{cdp,sessionId,baseUrl,record,directory,signal,browserContextId});this.captureIndex=0;this.touch=true;}
 send(method,params={}){return this.cdp.send(method,params,this.sessionId,{signal:this.signal});}
 async evaluate(body){const expression=`(async()=>{if(location.origin!==${json(this.baseUrl)})throw Error('Refusing non-preview origin');const f=document.getElementById('game-frame');const d=f?.contentDocument||document;const w=d.defaultView;return(async()=>{${body}})();})()`;const r=await this.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text||'Page evaluation failed');return r.result?.value;}
 async snapshot(){return this.evaluate("if(!w.__yardQA?.snapshot)throw Error('Read-only Yard QA hook missing');return w.__yardQA.snapshot();");}
 async waitState(predicate,label='Expected preview state did not appear',{timeout=30000,interval=100}={}){const end=Date.now()+timeout;let s;while(Date.now()<end){s=await this.snapshot();if(s.fatal||s.atlas?.error||s.view?.blocker)throw Error('Preview blocked: '+json(s.fatal||s.atlas?.error||s.view?.blocker));if(predicate(s))return s;await delay(interval,this.signal);}throw Error(label+': '+json({modelTime:s?.modelTime,pets:s?.view?.pets,episodeComplete:s?.episodeComplete}));}
 async navigate(options={}){const{scenario='mouse',width=390,height=760,dpr=1,touch=true,insets=false}=options;this.touch=touch;this.record.viewport={width,height,dpr,touch,insets,scenario,kind:'Actual desktop Chrome/Edge CSS viewport and touch emulation; not a real phone or Telegram client'};
 await this.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:dpr,mobile:false});await this.send('Emulation.setTouchEmulationEnabled',{enabled:touch,maxTouchPoints:1});
 const q=new URLSearchParams({scenario,insets:insets?'1':'0'});await this.send('Page.navigate',{url:`${this.baseUrl}/__qa_host.html?${q}`});await this.ready();
 const m=await this.frameMetrics();this.record.measured=m;const expectedHeight=height-(insets?44:0);if(Math.abs(m.width-width)>1.1||Math.abs(m.height-expectedHeight)>1.1)throw Error('Actual game iframe viewport does not match requested test size');
 await this.check('Synthetic preview only, no production data',"return w.__yardQA.snapshot().syntheticPreviewOnly===true;");await this.checkLayout();}
 async ready(){await until(async()=>{const s=await this.evaluate('return w.__yardQA?.snapshot?.()||null;');if(s?.fatal)throw Error('Preview fatal: '+s.fatal);return s?.view&&s.scene?.ppu>0&&s.renderReady===true;},{timeout:30000,message:'Yard did not mount with its read-only hook',signal:this.signal});}
 async frameMetrics(){return this.evaluate("const r=f?f.getBoundingClientRect():document.documentElement.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,innerWidth:w.innerWidth,innerHeight:w.innerHeight,dpr:w.devicePixelRatio,timeOrigin:w.performance.timeOrigin};");}
 async check(label,body){const actual=await this.evaluate(body),passed=actual===true;this.record.assertions.push({label,passed,actual});if(!passed)throw Error(`Assertion failed: ${label}: ${json(actual)}`);return actual;}
 async assertValue(label,passed,actual){this.record.assertions.push({label,passed:!!passed,actual});if(!passed)throw Error(`Assertion failed: ${label}: ${json(actual)}`);}
 async waitFor(body,label='State did not appear',{timeout=20000,interval=100}={}){return until(()=>this.evaluate(body),{message:label,timeout,interval,signal:this.signal});}
 async checkLayout(){await this.check('Document has no horizontal overflow',"return d.documentElement.scrollWidth<=w.innerWidth+1;");await this.check('Header, status and all three action controls are inside viewport',"return ['.topbar','.status',...['food','decor','guests'].map(x=>'[data-panel='+x+']')].every(s=>{const e=d.querySelector(s),r=e?.getBoundingClientRect();return r&&r.width>0&&r.height>0&&r.x>=-1&&r.y>=-1&&r.right<=w.innerWidth+1&&r.bottom<=w.innerHeight+1;});");await this.check('Canvas has positive measurable area',"const r=d.querySelector('#yard').getBoundingClientRect();return r.width>80&&r.height>=80;");}
 async click(locator){const p=await this.evaluate(`const e=${finder(locator)};if(!e)throw Error('Missing click target');if(e.disabled)throw Error('Disabled click target');e.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'});const r=e.getBoundingClientRect(),fr=f?f.getBoundingClientRect():{x:0,y:0},x=r.x+r.width/2,y=r.y+r.height/2,hit=d.elementFromPoint(x,y);if(!r.width||!r.height||!hit||!(hit===e||e.contains(hit)))throw Error('Click target hidden or obscured');return{x:fr.x+x,y:fr.y+y};`);await this.clickPoint(p);this.record.actions.push({type:'realPointerClick',locator,point:p});}
 async clickPoint(p){if(this.touch){await this.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p.x,y:p.y,id:1,radiusX:1,radiusY:1,force:1}]});await this.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await this.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:p.x,y:p.y,button:'none'});await this.send('Input.dispatchMouseEvent',{type:'mousePressed',x:p.x,y:p.y,button:'left',buttons:1,clickCount:1});await this.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.x,y:p.y,button:'left',buttons:0,clickCount:1});}await delay(80,this.signal);}
 async canvasPoint(p){return this.evaluate(`const r=d.querySelector('#yard').getBoundingClientRect(),fr=f?f.getBoundingClientRect():{x:0,y:0};return{x:fr.x+r.x+${Number(p.x)},y:fr.y+r.y+${Number(p.y)}};`);}
 async selectProp(slot){const s=await this.snapshot(),p=s.scene.props.find(p=>p.slotId===slot);if(!p?.anchor)throw Error('Prop projection missing');await this.clickPoint(await this.canvasPoint(p.anchor));this.record.actions.push({type:'realCanvasSelect',slot});await this.waitFor(`return w.__yardQA.snapshot().selected===${json(slot)};`,'Canvas prop did not select');}
 async dragSelectedTo(point){const s=await this.snapshot(),from=s.scene.props.find(p=>p.slotId===s.selected)?.anchor;if(!from)throw Error('No selected prop');const a=await this.canvasPoint(from),b=await this.canvasPoint(point);
 if(this.touch)await this.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:1,radiusX:1,radiusY:1,force:1}]});else await this.send('Input.dispatchMouseEvent',{type:'mousePressed',...a,button:'left',buttons:1,clickCount:1});
 for(let i=1;i<=10;i++){const p={x:a.x+(b.x-a.x)*i/10,y:a.y+(b.y-a.y)*i/10};if(this.touch)await this.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...p,id:1,radiusX:1,radiusY:1,force:1}]});else await this.send('Input.dispatchMouseEvent',{type:'mouseMoved',...p,button:'left',buttons:1});await delay(25,this.signal);}
 if(this.touch)await this.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});else await this.send('Input.dispatchMouseEvent',{type:'mouseReleased',...b,button:'left',buttons:0,clickCount:1});this.record.actions.push({type:'realCanvasDrag',from:a,to:b});await delay(100,this.signal);}
 async key(key,extra={}){const map={Enter:['Enter',13],Escape:['Escape',27],Tab:['Tab',9],' ':['Space',32]},[code,windowsVirtualKeyCode]=map[key]||[key,0];await this.send('Input.dispatchKeyEvent',{type:key==='Enter'?'keyDown':'rawKeyDown',key,code,windowsVirtualKeyCode,...(key==='Enter'?{text:'\r',unmodifiedText:'\r'}:{}),...extra});await this.send('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode,...extra});this.record.actions.push({type:'realKeyboard',key});await delay(80,this.signal);}
 async openPanel(kind){await this.click(`[data-panel="${kind}"]`);await this.waitFor("return d.querySelector('#panel')?.open===true;",'Panel did not open');await this.check('Panel and its close control are within usable viewport',"return ['#panel','#panel #close-panel'].every(s=>{const r=d.querySelector(s).getBoundingClientRect();return r.width&&r.height&&r.x>=-1&&r.y>=-1&&r.right<=w.innerWidth+1&&r.bottom<=w.innerHeight+1;});");}
 async scrollPanelToEnd(){
  for(let n=0;n<10;n++){
   const q=await this.evaluate("const e=d.querySelector('#panel'),r=e.getBoundingClientRect(),fr=f?f.getBoundingClientRect():{x:0,y:0};return{top:e.scrollTop,max:e.scrollHeight-e.clientHeight,x:fr.x+r.x+r.width/2,y0:fr.y+r.bottom-18,y1:fr.y+r.y+70};");
   if(q.top>=q.max-1){this.record.actions.push({type:'realPanelScroll',atEnd:true,scrollTop:q.top});return;}
   if(this.touch){await this.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:q.x,y:q.y0,id:1,radiusX:1,radiusY:1,force:1}]});for(let i=1;i<=8;i++){await this.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:q.x,y:q.y0+(q.y1-q.y0)*i/8,id:1,radiusX:1,radiusY:1,force:1}]});await delay(25,this.signal);}await this.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
   else await this.send('Input.dispatchMouseEvent',{type:'mouseWheel',x:q.x,y:q.y0,deltaX:0,deltaY:180});
   await delay(300,this.signal);
  }
  throw Error('Actual panel scroll did not reach the final controls');
 }
 async dismiss(){await this.click('#panel #close-panel');await this.waitFor("return d.querySelector('#panel')?.open===false;",'Explicit panel close did not work');}
 async waitReplacement(oldTimeOrigin,reason='navigation',{timeout=30000,interval=50}={}){
  const deadline=Date.now()+timeout;let last=null;
  while(Date.now()<deadline){
   try{last=await this.evaluate("const s=w.__yardQA?.snapshot?.()||null;return{timeOrigin:w.performance.timeOrigin,readyState:d.readyState,hookReady:!!w.__yardQA?.snapshot,viewReady:!!s?.view,renderReady:s?.renderReady===true,ppu:s?.scene?.ppu||0,fatal:s?.fatal||null};");}
   catch(error){const message=String(error);if(!/Execution context was destroyed|Cannot find context with specified id/.test(message))throw error;last={navigationContextPending:true,message};}
   if(last?.fatal)throw Error('Replacement preview failed: '+last.fatal);
   if(last?.timeOrigin!==oldTimeOrigin&&last?.hookReady&&last?.viewReady&&last?.renderReady&&last?.ppu>0){this.record.actions.push({type:'observedDocumentReplacement',reason,beforeTimeOrigin:oldTimeOrigin,afterTimeOrigin:last.timeOrigin});return last;}
   await delay(interval,this.signal);
  }
  throw Error('Replacement document did not expose a ready Yard hook within '+timeout+'ms: '+json({reason,oldTimeOrigin,last}));
 }
 async reload(){const before=await this.snapshot(),old=await this.frameMetrics();await this.send('Page.reload',{ignoreCache:true});await this.waitReplacement(old.timeOrigin,'real-page-reload');this.record.actions.push({type:'realPageReload',beforeClock:before.clock,afterClock:(await this.snapshot()).clock});}

 async resize(width,height){const before=await this.frameMetrics();await this.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:this.record.viewport.dpr,mobile:false});await this.waitFor(`return w.innerWidth===${width}&&w.innerHeight===${height};`,'Live resize failed');const after=await this.frameMetrics();await this.assertValue('Resize preserves the same app instance',before.timeOrigin===after.timeOrigin,{before,after});this.record.actions.push({type:'realViewportResize',width,height});await this.checkLayout();}
 async backgroundPause(ms=800){let targetId,sessionId;const before=await this.snapshot();try{({targetId}=await this.cdp.send('Target.createTarget',{url:'about:blank',browserContextId:this.browserContextId}));({sessionId}=await this.cdp.send('Target.attachToTarget',{targetId,flatten:true}));await this.cdp.send('Page.enable',{},sessionId);await this.cdp.send('Page.bringToFront',{},sessionId);await this.waitFor('return d.hidden===true;','Owned background tab did not actually hide Yard');const hidden=await this.snapshot();await delay(ms,this.signal);const after=await this.snapshot();await this.assertValue('Actual hidden tab pauses the presentation clock',hidden.clock.screenMs===after.clock.screenMs,{before:before.clock,hidden:hidden.clock,after:after.clock});}finally{if(targetId)await this.cdp.send('Target.closeTarget',{targetId}).catch(()=>{});await this.send('Page.bringToFront');}this.record.actions.push({type:'ownedBackgroundTabPause',milliseconds:ms});}
 async captureState(name){const s=await this.snapshot();const filename=name.replace(/[^a-z0-9_-]/gi,'-')+'.synthetic-preview.json';await writeFile(path.join(this.directory,filename),json({syntheticPreviewOnly:true,source:'read-only __yardQA.snapshot',snapshot:s},null,2));this.record.stateFiles??=[];this.record.stateFiles.push(filename);return s;}
 async screenshot(name){const readiness=await this.evaluate(`const collect=${animationSnapshot.toString()};const end=Date.now()+2000;let s;do{s=collect(d);if(!s.finite.length)break;await Promise.race([Promise.allSettled(s.finite.map(a=>a.finished)),new Promise(r=>setTimeout(r,Math.max(1,end-Date.now())))]);}while(Date.now()<end);s=collect(d);return{finiteAnimationsSettled:!s.finite.length,remainingFinite:s.finite.length,ignoredInfinite:s.ignoredInfinite.length,remainingDetails:s.details};`);this.record.assertions.push({label:'Finite CSS/Web Animations settled before capture; no pressure exemptions',passed:readiness.finiteAnimationsSettled,actual:readiness});const r=await this.frameMetrics();const{data}=await this.send('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:true,clip:{x:Math.max(0,r.x),y:Math.max(0,r.y),width:r.width,height:r.height,scale:1}});const bytes=Buffer.from(data,'base64');if(bytes.length<100||bytes.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('No genuine browser PNG');const filename=`${String(++this.captureIndex).padStart(2,'0')}-${name.replace(/[^a-z0-9_-]/gi,'-')}.png`;await writeFile(path.join(this.directory,filename),bytes);this.record.screenshots.push({file:filename,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),source:'Chrome DevTools Page.captureScreenshot',pngWidth:bytes.readUInt32BE(16),pngHeight:bytes.readUInt32BE(20),viewport:r,readiness});return filename;}
}
