import {assessEpisodeTiming,replayPreservation} from './episode-evidence.mjs';
import {placementAccuracy} from './placement-accuracy.mjs';
/** Real UI only: read-only snapshot observations plus genuine CDP pointer/keys.
 * Fresh app defaults are labelled synthetic; no saves or gameplay are injected. */
const view=(width,height,rest={})=>({width,height,dpr:1,touch:true,scenario:'mouse',...rest});
async function panels(a){await a.screenshot('loaded-yard');for(const kind of['food','decor','guests']){await a.openPanel(kind);await a.screenshot(`${kind}-panel`);if(['decor','guests'].includes(kind)&&a.record.viewport.height<=216){await a.scrollPanelToEnd();await a.check('Compact panel scroll reaches final content with sticky close visible',"const e=d.querySelector('#panel'),b=e.querySelector('#panel-content').lastElementChild,r=b.getBoundingClientRect(),c=e.querySelector('#close-panel').getBoundingClientRect();return e.scrollTop>0&&r.bottom<=w.innerHeight&&r.top>=0&&c.top>=0&&c.bottom<=w.innerHeight;");await a.screenshot(`${kind}-panel-scrolled`);}await a.dismiss();}await a.check('Normal UI has no fatal or reported app errors',"const s=w.__yardQA.snapshot();return !s.fatal&&s.errors.length===0;");await a.captureState('panels-complete');}
async function placement(a){const before=await a.snapshot();await a.selectProp('mouse');const target=before.scene.props.find(p=>p.slotId==='cushion').anchor;await a.dragSelectedTo(target);
 await a.check('Collision placement is rejected by the actual UI/kernel',"const s=w.__yardQA.snapshot();return s.ghost?.valid===false&&d.querySelector('#confirm-placement').disabled;");await a.screenshot('invalid-placement');await a.click('#cancel-placement');await a.check('Cancel removes placement ghost',"return w.__yardQA.snapshot().ghost===null;");
 const s=await a.snapshot(),candidate=s.scene.props.find(p=>p.slotId==='mouse').validMove;await a.selectProp('mouse');await a.dragSelectedTo(candidate);await a.check('Hook candidate is actually accepted by UI validation',"const s=w.__yardQA.snapshot();return s.ghost?.valid===true&&!d.querySelector('#confirm-placement').disabled;");await a.screenshot('valid-placement');await a.click('#confirm-placement');await a.waitState(s=>s.ghost===null,'Valid placement did not commit');
 const after=await a.snapshot(),old=before.view.props.find(p=>p.slotId==='mouse').transform,moved=after.view.props.find(p=>p.slotId==='mouse').transform,accuracy=placementAccuracy({old,moved,targetPx:candidate,actualPx:after.scene.props.find(p=>p.slotId==='mouse').anchor});await a.reload();const restored=await a.snapshot();await a.screenshot('placement-after-reload');await a.captureState('placement-restored');await a.assertValue('Local reload preserves committed placement exactly',JSON.stringify(restored.view.props.find(p=>p.slotId==='mouse').transform)===JSON.stringify(moved),restored.view.props);await a.assertValue('Real placement reaches requested +2 yard point within model and subpixel precision',accuracy.passed,{old,moved,targetPx:candidate,actualPx:after.scene.props.find(p=>p.slotId==='mouse').anchor,...accuracy});}
async function keyboardAndResize(a){await a.openPanel('food');for(let i=0;i<10&&!await a.evaluate("return d.activeElement===d.querySelector('#panel #close-panel');");i++)await a.key('Tab');await a.check('Keyboard focus reaches explicit panel close',"return d.activeElement===d.querySelector('#panel #close-panel');");await a.key('Enter');await a.waitFor("return d.querySelector('#panel').open===false;",'Enter did not activate explicit panel close');await a.screenshot('keyboard-closed-panel');await a.resize(520,216);await a.openPanel('decor');await a.screenshot('live-compact-landscape');await a.dismiss();await a.resize(320,464);await a.screenshot('returned-compact-portrait');}
async function observeRealTurn(a){
 const first=await a.waitState(s=>s.view.pets.some(p=>p.motion?.kind==='turn'&&p.motion.atMs>=150&&p.motion.atMs<700),'Authored entry turn never appeared',{timeout:120000});
 const pet=first.view.pets.find(p=>p.motion?.kind==='turn'),pose=first.presentationPoses.find(p=>p.visitId===pet.visitId);await a.assertValue('Turn uses authored media instead of a walking-facing snap',pose?.kind==='turn'&&pose.index>0,{pet,pose});await a.screenshot('turn-early-planted-step');await a.captureState('turn-early');
 const mid=await a.waitState(s=>s.view.pets.some(p=>p.visitId===pet.visitId&&p.motion?.kind==='turn'&&p.motion.fromFacing===pet.motion.fromFacing&&p.motion.direction===pet.motion.direction&&p.motion.atMs>=1100&&p.motion.atMs<1900),'Middle of the same turn was missed',{timeout:10000});
 const mp=mid.view.pets.find(p=>p.visitId===pet.visitId),mq=mid.presentationPoses.find(p=>p.visitId===pet.visitId);await a.assertValue('Fixed-root turn advances distinct real poses without sliding actor position',Math.hypot(mp.position.x-pet.position.x,mp.position.y-pet.position.y)<1e-8&&mq.mediaId===pose.mediaId&&mq.index>pose.index,{early:{position:pet.position,pose},middle:{position:mp.position,pose:mq}});await a.screenshot('turn-middle-weight-shift');
 await a.captureState('turn-before-reload-timing');await a.backgroundPause(500);const saved=await a.evaluate("const s=w.__yardQA.snapshot();return JSON.parse(w.localStorage.getItem(s.saveKey)).payload;");await a.reload();const restored=await a.snapshot();await a.assertValue('Reload preserves the saved in-progress turn presentation cursor',restored.clock.screenMs>=saved.clock.screenMs,{savedClock:saved.clock,restoredClock:restored.clock,poses:restored.presentationPoses});await a.captureState('turn-reloaded');
}
async function fullInteraction(a,scenario){const slot=scenario==='cushion'?'cushion':'mouse';await a.openPanel('food');await a.click({css:'#panel-content .row button',name:'Наполнить'});await a.waitFor("return !d.querySelector('#panel').open;",'Feeding did not close panel');await a.check('Real feeding populates bowl',"return w.__yardQA.snapshot().view.bowls.some(b=>b.foodId==='kibble'&&b.servings>0);");await a.screenshot('food-placed');
 if(scenario==='mouse')await observeRealTurn(a);
 const active=await a.waitState(s=>s.view.pets.some(p=>p.phase==='active-clip'&&p.assignedSlotId===slot),'Full interaction never started',{timeout:120000});await a.captureState('interaction-start');
 await a.assertValue('Active clip owns exactly its selected prop',active.view.props.find(p=>p.slotId===slot)?.drawStandalone===false&&active.view.props.find(p=>p.slotId===slot)?.reserved===true,active.view.props);
 await a.openPanel('decor');await a.check('Reserved prop cannot be selected for movement',`const s=w.__yardQA.snapshot(),index=s.view.props.findIndex(p=>p.slotId===${JSON.stringify(slot)});return index>=0&&d.querySelectorAll('#panel-content .row button')[index]?.disabled===true;`);await a.screenshot('reserved-prop-locked');await a.dismiss();
 const at=ms=>a.waitState(s=>s.view.pets.some(p=>p.phase==='active-clip'&&p.clipAtMs>=ms),'Expected authored clip point was missed',{timeout:90000});
 if(scenario==='mouse'){
  await at(3250);await a.screenshot('actual-mouse-tap-window');await a.captureState('mouse-contact-observed');await at(4000);
  await a.captureState('mouse-before-midclip-reload-timing');await a.backgroundPause(900);const saved=await a.evaluate("const s=w.__yardQA.snapshot();return JSON.parse(w.localStorage.getItem(s.saveKey)).payload;");await a.reload();const restored=await a.snapshot();await a.assertValue('Mid-visit reload never rewinds earlier than the saved presentation point',restored.clock.screenMs>=saved.clock.screenMs,{savedClock:saved.clock,restoredClock:restored.clock});await a.captureState('mouse-reloaded-mid-visit');
 }else{await at(10000);await a.screenshot('actual-cushion-curl-rest');await a.captureState('cushion-rest-observed');await at(15400);await a.screenshot('actual-step-off');await at(19200);await a.screenshot('canonical-walk-bridge');}
 const complete=await a.waitState(s=>s.episodeComplete,'Full interaction/departure did not complete',{timeout:120000}),episodeTiming=assessEpisodeTiming(complete);await a.captureState('episode-ended-before-gift-reload');await a.assertValue('Actor departs and all props return to standalone scene ownership',complete.view.pets.length===0&&complete.view.props.every(p=>p.drawStandalone&&!p.reserved),complete.view);
 if(scenario==='mouse'){const initial=active.view.props.find(p=>p.slotId==='mouse').transform,final=complete.view.props.find(p=>p.slotId==='mouse').transform;await a.assertValue('Mouse recoil/yaw persists after full departure',Math.abs(final.x-initial.x-1.04)<1e-6&&Math.abs(final.y-initial.y+3.04)<1e-6&&Math.abs(final.rotationZ-.1)<1e-7,{initial,final});}
 await a.screenshot('departed-persistent-prop');await a.assertValue('Completed visit exposes a collectible gift',complete.view.pendingGifts.length>0,complete.view.pendingGifts);await a.openPanel('guests');await a.screenshot('gift-before-collect');await a.click({css:'#panel-content .row button',name:'Забрать'});
 await a.check('One real collect empties pending gifts and disables repeated collect',"const s=w.__yardQA.snapshot();return s.view.pendingGifts.length===0&&d.querySelector('#panel-content .row button').disabled===true;");const claimed=await a.snapshot();await a.screenshot('gift-collected-once');await a.dismiss();await a.captureState('claimed-before-persistence-reload-timing');await a.reload();const reloaded=await a.snapshot();await a.assertValue('Gift claim and currency/inventory persist without a second grant',reloaded.view.pendingGifts.length===0&&JSON.stringify(reloaded.view.currencies)===JSON.stringify(claimed.view.currencies)&&JSON.stringify(reloaded.ownership)===JSON.stringify(claimed.ownership),{claimed:{currencies:claimed.view.currencies,ownership:claimed.ownership},reloaded:{currencies:reloaded.view.currencies,ownership:reloaded.ownership}});await a.openPanel('guests');await a.check('Reload does not re-enable already claimed gift',"return d.querySelector('#panel-content .row button').disabled===true;");await a.screenshot('gift-once-after-reload');await a.dismiss();await a.captureState('full-episode-complete');
 if(scenario==='mouse'){
  const previous=await a.snapshot(),oldPage=await a.frameMetrics(),oldText=await a.evaluate(`return w.localStorage.getItem(${JSON.stringify(previous.saveKey)});`);await a.openPanel('guests');await a.click({css:'#panel-content .row button',name:'Повторить'});await a.waitReplacement(oldPage.timeOrigin,'explicit-demo-replay');
  const fresh=await a.waitState(s=>s.demoRun!==previous.demoRun&&s.view.canFeed,'Explicit demo replay did not create a new isolated run');const retainedText=await a.evaluate(`return w.localStorage.getItem(${JSON.stringify(previous.saveKey)});`),preservation=replayPreservation(oldText,retainedText);await a.assertValue('Explicit replay preserves the completed gameplay data in the old namespace; only idle presentation clock may advance',fresh.saveKey!==previous.saveKey&&preservation.passed,{oldRun:previous.demoRun,newRun:fresh.demoRun,oldKey:previous.saveKey,newKey:fresh.saveKey,...preservation});await a.reload();const again=await a.snapshot();await a.assertValue('Reload keeps the selected new demo run without an extra gift',again.demoRun===fresh.demoRun&&again.saveKey===fresh.saveKey&&again.view.pendingGifts.length===0&&JSON.stringify(again.view.currencies)===JSON.stringify(fresh.view.currencies),{freshRun:fresh.demoRun,reloadedRun:again.demoRun});await a.screenshot('explicit-demo-replay');await a.captureState('explicit-demo-replay');
 }
 // Run this diagnostic last: optional timing must not prevent the real Replay path.
 await a.assertValue('Bounded active-episode timing was captured before reload and waiting playback clocks stayed held',episodeTiming.passed,episodeTiming.details);
}
export function casesFor({quick=false}={}){const out=[
 {id:'yard-load-panels-390x760',options:view(390,760),run:panels},
 {id:'yard-compact-320x464',options:view(320,464),run:panels},
 {id:'yard-compact-520x216',options:view(520,216),run:panels},
 {id:'yard-valid-invalid-placement-reload',options:view(390,760),run:placement},
 {id:'yard-keyboard-enter-live-resize',options:view(320,464,{touch:false}),run:keyboardAndResize},
 ];if(!quick)out.push(
 {id:'yard-mouse-full-pause-reload-gift-once',options:view(390,760,{scenario:'mouse'}),run:a=>fullInteraction(a,'mouse')},
 {id:'yard-cushion-full-departure-gift-once',options:view(390,760,{scenario:'cushion'}),run:a=>fullInteraction(a,'cushion')},
 {id:'yard-simulated-safe-insets',options:view(390,760,{insets:true}),run:panels});return out;}
