// Zero-dependency local QA helpers. Importing this module never opens a browser.
import {createServer} from 'node:http';
import {createReadStream} from 'node:fs';
import {readFile,realpath,stat,lstat,readdir,open,unlink} from 'node:fs/promises';
import path from 'node:path';
import {deflateRawSync} from 'node:zlib';
import {createHash} from 'node:crypto';
export function abortError(){const error=new Error('QA interrupted by user');error.name='AbortError';return error;}
export const delay=(ms,signal)=>new Promise((resolve,reject)=>{if(signal?.aborted)return reject(abortError());const done=()=>{signal?.removeEventListener('abort',cancel);resolve();},timer=setTimeout(done,ms),cancel=()=>{clearTimeout(timer);signal?.removeEventListener('abort',cancel);reject(abortError());};signal?.addEventListener('abort',cancel,{once:true});});
export async function until(check,{timeout=15000,interval=100,message='Condition timed out',signal}={}){const end=Date.now()+timeout;let last;while(Date.now()<end){if(signal?.aborted)throw abortError();try{const result=await check();if(result)return result;}catch(e){if(e.name==='AbortError')throw e;last=e;}await delay(interval,signal);}throw new Error(`${message}${last?`: ${last.message}`:''}`);}
export function safeRelative(name){return typeof name==='string'&&name.length>0&&!path.isAbsolute(name)&&!name.includes('\\')&&!name.split('/').some(x=>!x||x==='..'||x==='.')&&!name.includes('\0');}
export function browserArguments(profile){if(!path.isAbsolute(profile))throw new Error('Fresh absolute profile required');return [`--user-data-dir=${profile}`,'--remote-debugging-address=127.0.0.1','--remote-debugging-port=0','--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-sync','--disable-extensions','--disable-component-update','--disable-session-crashed-bubble','--window-size=1400,1100','about:blank'];}
export function loopbackWebSocket(port,endpoint){if(!Number.isInteger(port)||port<1||port>65535||!/^\/devtools\/browser\/[a-zA-Z0-9-]+$/.test(endpoint))throw new Error('Invalid owned browser endpoint');return `ws://127.0.0.1:${port}${endpoint}`;}
export class CDP {
 constructor(url,WebSocketType=globalThis.WebSocket){const parsed=new URL(url);if(parsed.protocol!=='ws:'||parsed.hostname!=='127.0.0.1')throw new Error('CDP only connects to the owned loopback browser');this.socket=new WebSocketType(url);this.serial=0;this.pending=new Map();this.listeners=new Map();this.closed=false;this.ready=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.socket.close();reject(new Error('Fresh browser WebSocket handshake timed out'));},20000);this.socket.addEventListener('open',()=>{clearTimeout(timer);resolve();},{once:true});this.socket.addEventListener('error',()=>{clearTimeout(timer);reject(new Error('Could not connect to the fresh browser'));},{once:true});});this.socket.addEventListener('message',event=>{let data;try{data=JSON.parse(event.data);}catch{return;}if(data.id){const pending=this.pending.get(data.id);if(!pending)return;this.pending.delete(data.id);clearTimeout(pending.timer);pending.cleanup?.();data.error?pending.reject(new Error(`${pending.method}: ${data.error.message}`)):pending.resolve(data.result||{});}else for(const fn of this.listeners.get(data.method)||[])fn(data.params||{},data.sessionId);});this.socket.addEventListener('close',()=>{this.closed=true;for(const p of this.pending.values()){clearTimeout(p.timer);p.cleanup?.();p.reject(new Error('Owned browser connection closed'));}this.pending.clear();});}
 on(method,fn){const set=this.listeners.get(method)||new Set();set.add(fn);this.listeners.set(method,set);return()=>set.delete(fn);}
 async send(method,params={},sessionId,{signal}={}){if(signal?.aborted)throw abortError();await this.ready;if(signal?.aborted)throw abortError();if(this.closed)throw new Error('Browser connection is closed');const id=++this.serial;return new Promise((resolve,reject)=>{const cleanup=()=>signal?.removeEventListener('abort',cancel),cancel=()=>{clearTimeout(timer);this.pending.delete(id);cleanup();reject(abortError());},timer=setTimeout(()=>{this.pending.delete(id);cleanup();reject(new Error(`CDP timeout: ${method}`));},20000);signal?.addEventListener('abort',cancel,{once:true});this.pending.set(id,{resolve,reject,timer,method,cleanup});this.socket.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}));});}
 close(){this.socket.close();}
}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2','.ogg':'audio/ogg','.mp3':'audio/mpeg','.wav':'audio/wav','.m4a':'audio/mp4','.txt':'text/plain; charset=utf-8'};
export async function startStaticServer(directory,{appPrefix='preview/yard-courtyard'}={}){
 const root=await realpath(directory);if(!safeRelative(appPrefix))throw new Error('Safe application prefix required');let port;
 const allow=[appPrefix+'/', 'prototype/yard-courtyard-preview-r5/'];
 const server=createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; media-src 'self' blob:; frame-src 'self'; frame-ancestors 'self'; worker-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'");
 try{if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);return res.end('Static preview only');}
 if(req.headers.host!==`127.0.0.1:${port}`){res.writeHead(403);return res.end('Owned loopback only');}
 if(req.headers.origin&&req.headers.origin!==`http://127.0.0.1:${port}`){res.writeHead(403);return res.end('Local origin only');}
 const u=new URL(req.url,`http://127.0.0.1:${port}`);if(u.pathname==='/favicon.ico'){res.writeHead(204);return res.end();}
 if(u.pathname==='/__qa_host.html'){
  const scenario=u.searchParams.get('scenario')==='cushion'?'cushion':'mouse';const insets=u.searchParams.get('insets')==='1'?[24,0,20,0]:[0,0,0,0];
  res.setHeader('Content-Type','text/html; charset=utf-8');res.writeHead(200);return res.end('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Yard local user-run QA</title><link rel="icon" href="data:,"><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#26333b}#qa-reserve{position:absolute;inset:'+insets.map(v=>v+'px').join(' ')+'}iframe{border:0;display:block;width:100%;height:100%}</style></head><body><div id="qa-reserve"><iframe id="game-frame" title="Actual synthetic Yard preview" sandbox="allow-scripts allow-same-origin allow-downloads" src="/'+appPrefix+'/index.html?scenario='+scenario+'"></iframe></div></body></html>');
 }
 const relative=decodeURIComponent(u.pathname.slice(1));if(!safeRelative(relative)||!allow.some(p=>relative.startsWith(p))||relative.split('/').some(p=>p==='qa'||p==='qa-results')){res.writeHead(403);return res.end('Outside allowlisted Yard preview');}
 const file=await realpath(path.resolve(root,relative));if(!file.startsWith(root+path.sep)||!(await stat(file)).isFile())throw new Error('Not a preview file');
 res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.writeHead(200);if(req.method==='HEAD')res.end();else createReadStream(file).pipe(res);
 }catch{res.writeHead(404);res.end('Not found');}});
 await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>{port=server.address().port;resolve();});});
 return{server,root,url:`http://127.0.0.1:${port}`,close:()=>new Promise(resolve=>server.close(resolve))};
}
let crcTable;
export function crc32(bytes){crcTable ||= Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});let crc=0xffffffff;for(const byte of bytes)crc=crcTable[(crc^byte)&255]^(crc>>>8);return(crc^0xffffffff)>>>0;}
export async function zipReport(directory,output,{maxBytes=512*1024*1024,maxFileBytes=64*1024*1024,maxEntries=4096}={}){const root=await realpath(directory),files=[];let plannedBytes=0;async function walk(dir,prefix=''){for(const name of(await readdir(dir)).sort()){const file=path.join(dir,name),relative=prefix+name,info=await lstat(file);if(info.isSymbolicLink())throw new Error('Report symlinks are not archived');if(info.isDirectory())await walk(file,relative+'/');else if(info.isFile()){if(!safeRelative(relative))throw new Error('Unsafe report file');plannedBytes+=info.size;if(info.size>maxFileBytes||plannedBytes>maxBytes||files.length>=maxEntries)throw new Error('ZIP safety budget exceeded; the complete report folder is preserved');files.push({name:relative,file,size:info.size});}}}await walk(root);const handle=await open(output,'wx'),hash=createHash('sha256'),central=[];let offset=0,ok=false;const write=async bytes=>{if(offset+bytes.length>maxBytes||offset+bytes.length>0xffffffff)throw new Error('ZIP32 size budget exceeded; report folder preserved');let position=0;while(position<bytes.length){const {bytesWritten}=await handle.write(bytes,position,bytes.length-position,null);if(!bytesWritten)throw new Error('ZIP write made no progress');position+=bytesWritten;}hash.update(bytes);offset+=bytes.length;};try{for(const file of files){const bytes=await readFile(file.file);if(bytes.length!==file.size||bytes.length>maxFileBytes)throw new Error('Report file changed while archiving');const name=Buffer.from(file.name),compressed=deflateRawSync(bytes),crc=crc32(bytes),entryOffset=offset,head=Buffer.alloc(30);if(name.length>65535||compressed.length>0xffffffff)throw new Error('ZIP32 entry limit exceeded');head.writeUInt32LE(0x04034b50,0);head.writeUInt16LE(20,4);head.writeUInt16LE(0x800,6);head.writeUInt16LE(8,8);head.writeUInt16LE(0x21,12);head.writeUInt32LE(crc,14);head.writeUInt32LE(compressed.length,18);head.writeUInt32LE(bytes.length,22);head.writeUInt16LE(name.length,26);await write(head);await write(name);await write(compressed);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50,0);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt16LE(8,10);c.writeUInt16LE(0x21,14);c.writeUInt32LE(crc,16);c.writeUInt32LE(compressed.length,20);c.writeUInt32LE(bytes.length,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE(entryOffset,42);central.push(c,name);}const centralOffset=offset,centralSize=central.reduce((sum,b)=>sum+b.length,0);for(const chunk of central)await write(chunk);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(centralSize,12);end.writeUInt32LE(centralOffset,16);await write(end);ok=true;return{files:files.length,bytes:offset,sha256:hash.digest('hex'),mode:'one-file-at-a-time ZIP32, bounded memory',budget:{maxBytes,maxFileBytes,maxEntries}};}finally{await handle.close();if(!ok)await unlink(output).catch(()=>{});}}

export function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
