import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{assessEpisodeTiming,replayPreservation}from'./episode-evidence.mjs';
const active={episodeComplete:true,timing:{eventLimit:240,events:[{type:'media-wait-end',durationMs:24,clockHeld:true}],stats:{atlasLoads:5}}};
test('active completed-page evidence is retained when the subsequent empty-page counters reset',()=>{const saved=assessEpisodeTiming(active),empty={episodeComplete:true,timing:{eventLimit:240,events:[],stats:{atlasLoads:0}}};assert.equal(saved.passed,true);assert.equal(assessEpisodeTiming(empty).passed,false);assert.equal(saved.details.atlasLoads,5);});
test('an actual advancing clock during a measured wait remains a failure',()=>{const bad=structuredClone(active);bad.timing.events[0].clockHeld=false;assert.equal(assessEpisodeTiming(bad).passed,false);});
test('collector captures active completion before reload and asserts optional timing after Replay',async()=>{const s=await readFile(new URL('./cases.mjs',import.meta.url),'utf8');assert.ok(s.indexOf("captureState('episode-ended-before-gift-reload')")<s.indexOf("screenshot('gift-before-collect')"));assert.ok(s.indexOf('episodeTiming.passed')>s.indexOf("captureState('explicit-demo-replay')"));assert.doesNotMatch(s,/snapshot\(\)\.timing;return.*atlasLoads>0/);});
const save=(clock=100,extra={})=>JSON.stringify({format:'yard-courtyard-save/v3',sha256:String(clock),payload:{episodeComplete:true,clock:{screenMs:clock,segment:null},kernel:{inventory:{future:3},giftClaimed:true},...extra}});
test('Replay preservation accepts only a monotonic idle presentation-clock update',()=>{assert.equal(replayPreservation(save(100),save(200)).passed,true);assert.equal(replayPreservation(save(100),save(99)).passed,false);assert.equal(replayPreservation(save(100),save(200,{kernel:{inventory:{future:2},giftClaimed:true}})).passed,false);assert.equal(replayPreservation(save(100),save(200,{episodeComplete:false})).passed,false);});
import{casesFor}from'./cases.mjs';
test('focused Replay launcher selects exactly one real complete mouse episode, not a quick shortcut',async()=>{const cmd=await readFile(new URL('../../../RUN-QA-REPLAY.cmd',import.meta.url),'utf8');assert.match(cmd,/--case mouse-full/);assert.doesNotMatch(cmd,/--quick/);assert.equal(casesFor().filter(c=>c.id.includes('mouse-full')).length,1);});
