import test from'node:test';import assert from'node:assert/strict';import vm from'node:vm';import{mkdtemp,mkdir,writeFile,readFile,rm}from'node:fs/promises';import os from'node:os';import path from'node:path';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';import{inflateRawSync}from'node:zlib';
import{Actor}from'./actor.mjs';import{animationSnapshot}from'./animation-readiness.mjs';import{safeRelative,browserArguments,loopbackWebSocket,startStaticServer,zipReport,crc32}from'./core.mjs';import{parseArguments,detectProfiles,browserCandidates}from'./run-qa.mjs';import{casesFor}from'./cases.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
test('nested Actor.evaluate retains the proven lexical-scope fix without browser execution',async()=>{const doc={defaultView:{name:'yard'}},frame={contentDocument:doc},actor=new Actor(null,'s','http://127.0.0.1:1234',{},'.');actor.send=async(method,{expression})=>({result:{value:await vm.runInNewContext(expression,{location:{origin:actor.baseUrl},document:{getElementById:()=>frame}})}});assert.equal(await actor.evaluate('const f=7;return f;'),7);assert.equal(await actor.evaluate('const d=3,w=4;return d+w;'),7);assert.equal(await actor.evaluate("return f.contentDocument===d&&w.name==='yard';"),true);});
test('Actor refuses a non-preview origin in serialized evaluation',async()=>{const a=new Actor(null,'s','http://127.0.0.1:1234',{},'.');a.send=async(_,p)=>({result:{value:await vm.runInNewContext(p.expression,{location:{origin:'https://example.com'}})}});await assert.rejects(a.evaluate('return true;'),/non-preview/);});
test('Enter is real keyDown with carriage-return text; explicit dialog close is scoped',async()=>{const a=new Actor(null,'s','x',{actions:[]},'.'),calls=[];a.send=async(m,p)=>{calls.push([m,p]);return{};};await a.key('Enter');assert.equal(calls[0][1].type,'keyDown');assert.equal(calls[0][1].text,'\r');assert.equal(calls[0][1].unmodifiedText,'\r');assert.equal(calls[1][1].type,'keyUp');const clicks=[];a.click=async x=>clicks.push(x);a.waitFor=async()=>true;await a.dismiss();assert.deepEqual(clicks,['#panel #close-panel']);});
test('all running finite animations gate captures; no pressure/timer exemption',()=>{const fake=end=>({playState:'running',constructor:{name:'CSSTransition'},transitionProperty:'width',effect:{getComputedTiming:()=>({endTime:end})}}),x=animationSnapshot({getAnimations:()=>[fake(300),fake(Infinity),{playState:'finished'}]});assert.equal(x.finite.length,1);assert.equal(x.ignoredInfinite.length,1);assert.equal('ignoredLive'in x,false);});
test('argument default is archive root and full run, with no unsupported target switch',()=>{assert.equal(parseArguments([]).root,root);assert.equal(parseArguments([]).quick,false);assert.equal(parseArguments(['--quick']).quick,true);assert.throws(()=>parseArguments(['--game','bubbo']));assert.throws(()=>parseArguments(['--browser']));});
test('archive-root and nested-app detection both serve the common archive tree',async()=>{for(const r of[root,path.join(root,'preview/yard-courtyard')]){const[p]=await detectProfiles(r);assert.equal(p.repository,root);assert.equal(p.appPrefix,'preview/yard-courtyard');assert.equal(p.markerData.productionCompatible,false);}});
test('case matrix is bounded and covers requested compact and real lifecycle cases',()=>{const all=casesFor(),quick=casesFor({quick:true});assert.equal(all.length,8);assert.equal(quick.length,5);for(const size of[[320,464],[520,216]])assert.ok(all.some(c=>c.options.width===size[0]&&c.options.height===size[1]));assert.ok(all.some(c=>c.id.includes('mouse-full-pause-reload-gift-once')));assert.ok(all.some(c=>c.id.includes('cushion-full-departure-gift-once')));});
test('CDP connection and owned profile arguments are restricted to loopback/fresh paths',()=>{assert.equal(loopbackWebSocket(1234,'/devtools/browser/abc-123'),'ws://127.0.0.1:1234/devtools/browser/abc-123');assert.throws(()=>loopbackWebSocket(0,'/devtools/browser/a'));assert.throws(()=>loopbackWebSocket(1234,'https://bad'));assert.throws(()=>browserArguments('relative'));const a=browserArguments(path.join(os.tmpdir(),'owned-qa-profile'));assert.ok(a.includes('--remote-debugging-address=127.0.0.1'));assert.ok(a.some(x=>x.startsWith('--user-data-dir=')));assert.ok(browserCandidates('win32',{PROGRAMFILES:'C:\\Program Files'}).some(x=>x.endsWith('msedge.exe')));});
test('relative path validator rejects traversal and absolute paths',()=>{for(const x of['../x','/etc/passwd','a/../x','a\\b','','a//b'])assert.equal(safeRelative(x),false,x);assert.equal(safeRelative('preview/yard-courtyard/app.mjs'),true);});
test('loopback HTTP serves app+prototype closure but rejects unrelated files and writes; no browser',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'yard-qa-http-'));let server;try{for(const d of['preview/yard-courtyard','prototype/yard-courtyard-preview-r5/browser'])await mkdir(path.join(dir,d),{recursive:true});await writeFile(path.join(dir,'preview/yard-courtyard/index.html'),'yard');await writeFile(path.join(dir,'prototype/yard-courtyard-preview-r5/browser/kernel.mjs'),'export{}');await writeFile(path.join(dir,'secret.txt'),'no');server=await startStaticServer(dir);const host=await fetch(server.url+'/__qa_host.html?scenario=cushion');assert.equal(host.status,200);assert.match(await host.text(),/\/preview\/yard-courtyard\/index.html\?scenario=cushion/);assert.equal((await fetch(server.url+'/preview/yard-courtyard/index.html')).status,200);assert.equal((await fetch(server.url+'/prototype/yard-courtyard-preview-r5/browser/kernel.mjs')).status,200);assert.equal((await fetch(server.url+'/secret.txt')).status,403);assert.equal((await fetch(server.url+'/preview/yard-courtyard/qa/run-qa.mjs')).status,403);assert.equal((await fetch(server.url+'/preview/yard-courtyard/index.html',{method:'POST'})).status,405);}finally{await server?.close();await rm(dir,{recursive:true,force:true});}});
test('ZIP is real bounded ZIP32 with correct CRC and SHA; no external archiver',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'yard-qa-zip-'));try{const source=path.join(dir,'report');await mkdir(source);const payload=Buffer.from('synthetic preview only');await writeFile(path.join(source,'evidence.txt'),payload);const out=path.join(dir,'report.zip'),info=await zipReport(source,out),bytes=await readFile(out);assert.equal(bytes.readUInt32LE(0),0x04034b50);const n=bytes.readUInt16LE(26),size=bytes.readUInt32LE(18);assert.deepEqual(inflateRawSync(bytes.subarray(30+n,30+n+size)),payload);assert.equal(bytes.readUInt32LE(14),crc32(payload));assert.equal(info.sha256,createHash('sha256').update(bytes).digest('hex'));assert.equal(info.files,1);}finally{await rm(dir,{recursive:true,force:true});}});
test('collector source has no gameplay setter/save injection and uses read-only hook',async()=>{const actor=await readFile(new URL('./actor.mjs',import.meta.url),'utf8'),cases=await readFile(new URL('./cases.mjs',import.meta.url),'utf8');assert.match(actor,/__yardQA\.snapshot/);for(const source of[actor,cases]){assert.doesNotMatch(source,/localStorage\.setItem|adapter\.action|advancePresentation\(|\.click\(\);|bb-pressure/);}assert.match(actor,/Page\.captureScreenshot/);});

import {placementAccuracy} from './placement-accuracy.mjs';
import {createProjection} from '../projection.mjs';
test('placement tolerance accepts measured Chrome fractional-pixel roundtrip and rejects meaningful errors',()=>{
 const old={x:35,y:45,rotationZ:0,compression:1},moved={x:37.00000188941175,y:44.99999501352009,rotationZ:0,compression:1};
 for(const size of[[390,626],[320,330],[408,158]]){const p=createProjection(...size),targetPx=p.project({x:37,y:45});
  assert.equal(placementAccuracy({old,moved,targetPx,actualPx:p.project(moved)}).passed,true);
  for(const delta of[[.1,0],[0,.1],[2,0]]){const bad={...moved,x:37+delta[0],y:45+delta[1]};assert.equal(placementAccuracy({old,moved:bad,targetPx,actualPx:p.project(bad)}).passed,false);}
  assert.equal(placementAccuracy({old,moved,targetPx,actualPx:{x:targetPx.x+.1,y:targetPx.y}}).passed,false);
 }
});
test('placement reload and screenshot execute before optional geometric precision assertion',async()=>{
 const source=await readFile(new URL('./cases.mjs',import.meta.url),'utf8'),a=source.indexOf('Local reload preserves committed placement exactly'),b=source.indexOf('Real placement reaches requested');assert.ok(a>0&&b>a);assert.ok(source.indexOf("screenshot('placement-after-reload')")<a);
});

test('touch highlight correction is button-scoped and preserves keyboard focus style',async()=>{const css=await readFile(new URL('../style.css',import.meta.url),'utf8');assert.match(css,/button\{-webkit-tap-highlight-color:transparent\}/);assert.match(css,/button:focus-visible\{outline:3px/);assert.doesNotMatch(css,/\*\{[^}]*outline:none/);});
