import fs from'node:fs/promises';import path from'node:path';import{createRequire}from'node:module';import{fileURLToPath,pathToFileURL}from'node:url';import{createHash}from'node:crypto';import assert from'node:assert/strict';
const here=path.dirname(fileURLToPath(import.meta.url));
export async function verifySceneResources(){
 const root=path.resolve(process.env.YARD_SOURCE_ROOT||process.cwd()),dependency=path.resolve(process.env.YARD_DEPENDENCY_ROOT||root),roots=[...(process.env.YARD_OVERLAY_ROOTS||'').split(path.delimiter).filter(Boolean),root,...(process.env.YARD_ASSET_ROOT?[process.env.YARD_ASSET_ROOT]:[])];
 async function resolve(relative){for(const r of roots){const file=path.join(r,relative);try{if((await fs.stat(file)).isFile())return file;}catch(e){if(e.code!=='ENOENT')throw e;}}throw Error('Missing Scene resource '+relative);}
 const require=createRequire(path.join(dependency,'package.json')),{build}=require('esbuild'),pip='src/games/companion-yard-v2/pip-prototype/';
 const built=await build({entryPoints:[path.join(here,'client.mjs')],bundle:true,write:false,metafile:true,format:'esm',platform:'browser',target:'es2022',logLevel:'silent',define:{'import.meta.env.VITE_YARD_SAVED_VISITS':JSON.stringify('true'),'import.meta.env.VITE_YARD_PAINTED_FOOD_TRIAL':JSON.stringify(process.env.VITE_YARD_PAINTED_FOOD_TRIAL==='true'?'true':'false'),'import.meta.env.VITE_YARD_PIP_PREVIEW':JSON.stringify('false')},plugins:[{name:'scene-source-overlay',setup(b){b.onResolve({filter:/./},async a=>{if(a.path.startsWith('/source/'))return{path:await resolve(a.path.slice(8))};if(a.path==='three')return{path:await resolve(pip+'vendor/three/build/three.module.js')};const parent=roots.find(r=>a.importer.startsWith(r+'/'));if(parent&&a.path.startsWith('.'))return{path:await resolve(path.relative(parent,path.resolve(path.dirname(a.importer),a.path)))};});}}]});
 const inputs=new Set(Object.keys(built.metafile.inputs).map(f=>path.resolve(f))),relativeOf=file=>{const r=roots.find(r=>file.startsWith(r+'/'));return r?path.relative(r,file).replaceAll('\\','/'):null;},resourceSet=new Set([
  pip+'data/fixture.json',pip+'data/location.json',pip+'data/calibration.json',pip+'source/pip-rest-coat.glsl',pip+'assets/clean-garden.png',pip+'assets/pip.glb',pip+'assets/planter-t2.glb',pip+'assets/food-r2/yard-food-source-r2.glb','tests/fixtures/canonical-saved-public.json',
 ]);
 for(const file of inputs){const relative=relativeOf(file);if(relative)resourceSet.add(relative);if(!/\.(mjs|js)$/.test(file))continue;const text=await fs.readFile(file,'utf8');for(const m of text.matchAll(/new URL\(\s*(['"])(\.[^'"]+)\1\s*,\s*import\.meta\.url\s*\)/g)){const target=path.resolve(path.dirname(file),m[2]),rel=relativeOf(target);if(!rel||m[2].endsWith('/'))continue;resourceSet.add(rel);}}
 const resources=[];for(const relative of [...resourceSet].sort()){const file=await resolve(relative),bytes=await fs.readFile(file);resources.push({path:relative,sourcePath:file,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}
 assert(resources.some(r=>r.path.endsWith('pip-rest-coat.glsl')));assert(resources.some(r=>r.path.endsWith('yard-food-source-r2.glb')));
 return {scope:'Complete compiled static/dynamic import graph plus literal URL resources and explicit runtime JSON, GLSL, background, actor, planter, food and genuine public fixture. In-memory parse only; not a browser or product build.',inputModules:inputs.size,bundledBytes:built.outputFiles.reduce((n,f)=>n+f.contents.length,0),warnings:built.warnings,resources};
}
if(process.argv[1]&&pathToFileURL(path.resolve(process.argv[1])).href===import.meta.url){const result=await verifySceneResources(),out=path.resolve(process.env.YARD_SCENE_OUTPUT||'test-results/saved-visit-scene');await fs.mkdir(out,{recursive:true});await fs.writeFile(path.join(out,'resource-closure.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({inputModules:result.inputModules,resources:result.resources.length,bundledBytes:result.bundledBytes,warnings:result.warnings.length}));}
