import{verifySceneResources}from'./preflight.mjs';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(process.env.YARD_SOURCE_ROOT||process.cwd()),dependencies=path.resolve(process.env.YARD_DEPENDENCY_ROOT||root),output=path.resolve(process.env.YARD_SCENE_OUTPUT||'test-results/saved-visit-scene');
assert.equal(process.env.VITE_YARD_SAVED_VISITS,'true','Explicit test-only saved-visit build gate required');
const require=createRequire(path.join(dependencies,'package.json')),{chromium}=require('@playwright/test');
const overlays=(process.env.YARD_OVERLAY_ROOTS||'').split(path.delimiter).filter(Boolean),roots=[...overlays,root,...(process.env.YARD_ASSET_ROOT?[process.env.YARD_ASSET_ROOT]:[])];
async function readSource(relative){assert(!relative.split('/').includes('..'));for(const r of roots)try{return{path:path.join(r,relative),bytes:await fs.readFile(path.join(r,relative))};}catch(e){if(e.code!=='ENOENT')throw e;}throw Error('Missing source '+relative);}
const mime=p=>p.endsWith('.json')?'application/json':/\.(mjs|js)$/.test(p)?'text/javascript':p.endsWith('.html')?'text/html':p.endsWith('.png')?'image/png':'application/octet-stream';
await fs.mkdir(output,{recursive:true});const closure=await verifySceneResources();await fs.writeFile(path.join(output,'resource-closure.json'),JSON.stringify(closure,null,2)+'\n');const pins=new Map(closure.resources.map(r=>[r.path,r.sha256]));const checks=[],errors=[],served=new Map(),browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox']});
async function open(v){const context=await browser.newContext({viewport:{width:v.width,height:v.height},deviceScaleFactor:v.dpr,isMobile:!v.desktop,hasTouch:!v.desktop,...(process.env.VITE_YARD_PAINTED_FOOD_TRIAL==='true'&&v.width===390?{recordVideo:{dir:path.join(output,'moving-video'),size:{width:v.width,height:v.height}}}:{})}),page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.route('**/*',async route=>{const u=new URL(route.request().url());try{assert.equal(u.origin,'https://saved-scene.invalid');if(u.pathname==='/favicon.ico')return route.fulfill({status:204,body:''});let row=u.pathname.startsWith('/source/')?await readSource(decodeURIComponent(u.pathname.slice(8))):{path:path.join(here,u.pathname==='/'?'index.html':path.basename(u.pathname)),bytes:await fs.readFile(path.join(here,u.pathname==='/'?'index.html':path.basename(u.pathname)))};
 const sourceHash=createHash('sha256').update(row.bytes).digest('hex');if(u.pathname.startsWith('/source/'))assert.equal(sourceHash,pins.get(decodeURIComponent(u.pathname.slice(8))),'Unpinned or changed Scene resource');let body=row.bytes;
 // Equivalent to the existing build's two compile-time environment definitions;
 // no source logic or plan is replaced and no preview fixture is enabled.
 if(u.pathname.endsWith('/scene-entry.mjs'))body=Buffer.from(body.toString().replaceAll('import.meta.env.VITE_YARD_SAVED_VISITS',JSON.stringify('true')).replaceAll('import.meta.env.VITE_YARD_PIP_PREVIEW',JSON.stringify('false')).replaceAll('import.meta.env?.VITE_YARD_PAINTED_FOOD_TRIAL',JSON.stringify(process.env.VITE_YARD_PAINTED_FOOD_TRIAL==='true'?'true':'false')));
 served.set(u.pathname,{sourcePath:row.path,sourceSha256:sourceHash,responseSha256:createHash('sha256').update(body).digest('hex'),bytes:body.length});await route.fulfill({status:200,contentType:mime(row.path),body});}catch(e){errors.push(`${u.pathname}: ${e.message}`);await route.fulfill({status:404,body:'Missing QA source'});}});await page.goto('https://saved-scene.invalid/');await page.waitForFunction(()=>window.sceneQA?.ready,{},{timeout:30000});return{context,page};}
async function snapshot(page,name,id){const d=await page.evaluate(()=>window.sceneQA.diagnostics());assert.equal(d.mode,'canonical-saved-visits');assert.equal(d.scene.plannerWorkerActive,false);assert.equal(d.scene.inspectionCount,0);assert.equal(d.sourceUnchanged,true);assert.equal(d.view.itemMutable,false);assert.deepEqual(await page.evaluate(()=>window.sceneQA.failures),[]);await page.screenshot({path:path.join(output,`${id}-${name}.png`)});checks.push({viewport:id,name,diagnostics:d});return d;}

function projectCanonical(frame,p){const w=frame.cameraWorld,m=frame.cameraProjection,v=[p.x/12-w[12],(p.z||0)/12-w[13],-p.y/12-w[14]],c=[v[0]*w[0]+v[1]*w[1]+v[2]*w[2],v[0]*w[4]+v[1]*w[5]+v[2]*w[6],v[0]*w[8]+v[1]*w[9]+v[2]*w[10]],x=m[0]*c[0]+m[4]*c[1]+m[8]*c[2]+m[12],y=m[1]*c[0]+m[5]*c[1]+m[9]*c[2]+m[13],r=frame.cssRect;return{x:r.x+(x+1)*r.width/2,y:r.y+(1-y)*r.height/2};}
async function movingTrial(page,id){
 await page.evaluate(()=>window.sceneQA.advanceTo(window.sceneQA.plan.inspectionPlan.phases[1].startMs+300));
 const samples=[],potCrops=[];let reference=null,start=null;
 for(let i=0;i<3;i++){
  if(i){const remaining=await page.evaluate(target=>Math.max(0,target-performance.now()),samples[0].realMs+i*3000);await page.waitForTimeout(remaining);}
  const row=await page.evaluate(()=>(()=>{const host=document.querySelector('#direct'),surface=host.querySelector('canvas'),rect=surface?.getBoundingClientRect();return{realMs:performance.now(),d:window.sceneQA.diagnostics(),surfaceVisible:getComputedStyle(host).visibility==='visible'&&getComputedStyle(surface).visibility==='visible'&&rect.width>0&&rect.height>0}})()),d=row.d,scene=d.scene,frame=scene.renderer.lastFrame,ledger=scene.foodResources;
  await fs.writeFile(path.join(output,`${id}-moving-${i}-diagnostics.json`),JSON.stringify(row,null,2)+'\n');
  assert.equal(scene.resources.renderProfile,'painted-native-1.5-v1');assert.equal(scene.resources.backingWidth,585);assert.equal(scene.resources.backingHeight,972);assert.equal(scene.lastFrame.visibility,'both');assert.equal(row.surfaceVisible,true,'Actual composed surface is visible');
  for(const k of ['rgba','knownCPU','estimatedGPU'])assert(Number.isSafeInteger(ledger.total[k])&&ledger.total[k]>=0&&ledger.total[k]<=ledger.limits[k],k+' budget');assert.equal(ledger.limits.estimatedGPU,20*1024*1024);
  const camera=[...frame.cameraWorld,...frame.cameraProjection,frame.cssRect.x,frame.cssRect.y,frame.cssRect.width,frame.cssRect.height];if(reference)camera.forEach((n,k)=>assert(Math.abs(n-reference[k])<1e-9,'Camera/raster moved with actor'));else reference=camera;
  const target=await page.evaluate(()=>window.sceneQA.plan.inspectionPlan.target),pot=projectCanonical(frame,{x:target.x,y:target.y,z:2.5}),actor=projectCanonical(frame,scene.lastFrame.root),actorDistanceCss=Math.hypot(actor.x-pot.x,actor.y-pot.y),clip={x:Math.round(pot.x)-4,y:Math.round(pot.y)-3,width:8,height:6};
  const viewport=page.viewportSize();assert(clip.x>=0&&clip.y>=0&&clip.x+clip.width<=viewport.width&&clip.y+clip.height<=viewport.height,'Projected pot crop inside viewport');
  await page.screenshot({path:path.join(output,`${id}-moving-${i}.png`)});const potBytes=await page.screenshot({path:path.join(output,`${id}-pot-${i}.png`),clip});const potHash=createHash('sha256').update(potBytes).digest('hex');if(actorDistanceCss>32)potCrops.push({i,hash:potHash});
  samples.push({realMs:row.realMs,serverNow:d.savedServerNow,frameCount:scene.frameCount,root:scene.lastFrame.root,phase:scene.lastFrame.savedPhase,frame,resources:scene.resources,ledger,potClip:clip,potHash,actorDistanceCss});
 }
 const a=samples[0],b=samples.at(-1),realElapsedMs=b.realMs-a.realMs,serverElapsedMs=b.serverNow-a.serverNow;
 assert(realElapsedMs>=6000&&realElapsedMs<10000,'Bounded real-time segment');assert(Math.abs(serverElapsedMs-realElapsedMs)<200,'Presentation must advance at actual 1x time');assert(b.frameCount-a.frameCount>10,'Moving segment did not render');assert(Math.hypot(b.root.x-a.root.x,b.root.y-a.root.y)>1,'Actor did not move');
 assert(potCrops.length>=2,'Insufficient unoccluded pot samples');assert(potCrops.every(x=>x.hash===potCrops[0].hash),'Static pot pixels changed while actor moved');
 checks.push({viewport:id,name:'painted-real-time-moving-pot-stability',realElapsedMs,serverElapsedMs,unoccludedPotSamples:potCrops,samples,scope:'Six seconds at natural presentation speed; source-saved approach, no synthetic feeding claim. Software browser timing is not physical-mobile performance.'});
}

try{for(const v of[{width:320,height:568,dpr:1},{width:360,height:800,dpr:1},{width:375,height:812,dpr:1},{width:390,height:844,dpr:2},{width:414,height:896,dpr:1},{width:568,height:320,dpr:1},{width:844,height:390,dpr:1},{width:768,height:1024,dpr:1},{width:1024,height:768,dpr:1},{width:1280,height:720,dpr:1},{width:612,height:982,dpr:1,desktop:true}]){const id=`${v.width}x${v.height}-dpr${v.dpr}`,{context,page}=await open(v);try{
 let d=await snapshot(page,'automatic-entry',id);assert.equal(d.scene.canonicalSavedVisits,true);assert.deepEqual(await page.evaluate(()=>window.sceneQA.manualDenied()),{prototype:false,items:false,disablePrototype:false,disableItems:false,inspect:false});
 if(process.env.VITE_YARD_PAINTED_FOOD_TRIAL==='true'&&v.width===390)await movingTrial(page,id);
 await page.evaluate(()=>window.sceneQA.advanceTo(window.sceneQA.plan.inspectionPlan.phases[2].startMs+2600));d=await snapshot(page,'on-screen-saved-visit',id);assert.equal(d.scene.lastFrame.visibility,'both');assert.equal(d.view.pets.length,1);assert.equal(d.scene.lastFrame.savedPhase,'interaction');
 await page.evaluate(()=>window.sceneQA.remount());d=await snapshot(page,'leave-return',id);assert.equal(d.scene.lastFrame.visibility,'both');
 await page.evaluate(()=>window.sceneQA.pending());d=await snapshot(page,'reconciliation-pending',id);assert.equal(d.hostVisibility,'hidden');assert.equal(d.view.pets.length,0);await page.evaluate(()=>window.sceneQA.recover());
 const before=await page.evaluate(()=>window.sceneQA.diagnostics().retirements);await page.evaluate(()=>window.sceneQA.loseAndRestoreContext());await page.waitForFunction(n=>{const d=window.sceneQA.diagnostics();return d.retirements>n&&d.scene?.ready&&!d.scene?.renderer?.contextLost&&d.scene?.lastFrame?.visibility==='both';},before,{timeout:30000});await snapshot(page,'context-restored',id);
 await page.evaluate(()=>window.sceneQA.advanceTo(window.sceneQA.plan.releaseAt+1000));await page.waitForFunction(()=>!window.sceneQA.diagnostics().scene.scheduler.pending);d=await snapshot(page,'quiet-no-raf',id);assert.equal(d.scene.lastFrame.savedPhase,'neutral-rest');assert.equal(d.scene.route.wakePending,true);
 await page.evaluate(()=>window.sceneQA.resumePastDeparture());d=await snapshot(page,'resume-after-departure',id);assert.equal(d.scene.lastFrame.savedPhase,'departed');assert.equal(d.view.pets.length,0);assert.equal(d.scene.route.wakePending,false);
 await page.reload();await page.waitForFunction(()=>window.sceneQA?.ready);await page.evaluate(()=>window.sceneQA.advanceTo(window.sceneQA.plan.inspectionPlan.phases[2].startMs+2600));d=await snapshot(page,'cold-reload',id);assert.equal(d.scene.lastFrame.visibility,'both');
 }finally{await context.close();}}assert.deepEqual(errors,[]);}finally{await browser.close();await fs.writeFile(path.join(output,'scene-report.json'),JSON.stringify({scope:'Actual scene-entry/createSceneOwner/createPipYardScene lifecycle with normal-service fixture and compile-time saved gate. Not full React app navigation. No manual preview, source route generation, or economic mutations. Resume uses injected monotonic elapsed and actual blur/focus listeners; cold reload reloads the fixed authoritative test snapshot.',checks,errors,served:[...served.entries()]},null,2)+'\n');}
