import{verifySceneResources}from'./preflight.mjs';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{fileURLToPath}from'node:url';import{createHash}from'node:crypto';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(process.env.YARD_SOURCE_ROOT||process.cwd()),dependencies=path.resolve(process.env.YARD_DEPENDENCY_ROOT||root),output=path.resolve(process.env.YARD_SCENE_OUTPUT||'test-results/saved-visit-scene');
assert.equal(process.env.VITE_YARD_SAVED_VISITS,'true','Explicit test-only saved-visit build gate required');
const require=createRequire(path.join(dependencies,'package.json')),{chromium}=require('@playwright/test');
const overlays=(process.env.YARD_OVERLAY_ROOTS||'').split(path.delimiter).filter(Boolean),roots=[...overlays,root,...(process.env.YARD_ASSET_ROOT?[process.env.YARD_ASSET_ROOT]:[])];
async function readSource(relative){assert(!relative.split('/').includes('..'));for(const r of roots)try{return{path:path.join(r,relative),bytes:await fs.readFile(path.join(r,relative))};}catch(e){if(e.code!=='ENOENT')throw e;}throw Error('Missing source '+relative);}
const mime=p=>p.endsWith('.json')?'application/json':/\.(mjs|js)$/.test(p)?'text/javascript':p.endsWith('.html')?'text/html':p.endsWith('.png')?'image/png':'application/octet-stream';
await fs.mkdir(output,{recursive:true});const closure=await verifySceneResources();await fs.writeFile(path.join(output,'resource-closure.json'),JSON.stringify(closure,null,2)+'\n');const pins=new Map(closure.resources.map(r=>[r.path,r.sha256]));const checks=[],errors=[],served=new Map(),browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox']});
async function open(v){const context=await browser.newContext({viewport:{width:v.width,height:v.height},deviceScaleFactor:v.dpr,isMobile:true,hasTouch:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.route('**/*',async route=>{const u=new URL(route.request().url());try{assert.equal(u.origin,'https://saved-scene.invalid');if(u.pathname==='/favicon.ico')return route.fulfill({status:204,body:''});let row=u.pathname.startsWith('/source/')?await readSource(decodeURIComponent(u.pathname.slice(8))):{path:path.join(here,u.pathname==='/'?'index.html':path.basename(u.pathname)),bytes:await fs.readFile(path.join(here,u.pathname==='/'?'index.html':path.basename(u.pathname)))};
 const sourceHash=createHash('sha256').update(row.bytes).digest('hex');if(u.pathname.startsWith('/source/'))assert.equal(sourceHash,pins.get(decodeURIComponent(u.pathname.slice(8))),'Unpinned or changed Scene resource');let body=row.bytes;
 // Equivalent to the existing build's two compile-time environment definitions;
 // no source logic or plan is replaced and no preview fixture is enabled.
 if(u.pathname.endsWith('/scene-entry.mjs'))body=Buffer.from(body.toString().replaceAll('import.meta.env.VITE_YARD_SAVED_VISITS',JSON.stringify('true')).replaceAll('import.meta.env.VITE_YARD_PIP_PREVIEW',JSON.stringify('false')));
 served.set(u.pathname,{sourcePath:row.path,sourceSha256:sourceHash,responseSha256:createHash('sha256').update(body).digest('hex'),bytes:body.length});await route.fulfill({status:200,contentType:mime(row.path),body});}catch(e){errors.push(`${u.pathname}: ${e.message}`);await route.fulfill({status:404,body:'Missing QA source'});}});await page.goto('https://saved-scene.invalid/');await page.waitForFunction(()=>window.sceneQA?.ready,{},{timeout:30000});return{context,page};}
async function snapshot(page,name,id){const d=await page.evaluate(()=>window.sceneQA.diagnostics());assert.equal(d.mode,'canonical-saved-visits');assert.equal(d.scene.plannerWorkerActive,false);assert.equal(d.scene.inspectionCount,0);assert.equal(d.sourceUnchanged,true);assert.equal(d.view.itemMutable,false);assert.deepEqual(await page.evaluate(()=>window.sceneQA.failures),[]);await page.screenshot({path:path.join(output,`${id}-${name}.png`)});checks.push({viewport:id,name,diagnostics:d});return d;}
try{for(const v of[{width:320,height:568,dpr:1},{width:390,height:844,dpr:2},{width:844,height:390,dpr:1}]){const id=`${v.width}x${v.height}-dpr${v.dpr}`,{context,page}=await open(v);try{
 let d=await snapshot(page,'automatic-entry',id);assert.equal(d.scene.canonicalSavedVisits,true);assert.deepEqual(await page.evaluate(()=>window.sceneQA.manualDenied()),{prototype:false,items:false,disablePrototype:false,disableItems:false,inspect:false});
 await page.evaluate(()=>window.sceneQA.advanceTo(window.sceneQA.plan.inspectionPlan.phases[2].startMs+2600));d=await snapshot(page,'on-screen-saved-visit',id);assert.equal(d.scene.lastFrame.visibility,'both');assert.equal(d.view.pets.length,1);assert.equal(d.scene.lastFrame.savedPhase,'interaction');
 await page.evaluate(()=>window.sceneQA.remount());d=await snapshot(page,'leave-return',id);assert.equal(d.scene.lastFrame.visibility,'both');
 await page.evaluate(()=>window.sceneQA.pending());d=await snapshot(page,'reconciliation-pending',id);assert.equal(d.hostVisibility,'hidden');assert.equal(d.view.pets.length,0);await page.evaluate(()=>window.sceneQA.recover());
 const before=await page.evaluate(()=>window.sceneQA.diagnostics().retirements);await page.evaluate(()=>window.sceneQA.loseAndRestoreContext());await page.waitForFunction(n=>{const d=window.sceneQA.diagnostics();return d.retirements>n&&d.scene?.ready&&!d.scene?.renderer?.contextLost&&d.scene?.lastFrame?.visibility==='both';},before,{timeout:30000});await snapshot(page,'context-restored',id);
 await page.evaluate(()=>window.sceneQA.advanceTo(window.sceneQA.plan.releaseAt+1000));await page.waitForFunction(()=>!window.sceneQA.diagnostics().scene.scheduler.pending);d=await snapshot(page,'quiet-no-raf',id);assert.equal(d.scene.lastFrame.savedPhase,'neutral-rest');assert.equal(d.scene.route.wakePending,true);
 await page.evaluate(()=>window.sceneQA.resumePastDeparture());d=await snapshot(page,'resume-after-departure',id);assert.equal(d.scene.lastFrame.savedPhase,'departed');assert.equal(d.view.pets.length,0);assert.equal(d.scene.route.wakePending,false);
 await page.reload();await page.waitForFunction(()=>window.sceneQA?.ready);await page.evaluate(()=>window.sceneQA.advanceTo(window.sceneQA.plan.inspectionPlan.phases[2].startMs+2600));d=await snapshot(page,'cold-reload',id);assert.equal(d.scene.lastFrame.visibility,'both');
 }finally{await context.close();}}assert.deepEqual(errors,[]);}finally{await browser.close();await fs.writeFile(path.join(output,'scene-report.json'),JSON.stringify({scope:'Actual scene-entry/createSceneOwner/createPipYardScene lifecycle with normal-service fixture and compile-time saved gate. Not full React app navigation. No manual preview, source route generation, or economic mutations. Resume uses injected monotonic elapsed and actual blur/focus listeners; cold reload reloads the fixed authoritative test snapshot.',checks,errors,served:[...served.entries()]},null,2)+'\n');}
